### ISSUE TITLE
Set up destination outside of .tmp for persistence

### ISSUE THREAD

**Issue by jeremiak** [18F/federalist#10]
Pulling this from a [code comment](https://github.com/18F/federalist/blob/master/api/services/buildEngines.js#L111) so that we can have them all in one place and prioritize.

**Comment by jeremiak** [comment]
The way I understand this issue is that we want the built sites to be stored in a place that is more permanent than .tmp but also we want (at least for the prototype) to have the/a web server in the root of that directory so that people can access the generated sites.

**Comment by dhcole** [comment]
Yea, actually this is set up now with the config option: https://github.com/18F/federalist/blob/master/config/build.js#L6

By publishing to `/assets/`, the content will be publicly available but not deleted each time the server is started. Just need to remove that comment.
