### ISSUE TITLE
Cancel button on Site Settings page doesn't do anything 

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1001]
It should reload the page, thus reverting all changes, I think.

**Comment by wslack** [comment]
What "cancel" button?

**Comment by wslack** [comment]
Oh, this cancel button:
<img width="815" alt="screen shot 2017-06-12 at 7 18 31 pm" src="https://user-images.githubusercontent.com/10016577/27059339-efc2549a-4fa3-11e7-82ed-d1014e41f27a.png">

**Comment by wslack** [comment]
Agreed it should just reload

**Comment by jmhooper** [comment]
Is there anything stopping us from removing the cancel button? The browser already has an 🔄 button?

**Comment by jseppi** [comment]
It's kind of a nice user affordance to have the cancel button there, even
if what it actually does is cause a refresh. I think we could also
relatively easily have it just reload the state and show a status message
that that happened, but I'm not sure if it is worth it.

**Comment by wslack** [comment]
Agreed. Can we say "cancel changes (reloads page)" as the text or is there something shorter we could use?

**Comment by jseppi** [comment]
This has been fixed as of #1185. Closing.
