### ISSUE TITLE
Custom domain text box's description is unclear

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#1006]
This morning @adelevie expressed that he was confused the the "Custom Domain" text box did not publish the site at the custom domain he provided. This seems like an easy misconception to have since the text under that box says this:

> If you build your site with Jekyll, Federalist can configure your production site to load at a custom domain specified here.

We should perhaps change that so it makes it clear the custom domain configuration only changes how the site is built, and doesn't actually handle any DNS or other such changes for you.

**Comment by jseppi** [comment]
Ooo, and maybe contain a link to the relevant section of federalist-docs

**Comment by wslack** [comment]
Agreed and flagging this as something to handle this week if there's capacity.
