### ISSUE TITLE
Investigate using Netlify CMS as an editor for sites

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#1007]
We should look into how challenging it would be to setup [Netlify CMS](https://github.com/netlify/netlify-cms) with Federalist sites. We may be able to integrate CMS tooling into Federalist.

**Comment by jmhooper** [comment]
Here's a few of my notes from looking over Netlify CMS:

The CMS is an SPA that lives inside the site. The code is hosted on a CDN and can loaded on a page at `/admin`. This allows site owners to go to `mysite.gov/admin` and edit their site. This may raise issues with our "3rd party connection" limitations.

I spent most of my time looking at the auth. It looks like a lot of the code for that lives [here](https://github.com/netlify/netlify-cms/blob/master/src/lib/netlify-auth.js). It supports multiple backends, but we may want to restrict it to just GitHub.

The user data is saved in the browser's local storage. When you login, a new window opens with the url for the authenticator. The authenticator's window communicates with the app using the [Window.postMessage()](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) API. The URL for the authenticator looks like this:

```
https://api.netlify.com/auth?provider=github&site_id=1&scope=repo
```

After an initial handshake, the authenticator calls back with an `authorization:github:success` or `authorization:github:error` message. The messages have a stringified object containing either the GH access token or an error message respectively. Once the message has been received, the SPA calls `close()` on the authenticator window and the user's data is fetched and written to local storage.

**Comment by jseppi** [comment]
Seems like the investigation has been done. Do we want to pursue? If so, that should be a separate feature issue.
