### ISSUE TITLE
Remove proxy_redirect rules from Federalist Proxy

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#1008]
Federalist is creating redirect objects in the S3 bucket again. This means that we can move towards removing [these proxy_redirect rules](https://github.com/18F/federalist-proxy/blob/58a3f41083a1a1eba3decfdd383c96839b67eef0/nginx.conf#L42-L43) from our proxy app.

These rules were necessary because when a site is served on a custom domain, we want to remove the `/site/org/repo` path component from the location header in redirects. Otherwise, requests to `example.gov/about` would redirect to `example.gov/site/18f/example/about/`.

After https://github.com/18F/federalist-docker-build/commit/2410288fc0a3cffc98b7839956939e464bebe379, Federalist creates redirect objects in the S3 bucket that tell S3 to serve a redirect with the format `{BASEURL}/path/to/target/`. This means that sites can configure their baseurl in Federalist's to serve content out of the S3 bucket/proxy or on a custom domain, eliminating the need for the proxy. The path component to be removed from the location is no longer present.

Older sites were built without this change. Those sites will need to be rebuilt with the new image before they will have the redirect objects in their S3 buckets. The best way to do this may be to run a script that creates a new build for each site and then let the build process run its course.

After all of the sites are rebuilt, we can remove the proxy_redirect. Also, we can start serving sites and demos without a custom domain on the proxy URL instead of from the S3 bucket.

The work to do for this:

- [x] Rebuild every Federalist site that doesn't have redirect objects
- [x] Remove the proxy_redirect rules from federalist-proxy
- [x] Change the links to view sites / demos without custom / demo domains to the proxy URL instead of the S3 URL

**Comment by wslack** [comment]
Planning to let this lapse for a few weeks while sites are rebuilt on their own; thoughts?

**Comment by jmhooper** [comment]
Agree, though at one point we may want to take a more active step and rebuild some of the dormant sites for their owners. Those shouldn't be hard to identify. We'd just need to look for sites in the S3 bucket without a root redirect object.

**Comment by wslack** [comment]
Done in https://github.com/18F/federalist-proxy/pulls/16!

**Comment by wslack** [comment]
If we missed a site doing rebuild, there will be a generic proxy 404 page!
