### ISSUE TITLE
Text is unreadable when View Website button is in :focus state

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1009]
Minor styling bug:

When you focus (such as by tabbing to) the View Website button, the text is unreadable:

<img width="275" alt="screen shot 2017-06-15 at 9 47 48 am" src="https://user-images.githubusercontent.com/697848/27187106-e739d966-51af-11e7-9cbb-9771d0953ab2.png">

**Comment by jseppi** [comment]
This might happen on other buttons as well. Need to investigate.

**Comment by wslack** [comment]
I don't see this on Chrome, FWIW.

**Comment by wslack** [comment]
<img width="217" alt="screen shot 2017-06-15 at 1 00 49 pm" src="https://user-images.githubusercontent.com/10016577/27192806-aa03690c-51ca-11e7-898b-baeaf8dc8637.png">
<img width="220" alt="screen shot 2017-06-15 at 1 01 08 pm" src="https://user-images.githubusercontent.com/10016577/27192810-b3fe6a60-51ca-11e7-9db4-a91261a753b7.png">

**Comment by jseppi** [comment]
Thanks for checking into it @wslack. I originally wrote "Add Website" but it should have been the "View Website" button. Nevertheless, I'm also not able to recreate now. I'll more fully confirm later and close if it doesn't happen again.

**Comment by jseppi** [comment]
I have confirmed that this is happening for me on dev and staging, but not on production.

To reproduce:

1. Visit https://federalist-staging.18f.gov/sites/32/settings or any other site settings page.
1. Press <kbd>tab</kbd> until you are focused on the "View Website" button. The text will not be readable.

**Comment by jseppi** [comment]
uhhh...now it isn't happening for me o_O

**Comment by wslack** [comment]
I got nothing. Ask the dev chapter?

**Comment by wslack** [comment]
Marking as blocked until this presents regularly.

**Comment by jseppi** [comment]
Arg, it happened again. However, upon inspection, the styling rules indicate that everything is as it should be. Note the `color: white;` shown in the screenshot below:

<img width="1246" alt="screen shot 2017-06-20 at 4 35 40 pm" src="https://user-images.githubusercontent.com/697848/27357151-b78c4e12-55d6-11e7-9cfe-57aa5abd0a86.png">

However, in the "Computed" styles, the computed color is the federalist blue, even though when that property is expanded it looks like it should be computed to be `white`!

<img width="472" alt="screen shot 2017-06-20 at 4 38 26 pm" src="https://user-images.githubusercontent.com/697848/27357260-2225c0a0-55d7-11e7-94dc-6cbf7317050e.png">

Maybe a Chrome bug?

**Comment by jseppi** [comment]
Tried this on my home Windows PC's Chrome and the bug was reproducible there.

**Comment by wslack** [comment]
Haven't seen in a month; closing!
