### ISSUE TITLE
Superfluous token in build-log API response

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1013]
The `token` property in each of objects in the build-log response seems like it should be stripped from the model during serialization. It's not needed for anything in the front end.

```json
{
  "id": 5583,
  "output": "[clone.sh] Cloning site\nCloning into '.'...\n[clone.sh] Cleaning up",
  "source": "clone.sh",
  "build": {
    "id": 2074,
    "branch": "feature-jobs-by-commodity",
    "commitSha": "4a55dcb6f785023d52fffd2d91e6f038db9ce3b2",
    "completedAt": "2017-06-15T21:54:36.243Z",
    "error": "",
    "state": "success",
    "token": "<THIS DOESN'T SEEM NECESSARY>",
    "site": 42,
    "user": 7,
    "createdAt": "2017-06-15T20:58:31.354Z",
    "updatedAt": "2017-06-15T21:54:36.245Z"
  },
  "createdAt": "2017-06-15T20:59:52.278Z",
  "updatedAt": "2017-06-15T20:59:52.278Z"
},
...
```

thoughts, @jmhooper?

**Comment by jmhooper** [comment]
Agree. If we add that specification to the swagger API spec, it should get picked up by the request specs. There's a function to compare API responses to the spec.

**Comment by wslack** [comment]
Need to make this in the swagger spec and apply to build logs.

**Comment by jseppi** [comment]
It appears to not be in the `/build` response, but is still in `build/<id>/log` response :\
