### ISSUE TITLE
Site Files Table can have blank file names

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1015]
<img width="826" alt="screen shot 2017-06-19 at 2 03 02 pm" src="https://user-images.githubusercontent.com/697848/27301229-1bd31f8e-54f8-11e7-8f4b-e66f63b1f975.png">

Need to investigate further, but I think those might be redirect objects. @jmhooper might know off the top of his head.

**Comment by jmhooper** [comment]
Yep, that would be the route redirect object.

**Comment by jseppi** [comment]
Ok, seems like we could just filter those out from the table display.

**Comment by wslack** [comment]
Likely not worth immediate attention, I think?

**Comment by jseppi** [comment]
I'm already doing stuff with tables, so I'll fix it. It's just one line: `.filter(f => !!f.name)`
