### ISSUE TITLE
Special characters in branch names (like "#") lead to sites that can't be viewed

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1018]
Characters that are allowed in git branch names, but not allowed, or that have special meaning, in URLs cannot actually be viewed. The build itself (and upload to S3) appears to work, however.

I'm not clear on how we want to solve for this. Some possibilities:

- Strip special characters from the branch name (like we do with repo names) for constructing the URLS
- Do nothing, including not doing a build, and communicate the problem to the user.

**Comment by wslack** [comment]
Flag those with a message in the branch list in the "settings" screen?

**Comment by jseppi** [comment]
Here's where I'm going with this:

<img width="770" alt="screen shot 2017-08-03 at 4 43 33 pm" src="https://user-images.githubusercontent.com/697848/28945163-fba358dc-786a-11e7-8e92-854affec3090.png">

Notice that I also changed the link text to hopefully better communicate the production branch site link and the demo branch site link.

Thoughts, @wslack and @jmhooper?
