### ISSUE TITLE
Add a way for hugo version to be specified in Site Settings

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1024]
Because hugo is under heavy development and has new releases quite often, some of which can be breaking, we should provide a way for a user to specify the hugo version used in building a hugo-powered site.

My first thought on how to do this is to show a text box when the `hugo` engine is selected. It can default to whatever we have over in `federalist-docker-builder`'s base image, but the user could then enter a different version string.

**Comment by wslack** [comment]
Honestly, until we see more usage or more stability, I'd rather have people just use the custom config box. I wouldn't want anyone using Hugo until its more stable. If that ok? (or is that box specific to Jekyll?)

**Comment by jseppi** [comment]
Yeah, this doesn't have to be high priority until we get more users of it.

I think regardless of where the user can enter the version it will be nearly the same amount of work. The UI portion of it should be easy either way. The rest of the work is just setting up passing along to the builder, but I'm not familiar enough with how that all works yet to know specifics.

**Comment by wslack** [comment]
Closing unless @jeremyzilar feels this is needed given we haven't heard about it.
