### ISSUE TITLE
[Federalist application] - Navigation Frontend updates

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1026]
This issue for discussion around information architecture/design of the Federalist website.

**Comment by jseppi** [comment]
Here's a quick sketch I did during today's card-sorting exercise with @wslack and @jmhooper:

![](https://user-images.githubusercontent.com/697848/27402501-75b427b0-568c-11e7-8ee9-31534bd97c4f.JPG)

My thoughts:
- Right now, the repo name is a bit disassociated from the left nav, so I think that the repo name ("My Site" in the sketch) should be located above both the nav and the main content. The links to the GitHub repo and to View Site are always shown.
- The selected top-level page (like "Settings" or "Published Data" should be highlighted in the left nav so you know where you are in the site.
- "Published Data" and "Build History" both have sub-pages: respectively, the list of files in a published branch, and the raw build logs for a given build. I think even when viewing a sub-page, the top-level nav item should be highlighted.

**Comment by wslack** [comment]
edited the name of this to reflect focus on the nav's look/feel/use

**Comment by line47** [comment]
@jseppi - I'd love to talk to you about this next week! I have some thoughts on navigation (words used, consistency and navigation in general)

**Comment by line47** [comment]
Here is a thought I has about moving the `view website` and `view repo`
### Screenshot
![screen shot 2017-12-22 at 11 14 25 am](https://user-images.githubusercontent.com/1449852/34304852-80e3ba0c-e709-11e7-893e-b73859dc73be.png)
 links into the left hand navigation along with the other consistent navigation items.

**Comment by jseppi** [comment]
I'm 👍 to moving them over to the nav.

Maybe we could somehow put the view repo into it's own section or something to make it more obvious that it's an external link? And maybe change the text to `GitHub Repo` or something like that?

**Comment by wslack** [comment]
I like having "view website" and "view repo" links in the top right to use that space and avoid clutter on the left side. Is there a benefit to putting them on the left?

**Comment by line47** [comment]
I'm thinking the benefit is making for a consistent user experience by grouping similar top level items on the left and giving more space in the right hand working pane for details. 

- The left hand pane for for navigation
- The right hand pane for details

**Comment by wslack** [comment]
I agree with that, but I don't think the links out to the site build or to the Github repo are like the other items in the menu. You can't navigate back from those outbound links so it feels disjointed to have some items in the menu act like a menu and others not.

But....this is what research is for! @tram whart guideance do you have for us?

**Comment by jseppi** [comment]
Maybe a horizontal divider between those items and the internal items would work well:

```
View Site
GitHub Repo
------------------
Build History
GitHub Branches
Published Files
Users
Settings
```

**Comment by line47** [comment]
I was thinking something similar @jseppi

**Comment by tram** [comment]
Love it. Might want to run this by @OpenGlobe, but maybe something like "Preview site" to differentiate between the preview and live site?

**Comment by OpenGlobe** [comment]
I like "preview site" - seems like it's also consistent with Github's "preview changes"

**Comment by jseppi** [comment]
That link is for the Live Site though, not a branch preview

**Comment by line47** [comment]
I think it's worth mentioning that it would be good to differentiate between `preview site` and `live site` throughout the UI where applicable.

**Comment by jseppi** [comment]
and the third option, `demo site`

**Comment by wslack** [comment]
I don't think the demo site or the various preview links need to be in the permanent nav for a site - and I agree that the word "preview" would be super confusing since there is no one "preview" link for a site.

@line47 can we mock up three or four wireframes or screenshots and show them to users - one based on how it used to look, one based on now, and a few possible changes?

**Comment by line47** [comment]
The view repo and view website links are already permanent as they are on every page view (just not with the other links on the left).

I'll throw some screenshots together to show in this thread and we can also get some folks thoughts on it.

**Comment by wslack** [comment]
Closing as we did some reorg and the status quo is sufficient.
