### ISSUE TITLE
New IA for Federalist

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1027]
Current IA
<img width="330" alt="screen shot 2017-06-21 at 3 53 48 pm" src="https://user-images.githubusercontent.com/10016577/27403875-21ef0ab0-569a-11e7-9edd-9477586fb347.png">

Current Target IA:
<img width="680" alt="screen shot 2017-06-21 at 3 55 07 pm" src="https://user-images.githubusercontent.com/10016577/27403876-220def16-569a-11e7-9cb0-9f489b9a68c9.png">

**Comment by wslack** [comment]
@ASaporta - per your request, are would helping to enact this be interesting? Another option is #940.

**Comment by jseppi** [comment]
@wslack - I don't recall: Should the new Advanced Settings be in a totally separate page from Settings, or in a demarcated "area" (that is perhaps expandable/collapsable) of a single Settings page?

**Comment by wslack** [comment]
@jseppi we said an expandable/collapsable area - so it doesn't need another set of "view site" links

**Comment by jseppi** [comment]
Great - thanks!

**Comment by jseppi** [comment]
Remaining tasks:

- Ability to rebuild a specific branch (from the SiteGitHubBranches table) - #1029 
- Add branch name to Build Logs view - https://github.com/18F/federalist/issues/858
