### ISSUE TITLE
Rebuild branches outside of the 100 item limit

### ISSUE THREAD

**Issue by line47** [18F/federalist#1029]
I ran into an issue where I needed to rebuild a branch that was not in the list of branches that show on the build view (current limit of 100).

My option was to add a change to the branch on GitHub to kickoff the build again because there was not another way for me to kickoff a build.

In this scenario we were working on a `dev` branch and were moving to `staging` and it had been quite some time since we had built the staging branch.

CC @wslack

**Comment by wslack** [comment]
the fix might be adding a "rebuild" button to the GitHub branch list under "Settings" but not sure.

**Comment by jseppi** [comment]
Moving back to Ready in favor of #834

**Comment by wslack** [comment]
@line47 how often did you see this recur?

**Comment by line47** [comment]
It seems I remember that this happened about 2-3 times during that project. 
Maybe we could poll Federalist users to see if there is a true need for this functionality?

**Comment by jseppi** [comment]
@el-mapache is just about finished adding this functionality :)
