### ISSUE TITLE
Make admin pages responsive

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1032]
Admin pages, particularly those with tables, are not very responsive. It would be nice if they were. 

Related:
- https://github.com/18F/federalist/issues/934
- https://github.com/18F/federalist/issues/1026

**Comment by el-mapache** [comment]
I think this issue might be good to close too...Our tables are now at least slightly more responsive, but to make true responsive tables we'd probably have to think about designing the way we present our tabular data on small screens

**Comment by wslack** [comment]
Right, and I don't hear about users needing to do Federalist config on their phones. I'm happy to change this issue to "think about designing the way we present our tabular data on small screens" and iceboxing it.

**Comment by jseppi** [comment]
How about close this and file the new issue if it comes up in the future?
