### ISSUE TITLE
Clair's analyze-local-images tool is now deprecated

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1035]
See notice at the top of https://github.com/coreos/analyze-local-images

This probably means we need to find another way to run Clair on our garden docker images.

**Comment by jseppi** [comment]
Recommendation seems to be to use https://github.com/jgsqware/clairctl

**Comment by jseppi** [comment]
Update on `clairctl`: I followed the instructions in the README at https://github.com/jgsqware/clairctl, waited for it to update its vulnerability definitions, and then used 

```sh
docker-compose exec clairctl clairctl analyze --local federalist-garden-build
```

to analyze my new local image. It says it found 0 vulnerabilities for all layers, which I find suspect:

```
$ docker-compose exec clairctl clairctl analyze --local federalist-garden-build

Image: /federalist-garden-build:latest
 19 layers found

  ➜ Analysis [0748585bfe84] found 0 vulnerabilities.
  ➜ Analysis [e5c6bff5a8f0] found 0 vulnerabilities.
  ➜ Analysis [5364c4a8d87d] found 0 vulnerabilities.
  ➜ Analysis [4cca81bf2456] found 0 vulnerabilities.
  ➜ Analysis [d3f98b765849] found 0 vulnerabilities.
  ➜ Analysis [83ad46f4c46e] found 0 vulnerabilities.
  ➜ Analysis [ddaf9cf0c21a] found 0 vulnerabilities.
  ➜ Analysis [4fcd71cd80ff] found 0 vulnerabilities.
  ➜ Analysis [2739a2f0d538] found 0 vulnerabilities.
  ➜ Analysis [5acf606edf78] found 0 vulnerabilities.
  ➜ Analysis [1fda93fdaac4] found 0 vulnerabilities.
  ➜ Analysis [1c8f4406c8ac] found 0 vulnerabilities.
  ➜ Analysis [a80cf70fb96b] found 0 vulnerabilities.
  ➜ Analysis [77cf162a3aa4] found 0 vulnerabilities.
  ➜ Analysis [7f8af5a36803] found 0 vulnerabilities.
  ➜ Analysis [711091fb1cad] found 0 vulnerabilities.
  ➜ Analysis [3157c92eeff3] found 0 vulnerabilities.
  ➜ Analysis [4ce126ac857d] found 0 vulnerabilities.
  ➜ Analysis [bd028d038089] found 0 vulnerabilities.

cleaning temporary local repository: remove /tmp: device or resource busy
```

Will wait for further guidance out of the ATO process to determine what, if anything, we should be doing regarding container image scanning.

**Comment by jseppi** [comment]
Do we know that we have to have some scanning? If not, then suggest moving this to "blocked" on needing more info until a determination is made.

**Comment by wslack** [comment]
We don't; we've removed everything in this workflow from our deploy process, right? If so, I think we can move this to "Done?"

**Comment by jseppi** [comment]
Works for me!

**Comment by jseppi** [comment]
Oh, I guess we should remove references to `Clair` from `federalist-docs`.

**Comment by wslack** [comment]
Bingo, but if its deprecated, we should do that anyhow.
