### ISSUE TITLE
Buttons in :hover + :focus states have rounded corners

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1044]
Minor styling bug. We have overridden the `.usa-button` classes from the USWDS to have non-rounded corners, but when a button is in both `:hover` and `:focus` states, which happens when you mouse click on them, the rounded corners are visible. 

<img width="360" alt="screen shot 2017-06-30 at 7 51 47 am" src="https://user-images.githubusercontent.com/697848/27736263-18e77990-5d69-11e7-9546-f9a2e827d20a.png">

**Comment by el-mapache** [comment]
I believe this can be closed with the work @line47 did recently!

**Comment by jseppi** [comment]
Confirmed, 🎉
