### ISSUE TITLE
Require HTTPS for demo domain and domain values

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#1050]
Now that we are validating the format of the domain and demo domain, we need to determine which protocols are valid.

I think the expectation is that all of our sites will use HTTPS (since we use the cloud.gov CDN route which handles HTTPS certs). For that reason, I suggest that we only allow `https`. Inviting discussion.

**Comment by wslack** [comment]
agreed

**Comment by konklone** [comment]
👍

**Comment by jmhooper** [comment]
Looks like we're all in agreement. I tagged this with "Documentation" so we can add some docs to communicate this to users.

**Comment by jseppi** [comment]
Moving this to done? because I think https://github.com/18F/federalist-docs/pull/103 takes care of the documentation
