### ISSUE TITLE
Authenticated user can restart builds for a site they don't have access to

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1054]
As reported by `sp1d3rs` in https://hackerone.com/bugs?subject=tts-private&report_id=245872

> ### Steps to reproduce
> 
> 1. Login to the Federalist with your test account (we call it user1).
> 1. Restart the build on one of the sites belongs to you.
> 1. Catch the request to the http://192.168.119.128:1337/v0/build/ and change site parameter to the siteID, which was created on some other account (we call it user2).
> 1. Execute the request. It will be accepted.
> 1. Login as user2 and go to this site's builds. You will notice that build was restarted by another user.
> 
> ### Suggested fix
> 
> It looks like other endpoint (e.g. site settings modify) checks the site id correctly. The fix is add additional check too on this specific endpoint.
>

**Comment by jmhooper** [comment]
We do have a test to make sure this doesn't happen. For some reason, it isn't holding up in staging prod: https://github.com/18F/federalist/blob/45ee891e37d14c2fdb731bd6aa278b1187e0a892/test/api/requests/site.test.js#L132

We'll want to look into why that test is failing while fixing this. From there, we should check on other, similar tests to make sure they don't suffer from the same failing.

**Comment by jseppi** [comment]
Should be this test: https://github.com/18F/federalist/blob/staging/test/api/requests/build.test.js#L124

**Comment by jseppi** [comment]
Here's the problem line: https://github.com/18F/federalist/blob/staging/api/authorizers/build.js#L6

Basically the first part of that if-condition will pass just if the `build.site` is truthy, so it is not actually doing a proper check to make sure the user has access to the specified site id.
