### ISSUE TITLE
Clean up custom / demo domain error label

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#1055]
Currently, the error message when a custom or demo domain is added without `https` is not very clear about what the problem is. We should figure out a way to make it clear that a URL must have `https` in the prefix.

![image](https://user-images.githubusercontent.com/963654/27882929-4d00985e-6194-11e7-841f-e8cf8f8f360b.png)

![image](https://user-images.githubusercontent.com/963654/27882939-58d53e82-6194-11e7-9f19-01c0aab96410.png)

**Comment by jseppi** [comment]
I think we could use the input `oninvalid` hook (https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/GlobalEventHandlers.oninvalid) and call `element.setCustomValidity('Please enter a URL that starts with "https://"')` to resolve this.

**Comment by wslack** [comment]
I think as long as the custom URL docs are clear about this, this update isn't that high priority. We generally walk people through this process.

**Comment by wslack** [comment]
Added such guidance here: https://github.com/18F/federalist-docs/pull/103

**Comment by jseppi** [comment]
Agreed, low priority. It is also low effort to implement though.
