### ISSUE TITLE
Error pages linked-to from GitHub checks can appear blank if user doesn't have proper permissions

### ISSUE THREAD

**Issue by toolness** [18F/federalist#1058]
When working on https://github.com/18F/web-design-standards/pull/2015, the federalist build that was triggered failed and the "Details" link pointed at https://federalist.18f.gov/sites/62/builds/9365/logs.  However, for me this page was almost entirely blank:

> ![blank-federalist](https://user-images.githubusercontent.com/124687/27918034-c01e8fa6-623b-11e7-80cb-deb29fbe2043.png)

I talked to @jseppi and he said that this was because I didn't have permission to view the logs. I thought it might be useful to say as much on this page, instead of being blank, thus I am filing this issue.

**Comment by wslack** [comment]
triaged to top of PR2 backlog. Most of the people who might click on these links aren't authorized for Federalist, so you're in a middle case.

**Comment by wslack** [comment]
This is beautifully fixed!
