### ISSUE TITLE
Error installing Jekyll in build container

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#1066]
A few sites have reporting running into the following error while building their sites:

```
ERROR:  Error installing jekyll:
    "listen" from listen conflicts with installed executable from sass-listen
```

It looks like this happens when the build container executes `gem install jekyll`.

**Comment by jmhooper** [comment]
I was able to recreate the issue locally by uninstalling every gem on my system and trying to install jekyll.

The issue with the executables makes sense. Both the `listen` and `sass-listen` gem have an executable named `listen`, but I can’t figure out why this suddenly started happening. Both gems are dependencies of jekyll. Neither has published a new version since 2016.

Trying to install an older version of Jekyll doesn't seem to solve the problem either.

**Comment by jmhooper** [comment]
This looks like the issue: https://github.com/jekyll/jekyll/issues/6221

**Comment by jmhooper** [comment]
This installs everything successfully:

```
gem install sass:3.4.0 jekyll:3.5.0
```

Now the question is, do we make this change to our build container and then turn around and revert it, or do we wait for an upstream fix from the Jekyll core team?

**Comment by jmhooper** [comment]
Looks like the Jekyll team rolled out a fix for this last night. There's no need to do anything on our end.

**Comment by Faynlee** [comment]
the same problem. :no_mouth:

**Comment by wslack** [comment]
@Faynlee but fixed for you right?

**Comment by Faynlee** [comment]
@wslack yeap, but the other way. I reinstalled ruby as the suggested default path(C:\), and it was fixed .
