### ISSUE TITLE
Consider using GitHub App instead of GitHub OAuth app

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#1067]
Currently, Federalist uses a GitHub OAuth app for authentication. This means that Federalist accesses GitHub on behalf of the user, giving Federalist access to repos the user can access. This is problematic because often there are repositories a user has access to that are outside of Federalist's purview.

An option to consider, is a [GitHub App](https://developer.github.com/apps/building-integrations/setting-up-a-new-integration/about-integrations/). From GitHub's documentation:

> GitHub Apps provide a service to an entire organization and use their own identity when performing their function. They can be installed directly on organizations and user accounts and granted access to specific repositories. They come with granular permissions and built-in webhooks. GitHub Apps are first class actors within GitHub. To install a GitHub App, you must be an organization owner.

A few advantages over OAuth apps are apparent:

- Installed on org-wide basis and can be given access to specific repos
- Built-in webhooks
- More granular permissions
- Act on their own behalf, instead of on the behalf of users

We should looks at how Federalist would function differently if it used a GH app, and at the challenges associated with migrating it to one.

**Comment by wslack** [comment]
cc @thecapacity - know anything about these?

**Comment by thecapacity** [comment]
No - no clue but that feels like something really useful for 18F and GSA repos!

I could see you might need "both" - i.e. maybe an agency+org doesn't want to give Federalist access to all their repos in which case you'd probably stick with OAuth, but maybe they do (e.g. 18F) in which case the GitHub App seems like it would be top notch!

**Comment by wslack** [comment]
I'm not sure they work the same way though. It might not be worth using both.

**Comment by wslack** [comment]
Moved to Ready for @jseppi to assess the difficulty of implementing.

**Comment by jseppi** [comment]
I read over some of the documentation today. I'll probably make a little demo app to see what all is involved first-hand. Then I'll be able to think more clearly about changes we'd need to make to Federalist.

**Comment by wslack** [comment]
SGTM cc @el-mapache if he's curious to pair on it or something.

**Comment by jseppi** [comment]
@el-mapache is taking a first stab at research for this 🎉

**Comment by el-mapache** [comment]
I peeked into this a little bit more today:

* We will still need user's OAuth tokens to clone and create empty repos. According to the GitHub Apps docs, creating repos works server-to-server for **organizations only**. Creating repos for a user's account requires an access token. See https://developer.github.com/v3/repos/#create

* Orgs or individual users can install the app, but we need to set the privacy setting to the app to public. This means that any entity on GitHub could install the app. We'd need to make sure that we check that any org or user attempting to interact with Federalist via a webhook is a member of one of the orgs we officially support.

* We will have control over the permissions, but it looks like they are set on a per installation basis, not a per repo basis. Not sure if we were expecting that, but I thought I would mention it.

* It looks like the user will still have to manually install the github app on their account. They can also choose which repos they's like to authorize when they install the app. We will also be able to programmatically install repos for an installation. 
  * If it makes it easier on users, we could have them install the app, and the next time they log into Federalist, we can add all the repos we have registered.

* I'm not 100% sure, but it looks like adding a repo to an installation requires a token from that installation, so there will be a bit more overhead in our requests.

**Comment by wslack** [comment]
Hmmm. These are not insignificant. Seems like the next exercise would be some type of journeymap for a new users's experience down each path? @onezerojeremy this might be a good project.

**Comment by wslack** [comment]
@davidewarren to book a time to discuss this for 20 minutes with Adam, James, Jonathan, and Will

**Comment by wslack** [comment]
Lessons Learned:

1. We've learned a lot about how GitHub apps work. This reduces the risk of an OAuth token because tokens have more limited permissions.
2. We'd still need their OAuth token to make new repos or clone a repo.
3. Even if you can log into Federalist using an installation instance, we'd still need to have OAuth token.
4. Could move from `user` to `read:user` but would have to keep `repo` in order to clone repos for builds.
5. The actual install process of installing the app wouldn't be tough, and would allow more granular repo control (if users prefer that).

Using a GitHub app will only make sense when: permissions have been more narrowly scoped for the GitHub OAuth app, if the GitHub App Token allows repos to be created and cloned, or if we modify Federalist to not allow private repos (would drop scope from `repo` to `public_repo`).

**Comment by wslack** [comment]
Moved to Done?
