### ISSUE TITLE
Use robots.txt to block search engines from indexing federalist-staging

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1079]
Currently we have the same `robots.txt` served on both [production](https://federalist.18f.gov/robots.txt) and [staging](https://federalist-staging.18f.gov/robots.txt). We should use a different `robots.txt` on staging to block search spiders from indexing the staging domain  because we don't want that to come up when people search for "federalist."

**Comment by wslack** [comment]
I don't know....deliberately desyncing https://github.com/18F/federalist/blob/master/public/robots.txt between branches seems unwise. I'm not opposed to it coming up in Google.

**Comment by wslack** [comment]
Googling "federalist staging" doesn't show the URL. I think Google may already do this for us.

**Comment by jseppi** [comment]
It wouldn't be de-syncing code branches. It would be delivering different robots.txt content based on the `APP_ENV` setting. In fact, we might want to do it based on request url, so that `federalist.fr.cloud.gov` isn't indexed.

I can't think of any way Google would know not to index it as it is currently setup.

![image](https://user-images.githubusercontent.com/697848/28536765-527f331a-706e-11e7-992e-f875684236d5.png)

**Comment by jseppi** [comment]
(also this is quite low effort to implement)

**Comment by wslack** [comment]
Will be closed after confirmed this worked on Prod.

**Comment by jseppi** [comment]
Confirming that now the production route work has been done (#1094) and prod has been deployed (#1104), our `robots.txt` content is properly returned.

Disallow only `/preview` when using the prod hostname:

<img width="415" alt="screen shot 2017-08-07 at 9 20 08 am" src="https://user-images.githubusercontent.com/697848/29030794-db2f6bec-7b51-11e7-94e8-488bd39850ff.png">

Disallow all if not using the prod hostname:

<img width="436" alt="screen shot 2017-08-07 at 9 19 56 am" src="https://user-images.githubusercontent.com/697848/29030801-e034e630-7b51-11e7-8592-5da3e45ac47f.png">

**Comment by wslack** [comment]
👏
