### ISSUE TITLE
/user/:id/builds 404 Not Found

### ISSUE THREAD

**Issue by anweiss** [18F/federalist#108]
As an authenticated user, the API endpoint at `/v0/user/:id` returns a valid JSON object with an array of builds, however a request to `/v0/user/:id/builds` returns a `404 Not Found`. Not sure if it has something to do with the `filterCurrentUser` and `filterSelfOnly` policies.

![image](https://cloud.githubusercontent.com/assets/2326106/8862320/b37a9a12-315d-11e5-8db7-aa782ba0a587.png)

**Comment by dhcole** [comment]
Hmm, I'm not seeing that. Are you seeing any other errors? What are the status codes on the other requests?

<img width="554" alt="screen shot 2015-07-23 at 5 30 40 pm" src="https://cloud.githubusercontent.com/assets/170641/8862704/9b052eb8-3160-11e5-823f-ebe9248a9623.png">

**Comment by anweiss** [comment]
Interesting. Yea, I don't see any other errors other than a 404 Not Found. /v0/user/1 returns a correct JSON response. However `/v0/user/1/builds` and `/v0/user/1/sites` both return 404s.

![image](https://cloud.githubusercontent.com/assets/2326106/8909074/8359fbd2-344d-11e5-8412-a50128f0659f.png)

**Comment by anweiss** [comment]
No longer seeing this error. Closing
