### ISSUE TITLE
[Dev] Webpack generates tons of js and style bundles, which can eat up lots of local disk space

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1089]
Perhaps amend our development webpack config to not create totally new js and style bundles with every build, i.e., get rid of the `[hash]` part of the filenames.

**Comment by jseppi** [comment]
This is more of a developer tooling ergonomics thing than a real `debt` with our actual code.

**Comment by eddietejeda** [comment]
@davemcorwin @amirbey is this still relevant?

**Comment by amirbey** [comment]
@davemcorwin - could speak to this better than I

**Comment by davemcorwin** [comment]
This is only a DX thing so if folks don't think there is a problem, then there isn't a problem :). I think it is ok to close unless @amirbey thinks the current setup is too slow.
