### ISSUE TITLE
Figure out routing for main branch vs previews

### ISSUE THREAD

**Issue by jeremiak** [18F/federalist#11]
Pulling from [code comment](https://github.com/18F/federalist/blob/master/api/services/buildEngines.js#L112) but also related to #10 - right now the sites are built under a directory named for the "owner" and then in another directory named for the branch.

How should the routing work for this when people are trying to see their sites?

**Comment by dhcole** [comment]
Made good progress on this in #91. Just two open tasks to complete. 

@ultrasaurus: we should be able to ship this feature early next week.

**Comment by jeremiak** [comment]
#91 got merged and this is done!
