### ISSUE TITLE
Write up how Federalist defends against malicious code in submitted sites

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1103]
#### User Story

As a person considering using Federalist, I want to know that malicious outside code can't bring down my build container.

#### Background (Optional)

This is a common question.

#### Acceptance Criteria

- [x] We've looked up the documentation about this and recorded a list of links.
- [x] We've written down what happens if someone submits malicious code that "takes over" a process to run a cryptominer.
- [x] We've written down what happens if someone submits malicious code that "takes over" a process to seek to steal the S3 keys that Federalist uses.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by jseppi** [comment]
Will create a google doc

**Comment by wslack** [comment]
@el-mapache interested in this one?

**Comment by jseppi** [comment]
Is this even necessary? Has it come up during the pre-ATO work?

**Comment by wslack** [comment]
Its more a thing for customer conversations. It comes up in sales meetings and we don't clearly explain it anywhere.

**Comment by amirbey** [comment]
Slack thread with cg-support
https://gsa-tts.slack.com/archives/C09CR1Q9Z/p1529605421000647

**Comment by amirbey** [comment]
https://drive.google.com/open?id=1jd7wnIMT9gb643WnTIUMhD7VE3viRsDwb_FkJf-hn-c

**Comment by jmhooper** [comment]
✅
