### ISSUE TITLE
Coverage reports only include the front end tests

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1107]
Since the front end tests are run second by our `yarn test` task, they overwrite and take the place of the back end tests.

I can't figure out a way to get `nyc` to make different coverage reports, which I think would be a solution to this problem. Seems like this issue (https://github.com/istanbuljs/nyc/issues/531) captures the missing functionality.

**Comment by wslack** [comment]
If this is fixed, we can put in controls to alert us when we lose significant test coverage.

**Comment by jseppi** [comment]
Got some advice in #javascript:

* from @cmc333333: Can submit multiple reports to CodeClimate via their CLI. See https://github.com/18F/omb-eregs/blob/master/.circleci/config.yml#L71-L75
* from @LinuxBozo: Use this to merge multiple reports: https://github.com/mweibel/lcov-result-merger

**Comment by jseppi** [comment]
I think @LinuxBozo's suggestion won't be totally straightforward because `nyc` doesn't allow specification of different coverage output filenames (istanbuljs/nyc#531), so it would require some more scripting on our part. i.e., run back-end tests, rename coverage file, run front-end tests, merge coverage reports.
