### ISSUE TITLE
Validate that custom / demo domains don't have paths in the backend

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1108]
We don't support paths (like `https://example.gov/subdir/`) in custom domains, so make sure that any existing custom/demo domains do not include paths.

From discussion in https://github.com/18F/federalist/pull/1106

**Comment by wslack** [comment]
Very low priority. People will learn this since they don't have the power to set up their own subdomains or domains on Federalist.

**Comment by wslack** [comment]
This never came up so closing.
