### ISSUE TITLE
Cannot read property 'completedAt' of undefined

### ISSUE THREAD

**Issue by anweiss** [18F/federalist#111]
Immediately after submitting an initial build for the first site, a `Cannot read property 'completedAt' of undefined` error occurs.

![image](https://cloud.githubusercontent.com/assets/2326106/8908715/954687ea-344b-11e5-8b99-38b47ee5789d.png)

Culprit seems to be [L26](https://github.com/18F/federalist/blob/master/assets/app/views/SiteListItemView.js#L26) in `SiteListItemView`.

**Comment by dhcole** [comment]
This code has been refactored. If you still see an error, please reopen.
