### ISSUE TITLE
Build log page should show "Not logged in" message when the user is not authenticated

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1114]
When a user tries to view a site's logs, such as from the Detail link in a GitHub status report for a failed build, but are not logged-in, they will see the same message as someone who is logged-in but who does not have access to the view the site's logs:

<img width="991" alt="screen shot 2017-08-09 at 4 52 39 pm" src="https://user-images.githubusercontent.com/697848/29145724-e5184b3c-7d23-11e7-81a1-dabaf43baf46.png">

We should tailor the error message for the case of the user not being logged in vs being logged-in but not authorized for the given site.

That is:
- Keep the existing message when a user is logged in but not authorized.
- Show a different message, such as "You are not logged in to Federalist. Please log in." when the user is not logged in. It would be nice if the log-in link in the message redirected back to the same route after successful authentication.

**Comment by jmhooper** [comment]
We had the tooling to set an after authentication path. It was used to redirect to previews after logging in. There may still be some remnants of that. If not, you could probably find it in the history.

**Comment by jseppi** [comment]
Yup, it's still in the back end as the session's `authRedirectPath` property

**Comment by jseppi** [comment]
I think this would be nicely solved by https://github.com/18F/federalist/issues/958

**Comment by wslack** [comment]
Done in #958!
