### ISSUE TITLE
UX for adding a repo for an existing Federalist site is confusing

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1115]
When a user would like to add an _existing_ Federalist site to their Federalist account, the UX is a bit confusing because the user is asked to specify the "Static Site Engine" and "Default Branch" in addition to the repository information. This is a bit scary to the user, and can cause problems if they select values different from those already set for the existing site.

An easy improvement would be to remove those two fields completely from the Add New Site page, and instead have them only on the site settings page. I think we should be able to default the values to `Jekyll` and `master` for sites that are actually "new" to Federalist.

**Comment by wslack** [comment]
Let's add an interstitial when people actually add new sites to get their branch to be published and build engine. Otherwise, keep it simple.

**Comment by jseppi** [comment]
Noting idea so I don't forget:

Upon submitting org and repo name, check response from back end to see if it is a new site or not.
If it is a new site, then display the default branch and build engine form fields before allowing user to continue.
If it is not a new site, then continue on the normal flow.
