### ISSUE TITLE
Gracefully handle if a package.json lacks a scripts object

### ISSUE THREAD

**Issue by konklone** [18F/federalist#1117]
I pushed a repo to Federalist which has a `package.json` but no `scripts` object in it. This caused the build to fail because `require('package.json').scripts` was null:

```
[eval]:1
require('./package.json').scripts.federalist ? console.log('federalist') : null
```

A quick check to make sure that `require('package.json').scripts` is not null before the next conditional would resolve this.

**Comment by wslack** [comment]
Triaged. Seems like an easy fix with some impact.

**Comment by jmhooper** [comment]
The primary challenge is this is not covered by tests and getting the javascript right as a bash string can be tricky. A problem that will hopefully go away once we address this one: https://github.com/18F/federalist-garden-build/issues/52

**Comment by wslack** [comment]
nice work y'all
