### ISSUE TITLE
Make and publish a template for the 18F guides

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1118]
Thanks to @hbillings, we have a great 18F Guides theme. It should be published as a template.

**Comment by afeld** [comment]
https://github.com/18F/guides-template

**Comment by line47** [comment]
I've been working on the [USWDS-Jekyll](https://github.com/18F/uswds-jekyll) template which has a lot in common with the guides template. I would suggest using the USWDS-Jekyll theme to build a guides like site instead of adding the guides theme as a template.

**Comment by adborden** [comment]
What work is left here?

**Comment by line47** [comment]
See this issue which has a bit more detail/info https://github.com/18F/federalist/issues/1242

**Comment by adborden** [comment]
Sounds like we can close this issue if the work is tracked elsewhere?

**Comment by line47** [comment]
I think so
