### ISSUE TITLE
15.3px Meriweather italic on homepage is creepy-looking on Windows

### ISSUE THREAD

**Issue by toolness** [18F/federalist#1124]
The following is based on a [conversation in #visual-design on slack](https://gsa-tts.slack.com/archives/C054CHWSJ/p1502980574000477).

The 15.3px italic variant of the Meriweather font, which is used on the Federalist home page, looks very creepy on Windows machines:

![have-an-account](https://user-images.githubusercontent.com/124687/29422451-3cbf0d6c-8346-11e7-9880-ba0d3555cd2c.png)

If enlarged to 16px, it looks much better:

![have-an-account-16px](https://user-images.githubusercontent.com/124687/29422547-8f3e9e2c-8346-11e7-96b3-fbacdc4e686b.png)

Note that using Georgia instead of Meriweather looks fine even at fractional font sizes.

This issue doesn't surface on OS X, possibly because [Macs and PCs have different philosophies on sub-pixel font rendering](https://www.joelonsoftware.com/2007/06/12/font-smoothing-anti-aliasing-and-sub-pixel-rendering/).

**Comment by wslack** [comment]
I see where we have Merriweather picked (https://github.com/18F/federalist/blob/62a923dbae1c6f00e2f6131f0544ce5fe056a7e1/frontend/sass/_variables.scss) but not the size....any ideas where that is in code?

**Comment by thisisdano** [comment]
@wslack line 22 here for the `p` size:
https://github.com/18F/federalist/blob/62a923dbae1c6f00e2f6131f0544ce5fe056a7e1/frontend/sass/_text.scss

**Comment by wslack** [comment]
Ok, sorry, dumb question as I'm not a front end dev....I don't get why .9em setting leads to 15.3px. Should I just change that to 1em?

**Comment by thisisdano** [comment]
Yeah, the base font size must be set to 17px to yield an effective size of 15.3px at 0.9em. (`15.3 / 0.9 = 17`) Seems like you could get away with setting `p` to `1em` — which would make the effective size 17px. That seems like it looks ok to my eye (though I don't have the perspective of this project's visual designer).

This could be a fine solution here, though if Merriweather performs poorly with fractional sizing on PCs, that will be a problem for other projects, since we can't (and perhaps shouldn't) always rely on whole-number sizing across the board and Merriweather is the USWDS default serif.

We've also taken this up with Merriweather's designer to see if there's anything that can be done at the typeface level as well.

**Comment by wslack** [comment]
Hmmm. Should we change the base size or would that affect the entire site?

**Comment by thisisdano** [comment]
I think scoping to `p` (i.e. setting `p` to `1em`) will limit the effect of the change and be more reliable. Changing the base font size to, say, `17.77777777777` would get you to 16px for the `p` but would _probably_ change the size of every element on the site, would likely introduce more fractional size errors, and it's also kinda wonky. If you _do_ find other instances of spooky italics, you can go and change each case individually.

**Comment by jseppi** [comment]
@wslack - what do you think about moving this up in priority? Seems easy enough to change the `p` styling to `1.0em`. My thought is that a lot of our uses and potential customers are likely on Windows and we want to present a nice looking home page to them.

**Comment by wslack** [comment]
@jseppi endorsed if you feel confident making the change

**Comment by jseppi** [comment]
I'll see how it looks at either `15px` or `16px` equivalent and choose the one that looks best to me.

**Comment by jseppi** [comment]
Well, I just checked out federalist-staging on a Windows machine and changing to `15px` didn't actually solve the issue unfortunately. So fractional sizes aren't the problem. `13px`, `14px`, and `16px` all look good. Even fractional versions of those (like `16.3px`) look ok. Something about values in the `15px` range makes the font render all wonky :\

**Comment by thisisdano** [comment]
Oooof.

**Comment by wslack** [comment]
@thisisdano @toolness care to check out https://federalist-staging.18f.gov/ and see if fixed?

**Comment by jseppi** [comment]
I just checked federalist-staging on my home Windows machine and the font looks good to me!

**Comment by wslack** [comment]
Closing this without review in order to avoid making James demo on his personal machine. Dan and Atul to confirm as well.
