### ISSUE TITLE
Site List ordering can change, which is slightly confusing

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1127]
There is no ordering enforced on the Site List page (https://federalist.18f.gov/sites) so sometimes the order of sites changes which is a little confusing (to me at least). 

It's a very easy fix to just order by `site.id` in the `SiteList` component.

**Comment by wslack** [comment]
They change? Huh. I think this only matters to extreme power users but it it only take 5 minutes to fix, would be fine. Put in backlog for now.

**Comment by jseppi** [comment]
More like 30 seconds:) I'll probably just roll it into some other PR
