### ISSUE TITLE
Add monitoring to federalist-builder to detect cloud.gov auth problems

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1138]
As part of the remediation for the federalist-builder outage on 8/31, it would be very helpful to know when federalist-builder is having problems authenticating to the cloud.gov API (and this unable to launch build containers). 

I think a good way to do this would be to add a healthcheck endpoint that exposes the result (a boolean) of the builder's last attempted authentication attempt to cloud.gov. A "Synthetic" check could then be setup in New Relic to ensure that the healthcheck endpoint is showing a successful result.

**Comment by wslack** [comment]
Is there a way for the health check to monitor a variety of things?   For example, if 10 builds in a row failed, or something like that, I would also want an alert.

**Comment by jseppi** [comment]
For sure, we built a similar endpoint for CALC: https://calc.gsa.gov/healthcheck/

**Comment by jseppi** [comment]
Monitoring has been added to `federalist-builder` staging.
