### ISSUE TITLE
The USA flag in the header may not be displayed in some cases due to the image src path issue

### ISSUE THREAD

**Issue by sp1d3r** [18F/federalist#1149]
Hello. I noticed very small issue with loading the flag icon:

![vc](https://user-images.githubusercontent.com/24297694/30166779-09ad732a-93ed-11e7-8121-5ef115def82e.PNG)

Usually it is unnoticeable, because upon login from the main page the icon path is correct, and this image displayed and cached by the browser on all pages. 
But if you reload the page using CTRL+F5, when staying on the `http://<federalist-domain>/anypath/` - the icon will disappear, because request will be done to the `http://<federalist-domain>/anypath/images/us_flag_small.png` - instead `http://<federalist-domain>/images/us_flag_small.png`

https://github.com/18F/federalist/blob/staging/views/base.njk, line 50:
```
src="images/us_flag_small.png"
```
should start with a `/`
```
src="/images/us_flag_small.png"
```
to prevent this.

**Comment by jseppi** [comment]
Whoops, good catch! Opened https://github.com/18F/federalist/pull/1150 to address.

**Comment by wslack** [comment]
@sp1d3r merged fix into staging, thank you!

**Comment by sp1d3r** [comment]
You're welcome, it's a pleasure for me to work with your team!:blush:
