### ISSUE TITLE
Jen drops her blue SVG Federalist logo into this repo

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1152]
Per https://gsa-tts.slack.com/archives/C02QNKTNK/p1463597438000666 -
 so that we all have access to the blue SVG file! https://github.com/18F/federalist/tree/master/public/images

**Comment by jenniferthibault** [comment]
Added in #1162 
It would have been nice if past me had just added the file to that original slack convo! I was able to dig it up through Illustrator files in Google Drive

**Comment by wslack** [comment]
all good - and now we have it (and I know that .ai files can be converted to .svg)
