### ISSUE TITLE
Consider replacing moment.js in our front end bundle

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1160]
`moment.js` is ~126 Kb of our bundle, which is nearly the same size as all of our custom code.

We barely use it, so I think we could get rid of in and instead use maybe https://date-fns.org/ and some other smaller humanize lib.

**Comment by el-mapache** [comment]
Might be worth investigating, but I believe we can just include the functions we need now from moment, rather than bringing in the entire package.

**Comment by jseppi** [comment]
Looks like moment still has open this issue from 2015 about making it more modularized: https://github.com/moment/moment/issues/2373

I couldn't find any reference to just bringing in required functions.

**Comment by el-mapache** [comment]
I see, I noticed in their source that they were exporting each function, but I guess they haven't actually exposed that to the user when installing via npm

**Comment by wslack** [comment]
What's the defnition of done and level of effort here @jseppi?

**Comment by jseppi** [comment]
AC:
- moment is no longer in the front end bundle, but datetime formatting still works as desired

LOE:
- already done in #1475 :)

**Comment by wslack** [comment]
LOL. Got it.

**Comment by jseppi** [comment]
Done by #1475
