### ISSUE TITLE
when I go to a federalist site and am prompted to authenticate, I should be sent to the site after authentication

### ISSUE THREAD

**Issue by ultrasaurus** [18F/federalist#117]
when I go to a federalist site and am prompted to authenticate, I should be sent to the originally requested URL after authentication

Steps:
1. Go to a site (branch) that requires authentication
2. Login
Result: I see Federalist page asking me if I want to create a site
Expected:  I should be re-directed to the URL I originally tried to go to

**Comment by dhcole** [comment]
Across the site, if you access a page without signing in first, #303 will take users back to the home page. The next step to accomplish this (and similar issues on other pages) would be to capture the user's intended URL in a cookie or local storage, and then after successful authentication, redirect the user back to that route. Or we could try passing that path as a query parameter back to the API controllers `/auth` routes, which would need to then use it to change the `redirect_uri` sent to github so github sends the user back directly to the desired page after authentication.
