### ISSUE TITLE
Error when trying to delete site from Federalist

### ISSUE THREAD

**Issue by sp1d3r** [18F/federalist#1170]
Hello. After last updates i noticed, that "delete site" option stopped working.
This button is now sending same request as "Save" button. It happens possibly due to JS error.

![2](https://user-images.githubusercontent.com/24297694/30606633-fd4d5f40-9d7a-11e7-8fb2-52d2bc9f1235.PNG)
![1](https://user-images.githubusercontent.com/24297694/30606634-fd555ac4-9d7a-11e7-90f6-613c96bbc0ae.PNG)

**Comment by jseppi** [comment]
Thanks for the report, @sp1d3r - we'll look into it!
