### ISSUE TITLE
Use consistent capitalization in top nav

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1193]
"Log out and Log in" are in sentence case; the others are all in title case.

I think our writing guide recommends sentence case in general, so perhaps we should go with that. 

<img width="509" alt="screen shot 2017-09-27 at 10 44 42 am" src="https://user-images.githubusercontent.com/697848/30931376-fe6e6fee-a370-11e7-8736-87fae8d7b219.png">

<img width="471" alt="screen shot 2017-09-27 at 10 44 57 am" src="https://user-images.githubusercontent.com/697848/30931383-049ccd7a-a371-11e7-90f8-ee4478d4e615.png">

**Comment by wslack** [comment]
agreed per https://content-guide.18f.gov/capitalization/. Opened a PR.
