### ISSUE TITLE
Set up starter templates for new sites

### ISSUE THREAD

**Issue by dhcole** [18F/federalist#12]
Instead of building their own Jekyll sites, developers may prefer to start with a template. We could offer a few templates that are pre-configured to work well with Federalist / Prose. Developers could select one, which would fork it to their own GitHub account, and allow them to make edit content through Prose or make changes to the layout through GitHub / local editing.

This raises some general questions: 

- What should a generic starter template include? For instance, what templates, page types, basic features does it need?
- What open source templates are available that we can use / modify for our purposes?

Steps to ship:

- [ ] Identify template requirements
- [ ] Fork and modify open source sites to meet requirements
- [ ] Allow Federalist users to fork a starter template to their own account

**Comment by dhcole** [comment]
Initial thoughts for template requirements:

- 508 compliant
- DAP code
- Prose configuration

**Comment by dhcole** [comment]
Initial template ideas

- Basic "brochure" site for new department, agency
- API doc site
- Interactive report site (like http://www.shopify.com/2013)

**Comment by jeremiak** [comment]
From what you know of the potential first users (or other static sites that 18F has done so far) is there a need for a blog-like site with feeds such as RSS/Atom?

**Comment by jeremiak** [comment]
Also, just because I'm still relatively uninitiated, what is a "DAP code"? I assume its analytics but does it function in a manner similar to Google Analytics?

**Comment by dhcole** [comment]
Yea, sorry, we should [ban acronyms](https://twitter.com/collision/status/602950284864692224). DAP is the [Digital Analytics Program](https://www.digitalgov.gov/services/dap/). It runs a government-wide Google Analytics account that feeds https://analytics.usa.gov/. 

Federalist should be a steward of best practices for government websites, so we should just bake things like this (and correctly configured HTTPS) into the templates and hosting.

**Comment by dhcole** [comment]
> From what you know of the potential first users (or other static sites that 18F has done so far) is there a need for a blog-like site with feeds such as RSS/Atom?

Good question. @gboone @meiqimichelle @shawnbot  @melodykramer @ultrasaurus @blacktm @gbinal: care to weigh in on what you'd want to see out of Federalist templates?

**Comment by dhcole** [comment]
There are some interesting ideas here: https://github.com/mdo/jekyll-snippets

**Comment by meiqimichelle** [comment]
None of the sites I've worked on so far have been blog-like.....except our own 18F blog. In my world, I don't see a use for the in the near future. Let's see what the others have :)

**Comment by blacktm** [comment]
Jekyll sites can certainly include blog capabilities without being blog centric. For a resource, here's my template (forked it for the "military-onesource-federalist" linked above): https://github.com/blacktm/standard-jekyll-template

**Comment by meiqimichelle** [comment]
@blacktm True. I interpreted the ask as "in the short term, what should we focus on templating first?" In my future, there is no need for blog capabilities.

**Comment by gbinal** [comment]
Re: existing templates, I've built both of these and welcome their being taken over/absorbed/made redundant/whatever:  
* [Examples of GH-Pages sites - both federal and not](http://gsa.github.io/Open-Data-Collaboration-Sandbox/website_examples/)
* [USG Website Templates](http://usg-website-templates.github.io/)

re: features, functions - i think it's easy to include a blog and/or rss capability that folks can remove or not use, so totally recommend it.  I have other ideas of possible features but the main ones that come to mind for me (beyond blog/rss) include: 
* light "api" [csv-based](https://github.com/GSA/Very-Simple-API-2) and/or [yml-based](https://github.com/GSA/Very-Simple-API)
* [api documentation](http://18f.github.io/API-All-the-X/pages/open_source_documentation)

**Comment by afeld** [comment]
Other template examples we have/use:

* http://if.io/open-source-program-template/
* https://github.com/18F/guides-template

**Comment by gboone** [comment]
RSS/Atom feeds are probably not a primary need but there are many good examples of how to do them well in Jekyll. [18f-site does them](https://github.com/18F/18f.gsa.gov/blob/staging/feed.xml), and there's also a [plugin built by Jekyll](https://github.com/jekyll/jekyll-feed) for creating feeds. 

> i think it's easy to include a blog and/or rss capability that folks can remove or not use, so totally recommend it.

Ditto. And if someone wants to have a blog or we give them a template that includes one but _doesn't_ come with feeds that would be jarring.

**Comment by bradnunnally** [comment]
One of the things you mentioned @dhcole was that the users would be developers tasks to create these static sites for other agencies. Does that mean we are defining developers as the users of Federalist? Or would it be the content writers/owners/editors that work at the agencies which would own the sites? 

I mean in reality I could see both of them being A user of the platform, but which do we feel is the primary?

**Comment by dhcole** [comment]
Two user groups:

1. Developers who want to build a site and turn it over to content editors to run
2. Content editors who get a site to maintain from a developer OR who need to set up a simple site from a template and don't have a developer available to set up the site (like someone doing comms for a task force that wants to publish a report, or someone who produces a dataset as an API and wants to publish docs [ @gbinal's example])

**Comment by bradnunnally** [comment]
Thanks @dhcole. That's what I was thinking and hoping you'd say, but good to have it "written down". 

I'll start putting some thought as to how we can gather some information from folks that fit that category so we can start thinking about overall flow and on going feedback cycles with end users.

**Comment by bradnunnally** [comment]
I've written up a brief user profile for a Site Developer, based on what I've read on this repo and general thoughts. I'll talk more about it at the 3CST standup. 
![federalist_diagrams_v0](https://cloud.githubusercontent.com/assets/12515096/8067591/4e12e0ec-0eb4-11e5-89be-e443feb8018e.png)

**Comment by melodykramer** [comment]
@dhcole I think it's a good idea to have interactive reports. If you want, I could ask the SM listserv to take a quick survey for use cases. Off the top of my head:

1. publishing a guide (http://nces.ed.gov/programs/coe/) (http://publications.usa.gov/)
2. documenting APIs or code
3. walking someone through a series of steps or instructions (http://business.usa.gov/start-a-business)
4. static information about resource (http://www.achp.gov/)
5. displaying photos or multimedia (http://www.usa.gov/Topics/Graphics-State.shtml)
6. contacting the government (http://beta.usa.gov/contact-by-topic)

When these templates go live, it may be good to give several examples like the ones listed above. "You can use this template if you'd like to create a series of instructions." etc.

**Comment by bradnunnally** [comment]
Here is the draft user profile for the content editor. 
![content_editor_v0](https://cloud.githubusercontent.com/assets/12515096/8086889/55e22856-0f5d-11e5-9aba-d6477b0d302a.png)

**Comment by bradnunnally** [comment]
Sketch time! I sketched up a quick idea (read - they will require many more iterations) that represent what the new user and established user view would look like. I'll start fleshing these out in Omnigraffle to play around with the concepts more. 
![img_4722](https://cloud.githubusercontent.com/assets/12515096/8093971/c6e93626-0f89-11e5-9272-8d7266423a88.JPG)
![img_4723](https://cloud.githubusercontent.com/assets/12515096/8093972/c6ed3ece-0f89-11e5-894a-281958bb3589.JPG)

**Comment by jeremiak** [comment]
So I think the following two templates would be excellent candidates for the first stab at the prototypal site creator:

* [Microsite](https://usg-website-templates.github.io/microsite-template/)  -  [repo](https://github.com/USG-Website-Templates/microsite-template)
* [Developer hub](http://usg-website-templates.github.io/developer-hub/)  -  [repo](https://github.com/USG-Website-Templates/developer-hub)

I think the first pass at this will have Github fork either of these repos to the user's account. Then we can play around with what settings we'll want in the _config for prose and open further issues for those.

**Comment by bradnunnally** [comment]
Here are some wireframes for the first time use and established user for the main landing page. @dhcole & @jeremiak if you'd like me to post these elsewhere, please let me know. Regarding the wireframes themselves, critique away! What doesn't make sense? What's confusing? What's missing? What needs to be added? How can it be simpler, but still clear?
![federalist_wireframe_established_user](https://cloud.githubusercontent.com/assets/12515096/8112983/eca10130-1030-11e5-8f0f-114dc0fbd273.png)
![federalist_wireframe_established_user_add](https://cloud.githubusercontent.com/assets/12515096/8112985/eca34bfc-1030-11e5-84b2-223ec59fd28a.png)
![federalist_wireframe_first_time_user](https://cloud.githubusercontent.com/assets/12515096/8112984/eca27e3e-1030-11e5-8d23-5c70a76324c1.png)
![federalist_wireframe_first_time_user_add](https://cloud.githubusercontent.com/assets/12515096/8112986/eca408a8-1030-11e5-82b5-158d2d010e67.png)

**Comment by jeremiak** [comment]
@bradnunnally cool! I'd say just open a [new issue](https://github.com/18F/federalist/issues/new) for these wireframes to be fleshed out and then implemented :)

**Comment by bradnunnally** [comment]
I can do that!


... I think.

**Comment by dhcole** [comment]
@bradnunnally want to summarize this conversation into a wiki page for template ideas? Seems like a simple homepage, reports, developer dashboard are some really actionable templates we can figure out.

**Comment by jeremiak** [comment]
Cool, I think I can knock this out pretty quickly. @dhcole can you point me in the direction of any `DAP` integration guides? I'm hoping that it is just a script tag with a unique ID or is that being too optimistic?

**Comment by dhcole** [comment]
@jeremiak not sure exactly...  but I pinged in the #dap room on Slack. If we don't hear back, we can email dap@gsa.gov. That's the usual on-boarding process.

**Comment by afeld** [comment]
More info here:

https://github.com/18F/analytics-standards

**Comment by jeremiak** [comment]
Cool, thanks @afeld - that's really helpful. Also, really cool that it is that easy to integrate. I'm going to close this issue because of #55 and we can open more specific issues for improvements to the templates so they don't get lost.
