### ISSUE TITLE
Add ability to add user from the Site Collaborators view

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1205]
#### Description of feature or bug

Add form to add a user to a Federalist site from the Site Collaborators page.

#### Definition of done

- Front end form to add a user by GitHub username is on the Site Collaborators page
- Backed validates that the username is valid and has "write" access to the associated repository
- Errors are displayed when they happen
- Success message is displayed when user is added successfully

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

Most of the logic for adding a user to a site already exists. This would primarily entail front end work for implementing the new form on the Site Collaborators page.

- Add back end API route
- Create form component
- Add form to Collaborators view
- Test

**Comment by wslack** [comment]
I'm curious how much work this is. If substantial, not sure we should prioritize since there's a working "add user" workflow already.

**Comment by jseppi** [comment]
Removing a user should be fairly easy. Adding one is a little more work for handling the cases where 1) that user isn't yet in Federalist at all; 2) checking that they have repo access. We have the logic for 2 already in the app, so it will be extractable/reusable.

**Comment by jseppi** [comment]
User removal has been implemented -- updated the issue title to reflect that only user adding is missing.

**Comment by wslack** [comment]
👍  adding is much lower priority.

The other check needs to be that the GitHub account has a Federalist login already, and the page will need to be clear that the screen doesn't send invites to Federalist; those need to go to the support e-mail.

**Comment by jseppi** [comment]
I don't think we'd necessarily need to check that the GH account has an associated Federalist account already.

We'd create the `User` model in Federalist if all the GH permissions check-out. Then, when the user first logs-in afterwards, their Sites List will be pre-populated with everything they'd been added to.
