### ISSUE TITLE
Branch input styling is different from url input styling

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1206]
Minor issue.

The branch inputs have a wide light gray outline, while the URL inputs have a thin black outline. They should probably be consistent:

<img width="490" alt="screen shot 2017-10-03 at 4 22 16 pm" src="https://user-images.githubusercontent.com/697848/31149887-31cc2666-a857-11e7-937e-6e53b42494f7.png">

**Comment by wslack** [comment]
Is this how the USWDS handles text boxes vs URL boxes, @maya?

**Comment by maya** [comment]
USWDS default styling is the latter, but I think a previous designer styled it to look like the former (thicker outline).

**Comment by wslack** [comment]
Cause is here: https://github.com/18F/federalist/blob/staging/frontend/sass/_forms.scss#L15

**Comment by jseppi** [comment]
Thanks. Just needs a `input[type="url"],` added there

**Comment by wslack** [comment]
Wouldn't it be `input[type="text","url"]`?

**Comment by jseppi** [comment]
No, that won't work. Needs to be a separate target.

**Comment by wslack** [comment]
I think I prefer the USWDS styling. Do you like the gray more?

**Comment by jseppi** [comment]
No preference other than consistency. If we change back to default, we also should change the `<textarea>` styling back to that as well.
