### ISSUE TITLE
Default to nvm 6.x (or latest)

### ISSUE THREAD

**Issue by konklone** [18F/federalist#1209]
A couple of customers now (myself included), have gotten bit by not having a `.nvmrc` that locks the Node version to something higher than what Federalist defaults to.

How about reversing this, so that Federalist defaults to using a later/latest version of Node, and instead having it break by default for folks depending on older behavior?

**Comment by wslack** [comment]
@jseppi @jmhooper welcome your ideas here.....I don't like the idea of old sites without a setting suddenly breaking but this is also a non-obvious issue.

**Comment by jmhooper** [comment]
We're going to have to upgrade eventually. Same goes for the ruby version. I don't suspect many sites will notice anything. 

:+1: from me as long as we have good comms with our customers beforehand.

**Comment by wslack** [comment]
yeah I bet internal folks will care the most.

What cadence should we have for updating the default?
