### ISSUE TITLE
Windows and Azure Installable Hook

### ISSUE THREAD

**Issue by anweiss** [18F/federalist#121]
Creating this issue for tracking purposes. To support #97 and #98 and in reference to the new [buildEngine](https://github.com/18F/federalist/blob/master/api/hooks/buildEngine/index.js) hook, an additional installable hook is being developed and maintained here: https://github.com/Microsoft/sails-hook-federalist-ms. A separate PR will be submitted upon completion of the hook's development so as to provide instructions in the README for enabling build support on Windows and publishing to Azure.

**Comment by dhcole** [comment]
:+1: this is looking great

**Comment by dhcole** [comment]
Followed up in #137. Next action is to refactor as a documentation change.
