### ISSUE TITLE
Create a way for Federalist to push notify users when builds are complete

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1215]
#### Push build status updates to browser

Users won't have to periodically refresh their browser to see when a build has finished. Provides a better overall UX

#### Definition of done

- [x] server side code to push updates to browser
- [x] client-side code to receive these updates (and develop tests)
- [x] bonus: popup browser notification that tells user the build is complete
- [x] We send notification out to partners!

#### Level of effort - <low/medium/high>

**High**

#### Implementation outline (if higher than "low" effort):
- [x] add sockets.io to server to to push build status messages
- [x] setup Redis and redis adapter to broadacast notifications across all Federalist instances
- [x] add sockets.io-client to frontend components to display received push notifications

**Comment by jseppi** [comment]
related:
- https://github.com/18F/federalist/issues/412
- https://github.com/18F/federalist/issues/886

**Comment by amirbey** [comment]
https://developers.google.com/web/fundamentals/push-notifications/display-a-notification

**Comment by wslack** [comment]
Current status:

- Some tests are failing
- Some issues with the tests initializing socket.io on the client side

Next Step:
- Make the test work
- Do the auth in rooms/namespace

**Comment by wslack** [comment]
Yaaaaaaaaay!
