### ISSUE TITLE
Hook up child components of SiteContainer to redux store instead of passing props

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1218]
To be more properly redux-y, instead of passing `childConfigs` to the `children` of `SiteContainer`, we should instead hook up each child component to the redux store using `connect(...)`.

This will have testing and code readability benefits.

**Comment by wslack** [comment]
what's the level of effort here?

**Comment by el-mapache** [comment]
Level of effort is medium-ish. It's not particularly difficult but will probably take more than a couple hours due to the number of components touched.
