### ISSUE TITLE
Change "add site" to use a link to the repo

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1222]
Instead of this, we should just ask for a URL to the GitHub repo:

![screen shot 2017-10-11 at 12 42 07 pm](https://user-images.githubusercontent.com/10016577/31453878-9e4a08f0-ae81-11e7-91b1-7beafc59fff9.png)

**Comment by jseppi** [comment]
We can split the repo URL on `/` and grab the last two items (which correspond to the `owner` and `repo` values.

**Comment by wslack** [comment]
👍  (one of those obvious things we should have done a while ago)

We should give an example when changing thing, like:

`Example: https://github.com/18F/federalist`
