### ISSUE TITLE
Adding an already added site results in a duplicate error message (on another page)

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1228]
Likely caused by #1221 or #1224 

Steps to recreate:

1) For a site already in Federalist and attached to your account, add it again via the GitHub Repo URL input on the Add Site page
2) You should see an error message on the top of the next page (the Sites List page).
3) Navigate to the Builds page for that site (by clicking on it in the Sites List). You will still see the same error message.

Expected result:

The error message should only be shown on the Sites List page.

<img width="1023" alt="screen shot 2017-10-20 at 4 17 56 pm" src="https://user-images.githubusercontent.com/697848/31842197-8712d29c-b5b2-11e7-98d0-158f4775dccb.png">

**Comment by jseppi** [comment]
If I comment out this line https://github.com/18F/federalist/blob/staging/frontend/components/app.js#L21
then this bug goes away. I'm not totally sure the reasoning behind that line, though, and am worried that removing it will probably cause some other issue. Any insight, @jmhooper?

I think the code that is probably involved with this situation is the `addUserToSite` action and its error-handling logic:

https://github.com/18F/federalist/blob/staging/frontend/actions/siteActions.js#L36-L53

**Comment by jseppi** [comment]
Ah, ok, I now think that the linked line is so that when a page doesn't change location upon some form submit, that the error will be shown. Like if there is an error when submitting the Site Settings form.

**Comment by jseppi** [comment]
This is not yet fixed

**Comment by el-mapache** [comment]
@wslack The error is being removed upon navigation, but it persists on the screen until the page has fully loaded. Shouldn't be too tough to fix it!

**Comment by wslack** [comment]
Oh - yeah that seems simple and worth prioritizing.

**Comment by jseppi** [comment]
@el-mapache already implemented this fix in #1424 🎉
