### ISSUE TITLE
Create docker-compose setup for Federalist

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1229]
For ease of development, it would be good if we had a working docker-compose setup for Federalist.

**Comment by jseppi** [comment]
It should be fairly easy to get a docker-compose setup working for the Federalist web app (ie the web app + Postgres), but a whole-system-docker-compose (federalist, federalist-builder, federalist-garden-builds, etc) would probably be a pretty big lift.

**Comment by wslack** [comment]
@jeremiak WDYT about the webapp vs the whole kit n' kaboodle?

**Comment by wslack** [comment]
We should discuss more about the cost vs reward here. Iceboxing for now.

**Comment by jseppi** [comment]
Here's the dockerizing issue, @wslack. I think we could get the main web app dockerized relatively easily.

Making a full-system setup would be harder due to all the S3/cloud.gov pieces.

**Comment by wslack** [comment]
What is "easy?" 5 hours? 20 hours?

Can you explain more about the benefits in terms of metrics?

**Comment by jseppi** [comment]
I think on the order of 2-4 hours. But, as I understand agile estimation, we're not really supposed to guess hours, just levels of (relative) effort.

The benefit is that getting new developers/designers/security researchers/etc setup with a local instance would be much faster (a few minutes) and require fewer steps (probably to 4~6 instead of the current 16). It would hopefully also obviate needing an experienced dev to pair during the setup process.

**Comment by jeremiak** [comment]
For what it is worth, I think that the docker compose would be most valuable if it is the entire system. That would not only significantly help with re-use (other Feds or people being able to use the system on their own) but would dramatically lower the set up costs for people who want to contribute to the code or fix bugs

**Comment by jseppi** [comment]
For sure, but that’s a much larger level of effort due to how build
containers are launched via CloudFoundry, and the use of SQS and S3.

Dockerizing the web app will be a necessary step in further system
dockerizing anyway.


On Nov 22, 2017, at 12:36 PM, Jeremia Kimelman <notifications@github.com>
wrote:

For what it is worth, I think that the docker compose would be most
valuable if it is the entire system. That would not only significantly help
with re-use (other Feds or people being able to use the system on their
own) but would dramatically lower the set up costs for people who want to
contribute to the code or fix bugs

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/18F/federalist/issues/1229#issuecomment-346437910>, or mute
the thread

**Comment by jmhooper** [comment]
When dockerizing the main app, I'm not sure how many of the more painful steps we could remove. You would still have to register a GitHub org, you would still have to register a GitHub OAuth application, and you would still have to grab the SQS creds from the staging environment in cloud.gov.

As the team grows, I do see a benefit in having all of the team with the app configured the same way. If we could Dockerize it such that all of those secrets are env variables instead of keeping them in the `local.json` file (which can be used to override pretty much any config and occasionally gets out of date) I think we benefit.

**Comment by jseppi** [comment]
I think it would help a lot with having postgres and node versions specified totally within the docker environment, so that folks don't have to manage versions of those themselves. Those are some of the bigger stumbling blocks that came up with this most recent round of getting new people setup.
