### ISSUE TITLE
Add functionality to repoint Federalist to a new repo

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1230]
Might be a dup; not sure. This would allow us to move sites. @jseppi did we already estimate the effort here?

**Comment by jseppi** [comment]
We have not.

Off the top of my head, it seems like it could be a little complicated. I think, as you mentioned, the easiest thing to do on the back end is to delete the existing site, add the "new" one, add the current user to the new one, and transfer the settings. The other users and previous build history would be lost.

**Comment by wslack** [comment]
Aha, it was in https://github.com/18F/federalist/issues/1226. Closing this as a dup.
