### ISSUE TITLE
Consider adding an example site on the plain language site

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1239]
https://plainlanguage.gov/

**Comment by line47** [comment]
This site is built off of the uswds-jekyll theme, what are the takeaways we would like to have here?

@hursey013 worked to create this and might know what would be good to work back into the templates as well.

**Comment by wslack** [comment]
The menu and downloads styling on https://plainlanguage.gov/guidelines/, the footer and header simple design.

**Comment by wslack** [comment]
(and another example of the kind of look/feel you can have with federalist). 

Maybe part of my interest is in these showing the "range" of Federalist, to spark imagination.
