### ISSUE TITLE
Consider adding a template based on the login.gov site

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1240]
Could be for the whole site or subcomponents like https://login.gov/help/

**Comment by line47** [comment]
@wslack are there specific components or design elements that are the reason to consider adding this site as a template?

**Comment by wslack** [comment]
How the menu, header, and footer works, and the scrolling feature at https://login.gov/playbook/principles/#privacy

**Comment by line47** [comment]
**Here are the takeaways I'm seeing that we could use**
- The right menu is sticky
- extra slim footer

**Here are the takeaways I'm seeing that we don't need**
- the header could be styled like the https://components.standards.usa.gov/components/detail/header--basic.html

let me know if I'm missing something @wslack

**Comment by wslack** [comment]
hmm. I like the view-on-mouseover feature of the login header but otherwise agree.
