### ISSUE TITLE
Consider adding an example site based on the FOIA site

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1241]
@AvivaOskow to look up a URL

**Comment by line47** [comment]
I think this is referring to https://open.foia.gov/ which is no longer available.  @AvivaOskow is this correct?

![screen shot 2018-01-09 at 10 23 26 am](https://user-images.githubusercontent.com/1449852/34728141-0e17f05c-f527-11e7-8e6d-4e8e12556ab4.png)

**Comment by adborden** [comment]
:wave: I setup open.foia.gov with this redirect, and I believe this is what should be made into an example site. Several folks have asked how to setup a domain redirect like this on Federalist, so it sounds like folks are interested in having an example or having it documented.

Is that what you were after when you created this issue @wslack ?

**Comment by line47** [comment]
Thanks for clarifying @adborden 👍

**Comment by wslack** [comment]
I think so - if I filed this after the redirect was in place, the intent is to make a templated site that people can use to deploy a soft redirect + explanation.
