### ISSUE TITLE
Add a template to Federalist based on our guides styling

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1242]
**Definition of done**
- [ ] When we can replace a guides site like https://agile.18f.gov/ with the [Federalist-uswds-template](https://github.com/18F/federalist-uswds-template)

**Comment by line47** [comment]
I have some thoughts here, the [USWDS-Jekyll](https://github.com/18F/uswds-jekyll) and the [guides template](https://github.com/18F/guides-template/) are very similar and I've been working to incorporate any functionality from the guides template into the uswds-jekyll. 

Question: Is there a particular guides site (URL) you have in mind to use at the template?

**Comment by wslack** [comment]
The template would not have any guides content but I think I want to use the styling at https://eng-hiring.18f.gov/ or https://boise.18f.gov/

**Comment by line47** [comment]
So basically this type of style layout (minus the top nav) https://standards.usa.gov/page-templates/docs/#section-heading-h2 

☝️ This is already part of USWDS-Jekyll

**Comment by wslack** [comment]
Hmmmm. That makes sense, but I would love a version from the USWDS site that's a little more stripped down - no headers, no complex footer. Is there a version of the site stripped of that?

**Comment by wslack** [comment]
The other, basic thing about this template is that anyone making a guide in the future would want it, so having the "guides" stuff in the footer is helpful from the getgo.

**Comment by line47** [comment]
Yeah I think these are all easily achieved and would like to get some different versions of the theme up for previews to see what can be done. I'm a bit unsure how we can get the uswds-jekyll setup within federalist so I can build out a few preview URLs with these different variations.

**Comment by wslack** [comment]
What happens when you just add the repo? (I don't know enough about it to see if Federalist can build the repo as is)

**Comment by line47** [comment]
Is there a way to try to add this branch as a template option in a staging environment to see if it's possible? https://github.com/18f/federalist-uswds-template/tree/report-config @jseppi

**Comment by wslack** [comment]
I think we can link to that build out from the branch table but I don't think the backend supports cloning a repo and then building out with a different master branch

**Comment by line47** [comment]
The code in the templates.js file leads me to believe we can point it at a branch other than `master`
```
  report: {
    owner: '18f',
    repo: 'federalist-report-template',
    branch: 'master',
    example: 'https://federalist-report-template.18f.gov',
    title: 'Basic Report Template',
    description: 'A basic template to host a set of pages about a recent report or order.',
    thumb: '/images/federalist-report-template.jpg',
  },```

**Comment by wslack** [comment]
(mving convo here from Slack, I suggested we go ahead and try this in staging, see if it works)

**Comment by line47** [comment]
Set the `report-config` branch for the report template and added a new website locally. And it seemed to work as expected, but I'd still like to try this in staging...

![screen shot 2017-12-15 at 2 24 41 pm](https://user-images.githubusercontent.com/1449852/34057136-d2bd9c82-e1a3-11e7-84b3-e9609f8ea176.png)

**Comment by jseppi** [comment]
I _think_ that will work, but it will also create the same branch name on the repo that is created for the user, which is a little weird. Which I think is what your screenshot shows, @line47.

**Comment by wslack** [comment]
I think we should just try it in staging.

**Comment by line47** [comment]
Agreed @jseppi, that does seem a bit odd.
With that in mind does it then make sense if you are creating a new site using one of our templates that happens to be a sub branch for it always to name the branch you are creating `master` ?

**Comment by jseppi** [comment]
yes, I think that would make sense. it would also be a fairly easy change in our new build container :)

**Comment by line47** [comment]
Opened PR https://github.com/18F/federalist/pull/1381 against staging to test this functionality

**Comment by wslack** [comment]
Hmmm. I'm less sure, if only because that means that the base repo won't have any "master" branch.

Why not just change what is set as the default branch?

**Comment by line47** [comment]
Just tested this out on `staging` and worked as expected! 🚀 

I'm going to add an issue for when adding a new site always create a `master` branch no matter what the branch name is of the site you are creating from. For example if I am creating a site from a branch named `awesome-branch` it will create my new site under the branch name `master`.

CC @jseppi @wslack

**Comment by line47** [comment]
This is still a work in progress, we should be able to use the uswds-jekyll theme to achieve a guides style site. It's based on this issue ATM https://github.com/18F/uswds-jekyll/issues/55

**Comment by line47** [comment]
I'd say this is blocked for now. I'll add a definition of done to the original issue.

**Comment by line47** [comment]
I've been speaking with @elainekamlley about using the federalist-uswds-template as a prof of concept that we can use that instead of a separate guides template. Hopefully will know more next week. 🚀

**Comment by wslack** [comment]
What's the next step? (just so I'm clear)

**Comment by line47** [comment]
Spoke with @elainekamlley and the first step is going to be updating https://agile.18f.gov to use the federalist-uswds-template and document this process for others to follow for future migrations.

**Comment by wslack** [comment]
@adborden to incorporate if he wants; otherwise closing
