### ISSUE TITLE
Consider adding a template based on the US Spending Feedback Site

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1243]
https://github.com/18F/federalist-beta-feedback-template

**Comment by wslack** [comment]
(confused - why am I assigned?) I thought we were moving this to the strategy doc.

**Comment by line47** [comment]
I thought that would help with adding some visibility, feel free to un-assign yourself. 👍 

Can you explain the functionality of this template it looks like to gather feedback but I'm unsure if I am missing something.

**Comment by wslack** [comment]
will circle back when its accessible again....but I think this was for a styling example

**Comment by line47** [comment]
Please add your thoughts here @wslack - the URL should be available now

**Comment by wslack** [comment]
Aha! Yes, this could be a template for a site to receive comments and feedback from the public.
