### ISSUE TITLE
"Required" validation on Add Site GitHub URL input is too sensitive

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1250]
Just putting the mouse in the text input and then clicking outside of it triggers the "Required" validation error state.

<img width="564" alt="screen shot 2017-10-27 at 2 42 32 pm" src="https://user-images.githubusercontent.com/697848/32122392-c9af887a-bb25-11e7-8ce3-7ff9344c13a7.png">

A simple solution is to remove the ReduxForm "required" validator totally, and just enable the button when the other validator (the valid github url validator) passes.

**Comment by wslack** [comment]
If this doesn't block using the templates on the page, I don't think it's  high priority, but welcome other thoughts.

**Comment by jseppi** [comment]
It doesn’t block anything. Also it’s just a code deletion so effort to fix is very low.

**Comment by wslack** [comment]
As long as it still informs the user when the format of the URL is wrong, this sounds fine to me!
