### ISSUE TITLE
After adding a site, the Site List page is scrolled to the bottom

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1251]
The scroll position should be at the top so that errors that happened during the add will be visible.

Not sure why it is scrolled to the bottom.

**Comment by wslack** [comment]
Maybe because that's where the site should be listed if everything worked?

**Comment by line47** [comment]
When I was demoing Federalist for @micahtaylor and @jenniferthibault the thought came up about where you are taken after creating a new website. The consensus was that it would be awesome to land on the  **builds page** after a new site creation instead of the *my sites* list.

**Comment by jseppi** [comment]
That sounds like a good idea to me -- and it would be very easy to implement

**Comment by wslack** [comment]
I'm good for trying this; however, jumping immediately will not show a build - since the first operation is to clone the repo, which takes a few seconds.

Could we combine this with a message if the table is blank explaining what is happening?

**Comment by line47** [comment]
I ❤️ that idea @wslack a message showing something is happening would be 💯

**Comment by wslack** [comment]
If we can do this in under an hour, 👍 . If longer, let's focus on the frontpage and converting more leads.

**Comment by wslack** [comment]
This worked beautifully in staging.

**Comment by jseppi** [comment]
Just tested myself, too! Nice!
