### ISSUE TITLE
Federalist app: Update select a template boxes height

### ISSUE THREAD

**Issue by line47** [18F/federalist#1263]
On the "Make a new site" page the height of the boxes for choosing a template are all different heights. Update so that all template boxes are of equal height.

I would also suggest changing the `Example` button into a link and change the text to read `View example`, `View live example` or something similar. 

### Screenshot

<img width="1062" alt="screen shot 2017-11-08 at 9 57 13 am" src="https://user-images.githubusercontent.com/1449852/32555693-7896c8c8-c46b-11e7-913e-587d732e2b21.png">

**Comment by wslack** [comment]
How about `View Template`?

**Comment by line47** [comment]
Yeah that sounds good to me, once i can build the app locally I'll make the edits and get a PR in for these updates.
