### ISSUE TITLE
federalist app: Top nav bar - Change username to something showing ownership

### ISSUE THREAD

**Issue by line47** [18F/federalist#1264]
Change username to "x's sites" or other language in the top navigation bar. 
I was thinking something like "My sites". Related, the title of the dashboard is "Your websites" so if we did use something like "My" our "Your" it would be important to be consistent in that naming. 

One other thought I had is that it would be good to have the username associated with "Log out" maybe something like "Log out, USERNAME".

### Screenshot
<img width="1033" alt="screen shot 2017-11-08 at 10 17 11 am" src="https://user-images.githubusercontent.com/1449852/32556570-cbd1734c-c46d-11e7-96a2-866e334d14de.png">

**Comment by wslack** [comment]
Hmmm. `Logout line47` seems unclear to me. 

I think its consistent to have `x's sites` in the menu bar and then to have Federalist label the page "Your websites" but would be open to changing the page title.

Open to pushback though.

**Comment by OpenGlobe** [comment]
Right now it seems like there's not really a clear reason to have the username in the top nav, since everything else takes you off the main site or logs you out.   So, perhaps something instead might look like (in the main content area): 

[username]'s sites:
Not you?  Log out. 

I'll put these thoughts in the revised review doc too.

**Comment by wslack** [comment]
@OpenGlobe having the username in the top nav is helpful for troubleshooting in screenshots and for people with multiple GitHub accounts. I get that its not consistant but having that in the general nav does have utility (unclear to me if the other links do)
