### ISSUE TITLE
Repo name and github icon link overrun when owner+repo is too long

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1266]
Happens on all `/sites/` pages:

<img width="813" alt="screen shot 2017-11-09 at 8 24 07 am" src="https://user-images.githubusercontent.com/697848/32610148-793da53c-c527-11e7-8b90-689749615c5b.png">

**Comment by jseppi** [comment]
Might be another good one for @line47 to get his feet wet.

**Comment by line47** [comment]
That sounds good to me !
Related to this I was confused at first to find that the github icon was in fact a link to the repo. I think this could be made more clear buy associating some text like "View the repo" or something similar next to the icon.

**Comment by jseppi** [comment]
Great idea!

**Comment by wslack** [comment]
Hm. I wouldn't want to do that all over the site since it will take up so much space, but we should have microcopy to explain this somewhere.

**Comment by jseppi** [comment]
here's how CodeClimate does it:

![githublink](https://user-images.githubusercontent.com/697848/32619888-9cc02ede-c541-11e7-9d10-4664bd3830fd.gif)

**Comment by line47** [comment]
Here is a before/after screenshot of moving a few things around to give more breathing room to the repo name and titles closer with navigation items and page content.

I've included some layout thoughts below: 

### Before screenshot
![screen shot 2017-11-09 at 11 58 56 am](https://user-images.githubusercontent.com/1449852/32619996-6a08f2e2-c54a-11e7-835d-948df83ba5de.png)

### After screenshot
![screen shot 2017-11-09 at 11 59 20 am](https://user-images.githubusercontent.com/1449852/32620002-70fdc172-c54a-11e7-8cdc-1905738d056f.png)

**Here is what is different in the after screenshot**
- Moved the view website button to the left hand nav to give some space for the title and also group the view website with other site actions
- Moved page title of "builds" down closer to the table listing the builds and also updated the naming to match the title in the left hand nav "Build history" 
- Moved the link to github onto it's own line under the site title and included some text "View repo" to make more clear that there is a link to follow.

**Comment by line47** [comment]
Currently, this is hard to test locally as I don't have any test data :(

**Comment by jseppi** [comment]
You should be able to add your own repositories to your local instance. So you could create a repo called `line47/super-duper-really-long-repo` and add it to your local Federalist.

**Comment by line47** [comment]
Awesome! Thanks!

**Comment by line47** [comment]
Talked about this example in my critique group today and all agreed using the text to accompany the GitHub icon is clearer. I'd like to more forward with implementing this next week @wslack

**Comment by wslack** [comment]
@line47 as an MVP, can we try adding the text in the "site list" page first and doing the others like in James's screenshot?

If you feel strongly that we have to do the same thing everywhere, I'll relent.

**Comment by line47** [comment]
@wslack I do feel strongly about being consistent in the usage of linking to something. Inconsistency in how links appear and expectations on what link will go where ends up being difficult for the application user.

**Comment by wslack** [comment]
@line47 Hmmm. Ok.

Let's go ahead and make the change. In the PR you file, please include some before-and-after screenshots; I'd like to check with some users before merging.
