### ISSUE TITLE
Update Federalist homepage design

### ISSUE THREAD

**Issue by line47** [18F/federalist#1278]
The Federalist homepage hasn't been updated in a while and could use some design and front end work.

This will be done first with visual/front end design. 
We know this will be done when there's a pull request.

From other issue
- [x] Change the "Documentation Site" link on the homepage so that its clear that that has more than technical documentation (done)

PR https://github.com/18F/federalist/pull/1282 addresses this issue

**Comment by wslack** [comment]
Awesome! How much of a lift do you expect for this, and how will we know when its done?

**Comment by line47** [comment]
Some ideas I'm working on: 

### Screenshot 
![localhost-1337-](https://user-images.githubusercontent.com/1449852/32858225-d1429328-ca18-11e7-84fb-a2051e0239c0.png)

Updates:
- Using a single `log in` button and changing the link in the top nav bar to be a button
- Update the hero unit and text to encourage signup for more info 
- 3 column layout to show the high level features 
- Simplify and call attention to the open for business section (also wondering if that content would be moved up into the hero)

**Comment by line47** [comment]
Planning on pairing with @ericronne on the visual design for the homepage this Friday 11/24/17

**Comment by OpenGlobe** [comment]
@line47 I'm going to talk to Kate re: next steps, but seems like a first pass at rewriting the content might be a good place to start next.  If so, happy to work on this a bit heading into tomorrow with you.

**Comment by wslack** [comment]
I *think* these efforts can run concurrently without colliding.....y'all comfortable with that?

I wonder if we should put the "new content" in a Google Drive doc for easier editing and more transparency to the visual design work. WDYT?

**Comment by line47** [comment]
Yeah! That's fine with me 🎉 
I'm open to working directly in GitHub or in a Google Doc, whatever you folks think is best.

**Comment by line47** [comment]
Met with @ericronne last week about visual design - 
Hoping to get some direction this week (Palette , updated photos, layouts, etc... )

**Comment by line47** [comment]
I think we should move forward with this homepage design update

**Comment by ericronne** [comment]
here's a draft

![federalist-landing-v2](https://user-images.githubusercontent.com/9259185/33560400-3fd4ac48-d8d5-11e7-9ea2-b8e8fcb4e2a2.png)

**Comment by jseppi** [comment]
@ericronne...noice

**Comment by line47** [comment]
Awesome! I'd love to incorporate some of the designs here into the homepage, thanks @ericronne !

cc @wslack

**Comment by wslack** [comment]
Oh this is nice! I would like some other options WRT to the colors if that's alright. (mostly the green)

**Comment by line47** [comment]
Here are some of the other color palettes @wslack 
<img width="257" alt="screen shot 2017-12-05 at 11 48 17 am" src="https://user-images.githubusercontent.com/1449852/33618882-b8953c1a-d9b1-11e7-9741-01ee2b0b0d00.png">

**Comment by wslack** [comment]
I like #3.

**Comment by ericronne** [comment]
Nope, these are all new explorations
