### ISSUE TITLE
UX Analysis Work

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1279]
(prereq) - David and Will finish the customer interview takeaways.

1. Understand who is using it, directly and indirectly
2. Understand who would benefit who is not using it
3. Understand who is affected by it, regardless of usage.
4. Go through notes, determine what we know/don't know.

Sidetask: Capture Data about how people use a Github Repo

Background:
We want to visualize the universe of affected Federalist users - direct and indirect. Do user type grouping.

Step after this will be building paths based on those groups, but we don't know a lot about those groups right now.

This will be completed when there is a document - in Google, Murally, or otherwise - expressing these user types.

## Acceptance Criteria
- [x] Identify user roles.
- [x] Categorize user goals.
- [x] Frame goals, signals, and metrics.
- [x] Build journey map.
- [x] Write plan for ongoing research.

**Comment by tram** [comment]
Steps 2 and 4 still need a little work and GSM exercise is in progress.

**Comment by wslack** [comment]
Is GSM done now? I admit, I'm unsure of the implied next step.

**Comment by tram** [comment]
I think it's ok where it is—for now. Can use some more work after initial journey mapping is wrapped up. (@OpenGlobe and I are working on this more tomorrow.)

**Comment by OpenGlobe** [comment]
We could post a link to the Mural with is a work in progress...

**Comment by OpenGlobe** [comment]
Federalist Research Plan is here: 

https://docs.google.com/document/d/1WhfuVzTAjucPxmlVEKJjxZGIcosHybO7D9MH8sG6Axw/edit#heading=h.ed0p8js5q4vf
