### ISSUE TITLE
As an administrator / federalist system owner, I want to begin understanding how other similar organizations are handling content so that I can make informed decisions about what appears to work well and what doesn't.

### ISSUE THREAD

**Issue by OpenGlobe** [18F/federalist#1280]
Acceptance criteria: 
- [x] Begin researching comparable solutions (likely commercial).
- [x] Document comparable solutions.
- [x] Create a matrix for a comparative analysis of other science sites/resources.

Definition of done: 
- [x]  A first shell document / draft (in progress) of the comparative analysis is circulated.

**Comment by wslack** [comment]
Some of the original pitch docs about Federalist have competitors. I think GitHub Pages and Netlify are good to look at; we know the Netlify people (they based their product on Federalist a bit).

**Comment by OpenGlobe** [comment]
Also looking at sites like Squarespace...

**Comment by wslack** [comment]
Done here: https://docs.google.com/spreadsheets/d/1TekHre9fs1BTG4FV0ix_qunll2R45-mjcFOAhR_Jhy4/edit#gid=0
