### ISSUE TITLE
In Site Builds table, show the associated commit SHA

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1286]
and link to it on GitHub

This will allow users to easily see which build was for which commit, which is nice especially if there are a lot of restarted builds on the same branch.

**Comment by wslack** [comment]
@el-mapache interested in this one?

**Comment by el-mapache** [comment]
@wslack I can pick this up

**Comment by wslack** [comment]
Just as a starting place to re-familiarize with the code.

**Comment by el-mapache** [comment]
This has been merged!

**Comment by wslack** [comment]
Awesome - now we move to "Done?" in ZenHub!
