### ISSUE TITLE
Make sure our Google Analytics are working well for federalist.18f.gov and federalist-docs.18f.gov

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1287]
@line47 you mind taking care of this?

**Comment by line47** [comment]
Can you define the scope here? 
It looks like there are analytics already setup for federalist.18f.gov

**Comment by wslack** [comment]
If we have the analytics data for federalist.18f.gov and federalist-docs.18f.gov, this is done.

**Comment by line47** [comment]
There **are** analytics for https://federalist.18f.gov but there **are not** any analytics on https://federalist-docs.18f.gov/

Do we wan to use the same analytics code that is already on the https://federalist.18f.gov site or create a new analytics code?

CC @wslack

**Comment by wslack** [comment]
I think we should do new: the analytics code UA-48605964-19 is already in the site config.

**Comment by line47** [comment]
UA-48605964-19 is used for some other sites currently, do we want to continue with that?

**Comment by wslack** [comment]
🤷‍♂️ I don't know enough about Google Analytics to say one way or the other. It depends on if the data we have right now is useful. If it is, I would think we wouldn't want to change since moving the analytics will break historical reporting.

**Comment by line47** [comment]
the GA value is in the `_config.yml` but it's not building to anywhere when you view source on https://federalist-docs.18f.gov/. There is not any tracking currently for the docs site 😬

**Comment by wslack** [comment]
Oh derp; I see now that that was deleted when Shawn set up our new site look. Yes, let's get a new account and add the tracking code please.

**Comment by line47** [comment]
I'm wondering about adding the GA code from https://federalist.18f.gov/ to the docs site instead of creating a new GA code. 

I'm thinking longer term it would be great to have the docs under the https://federalist.18f.gov/ URL similar to how cloud.gov is doing it. https://cloud.gov and https://cloud.gov/docs/

thoughts @wslack

**Comment by wslack** [comment]
Its ok to have the same code on both.

Re putting the docs under the same URL, we can't do that without stopping the docs site from being a dogfooded Federalist site itself. That seems like a larger scope to tackle than focusing on the sales / possible user experience.

**Comment by line47** [comment]
Analytics are setup and working as expected 🚀
