### ISSUE TITLE
Add ability to delete users from Federalist settings access for a site

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1289]
We need a way for people to delete themselves and each other from app access.

* People should be able to delete themselves and others from the "users" screen in the app.

* An owner should not be able to be removed from a site.

* When someone deletes themselves, the app simply needs to register success and nothing else.

* When people delete each other, the "deleted person" should be notified in the site list (you were removed from access to XYZ by user ABC) with an option to re-add themselves **if** they still have `write` access or clear the message.

**Comment by wslack** [comment]
@el-mapache this is actually pretty important, now that I think about it. We need a way for people to delete themselves and each other. When people delete each other the "deleted person" should be notified in the site list with an option to re-add themselves **if** they still have `write` access or clear the message

**Comment by el-mapache** [comment]
I'm on it!

**Comment by jseppi** [comment]
Nice, this one shouldn't be too bad to implement

**Comment by el-mapache** [comment]
In the case of a user attempting to remove themselves, when they are the sole owner of a federalist site, we should display an error telling them to delete the app instead.

**Comment by el-mapache** [comment]
The most annoying part is probably seeing the database 😄

**Comment by jseppi** [comment]
You could also just not show the "delete user" button for the user that is the owner

**Comment by jseppi** [comment]
Oh, I see the difference now though. Like if there is an 18F site that a user is the last Federalist user of, then show that error. Makes sense.

**Comment by el-mapache** [comment]
@wslack The last bullet point here seems a little tricky without adding some kind of notification table to the database. I don't think we really have have any other mechanism to alert users when an action is taken on the site (push notification, web sockets, polling, etc) so it might be better to break the last bullet off into it's own issue.

**Comment by wslack** [comment]
@el-mapache: hmmm. @jseppi can confirm, but we added some type of alert styling when saving settings was successful. That didn't exist before.

Or are you saying that there's no way for users to see in the site list that they were removed from a site? That feature isn't mandatory and we can split it off.

**Comment by el-mapache** [comment]
@wslack We do have a global notification component, but only for actions taken by a user themselves. We don't have a way to alert other users when actions are taken.

**Comment by jseppi** [comment]
Yup, what @el-mapache said.

**Comment by el-mapache** [comment]
@wslack And we are fine with any user being able to remove any other user from a site correct?

**Comment by wslack** [comment]
@el-mapache correct. If you have write access, you can remove someone else. Maybe the better answer re the site list FYI is just having a quick and dirty log of user actions taken (people added, people removed) available from the users tab.

That way someone confused can re-add themselves and check the logs.

**Comment by wslack** [comment]
But we're going to maintain our stance of leveraging GitHub permissions to determine Federalist access.

**Comment by el-mapache** [comment]
@wslack Thats fine, it will still require a new table. We should probably make another related issue.

**Comment by el-mapache** [comment]
@wslack One issue I think we might run into is that while a user who is removed from a site won't be able to see that site in their dashboard, that site will be orphaned in the database / on s3 / their github.

Should we delete the site from that user's federalist once they are removed from the site by another user?

**Comment by wslack** [comment]
Yes; its fine if they need to re-add the site again from scratch.

**Comment by jseppi** [comment]
I don't think we should ever delete anything from GitHub.

**Comment by wslack** [comment]
Agreed; Federalist should *never* remove any repo from GitHub. It should only delete its Federalist records and builds for that repo.

Federalist creates, but does not destroy. :P

**Comment by el-mapache** [comment]
Then we are all in agreement

**Comment by el-mapache** [comment]
@wslack Do we want to move the final bullet point here into a new issue? We don't have the 'adding a user' feature scoped out at the moment, correct?

**Comment by wslack** [comment]
@el-mapache that's fine! Correct - we don't have "add user" set up yet except for the "add a site" method. I was thinking that function could call the "add a site" code but if not, it can be pushed.
