### ISSUE TITLE
Have consistent look and feel between federalist site and docs site

### ISSUE THREAD

**Issue by line47** [18F/federalist#1290]
- [x] Make sure search.gov functionality is preserved.
- [x] Mimic header links from federalist.18f.gov.
- [x] Footer, do we need a footer?
- [x] Set up left hand navigation.
- [x] Update to new version of USWDS-Jekyll

**Comment by line47** [comment]
@wslack I noticed on the Federalist and Federalist docs site that there is no footer or not much of one anyways. 
1 - Do we want a consistent footer?
2 - What would be in the footer?

**Comment by wslack** [comment]
I would want something like https://boise.18f.gov/ footer but with the Federalist icon. I don't think we need the footer in the federalist.18f.gov main page...its ok for them not to be consistant.

**Comment by wslack** [comment]
The main thing is to have the "edit this page" link. It can be minimalistic. If there's a way to put the edit link to the side like on https://cyber.dhs.gov/ we don't need any footer.

**Comment by line47** [comment]
I've got to get digital-gov search working as an option here - that's my next step

**Comment by wslack** [comment]
Cool - I think each new site has to be registered, so your steps might be documenting a workflow.
