### ISSUE TITLE
Incorrect files can be listed in SitePublishedFilesTable when repos have similar names

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1293]
Similar to the root cause of https://github.com/18F/federalist-garden-build/issues/77.

If a repo owner has two repos, where the name of one is a substring of the other (like `my-site` and `my-site-2`), then the `S3PublishedFileLister.js` will list the files of each repo when the files for `my-site` are requested. This can result in the other site's files getting into the `SitePublishedFilesTable.jsx`.

**Comment by wslack** [comment]
What's the level of effort to fix? Seems simple to ask folks not to use substrings.

**Comment by jseppi** [comment]
I _think_ it might be as simple as adding a trailing `/` to the `Prefix` arg of S3's `listObjects` API call.

**Comment by jseppi** [comment]
or maybe using the `Delimiter` arg to that API call

**Comment by wslack** [comment]
ah ok, seems worth a run at fixing here then
