### ISSUE TITLE
Format dates more nicely in log tables

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1301]
Something slightly more readable.

Perhaps:
`2017-11-13T21:50:25.629Z` -> `2017-11-13 21:50:25 UTC`

<img width="750" alt="screen shot 2017-11-21 at 10 53 43 am" src="https://user-images.githubusercontent.com/697848/33085468-56142b30-ceaa-11e7-8258-d03195756eac.png">

**Comment by wslack** [comment]
@el-mapache interested in this one?

**Comment by jseppi** [comment]
@line47 and/or @OpenGlobe: Any suggestions for formatting these datetimes? A thought I had is that using US Eastern time for them would be nicer than UTC.

So, for example,
Changing `2017-11-13T21:50:25.629Z` to `2017-11-13 4:50:25 PM (ET)` (or something very similar to that)

**Comment by el-mapache** [comment]
In the table currently up there, I think I have Day month and year written out in english. Do we want a timestamp or a friendly date?

**Comment by jseppi** [comment]
@el-mapache: you mean on the User Actions table, right? Perhaps we should switch the Build Logs table to be formatted like the User Actions table so that we're consistent across the two tables.

The Build Logs table just has the ugly default JavaScript datetime-to-string datetimes:

<img width="818" alt="screen shot 2018-01-08 at 2 40 15 pm" src="https://user-images.githubusercontent.com/697848/34691344-ef8774be-f481-11e7-93e5-6374002345e0.png">

**Comment by el-mapache** [comment]
Yeah I'm all for standardizing! Almost any other format is better than that one 😄

**Comment by el-mapache** [comment]
But I also don't really have strong feelings about which one we should use, whatever is friendliest to users

**Comment by wslack** [comment]
4:50 PM 11-13-2017 (ET)

I think this format might be better, unless the seconds ever matter.

**Comment by line47** [comment]
We're using this on the your websites listing 

`January 9th 2018, 11:07:36 am`

**Comment by jseppi** [comment]
Update: the times we display are user localized currently, except for those in the build log table, which are utc. I think that handling is good as is.

**Comment by jseppi** [comment]
My PR will be finished soon and we can iterate on what I’ve implemented there. I’ll add screenshots of the various date(time)s we show.

**Comment by jseppi** [comment]
Done by #1475
