### ISSUE TITLE
UI for template info

### ISSUE THREAD

**Issue by line47** [18F/federalist#1304]
Take a look at the template selection block and think about the best UX/UI to display the following.

- [ ] Name/Title of template 
- [ ] Description of template
- [ ] Image of template
- [ ] Link to template on GitHub
- [ ] Link to preview/live demo of template
- [ ] Action for selecting the template

### Screenshot of template and selecting template

![screen shot 2017-11-22 at 10 04 28 am](https://user-images.githubusercontent.com/1449852/33133868-22237426-cf6c-11e7-89d4-ffadabe2f311.png)

**Comment by wslack** [comment]
For right now, I think we should icebox this. The functionality is very rarely used and improving the actual templates seems more important than redesigning here, though I welcome feedback.

**Comment by wslack** [comment]
Closing this and making @AlanAtlas happy since we aren't going to touch this part of the code for some time.
