### ISSUE TITLE
Live and demo URL input focus is lost after first character is typed

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1307]
Steps to reproduce:
1. Click into a blank Live (or Demo) URL input box on the Site Settings page.
1. Type a character. The focus will jump to the Save Basic Settings button.

Expected behavior:
Focus remains in the input box while typing.

![url-focus-lost](https://user-images.githubusercontent.com/697848/33139230-476b1be8-cf72-11e7-8ec9-3c58c2b274f4.gif)

**Comment by jseppi** [comment]
It is due to code like this, which results in React re-rendering the component on change, which then makes the input lose focus (because it's actually a new DOM element):

```jsx
component={p =>
  <HttpsUrlInput
    value={p.input.value}
    onChange={p.input.onChange}
    className="form-control"
    id="domainInput"
  />
}
```

This method was taken from the ReduxForm docs, but those examples are apparently wrong. More explanation at https://github.com/erikras/redux-form/issues/1094

**Comment by wslack** [comment]
Effort to fix?

**Comment by jseppi** [comment]
Fairly low effort. I’m thinking I could roll it in with fixing the weird
error message when anything in the related form’s submission goes wrong.


On Nov 22, 2017, at 12:41 PM, Will Slack <notifications@github.com> wrote:

Effort to fix?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/18F/federalist/issues/1307#issuecomment-346439294>, or mute
the thread

**Comment by wslack** [comment]
Makes sense, seems like we can put in "Ready" for you to pull off when wanted.
