### ISSUE TITLE
Monitor webhook responses

### ISSUE THREAD

**Issue by jeremiak** [18F/federalist#131]
We've seen a few instances of the webhook `POST` request from Github generating errors in the application and therefore preventing builds from working. It is hard to track down the exact cause, so we want to have a bit more monitoring (and ideally some notifications) around this part of the application.

Since api.data.gov is a available to us, let's start with implementing that.

**Comment by jeremiak** [comment]
I renamed this issue to capture that we'll want more than just this endpoint monitored as our application is about to be part of two client launches in the month of September.  So this issue is now larger to include monitoring for the build errors as well as general application errors.

**Comment by dhcole** [comment]
We have New Relic for server errors and uptime. Last step is to monitor responses from the application to GitHub webhook requests, just to make sure we don't miss anything if the server is down.

**Comment by dhcole** [comment]
This has only very rarely been an issue, but if a build doesn't start after a change, check the webhook section on the repository's settings on github. There will be a list of the status returned from past webhooks. On some particularly large webhook requests, it seems like the code that validates the signature of the webhook body may be breaking, such as https://github.com/18F/college-choice/settings/hooks/5292591#delivery-request, `61340c00-c48a-11e5-8725-acd1494c6ea9`

**Comment by wslack** [comment]
I think existing controls/monitoring are good enough
