### ISSUE TITLE
UI/UX for template selection

### ISSUE THREAD

**Issue by line47** [18F/federalist#1311]
The process for selecting a template could use some UI/UX love.

- [ ] Add a close button to allow the use to collapse the form
- [ ] Could we provide a user and org dropdown instead of the textbox for github account?
- [ ] Show the form outside the context of the template box (maybe show below the templates?)
- [ ] Show success message after creating new site

![screen shot 2017-11-22 at 10 04 28 am](https://user-images.githubusercontent.com/1449852/33134898-eec5cebe-cf6e-11e7-91dc-a6ca1ec0de44.png)

**Comment by wslack** [comment]
For right now, I think we should icebox this. The functionality is very rarely used and improving the actual templates seems more important than redesigning here, though I welcome feedback.

cc @jseppi as he gave a 👍  as well.

**Comment by wslack** [comment]
Same as #1304 and making @AlanAtlas very happy!
