### ISSUE TITLE
Content design: As a user of the Federalist site, I want to understand how Federalist benefits me, what it provides so I can choose to move forward if it is a fit for me. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/federalist#1312]
As a user of the Federalist site, I want to understand how Federalist benefits me, what it provides so I can choose to move forward if it is a fit for me. 

Acceptance criteria: 
- [x] Default to 18F Content Guidelines

- [x] **First pass at rewriting the Federalist content**
  - [x] Readme
  - [x] Landing page
  - [x] Examples page
  - [x] [Login page](https://federalist.18f.gov/sites)
  - [ ] [Sign-up form](https://docs.google.com/forms/d/e/1FAIpQLSesNI1qlov7Ec_1u2FralYWg9hV4WsB-3FyAHPXc1pRT6In7w/viewform) *

* Sign-up form will also be addressed in the User Research plan following the first rewrite. 

Definition of Done: 
- [x] Presenting the first pass of the rewritten content

**Comment by OpenGlobe** [comment]
Update 12/08/2017: 

We've pushed first-pass updates to: 
- readme file (instructions / background)
- examples page

**Comment by wslack** [comment]
@OpenGlobe will set up a time to go through the changes with the team

**Comment by annahsebok** [comment]
Hi folks. Can you tell me a little bit more about what you're looking for here?

**Comment by wslack** [comment]
I think this one is better off left alone; some of Chris's work is still in progress.

**Comment by wslack** [comment]
being worked in https://github.com/18F/federalist/pull/1582
