### ISSUE TITLE
Investigate and modify Code Climate settings for new Maintainability metric

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1315]
Ref: https://codeclimate.com/blog/a-new-clearer-way-to-understand-code-quality
and https://docs.codeclimate.com/v1.0/docs/maintainability

**Comment by jseppi** [comment]
I think we should do this ASAP since the CodeClimate status checks are going to begin failing due to the changes they made in their engine. Should not take much time to relax the rules a bit.

**Comment by wslack** [comment]
Make it so.
