### ISSUE TITLE
[Federalist application] - Add link tracking for outbound links

### ISSUE THREAD

**Issue by line47** [18F/federalist#1316]
Use Google Tag Manager to track outbound links from the Federalist application
Things like links to (GitHub, Documentation, Previews of sites, live versions of sites, etc...)

@laurenancona has offered up to put in a PR around this

**Comment by jseppi** [comment]
What's blocking this one?

**Comment by line47** [comment]
I'm unsure how to use GTM to set this up and was going to pair with @laurenancona on it. If this is something that you know how to do @jseppi and we can pair on it that would be awesome!

**Comment by jseppi** [comment]
Not a clue actually :)

**Comment by laurenancona** [comment]
@line47 we can pair on config in the GTM UI if you'd like whenever this is merged to a server we can both see

**Comment by laurenancona** [comment]
Config to add to GTM:
[ ] add GA Pageview tag for 18f account - Federalist profile
[ ] add GA Custom Event tag: Outbound Link Tracking

We'll use this schema for the[ Custom Event parameters](https://developers.google.com/analytics/devguides/collection/gajs/eventTrackerGuide)

| Category | Action | Label |
|:----|:----|:----|
 Exit | Outbound link | {{ URL }}

**Comment by line47** [comment]
Set up a time on Thursday Dec, 21 to pair with @laurenancona to get this knocked out! 🎅

**Comment by laurenancona** [comment]
One more PR (#1400) that should be merged at the same time as #1382 when pushing to prod and this should be 💯
