### ISSUE TITLE
[Federalist application] - Update alert styling 

### ISSUE THREAD

**Issue by line47** [18F/federalist#1321]
Update styling and markup for informational, warning, error and success alerts in the Federalist application.

**Comment by jseppi** [comment]
We already have USWDS, which gives us the various `.alert-STATUS` classes. Should we just use those where appropriate (and we do already use them in _some_ places), or were you thinking of overriding those styles?

**Comment by jseppi** [comment]
I think the main places the alert styles need to be used is in the various "empty" messages, like when there are no build logs found for a given site (ex screenshot: https://github.com/18F/federalist/pull/1317#issue-278237334).

**Comment by line47** [comment]
I was thinking of using the USWDS alerts to start.

**Comment by line47** [comment]
@jseppi is there a way I can locate the alerts in application code?

**Comment by jseppi** [comment]
I think searching for `renderEmptyState` will get you most of the components that render an empty message, but there might be some others not in a similarly-named function.

**Comment by jseppi** [comment]
Closing. Styling bugs found during review on 12/22/17 have been fixed (#1411) and deployed to production.
