### ISSUE TITLE
Static Site Engine dropdown needs bottom margin/padding

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1324]
Pretty sure it used to have some more padding/margin between it and the Site Configuration box.

Here's what it currently looks like:

<img width="832" alt="screen shot 2017-12-04 at 2 29 38 pm" src="https://user-images.githubusercontent.com/697848/33574795-fefeb7ba-d8ff-11e7-8c03-b7443eea18ed.png">

Likely due to changes in #1295

**Comment by line47** [comment]
I'd like to update the grid system used on this settings page, right now there is a lot of extra HTML that is not needed, for example, multiple `usa-grid` and `usa-width-one-whole` divs
