### ISSUE TITLE
GitHubURLProvider renders as Component in SiteGitHubBranches test

### ISSUE THREAD

**Issue by el-mapache** [18F/federalist#1325]
In `SiteGitHubBranches`, this component renders as `Component`, which enzyme can't select using its `find` method. We should investigate how to ensure that `GitHubURLProvider` renders the final composed component in the same way as the `connect` higher-order component — in the form of `Connect(MyComponent)`.

This should enable enzyme to select the component in tests, making the tests less brittle.

**Comment by el-mapache** [comment]
Doing a little further reading, it seems like the consensus of the community is that `connect` renaming the component is actually an anti-pattern. I'll find the relevant discussions and link them here.

**Comment by wslack** [comment]
Can you help me understand the priority here?

**Comment by el-mapache** [comment]
Sorry! I think this is a pretty low priority. As noted above, I don't think we should be renaming components from other components just for the sake of slightly less verbose testing.

**Comment by wslack** [comment]
To the icebox it goes! (or we can close it, if the antipattern finding means this is no longer an issue)

**Comment by jseppi** [comment]
`GitHubURLProvider` is gone, so this can be closed now.
