### ISSUE TITLE
Add YAML validation to site configuration textareas

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1330]
Adding validation would elimination a whole class of potential errors during build, and would shorten the feedback loop for site builds (ie, you wouldn't have to wait until the jekyll step to see that you screwed up your YAML).

**Comment by wslack** [comment]
Moving to backlog subject to further user feedback. 

Users haven't set text config w/o the skill set to address issues, and while this would be helpful, I'm unsure of the impact.
