### ISSUE TITLE
Create page design for federalist.18f.gov for use cases

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1332]
As part of https://github.com/18F/federalist/issues/1312, we should create a page design for federalist.18f.gov that explains various Federalist use cases and example sites.

The page should have

- [x] A way to showcase 3-4 "main examples" with a title (like "display data"), screenshot, link to the relative site, and blurb about how Federalist helped the site.
- [x] A way to showcase a larger "grid" of example sites showing the breadth of Federalist sites, with mini screenshots and names of the sites "like 18F Method Cards" like seen here: https://18f.gsa.gov/what-we-deliver/
- [x] A place at the top of the page to showcase the number of pageviews for Federalist sites and the number of sites hosted.

CC @OpenGlobe and @tram

**Comment by line47** [comment]
Here are some layout ideas, let me know which direction sounds best or we can mix n match 🍬 

### Option 1
![photo on 12-5-17 at 1 46 pm](https://user-images.githubusercontent.com/1449852/33624621-f6877fcc-d9c2-11e7-8af6-65a19758af85.jpg)

### Option 2
![photo on 12-5-17 at 1 46 pm 2](https://user-images.githubusercontent.com/1449852/33624638-00d44794-d9c3-11e7-9459-b29241607c7a.jpg)

### Option 3
![photo on 12-5-17 at 1 47 pm](https://user-images.githubusercontent.com/1449852/33624676-207594ae-d9c3-11e7-9dba-01fc81ed6e68.jpg)

CC @wslack

**Comment by line47** [comment]
@wslack do you have sites/URLs you'd like to use for the 3 to 4 examples ?

**Comment by wslack** [comment]
Option 3 and the sites will be:

Vote.gov
College Scorecard
cyber.dhs.gov

**Comment by wslack** [comment]
Actually I take it back. I'd like the top piece from section 3 and then cards like in option 1.

**Comment by line47** [comment]
Great! Thanks!

**Comment by line47** [comment]
What should the URL of the page be?

**Comment by line47** [comment]
WIP @wslack @OpenGlobe 
For the featured images I was using both a big view with a small screen view overlay on top. Let me know any changes you'd like to see 👍 

![localhost_1337_content_examples](https://user-images.githubusercontent.com/1449852/33733151-d4e63e0e-db56-11e7-9a70-268c3dc0cf98.png)
