### ISSUE TITLE
[Federalist application] - Update GitHub links to be consistent across the application 

### ISSUE THREAD

**Issue by line47** [18F/federalist#1334]
## Current state of the links from the Federalist application to GitHub 
<img width="662" alt="screen shot 2017-12-05 at 11 13 43 am" src="https://user-images.githubusercontent.com/1449852/33627833-bb4d8d20-d9cc-11e7-9f70-0beaca4d3a80.png">

## Proposing we use a text link in association with the GitHub icon

**Example**
[GitHub link](www.federalist.18f.gov) :octocat: 
In this example the link and icon are both inside the same `<a>` tag

in the cases mentioned above this would be 

[18f/methods](www.federalist.18f.gov) :octocat: 
[master(live branch)](www.federalist.18f.gov) :octocat: 
[githubusername](www.federalist.18f.gov) :octocat: 

@wslack @jseppi @el-mapache was thinking this is the issue we can use to track

**Comment by wslack** [comment]
Thanks for opening. This won't work for the top left example - the link there doesn't point to GitHub (the link and the icon point to different places). We'll need to add another link "view repo" or something like that.
