### ISSUE TITLE
Add support for sub-page static content 

### ISSUE THREAD

**Issue by line47** [18F/federalist#1337]
Currently there is no way to setup a static page other than the homepage.

I'm trying to work on a new page for use cases and can't see the page locally or set the URL
https://github.com/18F/federalist/issues/1332

Also this ties into a broad issue to look into around having a static site for all the docs/homepage and the app all under one federalist.18f.gov URL 
https://github.com/18F/federalist/issues/1333

**Comment by jseppi** [comment]
Do you want all sub-pages and nested sub-directories to be accessible from a single sub-directory path (like `federalist.18f.gov/content/`) or do you want to be able to put basically any sub-path from the root URL?

**Comment by line47** [comment]
I would guess that any sub-path would be more flexible - but i would also say whatever is quicker at the moment given the possibility of switching over to a federalist static Jekyll site in the near future

**Comment by wslack** [comment]
@jseppi if one subpath is easier, let's do that. I think it would be `federalist.18f.gov/overview` or `federalist.18f.gov/about`
