### ISSUE TITLE
Add http-server to dev deps or globally in app Docker for viewing coverage results locally 

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1342]
Also add info on usage to README (via `docker-compose run app yarn serve-coverage` or something).

https://www.npmjs.com/package/http-server

This will be a quick lift, useful for developers.

**Comment by wslack** [comment]
This is to look at test coverage reports?

**Comment by jseppi** [comment]
yeah. they're already generated and I locally use python's built-in server, but figured it would be nice to both document the ability and make it easier for others to use.

**Comment by wslack** [comment]
👍
