### ISSUE TITLE
Deploy Next Prod Release

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1354]
- [ ] Make the PR
- [ ] Merge the PR
- [ ] Post the [Release Notes](https://docs.google.com/document/d/16uXQsMUpZ4F76jgHh8GVWenbVSaf_0OczkmFUMsgb84/edit)

**Comment by jseppi** [comment]
@wslack: what is this? seems old, but I'm not sure what it was supposed to be tracking.

**Comment by wslack** [comment]
It was tracking if we actually released to prod or not - and we did!
