### ISSUE TITLE
Add link to non-custom preview URL

### ISSUE THREAD

**Issue by konklone** [18F/federalist#1355]
Federalist's (wonderful) preview feature is only shown in the UI as using a custom domain, but the Federalist application generates a preview URL per-brach per-repo, such as (fake example):

https://federalist-proxy.app.cloud.gov/preview/18f/hub/new-draft/

I had to dig around in the Federalist docs for a little while to figure this out, because the Federalist UI didn't expose a link or describe how to get here. A link in the UI would be helpful.

**Comment by wslack** [comment]
Hey @konklone, did you see the preview links in the “GitHub Branches” section of the federalist screens?

Where else would you want us to expose that link? We can explain it on the settings screen.

**Comment by konklone** [comment]
Yes, I did eventually see the link on the GitHub Branches page, though it is a different URL structure:

https://federalist-proxy.app.cloud.gov/demo/18f/hub/

I guess I expected to see it on the Settings page, but I do see that it's in a couple of other places. That may be enough, but I can at least report that, for whatever reason, I didn't think to look there and spent time poring around documentation instead

**Comment by jseppi** [comment]
The preview link should also show up in the GitHub status check on PRs (the linked “Details” for a green light status check).

Any other ideas for surfacing it or making it more visible?

**Comment by konklone** [comment]
I expected to see it on the settings page, which is where I set which branch was to be used for previews. I can see now that it's in a couple places, but for whatever reason, I gave up after not seeing it in the interface where I was setting the branch.

**Comment by jseppi** [comment]
ohhhhhhh, it also sounds like there is confusion over demo vs previews.

_Every_ branch is built by Federalist and is previewable. There can be two "special" branches, which are specified in the web UI's Basic Settings page as the Live Site Branch and/or the Demo Site Branch. Those branches can be built with custom domains (that's really the only way they're special).

Here's how the URLs work:
- for the live site: Live Site Domain OR `https://federalist-proxy.app.cloud.gov/site/<OWNER>/<REPOSITORY>`.
- for the demo site:  Demo Site Domain OR `https://federalist-proxy.app.cloud.gov/demo/<OWNER>/<REPOSITORY>`.
- for branch previews:  `https://federalist-proxy.app.cloud.gov/preview/<OWNER>/<REPOSITORY>/<BRANCH>`.

**Comment by wslack** [comment]
@konklone maybe better to do a user interview on this, but I'm confused why you were looking at the settings pages for these links. I'll add some text to the settings page to explain this, though.

**Comment by wslack** [comment]
Created a new docs page. We'll link to that from the settings screen after its merged.

**Comment by wslack** [comment]
Working on the next PR here: https://github.com/18F/federalist/pull/1370
