### ISSUE TITLE
Site List page - GitHubRepoLink is missing and `baseHref` prop is undefined

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1359]
There should be GitHubRepoLink components visible for each listed site, but a missing/broken prop is preventing them from rendering:

<img width="647" alt="screen shot 2017-12-12 at 8 49 34 am" src="https://user-images.githubusercontent.com/697848/33890638-766a18b6-df19-11e7-879b-ea8b557d6cd6.png">

<img width="841" alt="screen shot 2017-12-12 at 8 47 12 am" src="https://user-images.githubusercontent.com/697848/33890541-2df10acc-df19-11e7-9882-f06248fd4fa3.png">

**Comment by el-mapache** [comment]
@jseppi Did this previously have a github icon as well?

**Comment by jseppi** [comment]
yeah, see `siteListItem.js`. It's still there, just not rendering properly.

**Comment by el-mapache** [comment]
I was asking if the list item component used to display the octocat icon, but I suppose it would have had to.

**Comment by jseppi** [comment]
oh yeah, sorry. It did previously just have the icon. @line47 might have thoughts on if it should add some link text as well (and placement).

**Comment by el-mapache** [comment]
Word, I'll push up the PR and amend if necessary!

**Comment by wslack** [comment]
Whoops; I didn't notice this in staging. Happy to do a merge to `master` when this is ready to fix the bug if y'all agree.
