### ISSUE TITLE
Add table to track user actions

### ISSUE THREAD

**Issue by el-mapache** [18F/federalist#1360]
Proposed table to be named `user_actions` and will have the following fields:

* user_id
* target_id
* target_type
* action_type (action)
* created_at

I think the action types will be:
* remove a user
* add a site
* potentially update site settings? might be good to know when a field changes for troubleshooting purposes. Might require another field
* delete a site
* restart a build

I'm not 100% sure if this table needs to be made more generic to handle different types of actions, but based on the current site, all of the outlined actions are performed by a specific user.

Feedback wanted / welcome!

**Comment by el-mapache** [comment]
Not sure if a straight join table will work in this case, since several of the actions we might want to track are destructive. Maintaining a reference to an id that no longer exists in the database isn't particularly beneficial.

The table might work better with a JSON blob field so we can store metadata associated with the actions

**Comment by jseppi** [comment]
Alternatively, rather than actually deleting records (sites, users, etc), we could use an `is_active` column and set that to `false` when they are "deleted".

**Comment by el-mapache** [comment]
Yep, we could definitely take that approach! Do you think that might raise any concerns over privacy/data persistence?

**Comment by jseppi** [comment]
I wouldn't expect any privacy issues given that all (?) users are federal employees or contractors. t seems like it would be even better for auditing and/or data loss prevention.

**Comment by el-mapache** [comment]
Cool, so assuming we go this route, the tables, `site`, `user` and their join table would all need an `active` field added to them? I think the join table will need it too since a user could be inactive from a number of sites, or from federalist (not sure if they can get into this state) itself.

**Comment by jseppi** [comment]
I think that's correct, @el-mapache. I don't believe there is currently a way for a `user` to be fully deactivated from Federalist, but maybe that's something that will come along.

**Comment by wslack** [comment]
I think we only need removing users, adding users (when that is added), adding a site, and deleting a site. Maybe also settings changes but doesn't need to include the specific change.

**Comment by el-mapache** [comment]
I think PR #1396 can be merged, although we won't begin tracking user actions until the code is added to the controllers/models to create records on add/delete.
