### ISSUE TITLE
Workshop video short bytes 

### ISSUE THREAD

**Issue by davidewarren** [18F/federalist#1364]
- identify sections of the workshop video  to be cut into short and useful bytes about specific topics
- Workshop: Making Government Websites with Federalist + GitHub Basics video - https://www.youtube.com/watch?v=qeFNf2EPzpE
- working doc https://docs.google.com/document/d/15YJanv1c-VNMaTOeGA0tpZqRyBwPJEyQUyCq60djPuY/edit

**Comment by wslack** [comment]
Done and being worked on now by DGU

**Comment by davidewarren** [comment]
all videos - may need to ask digital gov to update descriptions again:

    Government Website Hosting and Federalist:  https://youtu.be/Ld14X-9g1FM
•    Federalist and the US Web Design Standards - https://youtu.be/d2wAjWOk5JY
•    Federalist and Compliance - https://youtu.be/41a2TyiA5UA
•    Federalist - Make a New Site Demo - https://youtu.be/OdhZz7udd1o
•    GitHub Basics 1 - https://youtu.be/46T7Nbssyow
•    GitHub Basics 2 - https://youtu.be/fql8MAyhLTU

**Comment by wslack** [comment]
Let's circle back to this when the real videos are posted.
