### ISSUE TITLE
Removing a user from a site on federalist should also delete that site on federalist

### ISSUE THREAD

**Issue by el-mapache** [18F/federalist#1367]
Currently, the only way for a user to add themselves to a site on federalist is to clone the repo via Federalist. If a user is removed from that site, it will no longer show up in their list of sites, and should be deleted from the federalist database.

The repo will remain on the user's GitHub in case they need to re-add themselves.

Part of #1289 

**AC:**
- [ ] Removing a user from a site also deletes the site's record, where:
  * the `owner` field of the site matches the username of the user being removed
  * the `repository` field matches the repository of the site the user is being removed from

**Comment by wslack** [comment]
> The repo will remain on the user's GitHub in case they need to re-add themselves.

I think this is just saying "Federalist never changes user GitHub permissions; users who are improperly removed from Federalist access for a site can always re-add it." Is that right?

**Comment by wslack** [comment]
But we do want the *site* to remain, even if a specific user is dropped.

**Comment by jseppi** [comment]
I'm not sure I am following. When a site is already Federalist, and a user (with valid permissions) adds themself to it, the repository is _not_ cloned to their GitHub account.

**Comment by el-mapache** [comment]
@wslack Yes, although I don't think it has to be an improper removal per se....I just mean that we aren't going to remove repos from github.

**Comment by el-mapache** [comment]
@jseppi For some reason I thought adding a site always cloned it.

**Comment by el-mapache** [comment]
Ya'll can please feel free to edit the issue!

**Comment by jseppi** [comment]
This whole issue might be invalid. For a given `site` object in Federalist, there can be multiple `user` models associated to it. That `site` though only represents a single GitHub repository (in its `owner` and `repository` fields).

I do not think we want revoking a `user` to delete the associated `site`. We only want calling delete on the site itself to delete the `site` (but again, not the repository on GitHub).

**Comment by jseppi** [comment]
(it is confusing, I know :) )

**Comment by el-mapache** [comment]
Ok so, assuming I create a site on federalist backed by a repo in my personal github account, and I am accidentally removed from the site by a collaborator, will trying to re-add the site just create a new record in the join table (since the site already exists in federalist)? Or, will it throw an error, saying the site already exists?

**Comment by jseppi** [comment]
Well, I think we don't want the site repo owner to be able to get removed at all, right?

But in general, yes, the Add Site flow checks to see if the repo is already represented by a `site` model. If it is, then the user is added to the join table. If it is not, then a new `site` model is created.

**Comment by el-mapache** [comment]
Based on the original issue, I think we agreed that the owner shouldn't be able to delete themselves, but not that they shouldn't be able to be removed. To me this is sort of tricky since we don't really have a way to transfer ownership easily.

**Comment by el-mapache** [comment]
Also, for the record, I'm fine with an owner never being able to be removed!

**Comment by jseppi** [comment]
Yeah, true. Though I don't think the owner should be able to get deleted. The `owner` in the `site` model is the name of the GitHub account who owns it, not necessarily a Federalist user (especially since a GitHub owner could be an organization).

We do have an issue about transferring Federalist site ownership, though I can't find it right now. I think that would have to be kicked off on GitHub though, somehow.

**Comment by wslack** [comment]
Right - I think based on this chain that this issue might be an N/A. Users in Federalist are interchangable, but a GitHub repo always has an "owner." As long as we don't let the last user delete themselves, we're good.

**Comment by jseppi** [comment]
...and/or the `owner`, right? Like if I have a personal repo `jseppi/my-site`, and I have given `wslack` access, he shouldn't be able to remove me from my own site.

**Comment by wslack** [comment]
sure! I don't think that would ever happen, but it applies.

**Comment by el-mapache** [comment]
Ok, closing this and updating the original issue to specify that an owner should never be able to be removed.

**Comment by wslack** [comment]
But when the owner is the `18F` org, there is no "owner" right?

**Comment by jseppi** [comment]
In our database the owner field would be `18f`. There will not ever be a `user` model with that username though.

**Comment by wslack** [comment]
Perfect. So in that instance the last "user" should still not be able to delete themselves. Ok I'm good now, thanks.
