### ISSUE TITLE
Site User Access Relationship to GitHub

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1375]
Thanks to @el-mapache's great work in https://github.com/18F/federalist/issues/1289, we now have the ability to manage user access to backend Federalist settings.

As we consider how to further build on a "add user" function, I want to step back and think about different strategies for how to manage access. Here are some of the guiding principles we apply today.

1. Access to the Federalist backend should not allow a user to change website content - the worst action they should be able to take is obviously bringing the site down. (by changing the custom URL or deleting from Federalist). This is important to ensure that site **integrity** can't be threatened by a Federalist user who goes rogue.
2. Federalist should not build out a repo unless someone with admin permissions for the repo adds it to Federalist.
3. Access to the Federalist backend shouldn't be required to edit the site - only to troubleshoot builds or file upload problems.

I think we have three options right now in terms of how to move forward with how to handle cases where users should lose permissions in GitHub and want to remove themselves in Federalist.

1. The status quo: users can be removed by other Federalist users and cannot remove or re-add themselves without `write` permission.
2. Set up access permission changes in GitHub to automatically modify permissions in Federalist. (would be really tricky when dealing with GitHub orgs and how they change permissions)
3. Modify the removal command to allow users to remove themselves even when they've lost permissions on the repo.

**Comment by jseppi** [comment]
Probably also related to https://github.com/18F/federalist/issues/1067 (Changing Federalist to a GitHub App instead of an OAuth App)

**Comment by wslack** [comment]
Seems like we are going with option 1?

**Comment by jseppi** [comment]
We've gone with option 1, so I think this can be closed.

If we want to have a feature where we do some syncing with GitHub, I think that should be in a separate issue.

**Comment by wslack** [comment]
Concur, should be in "Done?"
