### ISSUE TITLE
The same user can't fork a template multiple times

### ISSUE THREAD

**Issue by gbinal** [18F/federalist#138]
When I'm on https://federalist.18f.gov/#new and try to click 'Use this template' for the developer hub template, nothing happens.  

![screen shot 2015-08-31 at 3 57 06 pm](https://cloud.githubusercontent.com/assets/633088/9588920/0ee7403a-4ff9-11e5-99a1-8701042a143c.png)

**Comment by dhcole** [comment]
@gbinal are you taken back to the main home page (https://federalist.18f.gov/#)? If you go to that page, do you see `developer-hub` listed? 

<img width="755" alt="screen shot 2015-08-31 at 4 00 54 pm" src="https://cloud.githubusercontent.com/assets/170641/9588995/8105c196-4ff9-11e5-89c6-403bbd5f2e85.png">

If not, can you confirm that you authenticated with Github and check the web inspector to see if there is a JS error after you click the template?

**Comment by gbinal** [comment]
> are you taken back to the main home page (https://federalist.18f.gov/#)?

Nope.  Nothing happened.  

> If you go to that page, do you see developer-hub listed?

Nope.  

>  ...can you confirm that you authenticated with Github...

Si.  

> ... and check the web inspector to see if there is a JS error after you click the template?

Hmmm.... Let's see.    Yep.  Here you go.  

![screen shot 2015-08-31 at 4 09 27 pm](https://cloud.githubusercontent.com/assets/633088/9589199/b64b7098-4ffa-11e5-8466-e906bb1b2226.png)

**Comment by dhcole** [comment]
Let me look into this. Thanks for the report.

**Comment by dhcole** [comment]
The issue is that @gbinal already has a fork of this template. So using forks for templates means users would only be able to use a template once. We may need to look into some sort of cloning instead of using the fork API. :/
