### ISSUE TITLE
Incorporate ITIF report ranking into vote.gov site blurb

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1380]
#### Description of feature or bug

Incorporate brief note about vote.gov's ranking in the [ITIF report](http://www2.itif.org/2017-benchmarking-us-government-websites.pdf) into the vote.gov blurb [here](https://federalist.18f.gov/content/examples/)

#### Definition of done

Vote.gov's #1 ranking is written, edited, and added to example blurb. 

_After evaluating, edit this part:_

#### Level of effort - <low/medium/high>

low

**Comment by annahsebok** [comment]
Updated the issue to reflect the new piece of work specific to the ITIF report.

**Comment by wslack** [comment]
👍

**Comment by annahsebok** [comment]
Submitted https://github.com/18F/federalist/pull/1755, awaiting review, then this is done.

**Comment by annahsebok** [comment]
Merged!

**Comment by wslack** [comment]
Let's see if this can be a link!

**Comment by annahsebok** [comment]
Link update is over in #1772 PR awaiting review.
