### ISSUE TITLE
When creating new site from a template, always use `master` for the destination repo branch

### ISSUE THREAD

**Issue by line47** [18F/federalist#1386]
When adding a new site always create `master` branch no matter what the branch name is of the site you are creating from. For example, if I am creating a site from a branch named `awesome-branch` it will create my new site under the branch name `master` and not `awesome-branch`.

**Comment by jseppi** [comment]
This is for when creating a new site from a template only, right?

**Comment by line47** [comment]
Yep that's correct 👍

**Comment by jseppi** [comment]
I think this should only require a change to the build agent https://github.com/18f/federalist-garden-build

**Comment by jseppi** [comment]
The template repo can have any number of branches. The branch from it to use will be specified in the template config, as it currently is.

The change is that when a template repo is cloned and a new destination repo is made from that template, we will always call the destination branch on the new repo `master`. Currently it uses the same branch name as specified in the template config.

**Comment by jseppi** [comment]
Basically this is the change:

Current behavior:
`18f/template-repo/whatever-branch` -> `new-owner/repo-name/whatever-branch`

Suggested behavior:
`18f/template-repo/whatever-branch` -> `new-owner/repo-name/master`

**Comment by wslack** [comment]
I get that. My point is that our template repos will not be able to have a `master` branch since that would prevent the nameswap during cloning.

**Comment by jseppi** [comment]
No, that's not the case. There is no swapping going on. The template repos are not modified, only cloned. The destination repo can have a branch of any name pushed to it.

**Comment by jseppi** [comment]
I think we'd have to essentially just change this line https://github.com/18F/federalist-garden-build/blob/staging/tasks/clone.py#L84

to 

```py
ctx.run(f'git push {remote_name} {branch}:master')
```

**Comment by wslack** [comment]
I'm so confused. If you clone a repo with three branches: `master`, `new-feature`, and `legacy` - and then you choose to rename `new-feature` to `master`, doesn't that cause a problem?

**Comment by jseppi** [comment]
There is no renaming. The way creating a new site from a template works is: 

1. create a new repository in GitHub called`target-owner/target-name`
1. clone the source template repo to the build container filesystem
1. `git push` the specified `whatever-branch` from the cloned template repo to the target repo in GitHub (`target-owner/target-name`).

We currently push the same branch name that was cloned (`whatever-branch` in this example). We can easily change that to push that same branch (`whatever-branch` but with a different branch name on the target repo (`master`).

**Comment by wslack** [comment]
Ohhhhh I was mistaken; I thought all of the branches follow the clone. This makes complete sense then and I endorse it.

**Comment by jseppi** [comment]
:woohoo: 

Also interesting: in the build container we only actually grab the single, specified branch when we do a clone (from either a template or for a "normal" build). This saves on bandwidth and space.

**Comment by wslack** [comment]
👍 had no idea the mechanisms were shared

**Comment by wslack** [comment]
Why wasn't this closed in retro? Did we forget?

**Comment by jseppi** [comment]
we wanted to make sure the experimental template was removed (it has been) and that the container changes were deployed to prod (they have been)
