### ISSUE TITLE
Investigate individual test slowness and see if we can speed them up

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1387]
Individual tests are intermittently timing out when run in Circle. My guess is that this is a Circle load issue, but if we could speed our tests up then perhaps we won't get bit by it.

**Comment by jseppi** [comment]
This is getting fairly annoying. Mocking/stubbing out methods that do database calls during tests might be a good thing to do. It'll probably be a somewhat large lift though. The timeouts seem to be happening specifically on api-related tests that touch the database.

We could also just increase our test timeout _even more_, maybe just when running in CI (we can look for the `CI` environment variable and bump the timeout to like 5000ms when detected).

**Comment by jseppi** [comment]
cc @jmhooper

**Comment by wslack** [comment]
Let's talk about how to prioritize this during standup!

**Comment by jmhooper** [comment]
FWIW I vote that we don't stub database calls. Especially for the request specs since those function as integration tests for our backend and stubbing db calls leaves a pretty gaping hole in what's covered by those.

**Comment by wslack** [comment]
Discuss during standup?

**Comment by wslack** [comment]
Iceboxing as this hasn't reoccured.

**Comment by wslack** [comment]
Closing as we can reopen if circumstances force us, but don't feel this is a current issue.
