### ISSUE TITLE
Federalist site add feature fails to display error messages

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1392]
When I try to add a brand new repo in https://federalist.18f.gov/sites/new that's new, and I don't have admin privileges, Federalist fails but displays no error message. Clicking on the button appears to do nothing.

**Comment by wslack** [comment]
Confirmed that I can still add sites when I have `write` permission and they are already in Federalist.

**Comment by wslack** [comment]
I should have noted: I had this happen with https://github.com/gsa/emerging-technology-atlas

**Comment by saracope** [comment]
I just had this happen to me also with Opstat. Clicking the Submit repository-based site does nothing, but I can see the error in the console. 

<img width="1025" alt="screen shot 2017-12-21 at 9 01 36 am" src="https://user-images.githubusercontent.com/2197515/34258858-e317a698-e62d-11e7-805c-b9dd4e17fd0e.png">

**Comment by jseppi** [comment]
Sorry about that, Sarah. We have the fix implemented and will roll it out to production with our release tomorrow.
