### ISSUE TITLE
S3 file viewing doesn't show folders for "static" builds

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1398]
Example: https://federalist.18f.gov/sites/334/published/master121917

We thus run out of room for viewing all of the files on this screen.

<img width="1026" alt="screen shot 2017-12-21 at 10 37 44 am" src="https://user-images.githubusercontent.com/10016577/34262672-09fe3d32-e63b-11e7-8c01-1601ab5f4203.png">

**Comment by jseppi** [comment]
duplicate of #1362?
