### ISSUE TITLE
Front end website for users to interact with Federalist

### ISSUE THREAD

**Issue by dhcole** [18F/federalist#14]
Federalist is an API-driven application, so it needs a front-end website for users to interact with it:

- [x] Log in with GitHub
- [x] Add sites
- [x] Browse sites associated with user
- [x] Launch a site in Prose to edit it
- [x] Track build status messages

**Comment by dhcole** [comment]
Here's the latest draft of the 18F frontend guide: https://github.com/18F/frontend/pull/5/files?short_path=9fa8081&unchanged=expanded#processor

I'd also say we try to stick with `npm` and `browserify` for building and avoid Grunt, Gulp, Bower, Make, or anything additional unless there's a good reason.

**Comment by bradnunnally** [comment]
@dhcole I took a look at what you have listed here and started to think out various flows that may, or may not, occur when someone is using the federalist admin front end. This is purely brainstorming stuff, but I took the overall concept you had for a front end and thought about what would it looks like if it was a true admin management site/page. 


![federalist_diagrams_v0](https://cloud.githubusercontent.com/assets/12515096/8042779/22ca71c0-0de7-11e5-9e40-abe0655566da.png)

**Comment by jeremiak** [comment]
This looks cool, @bradnunnally!

I think for the first phase the edit and new post functions will both be handled by a tool like [prose.io](http://prose.io) but otherwise we're on the same page :)

**Comment by dhcole** [comment]
:+1: looks great @bradnunnally

**Comment by bradnunnally** [comment]
Sweet. Yeah this isn't meant to showcase screens or UI all that much. More just list out the types of tasks people may, or may not, wish to accomplish and what order. 

This can be a bit of a living document as the platform expands and we learn more about the two main user groups and their underlying goals and needs.
