### ISSUE TITLE
Alerts are styled strangely (not full width or always full width)

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1406]
For instance: this should not be 100% across the screen:

<img width="955" alt="screen shot 2017-12-22 at 1 15 37 pm" src="https://user-images.githubusercontent.com/697848/34309946-4d60553a-e71a-11e7-80da-56c53cf8b5b5.png">

And this is not wide enough:

<img width="1092" alt="screen shot 2017-12-22 at 1 17 45 pm" src="https://user-images.githubusercontent.com/697848/34309989-86acc080-e71a-11e7-8ae1-e9dbb9e748f0.png">

**Comment by line47** [comment]
@jseppi - how can I generate that second "unauthorized" error locally?

**Comment by jseppi** [comment]
good question. I think the easiest thing to do is to modify `main.js` so that the `home` method looks like this:

```js
  home(req, res) {
    // Here's the code that will trigger showing an error message
    req.flash('error', {
      title: 'Unauthorized',
      message: 'You are not permitted to perform this action. Are you sure you are logged in?',
    });
    // ^ Make sure to remove this before the PR

    // redirect to main app if is authenticated
    if (req.session.authenticated) {
      return res.redirect('/sites');
    }
    const context = defaultContext(req);
    return BuildCounter.countBuildsFromPastWeek().then((count) => {
      context.buildCount = count;
      res.render('home.njk', context);
    });
```

then log out of your local instance at https://localhost:1337 and refresh your browser window.

Just make sure to remove that code before making your PR :)

**Comment by wslack** [comment]
Why was this closed?

**Comment by wslack** [comment]
Connected to PR, moved to "Done?"

**Comment by wslack** [comment]
Oh, because we fixed before merge. Right.

**Comment by jseppi** [comment]
yup, sorry, should have mentioned in comment
