### ISSUE TITLE
Update dashboard view to be more useful

### ISSUE THREAD

**Issue by maya** [18F/federalist#1408]
The layout and functionality of the CircleCI dashboard could work pretty well for federalist. I’m always searching for my project whenever I login to federalist, and pretty much am always looking for the last project that’s building.

## CircleCI Dashboard
<img width="1279" alt="screen shot 2017-12-22 at 11 25 22 am" src="https://user-images.githubusercontent.com/5249443/34310284-862aa2c6-e70b-11e7-8271-cb3c152ec282.png">

**Comment by wslack** [comment]
@maya is the main goal here to have all of a single user's recent builds show up together?

(also, would it be helpful to note that a builds page can be bookmarked?)

**Comment by wslack** [comment]
I'm not sure how much to prioritize this. It will be a lot of work and users can bookmark their builds pages.

**Comment by wslack** [comment]
Closing; happy to pull our specific user stories to replace this if and as they come up. (for example, if you want your last built project to show up at the top)
