### ISSUE TITLE
Only enable tracking scripts (Google analytics/tag manager/DAP) in production

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1413]
@line47 and @laurenancona: should we only include our tracking scripts in the production instances of Federalist?

**Comment by jseppi** [comment]
(this would be easy to implement)

**Comment by line47** [comment]
Yeah - we should only be tracking on Production 👍

**Comment by wslack** [comment]
Moved to "ready" when @jseppi has time to do this.

**Comment by jseppi** [comment]
Confirmed that tracking scripts are present in production after today's deploy.

<img width="375" alt="screen shot 2018-01-19 at 2 28 24 pm" src="https://user-images.githubusercontent.com/697848/35170241-1b32822e-fd25-11e7-84cc-9a479d014629.png">
