### ISSUE TITLE
S3SiteRemover likely does not delete all site files if there are more than 1000 of them

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1416]
While working on #1402, I noticed that the `getObjectsWithPrefix` function in `S3SiteRemover.js` is not called recursively, which means it is likely subject to the same issue as the `S3PublishedFilesLister` (#1398), ie only the first 1000 objects with the specified prefix are retrieved (and thus deleted) from S3.

**Comment by wslack** [comment]
Flagging to "ready" since this seems important to fix alongside https://github.com/18F/federalist/pull/1402.

**Comment by wslack** [comment]
Can we address this with #1402 or will we need another PR?

**Comment by jseppi** [comment]
I'll address this one with #1402 (making some shared code that both the deletion logic and file listing logic can share)

**Comment by jseppi** [comment]
Yup

**Comment by jseppi** [comment]
Done by #1402
