### ISSUE TITLE
Deleting a site whose owner/name is a substring of another's will also delete the other site's files

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1417]
If there is "repo1" with owner/name `owner/repo-a` and "repo2" with owner/name `owner/repo-a-test` (ie repo1's owner/name is a substring of repo2's), then when repo1 is deleted, repo2's files will also be deleted.

This is because every repo2 file has an S3 key that is prefixed the same as those for repo1. When our deletion code (in `S3SiteRemover.js`) retrieves a list of S3 keys for a site , it uses the `Prefix` argument (ex `site/owner/repo-a`) to retrieve that list. Because repo2's files all start with the same characters (ex, `[site/owner/repo-a]-test/whateverfile.txt`), they will also be retrieved and added to the list of files to be deleted.

**Comment by wslack** [comment]
Does this apply to `owner` and `name` or just `name`? Seems like if the owner is different than the substring wouldn't fire.

**Comment by jseppi** [comment]
yes, `owner` must be the same. It has to be something like `18f/some-site` and `18f/some-site-that-also-will-get-deleted`

**Comment by jseppi** [comment]
this is pretty nasty bug in my opinion

**Comment by el-mapache** [comment]
Seems like we might want to prefix the prefix (ugh) with some flavor of SHA to minimize the chance of this happening.

**Comment by jseppi** [comment]
I think we mostly just have to add a trailing slash when we specify the prefix in our calls to S3's `listObjects`. Ie, always call it with `18f/some-site/` and `18f/some-site-that-also-will-get-deleted/`.

Though I think adding the slash will miss the "root" redirect object that exists at the exact path `18f/some-site`, so we'll need to account for that as well.

**Comment by wslack** [comment]
I don't think this will hit us that often, and its easy to fix by re-adding the deleted site, but agree it should be prioritized.
