### ISSUE TITLE
How can users measure memory consumption of their builds locally so that they can make sure they'll work in our build container?

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1418]
(Edit: this issue will be done when we've identified a mechanism to make this measurement or concluded we don't know of one)

Our build containers are limited to 1G of memory. How can users who are having problems with overrunning that memory allotment find out locally on their machines how much memory their build process uses?

For more information, it appears that `npm install` and `npm install --dev` are big memory hogs.

**Comment by jseppi** [comment]
cc @donjo: If you figure out something, please let us know so we can recommend to future folks

**Comment by donjo** [comment]
I didn't figure out how to do this specifically but some general tips:

1. I bumped the node version in `.nvmrc` from `6` to `8` and builds that weren't happening before are now working so it looks like npm 5+ may be a bit more efficient.

2. [cost-of-modules](https://www.npmjs.com/package/cost-of-modules) is a package I found for seeing which packages have the most children.

**Comment by jseppi** [comment]
Thanks, @donjo. I do remember reading a while back that npm 5 had a lot of performance enhancements over previous versions.

**Comment by jseppi** [comment]
This hasn't come up again since we upped our build container's memory to 1.5G, and I don't have a good path forward on figuring this out. 

@wslack: I suggest closing or de-prioritizing since the memory bump seems to have cleared up the problem.

**Comment by wslack** [comment]
Backed down to backlog per James's message.
