### ISSUE TITLE
Only pass build id when restarting a build

### ISSUE THREAD

**Issue by el-mapache** [18F/federalist#1420]
Currently, when a user restarts a build from the front-end, we unnecessarily pass data to the server that the back-end could easily look up. Rather than explicitly provide the branch and commit, we can pass the build's `id` to the server and let it get the data necessary to restart a build.

**AC:**

- [x]  amend front-end to pass only the build `id` to the federalist API
- [x]  amend controller to get the build data from the database

**Comment by wslack** [comment]
@el-mapache do you think you can get to this next week?

**Comment by el-mapache** [comment]
@wslack This work is done and merged!

**Comment by wslack** [comment]
Bah, penalty for being on wrong computer, sorry.

**Comment by el-mapache** [comment]
Hah no worries!
