### ISSUE TITLE
Validate `commitSha` shown in front-end builds table

### ISSUE THREAD

**Issue by el-mapache** [18F/federalist#1421]
Since we know a `commitSha` is always going to be a valid hexadecimal string, we should validate it with a regex and only show it if the sha is valid.

**AC:**

- [x] Validate the `commitSha`property against a hex regex.

**Comment by jseppi** [comment]
Both front and back end?

**Comment by el-mapache** [comment]
I don't think we currently have a way for an invalid commit SHA to be passed to the `Build` model during creation, so I think we only have to validate the SHA on the client side

**Comment by jseppi** [comment]
Can't invalid commitSHAs be passed in (currently) at both https://github.com/18F/federalist/blob/staging/api/controllers/build.js#L49 and https://github.com/18F/federalist/blob/staging/api/controllers/webhook.js#L74 (through tampered/spoofed requests)?

**Comment by jseppi** [comment]
Oh, the webhook one can't be messed with since the requests are signed with the webhook secret, and once the refactoring of rebuilds is done (#1422), then there shouldn't be any other place commitSHAs are used.

**Comment by wslack** [comment]
Assigned to @el-mapache but happy for @jseppi to take.

**Comment by wslack** [comment]
Should be completed in https://github.com/18F/federalist/pull/1422

**Comment by jseppi** [comment]
And also in https://github.com/18F/federalist/pull/1432: https://github.com/18F/federalist/pull/1432/files#diff-474d1fcce1481fd70cce15a93b699614R110
