### ISSUE TITLE
Federalist reports a successful build when it actually failed

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1423]
Code: https://github.com/18F/project-guide/tree/d5e7b4940316d0a6fb3263a30ce7fa6456601603

**Comment by jseppi** [comment]
What's the failure cause? Is there something in the logs that looks like a failure?

**Comment by wslack** [comment]
Logs:
```[COMMON] 2017-12-27 22:29:11 INFO: Cleaning /tmp/site_repo
[CLONE] 2017-12-27 22:29:11 INFO: Cloning 18f/project-guide/master to /tmp/site_repo
[COMMON] 2017-12-27 22:29:11 INFO: Cleaning /tmp/site_repo/_site```

```[BUILD] 2017-12-27 22:29:12 INFO: Node version: v8.9.3

[BUILD] 2017-12-27 22:29:13 INFO: NPM version: 5.5.1
```

**Comment by jseppi** [comment]
The logs just end after reporting the NPM version AND it somehow reported a success? That's very strange...

**Comment by wslack** [comment]
Yep.
<img width="796" alt="screen shot 2017-12-29 at 3 06 29 pm" src="https://user-images.githubusercontent.com/10016577/34446543-df4da12a-eca9-11e7-87b6-7dec0b83f5e9.png">

**Comment by wslack** [comment]
The logs I put above are from the second-to-bottom shot

**Comment by wslack** [comment]
Checking to see if this recurred

**Comment by jseppi** [comment]
Reported by another user today. As @jmhooper suggested, this is potentially due to the log request being too big and getting rejected by the web app. The web app limits request size to 2mb (https://github.com/18F/federalist/blob/staging/app.js#L58).

**Comment by jseppi** [comment]
If the log size is the case, I wonder if instead of increasing the limit, we should split the logging into multiple requests.

**Comment by jseppi** [comment]
I searched through logs from this weekend (1/6/18-1/8/18) and if it was the size that was the problem I would have expected to find a message that said `"request entity too large"`. I did not find any such error messages logged.
