### ISSUE TITLE
Build status not reported to GitHub when GH user does not have Federalist account

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1425]
Reported by @hursey013:

A GitHub user with write access to a repository that had been added to Federalist opened a Pull Request with a single commit change. The user did not have a Federalist account. The Federalist build succeeded, but the no PR status was ever reported to GitHub.

**Comment by jseppi** [comment]
Here's a PR where this happened: https://github.com/GSA/plainlanguage.gov/pull/185

Notice when clicking the first checkmark to see the passing status checks from the initial commit, Federalist's PR status check is not there:

<img width="787" alt="screen shot 2017-12-29 at 9 21 11 am" src="https://user-images.githubusercontent.com/697848/34440262-ab197170-ec79-11e7-8a30-3f9b88ea5efb.png">

**Comment by jseppi** [comment]
More context: This commit was the user's first commit to the repository. A subsequent PR opened by the same user with a new commit did properly get Federalist status checks reported.

**Comment by wslack** [comment]
Also, it seems like at least one other "first" commit had an issue as well.

**Comment by wslack** [comment]
Moving to "backlog" right now absent other user reports.
