### ISSUE TITLE
[Federalist application] - Use demo, preview and live site text consistently

### ISSUE THREAD

**Issue by line47** [18F/federalist#1427]
EDIT:
This is done when we've implemented consistant language in the Federalist application, noted what else in the content rules isn't implemented yet, then linked the content rules from the README.

----
Original issue:
Throughout the Federalist application the words `site` and `website` are both used for headers links and buttons. We should be consistent about which word is used. In addition sometimes `view` is used and other times `visit` is used. for example, `visit site` and `view website`.

This can be seen on the all sites listing page as well as the branches and published files pages.

**Comment by wslack** [comment]
@line47, mind pairing with @davidewarren on this one?

**Comment by line47** [comment]
A doc that @OpenGlobe started around this naming https://docs.google.com/document/d/1bqRoi97-G-ixoaJU2pB1K-tNJT57_h4L5twE3kkKer4/edit#heading=h.kxxwigcc0fsb

**Comment by wslack** [comment]
Once @OpenGlobe is good with that doc (and I'm good with it), this can be executed against. Needs to hold for David to have time given the ATO priority, though.

**Comment by annahsebok** [comment]
Hi folks! I popped into https://docs.google.com/document/d/1bqRoi97-G-ixoaJU2pB1K-tNJT57_h4L5twE3kkKer4/edit#heading=h.kxxwigcc0fsb and dropped a few comments but otherwise, this appears to be good to go and is just in need of @OpenGlobe's 👍. Does that seem right to you all, or am I missing something?

**Comment by wslack** [comment]
Yep! Thanks @annahsebok!

**Comment by davidewarren** [comment]
Checklist of changes from this working doc - https://docs.google.com/document/d/1bqRoi97-G-ixoaJU2pB1K-tNJT57_h4L5twE3kkKer4/edit#heading=h.kxxwigcc0fsb

- [ ] "Visit site" changed to "View site" on https://federalist.18f.gov/sites
- [ ] "Published files" changed to "Uploaded Files" in left nav
- [ ] add site name to the left navigation bar

**Comment by davidewarren** [comment]
going with @line47 's recommendation, I submitted the PR with just the first and second changes above. We may want to open a new issue for - adding site name to the left navigation bar - if it's something we want to go ahead with

**Comment by wslack** [comment]
@davidewarren let's note what you did in the doc, note what might be left, then memorialize what's been done. I'll modify the issue a bit to reflect that.

**Comment by wslack** [comment]
edited above

**Comment by davidewarren** [comment]
"Visit site" changed to "View site" on https://federalist.18f.gov/sites
"Published files" changed to "Uploaded Files" in left nav
opened issue #1577 for adding site name and description to navigation
