### ISSUE TITLE
[Federalist application] -  Make left hand nav names and page titles match

### ISSUE THREAD

**Issue by line47** [18F/federalist#1429]
Currently the title of the page does not match the left hand navigation name.
For example, navigation name is `Build history` but page header is `builds`. 

Update so the navigation link and page header are the same.

**Comment by line47** [comment]
@OpenGlobe - love to have your thoughts on this left hand nav and page titles thread

**Comment by OpenGlobe** [comment]
I put a section in [this doc](https://docs.google.com/document/d/1bqRoi97-G-ixoaJU2pB1K-tNJT57_h4L5twE3kkKer4/edit#heading=h.hl1ckqk2b6fx) that addresses this (the table) - let me know if that's what you needed?

**Comment by line47** [comment]
Thanks @OpenGlobe - here is what I've distilled from that doc

Left Nav | Header
-- | --
Build history | Build history
Github branches | Github branches
View files | View files
Collaborators | Collaborators
Settings | Settings 

CC @wslack like to get your thoughts on this

**Comment by wslack** [comment]
I don't have access to @OpenGlobe's doc, but this seem generally good to me. I question "view" since the menu is more for auditing the files than viewing them.

**Comment by line47** [comment]
I'm also unsure on the "View files", consequently this led to my thinking about combining the "GitHub Branches" and "Published files" pages merging in #1439

**Comment by line47** [comment]
@jseppi Are the titles for the pages in the federalist application taken from the URLs? 
I’m looking for where to update `branches` to be `GitHub branches` and can’t find it.

**Comment by jseppi** [comment]
Yeah, they're taken from the URLs

**Comment by line47** [comment]
hmmmm, I'd love to be able to set these with a variable or match them to the left nav name somehow if you or @el-mapache have thoughts on how to accomplish that?
