### ISSUE TITLE
[Federalist application] - Removing duplicate "Add website" button 

### ISSUE THREAD

**Issue by line47** [18F/federalist#1430]
Remove the duplicate add website button from the bottom of the `Your websites` page.

There is already an add website button at the top of that page therefore removing the duplicate add website button from the bottom of the page cleans up the UI a bit.

**Comment by line47** [comment]
OK to move this to `Ready` ?

**Comment by wslack** [comment]
🤷‍♂️ it's somewhat helpful during demos not to have to scroll up, but I can understand how it doesn't look good on a blank page. Not questioning the low effort, but it is a bit helpful when demo'ing. @leahbannon wdyt?

**Comment by line47** [comment]
I'm happy to work this in to some other minor issues.

I don't feel that leaving the duplicate button in the application because of demo'ing is a strong enough reason to keep it.

**Comment by wslack** [comment]
What if we change it to a return to top button?

**Comment by line47** [comment]
I like that much better, Return to top [_link_](url) and I'm 💯  in 👍

**Comment by wslack** [comment]
Cool, do you want to edit the issue or should I?

**Comment by line47** [comment]
I'll add it
