### ISSUE TITLE
Sites page title styling is broken (on staging only, currently)

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1433]
<img width="603" alt="screen shot 2018-01-02 at 1 13 32 pm" src="https://user-images.githubusercontent.com/697848/34496345-d5e9efd6-efbe-11e7-984d-21a3273050d6.png">

As pointed out by @wslack in https://github.com/18F/federalist/pull/1431#issuecomment-354846114

**Comment by line47** [comment]
Thanks for this! I'm going to update to make the headers more consistent in the markup 👍  PR coming soon...
