### ISSUE TITLE
Add a new view to display all of the actions taken by users of a site

### ISSUE THREAD

**Issue by el-mapache** [18F/federalist#1435]
Rather than only showing actions taken by the current user, we want a table that shows all actions taken by all users of a given site. For example, a user should be able to see when they have been removed from a site, and by whom. 

For now, the only action enumerated is removing a user from a site.

A couple of open questions:

* How do we want to present the table?
  * Each user row has its own link, that shows only actions taken by that user?
  * or, one large table that can be filtered with actions taken by all users?
  * First case seems more desirable, unless users want the ability to see all the data and filter it
* What is the cutoff point for paginating the table?

**Comment by wslack** [comment]
My first guess, subject to user feedback, is:

- Paginated at 50
- Each row is an action
- One column is the user who did the action, another is the exact time of the action, the other is a description of the action.
- Doesn't have to be a fancy description; this is for auditing, not for most users.
- Linked from the user page

**Comment by el-mapache** [comment]
I think we may also want a column in the table saying against what entity the action was performed. 

Like if Sally removed Joe, we would want the table to explicitly say that Joe was removed.

**Comment by jseppi** [comment]
Like this?

| Initiator | Target | Timestamp          | Action            |
|----------|--------|--------------------|-------------------|
| sally    | joe    | 2018-01-01 5:00:00 | removed from site |
| sally    | sara   | 2018-01-01 5:10:05 | added to site     |
| sara     | joe    | 2018-01-02 8:20:45 | added to site     |

**Comment by el-mapache** [comment]
I think so! Thats more or less what we have already, in terms of data. Or will have, when the first PR is merged 😄

**Comment by wslack** [comment]
Oh right - I was just saying that `Target` and `Action` cane be combined if wanted.

**Comment by jseppi** [comment]
I personally like separate columns (easier to visually scan IMO), but could also maybe see that feeling crowded or something.

**Comment by jseppi** [comment]
I think we might also want to capture and display which site a user was added/removed from.

| Initiator | Target | Timestamp          | Action            |
|----------|--------|--------------------|-------------------|
| sally    | joe    | 2018-01-01 5:00:00 | removed from 18f/federalist-docs |
| sally    | sara   | 2018-01-01 5:10:05 | added to jseppi/test-federalist-site     |
| sara     | joe    | 2018-01-02 8:20:45 | added to site 18f/frontend    |

**Comment by jseppi** [comment]
thus, I think the `UserAction` model needs to also include an FK reference to the site it was enacted upon

**Comment by wslack** [comment]
@jseppi I thought that logs were being maintained separately per site - so the context should always be clear. If there's a master database instead, that would make sense, but we don't *need* that IMHO.

**Comment by jseppi** [comment]
The site was not captured at the time of my commenting, but I think it is now in #1414

**Comment by wslack** [comment]
Sadly, its not. Right now the action log doesn't explain which site so its confusing. It's also not explained that the log is specific to actions from the viewing user.

I don't think we've yet completed the use case from the original issue https://github.com/18F/federalist/issues/1360:

> Users need a way to see when they have been removed from a site, and by whom. While we're at it, we might as well capture other actions too!

**Comment by el-mapache** [comment]
@wslack I'm starting to add this right now. All the user action records have an explicit site id, I'm just figuring out the best way to get that data to the front-end

**Comment by jseppi** [comment]
How about just changing the Action table on the Users page to only display the actions for the site that's currently in "scope?" The site id (as a string) is in `props.params.id`.

**Comment by el-mapache** [comment]
That is definitely the quickest way, but when users start accumulating a lot of actions we are going to be fetching a lot of unnecessary data, and limiting the number of records we retrieve is going to mess with the action log too....but I guess that's premature optimization at this point, since we are only tracking one action that isn't _super_ frequent.

**Comment by jseppi** [comment]
Ah, that's true. Maybe rather than always returning the actions for `me`, what about a separate API call that returns all actions for a given user id, with optional filtering if site id is also provided?

**Comment by el-mapache** [comment]
That is what I was thinking! My first thought was to put that call into the `SiteContainer`, but since we use redux and connect now we can make any component a 'container'.

Do we have a standard practice about which components we try to lift up to containers? I know generally you want them to be as high up in the tree as possible, I suppose its just up to our discretion where we want to define new branch nodes. At this point I guess `SiteUsers` could be a container component?

I'm probably overthinking this, but some of the decision will probably be based on what view ultimately ends up displaying the table.

**Comment by jseppi** [comment]
I don't think we have a standard practice, no. I'd just put it where is easiest at this point. I suspect we'll want to break off a new "top-level" view called "Audit Actions" or something at some point rather than having it in the Users view, if that helps guide you.

**Comment by el-mapache** [comment]
I think that getting user actions by site id should be the default. The most common use case, if I've understanding this thread correctly, is that a user wants to be able to see all actions taken by all users of the site.

I think the optional filtering call might come in the form of restricting actions retrieved to a specific user, or a specific type of action or whatever.

**Comment by jseppi** [comment]
Oh, yeah, you're right re:filtering by site id (and not by user id). Definitely want to get all actions by all users for the given site. My mistake!

**Comment by wslack** [comment]
@el-mapache is this still something you want to tackle? I assumed it was still on your plate but now that its in backlog I wanted to check on.

**Comment by wslack** [comment]
I think this is blocked by the other issue.

**Comment by el-mapache** [comment]
@wslack Yep! Was planning on starting this afternoon, depending on whether or not my API PR gets reviewed.
