### ISSUE TITLE
Add section on eslint strategy and tooling to README

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1437]
- linting files as they are modified, since this is a somewhat old codebase that is being brought up to the g-frontend standard
- using `eslint --fix` to auto fix a file (via command line or through your editor)

**Comment by wslack** [comment]
Help me understand the priority?

**Comment by jseppi** [comment]
Fairly low, but also should only take a few minutes to write up. It's just documenting our process of linting old files as they are touched.

**Comment by wslack** [comment]
I trust your judgement if its quick. Feel free to self-assign and move to ready so you can pull it as a palette cleanser sometime. :)

**Comment by jseppi** [comment]
Bumping to Ready. This will be quick and will help folks who join the project.

**Comment by wslack** [comment]
SGTM
