### ISSUE TITLE
Can GitHub branches and Published files pages be merged?

### ISSUE THREAD

**Issue by line47** [18F/federalist#1439]
I was wondering if it would be possible and easier to understand if the **GitHub Branches** and **Published files** pages were combined to show GitHub branches on the top and then the branches that only exist on S3 below on the same page?

Here is a screenshot/mockup to help illustrate.
(Also adding the **view files** link to the branches here)

### Screenshot
![screen shot 2018-01-03 at 5 39 33 pm](https://user-images.githubusercontent.com/1449852/34543030-f849d732-f0ac-11e7-94cd-dea45f1bdb63.png)

**Comment by wslack** [comment]
What's the user benefit here? (do people typically need to look at the info together?)

**Comment by line47** [comment]
The thought here is to simplify the experience between the branches and published files pages as they are almost identical. Both contain a table of branches and actions. The current difference is nuanced and I feel makes it harder to understand.

**Comment by wslack** [comment]
Setting to low as this has som impact and the current app design could be researched more?
