### ISSUE TITLE
Alpha to Beta transition

### ISSUE THREAD

**Issue by jeremiak** [18F/federalist#144]
This issue is a list of things we must get done before the launch of Federalist
- [ ] Change "Alpha" to "Beta" across the site (#143)

**Comment by dhcole** [comment]
@jeremiak does it make sense to tie the alpha => beta transition to a new editor?

**Comment by jeremiak** [comment]
Sure @dhcole, I'm open to that. I think with two launches and a completely new editing interface we're pretty squarely in a [beta](https://18f.gsa.gov/dashboard/stages/) phase
