### ISSUE TITLE
Allow users to create builds from branches on GitHub

### ISSUE THREAD

**Issue by el-mapache** [18F/federalist#1440]
On the `SiteGithubBranches` view, users can see all branches for a given site, however, they can only build branches that have previously been built on Federalist. To give the user a more consistent experience, we should consider adding the ability to build any arbitrary branch.

To do this, we'll have to use the GitHub API to grab the requested branch and base the new build off of it. We should already have the code to do this, so it's just a matter of wiring it up!

**Comment by wslack** [comment]
The other advantage of wiring this up is that if builds don't trigger for any reason, the user can do it with a click. I like this as a mitigation against the recent bug report.

What do you think the effort is @el-mapache?

**Comment by el-mapache** [comment]
I don't anticipate it taking more than a day to finish!

**Comment by wslack** [comment]
Cool; I think this can go to "ready"
