### ISSUE TITLE
Rerecord demo

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1443]
Don't use "backend" and "frontend" in materials

Talk about "Infrastructure, Security and Compliance" and "Design, Content" as the two areas.

**Comment by wslack** [comment]
@wslack 

Write outline

@leahbannon 

Critique existing demo vid

@tram 

Provide feedback.

If the demo is good enough, open issue to put on the main site.

**Comment by eddietejeda** [comment]
Good idea but will not be worked on anytime soon.
