### ISSUE TITLE
[Federalist application] - Consider updating time last published text

### ISSUE THREAD

**Issue by line47** [18F/federalist#1448]
Consider updating time last published text on site list to be more succinct.

- Currently reads `This site was last published at January 5th 2018, 12:34:35 pm.`
- Shorten to read `Last published on January 5th 2018, 12:34:35 pm.`

### Screenshot example 

![screen shot 2018-01-05 at 12 46 03 pm](https://user-images.githubusercontent.com/1449852/34621221-4c260974-f216-11e7-9592-8fe16d46823b.png)

**Comment by jseppi** [comment]
hrm, I wonder what timezone those are in. We specify it! And, if it is UTC or something, maybe standardize them all to Eastern.

**Comment by jseppi** [comment]
Done by #1475
