### ISSUE TITLE
No padding between error and first site in site list

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1454]
I'd expect some padding to be between them.

Here's what it currently looks like:
<img width="1005" alt="screen shot 2018-01-05 at 2 40 01 pm" src="https://user-images.githubusercontent.com/697848/34627518-6d29072e-f226-11e7-84c0-b19f98ec6f15.png">

To duplicate, add an already added repo to your federalist account, then see the error at the top of the Sites list page that you're redirect to.

cc @line47

**Comment by wslack** [comment]
Moved to ready; this should be easy to fix.

**Comment by line47** [comment]
Looks like this is no longer an issue 😃 

Just took this screenshot from staging...
![screen shot 2018-01-25 at 11 39 02 am](https://user-images.githubusercontent.com/1449852/35400099-e94931ec-01c3-11e8-99f8-e672707c6fa0.png)
