### ISSUE TITLE
User record was attached to a Federalist site prior to user being able to log into Federalist

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1460]
![image 1](https://user-images.githubusercontent.com/10016577/34632812-b0c5ada6-f245-11e7-8916-1c2952d7c6ad.png)

At the time this screenshot was take (1/4/18 16:30 ET) the bottom user had not gotten access to log into Federalist, despite repeated attempts to log in and set up 2FA.

As of today (1/5/18 14:02 ET), the user is now white-listed and can log in as normal.

Definition of Done: We should understand how the user record was able to appear there in order to assess if there's a wider issue. Would logs be able to tell us when his user record appeared (sometime after mid-October?)

Effort: low?

@jseppi or @jmhooper, want to take a crack at looking into this? I'm mostly curious because that screenshot **should be impossible** so something is misbehaving.

**Comment by jseppi** [comment]
Yeah, this is perplexing. I don't see anything in the auth code that should have allowed this. Will have to do some more in-depth digging.

**Comment by jmhooper** [comment]
If the user pushed a commit to the site, we add a non-auth user record for them to associate with the build.

**Comment by jseppi** [comment]
Ah, so we should filter that site users API response to only include auth'd users in order to avoid confusion like this.

**Comment by jmhooper** [comment]
Yep, that should work.

For reference, here is where that user record is created: https://github.com/18F/federalist/blob/staging/api/controllers/webhook.js#L84-L87

**Comment by jmhooper** [comment]
Another suggestion would be to flag it as "Commit user" or "Build only user" or something like that.

**Comment by jseppi** [comment]
What do you think, @wslack?

Options:
- Demarcate the user somehow ("commit user", "build user", "no Federalist account yet", ???)
- Filter such users from the users table

**Comment by wslack** [comment]
Hmmm. I think we should filter such users from the table, since their Github account being associated with builds is separate from logging into Federalist, the focus of the "remove" function.

**Comment by wslack** [comment]
There's nothing Federalist can say about their commits that GitHub doesn't already say better.

**Comment by jseppi** [comment]
Suggest closing this, since we figured out what is going on, in favor of new issue https://github.com/18F/federalist/issues/1480 that documents what to change
