### ISSUE TITLE
Not getting one time passcode

### ISSUE THREAD

**Issue by pahan12** [18F/federalist#1461]
Hi,
 i came through hackerone bug bounty program and want to install federalist locally.
i followed all the step in README.md . 
In step 5 i typed ```cf login --sso -a https://api.fr.cloud.gov -o gsa-18f-federalist -s staging```
And in step 6 , i visited https://login.fr.cloud.gov/passcode to get passcode but it redirect me to login page.
So, how i will get this passcode to install it locally or i have to change url in above command ?

thanks............

**Comment by wslack** [comment]
Hi @pahan12,

You shouldn't need a cloud.gov account (which we cannot provide) to run part of Federalist locally. @line47 - do you have advice here?

**Comment by jseppi** [comment]
That part of the setup instructions is to get S3 bucket credentials that we use for our local development instances. You can setup your own S3 bucket and use those credentials instead of needing to use ours.

**Comment by pahan12** [comment]
OK now understood .
Is there any documentation for setup using s3 bucket?

Thanks

**Comment by wslack** [comment]
Yes. The README explains what to do with the S3 information when you get it.
