### ISSUE TITLE
Build Logs page receives 403 error and displays error message to user

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1463]
![image](https://user-images.githubusercontent.com/697848/34676224-bd4138ee-f451-11e7-8003-dfb45f721d6f.png)

Definition of Done: Bug is resolved and there's a test for this scenario
Effort: probably low?
Implementation: Adam is looking at logs and troubleshooting.

**Comment by jseppi** [comment]
Haven't tracked it all the way down yet, but this happens when a build is associated with a different user from the currently logged-in user.

**Comment by jseppi** [comment]
Yup, it is the `buildAuthorizer`'s `findOne` method causing the unauthorized error here.

**Comment by jseppi** [comment]
With the fix, we should add a test that makes sure the logs from a build created by a different users are accessible by the current user (when both of them have access to the associated site).

**Comment by wslack** [comment]
Moved to In Progress; @el-mapache will assume you have this.
