### ISSUE TITLE
Audit `/build/:id`API route and associated methods

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1467]
Route in question: https://github.com/18F/federalist/blob/staging/api/routers/build.js#L9

Related to PR #1466  and issue #1463.

Due to changes in the `buildAuthorizer`'s `findOne` method as part of #1432, the logic will only authorize fetching of a specific build by the user who made the build initially (which was the problem that caused #1463).

Cursory search reveals that fetching a specific build is not actually used anywhere in the front end application. If it is really not used anywhere I think we should remove that API route and associated code, including the controller, authorizer, and tests.

@jmhooper: do you recall anywhere that fetching a specific build by id is used?

**Comment by jseppi** [comment]
Also, currently when trying to access a build that the current user did not create (even if it is for a site that the user has access to), the `403` error message is off since it references the creation of a new build, when it should only be about access:

```json
"message": "Unable to build. Check that you have access to this site, and that this branch has previously been built on Federalist.",
"status": 403
```

**Comment by jmhooper** [comment]
I don't know of anywhere that it is used. From the git blame, it looks like I added it when I disabled sails's blueprint route generation tooling, so it may have been a route that was auto-generated by blueprint that was never used.

**Comment by jseppi** [comment]
Cool, thanks for the info.

My recommendation is that we remove it and associated code/tests. If it becomes necessary, we can take another look at it.

**Comment by jmhooper** [comment]
Agreed :+1:

**Comment by jmhooper** [comment]
ref https://github.com/18F/federalist/commit/0f2876b986c1af9e688e24c12bb59274e688773b
