### ISSUE TITLE
User actions table doesn't appear after first time removing a user

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1478]
- Level of Effort: Probably low
- Implementation Sketch (if higher than a "low" effort): Probabl
- Definition of Done:
  - After clicking a "Remove User" link, the User Actions table is visible and displays the log of the removal action. 

This may become invalid due to pending changes with this table in currently open PRs, but I wanted to log it just in case.

Gif - Note that the log table is not shown until after I do a browser window refresh:

![no-log-refresh](https://user-images.githubusercontent.com/697848/34779384-a0b35aa0-f5e5-11e7-885f-41e9cd79da6b.gif)

**Comment by el-mapache** [comment]
I believe this is resolved!

**Comment by wslack** [comment]
I just removed @jseppi from https://federalist-staging.18f.gov/sites/60/users (federalist-docs) and this worked. However, the timestamps were lost on the log for my first 3 actions....strange.

**Comment by jseppi** [comment]
Can you post a screenshot?

**Comment by wslack** [comment]
NVM, you alredy addressed with https://github.com/18F/federalist/issues/1479#issuecomment-356730143 :P
