### ISSUE TITLE
User Actions are only logged with date, not datetime

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1479]
- Level of Effort: Probably low

- Definition of Done:
  - User Action records' `createdAt` and `updatedAt` fields are recorded as datetimes.

**Comment by jseppi** [comment]
I think I figured it out, should be easy:

Implementation sketch:
 - add a new migration that changes the `createdAt` and `updatedAt` columns of the `user_action` table to be of type `timestamp` instead of `date`

**Comment by jseppi** [comment]
@wslack: went ahead and did this since it was a 5 minute fix.

**Comment by wslack** [comment]
perfect
