### ISSUE TITLE
Resolve bizarre prop type validation issue in Users view

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1482]
- Level of Effort: ?
- Implementation Sketch (if higher than a "low" effort): ?
- Definition of Done: the React prop type validation error message does not show up in the console any longer. This error is only visible in non-prod builds, btw.

For more context, see https://github.com/18F/federalist/pull/1476#issuecomment-356671202

**Comment by el-mapache** [comment]
One thing I think we could do is just remove `connect` entirely and subscribe to the store directly in the component, saving the actions to the component's state.

This means we lose the value of the propTypes type checking, but our tests basically already outline what we expect to get back from the API, so its not a huge deal.
