### ISSUE TITLE
Clicking "restart" on a build that is in progress produces a 403 error

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1484]
Def of done: we know the cause of the bug and have identified a resolution path

doi-extractives-data had a "stuck" build on their `dev` branch (it actually completed but the status never reported for some reason):

<img width="841" alt="screen shot 2018-01-10 at 2 49 44 pm" src="https://user-images.githubusercontent.com/697848/34794847-9a3ba300-f615-11e7-810a-92461a060fe7.png">

Clicking the "Restart" link for that build produced a `403` error that said `Unable to build. Check that you have access to this site, and that this branch has previously been built on Federalist.`

Here's what the specific build looked like:

<img width="1037" alt="screen shot 2018-01-10 at 2 53 22 pm" src="https://user-images.githubusercontent.com/697848/34794977-181451a0-f616-11e7-92ac-0ec53c9881e3.png">

**Comment by jseppi** [comment]
By the way, I did use the redux-logger stuff when looking into this, so maybe it _is_ worth keeping (ref #1481).

**Comment by wslack** [comment]
Moved to ready

**Comment by jseppi** [comment]
@el-mapache want to take this? or maybe it will even be resolved by #1492.

**Comment by el-mapache** [comment]
This appears to be resolved!

**Comment by wslack** [comment]
How did we resolve this? #1492?

**Comment by wslack** [comment]
How did we resolve this? (I can't figure out if we ever reproduced it)

**Comment by el-mapache** [comment]
@wslack I think it was just a fluke, possibly from the code I introduced that accidentally tied builds to users

**Comment by wslack** [comment]
Ah kk. @msecret this only hit you once right?

**Comment by el-mapache** [comment]
@wslack Can we move this to `done?`

**Comment by wslack** [comment]
done. Would love a 👍 from @msecret but w/o known recurrence we can close out on Friday.
