### ISSUE TITLE
Designate Federalist Backup Leads (line of succession) 

### ISSUE THREAD

**Issue by davidewarren** [18F/federalist#1486]
- Level of Effort: Low
- Definition of Done: Reference document for line of succession is complete and available to all who need it.

- [x] Josh is e-mailed
- [x] Google Doc is good with team.

**Comment by wslack** [comment]
Posted for feedback; not sure where to put these officially

**Comment by wslack** [comment]
Documented here: https://docs.google.com/document/d/1qJnW8FZcfteVwanM2tVd7juB998jFLBT91HriQCdUzc/edit
