### ISSUE TITLE
Document Downtime Procedures

### ISSUE THREAD

**Issue by davidewarren** [18F/federalist#1488]
- Level of Effort: Low
- Definition of Done: Downtime procedures (technical and communication) documented on wiki or federalist-docs 

- For customers where someone else “owns” the relationship, they should get a cc.
- Post in #federalist-news that “I sent this comms out”

**Comment by wslack** [comment]
Working on those here: https://docs.google.com/document/d/1D04u9k-HtMJWiXB9xUbLUh5TgaBc5ftRYC9kH7dQrV8/edit

**Comment by wslack** [comment]
@leahbannon want to take a first stab at pulling together a template?

**Comment by leahbannon** [comment]
Sure


--
Leah Bannon
18F <http://twitter.com/18F> Product Lead

**Comment by wslack** [comment]
@jmhooper or @el-mapache want to take a pass?

**Comment by jseppi** [comment]
Looked over the content in https://docs.google.com/document/d/17vcjJ0PB4yxCUIDoKh8TP3mYK5ArhF90SymGrITxEx0/edit#heading=h.gjq9kizacbkd. Looks good to me 👍.
