### ISSUE TITLE
Document / Publish CloudFront update workflow

### ISSUE THREAD

**Issue by davidewarren** [18F/federalist#1490]
- Level of Effort: Low

- Definition of Done:  CloudFront update workflow is documented on the federalist-docs site under "developers" section.

**Comment by wslack** [comment]
First Draft: https://docs.google.com/document/d/1EdeozkC6DFExriGIz2DXkLhrPkgLVh9GIJlInEDl4Co/edit

**Comment by wslack** [comment]
Draft is reviewed and good.

**Comment by wslack** [comment]
@amirbey and @jamiealbrecht, could y'all please pair and:

- make sure this makes sense
- Make sure its in the right location

**Comment by amirbey** [comment]
I modified the document to have sequence numbers. I think its clear.  As far as where it lives. I'd like for it to be easy to find ...  Ideally this document could live in federalist-docs, but I think the s3 screenshot should contain a bogus bucket string.  I'm afraid if in gDoc it will be easily forgotten.

**Comment by wslack** [comment]
@wslack to PR this into federalist-docs

**Comment by wslack** [comment]
PR opened!
