### ISSUE TITLE
SI-10 information input validation 

### ISSUE THREAD

**Issue by davidewarren** [18F/federalist#1498]
Assess the validation for each of the following

# Adding a site

- [ ] Github account
- [ ] Site name
- [x] Github Repo URL

# Basic Settings

- [ ] Live site - Branch name
- [x] Live site - Live URL
- [ ] Demo site - Branch Name
- [x] Demo site - Demo URL 

# Advanced Settings 

- [ ] Live site - site configuration 
- [ ] Demo site - demo configuration 
- [ ] Preview site - Preview configuration

**Comment by jseppi** [comment]
Language we can use for the control documentation in the SSP:

> Federalist Core performs validation on all user inputs to ensure they meet the requirements for type of data, data
length, and other acceptable values. When a user attempts to enter an invalid value, Federalist Core provides an error
message and prevents the data from being saved.

**Comment by jseppi** [comment]
SQL injection is protected against via Sequelize, but I did find and file some other ways we could be better about our input validation. Filed issues:
- #1499
- #1330 
- #1500
