### ISSUE TITLE
Add validation to new site form template fields

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1500]
- Level of Effort: Low
- Implementation Sketch (if higher than a "low" effort):
- Definition of Done: 
  - Only valid values can be submitted from the front end
  - Only valid values are accepted by the back end 

The site owner and site name fields in the Add New Site from Template forms will accept any text. They should have some validation that only valid GitHub usernames and GitHub repo names can be submitted.

<img width="262" alt="screen shot 2018-01-11 at 5 04 54 pm" src="https://user-images.githubusercontent.com/697848/34851892-b8738220-f6f1-11e7-904e-4ff38da2f1ed.png">

Note that even though "bad" values can be submitted, sites are not actually created because the process fails elsewhere (I think at the repo creation step), but we should not even allow it to get that far, and instead display an error somewhere in that form or on the next page (like we do for duplicate sites).

**Comment by wslack** [comment]
The chance that someone can do anything harmful with this is minimal but makes sense to add.

**Comment by jseppi** [comment]
With @el-mapache's fix in #1505, an error message is shown on the next page (the Sites List) though it is not very user-friendly since it is the "raw" error message from GitHub:

<img width="780" alt="screen shot 2018-01-14 at 8 40 18 am" src="https://user-images.githubusercontent.com/697848/34917039-be8513e2-f906-11e7-9b4b-2de588b9b562.png">

**Comment by wslack** [comment]
I'm honestly not too concerned about an ugly error message.
