### ISSUE TITLE
[Federalist application] - Adding a new site (own repo) it doesn't create and I don't get any feedback

### ISSUE THREAD

**Issue by line47** [18F/federalist#1503]
1. When I try to add `https://github.com/GSA/redir` as a new website in the federalist application it acts like it gets added. 
1. Click `Create repo based site`
1. No errors or alerts received
1. I get taken to the your websites dashboard page 
1. the site I just tried to add is not listed and there is no error message or alert. 

I would expect to get an error or alert of what happened after clicking the `Create repo based site` button

- Level of Effort: ???

- Implementation Sketch (if higher than a "low" effort):

- Definition of Done:

**Comment by jseppi** [comment]
I confirmed that this happens. When I try to add that repo, I see in my browser console that an error about not being an admin of the repo is logged, but it is not surfaced to the user as expected:

<img width="810" alt="screen shot 2018-01-12 at 11 40 52 am" src="https://user-images.githubusercontent.com/697848/34887845-85934740-f78d-11e7-8046-38c0ce827e1b.png">

I'm certain this used to be surfaced as an error alert on the next page shown after submitting the form.

**Comment by jseppi** [comment]
I think this is because the `SET_STALE` action is dispatched before the error gets displayed

<img width="784" alt="screen shot 2018-01-12 at 11 45 34 am" src="https://user-images.githubusercontent.com/697848/34888007-20caea10-f78e-11e7-8e3b-bcbd1be699e2.png">

**Comment by wslack** [comment]
Oh, this is no good. @jseppi can you take it or should we ask Adam? Should probably fix ASAP.

**Comment by jseppi** [comment]
@el-mapache can you take? I will have a fair amount of TalentMap to do early next week.

**Comment by el-mapache** [comment]
@wslack This is happening only with repos the user shouldn't be able to add? Or every repo?

**Comment by wslack** [comment]
I think those that it shouldn't but @line47 can confirm.

**Comment by line47** [comment]
@el-mapache I believe only with repos the user doesn't have access to or can't add. 
For example, I tried to add - https://github.com/GSA/redir (I'm not a part of that repo)
