### ISSUE TITLE
Unable to restart a build on a branch created by another user

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1508]
For a shared repository, like `18f/federalist-docs` that I have appropriate access to, I should be able to restart any build. However, when I tried to restart a build from a branch/commit made by another user, I received an error message and the build was not restarted. See gif:

![restart-bug](https://user-images.githubusercontent.com/697848/35003174-98373ea2-fab1-11e7-8740-ddf9f001d211.gif)

- Level of Effort:
- Implementation Sketch (if higher than a "low" effort):
- Definition of Done:

**Comment by wslack** [comment]
🤔 yeah this is important to fix.
