### ISSUE TITLE
Add back end validation for branch names

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1509]
- Level of Effort: low
- Implementation Sketch (if higher than a "low" effort):
- Definition of Done: 
  - `defaultBranch` and `demoBranch` fields of the `site` model have validations in places:
    - only allow the class of characters [alphanumeric, `_`, `-`, `.`], similar to the validations put in place in the front end as part of #1506

**Comment by jseppi** [comment]
This was kind of already specified in the Definition of Done for #1499, but this issue makes it more explicit what needs to be done for the back end.

**Comment by el-mapache** [comment]
Do we save the branch name the user supplies vs the one github reports back? If the former, maybe it makes sense to just use the value github gives us back?

**Comment by jseppi** [comment]
The branch names can be set from the Settings view, not just from the Add Site flow. We definitely save what the user specifies in the Settings view.

**Comment by el-mapache** [comment]
ah gotcha, I thought this was happening purely on the add site form.

In this case, maybe we can just call out to GitHub and verify that the branch name is real before persisting? Or is that a bad idea design wise

**Comment by jseppi** [comment]
Yeah, that's a good idea, and we have a somewhat related issue to that that's pretty old: https://github.com/18F/federalist/issues/1003 (using dropdowns of branch names from github instead of having text inputs).

I still think it would be a good idea to add the model validation because it's much easier and I can't think of any downsides to doing so.
