### ISSUE TITLE
Add new example sites

### ISSUE THREAD

**Issue by line47** [18F/federalist#1512]
#### Description of feature or bug

Add [example sites](https://federalist.18f.gov/content/examples/) for seedfund.nsf.gov and plainlaunguage.gov.

#### Definition of done

- [ ] seedfund.nsf.gov added as example site
- [ ] plainlaunguage.gov added as example site

**Comment by adborden** [comment]
Clarified definition of done.

**Comment by annahsebok** [comment]
I recommend we close this issue in favor of https://github.com/18F/federalist/issues/1885, where all example sites implementation is now outlined and informed by our card sort study and [newest information architecture](https://app.mural.co/t/gsa6/m/gsa6/1522093516875/88001f9a465e1c1a57860657f3cbf6cb4708a7a4).

**Comment by wslack** [comment]
Nice job editing this into acceptance criteria! Done.
