### ISSUE TITLE
Show more helpful error when S3 can't be read

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1523]
- Level of effort: Low
- Implementation outline (if higher than a "low" effort):
- Definition of done: Better error message is shown when Federalist is running in development mode and S3 cannot be reached

When the `federalist-staging` s3 keys are rotated (usually due to a staging deploy), local development instances need to have their s3 keys updated, which can now be done using the new `npm run update-local-config`.

However, the error message that is shown when s3 keys are outdated is very vague (see screenshot). We could give more helpful instructions to devs running federalist locally by updating the error message to say something like "S3 keys are out of date. Please update them by running `npm run update-local-config`." in place of the generic error message when the app is running in `development` mode.

<img width="622" alt="screen shot 2018-01-19 at 9 58 26 am" src="https://user-images.githubusercontent.com/697848/35159395-b85a6db2-fcff-11e7-9cf9-cd5a41001a52.png">

**Comment by wslack** [comment]
Put in backlog for now until we hear from users.

**Comment by wslack** [comment]
@el-mapache this is something you could retrieve

**Comment by el-mapache** [comment]
I don't think we will hear from users, I believe this issue will only surface for developers, locally. I actually looked into this yesterday, the next time we make a staging deploy I can go in an verify the error and add some error handling.

**Comment by wslack** [comment]
Is it worth the effort for the benefit? I would guess not unless it takes less than an hour to patch and PR.

**Comment by jseppi** [comment]
This is something I envisioned helping new developers and designers working locally on federalist.

**Comment by el-mapache** [comment]
Yes, I think it will probably take and hour or less to fix. I'm just not sure what the exact error is that we need to catch.

**Comment by wslack** [comment]
👍 moved to _ready_
