### ISSUE TITLE
Hide "Trigger Build" link for branches that are "un-linkable"

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1524]
- Level of effort: Low
- Implementation outline (if higher than a "low" effort):
- Definition of done: No Trigger Build links for un-linkable branches

For example:
<img width="632" alt="screen shot 2018-01-19 at 11 23 23 am" src="https://user-images.githubusercontent.com/697848/35163114-442e7468-fd0b-11e7-9071-0a30afc1d1c5.png">

**Comment by wslack** [comment]
Seems low effort; moved to "ready" for someone to pick up at will.
