### ISSUE TITLE
On GitHub Branches page, hide View Preview link if no build exists

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1525]
- Level of effort: Low?
- Implementation outline (if higher than a "low" effort):
- Definition of done: Branches that have not yet been built do not have a "View Preview" link in their actions column.

I think this could be done by looking at the builds table and checking to see if a build exists for the given site and branch name.

**Comment by wslack** [comment]
Seems pretty easy for someone to hit the "trigger" button right? The only times this will apply are when people add an existing repo to Federalist (vs starting from a template). I'm dropping in icebox for now but open to raise priority for a user story.

**Comment by wslack** [comment]
Really small benefit.
