### ISSUE TITLE
Create new repo/site from arbitrary existing repo

### ISSUE THREAD

**Issue by el-mapache** [18F/federalist#1530]
### Description

To facilitate eventually being able to 'move' a repository, we need a mechanism for users to create an entirely new repo from an existing repo — similar to the creation of a repo from a template, but from any repo that user is an admin of.

Simply put, a user, who is an admin of a repo, can enter the:
- name of that repo
- name of the new owner
- source branch
and Federalist will create a new repo in the specified user's account.

### Definition of done

- [x] we validate that the user attempting to copy the repo is an admin of the repo
- [x] a new repo is created in the specified user's account
- [x] messaging that explains:
  * this is an alpha feature
  * only the site information will be copied, advanced settings/configs, builds, and associated users will not 
  * if the site has a custom domain, customer will need to contact us directly to get new CDN routes created
  * User is responsible for deleting old app once this is done? Not sure if we need to mention this, since it will still technically work, just not at the custom domain
- [x] tests cover new functionality
- [x] refactors SiteCreator class/function bag

-------

### Level of effort

Medium

### Implementation outline

* Add a new view that uses a similar form to the `add site from template` feature
* Leverage existing or create a new authorizer to ensure user has admin access to a repo
* Should be able to use existing create site route/controller and site creation service.

**Comment by el-mapache** [comment]
@jseppi I'm planning on adding this under the `site` section, with it's own space on the nav. Do you think this approach is reasonable? It seems best to me for a couple of reasons:

* we need the site's information
* it will let us do things like provide a dropdown of branches for the site
* gives it some more room to grow — we don't shoehorn this feature into the add sites page

let me what what you think!

**Comment by jseppi** [comment]
What about putting it down in the Advanced Settings section of the Site Settings page for now?

**Comment by el-mapache** [comment]
I thought about that, but I feel like there isn't much visibility there. I suppose maybe it's reasonable to think that someone who wanted this functionality would check the advanced section, but I also like the idea of it being a first-class feature.

**Comment by jseppi** [comment]
I think it'll be used fairly infrequently. Nested side nav might be a nice thing to have (though that's not really in the scope of this issue).

I don't have too strong an opinion though. Maybe @ericronne would have a good idea.

**Comment by el-mapache** [comment]
Just to be clear, nesting is a new idea you are putting forward? I was
suggesting putting it right in the side nav on the sites page. I'll just
move it to advanced since it seems like this isn't going to be used too much

**Comment by jseppi** [comment]
Yeah, nested side nav sections was a new idea. Apologies for clouding the discussion.

**Comment by ericronne** [comment]
Thanks for the tag @jseppi :)

Please tag me on anything design, and i will gleefully pitch in!

I'm not sure i fully get what's being suggested yet, but if you share a preview link once it's stubbed out, i'll check it out. (I hope to have time to look at the overall logged-in design before i have to ghost, btw.)

**Comment by el-mapache** [comment]
@jseppi Not a problem! just double checking 😄
