### ISSUE TITLE
Need a better error message when org hasn't approved Federalist

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1532]
### Description of feature or bug
When sites can't be added to Federalist because the org hasn't approved Federalist access, the error message is "you must be an admin user of the repository to add it to Federalist."

### Definition of done
The error message is correct for the problem.

-------
_After evaluating, edit this part:_

### Level of effort

medium

### Implementation sketch

We need to follow the following logic to determine if:
* The user initiating the request has admin access to the repo
* The 'org' the repo belong to is an actual org. We do this by checking if there is a user in the database with the same name as the org
  * if it isn't an org, everything is fine and we can build the site
  * if it is an org, get all the organizations the user belongs to that have authorized federalist,
    and check that the requested org name is among them

**Comment by wslack** [comment]
@el-mapache care to look at the level of effort for this error? Also happy to ask @jseppi.

**Comment by el-mapache** [comment]
@wslack looking now

**Comment by el-mapache** [comment]
I'm going to tentatively say 'low' because i don't think this is super complicated, but it doesn't appear that we have any checks for an org's federalist status when we try and add a site.

**Comment by el-mapache** [comment]
@wslack I'm not 100% sure its possible to get this information. The GitHub API intentionally returns a 404 error when permissions to perform an action don't exist. I think in this case GItHub doesn't distinguish between whether the user has access to the org or the org has authorized our app.

**Comment by el-mapache** [comment]
Changed this to medium as there is some new logic to add and that means new tests!

**Comment by wslack** [comment]
@el-mapache we could also just change the 404 error message to "you need to be an admin on the repo and the org must be approved to use Federalist." Between those two, do you have a preference? I'm ok with a more relaxed error message.

**Comment by wslack** [comment]
Ignore me, this is done and I didn't realize.
