### ISSUE TITLE
Completed build not being communicated to GitHub PR screen

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1535]
### Description of feature or bug

builds are continuing to hang when certain folks open pull requests - @hursey013 has to take over the PR in order to get it to build.

-------
_After evaluating, edit this part:_

### Level of effort

medium

### Implementation outline (if higher than a "low" effort):

* Query GitHub API to ensure that the next token has the correct permissions to update the PR status
* If no valid token are found, report an error to the user. This is pretty unlikely, and might be the repo has been abandoned, but we should account for it.

**Comment by jseppi** [comment]
When a build is initiated by a non-federalist user, federalist attempts to use another site-associated user's token to make the PR status update. In this case, the user that was found had previously been removed from this repo's `write` users (via the GitHub interface), but they were still associated with the site in federalist. Thus, using their token to make the PR status update request failed.

**Comment by jseppi** [comment]
Possible technical remediations:

- When finding the next available access token, make sure that the token has sufficient permissions to make a PR status update request. If not, find the next one, and so on.
- Bigger effort, but much better overall: turn Federalist into a GitHub App instead of an OAuth App. ref: #1067

**Comment by wslack** [comment]
@jseppi what's your recommendation between those two? (just to put it in writing)

**Comment by jseppi** [comment]
The first option is at best a band-aid, but it is not very high effort.

I'd recommend we scope the GitHub App solution. It will be a very large change to the app to make that conversion, so we'll need to think carefully about the cost-benefit. I definitely think in the long-term that it's the way to go though.

**Comment by wslack** [comment]
Sounds like we should open an issue to evaluate the work effort of that. Do you want to run that or ask someone else to?

**Comment by jseppi** [comment]
We have an issue for the "consideration" already, so I think we can just update that: https://github.com/18F/federalist/issues/1067

I'm happy to do the research!

**Comment by wslack** [comment]
We closed #1067; @jseppi should we return to the first option? 

> When finding the next available access token, make sure that the token has sufficient permissions to make a PR status update request. If not, find the next one, and so on.

**Comment by wslack** [comment]
Tagging folks to ascertain priority.

**Comment by el-mapache** [comment]
In my opinion we should take the first option, it's the most straightforward way to achieve what we want.

**Comment by wslack** [comment]
👍 let's do it. Upgraded to Ready (but this is less important than the homepage)

**Comment by wslack** [comment]
This was a dup of #1425 it turns out.
