### ISSUE TITLE
Documentation site breakpoint is too wide

### ISSUE THREAD

**Issue by ericronne** [18F/federalist#1539]
### Description of feature or bug

On the documentation site, the side nav bumps down to the odd, footer-ish position at a window width of 1,200px or so. There's still plenty of room for it then.

![image](https://user-images.githubusercontent.com/9259185/35345716-ef33ed3c-00f5-11e8-97e5-6d9e7ab1b222.png)

Adjust breakpoint soon; consider redesign next.

### Definition of done

Site accommodates narrower window widths before shifting the nav. See [this page](https://standards.usa.gov/page-templates/#documentation-page), eg, which does a good job.

-------
_After evaluating, edit this part:_

### Level of effort

TODO: e.g., low/medium/high

### Implementation outline (if higher than a "low" effort):

TODO

**Comment by wslack** [comment]
@line47 IIRC this is because of the way that the docs site uses the standards. Is that right?

**Comment by line47** [comment]
The docs site uses this layout https://standards.usa.gov/page-templates/docs/ 
which has the same breakpoint issue 😢

**Comment by wslack** [comment]
Alas! I feel like we filed a ticket to the USWDS about this forever ago, but not sure.

**Comment by line47** [comment]
Would dropping the left nav at 950px be the preference here? 
Take a look at https://plainlanguage.gov/guidelines/ and https://designsystem.digital.gov/components/ for example.

I like how the plainlanguage.gov site pulls the items from the left nav into the offcanvas menu instead of pushing them to the bottom. 

Thoughts?

**Comment by wslack** [comment]
I'm fine if it all goes into the menu at top right. (right now that menu seems to draw nav from somewhere else than the left hand menu)

If the menu has to appear on the page, I would do bottom over top.

**Comment by ericronne** [comment]
top-right hidden in menu sounds great!

**Comment by line47** [comment]
This is much more complex as I'm finding that the uswds site is using 2 navigations and just showing/hiding based on screen width. 🤔 the HTML purist in me doesn't like the fact that there are 2 separate HTML blocks for navigation.

<img width="991" alt="screen shot 2018-02-23 at 12 04 56 pm" src="https://user-images.githubusercontent.com/1449852/36622786-735993d4-18cd-11e8-8970-2e055246d303.png">

**Comment by wslack** [comment]
oh wow. Well, my default would be to follow their suggestion unless there's good reason not to. (or ask them why its this way)

**Comment by line47** [comment]
We can definitely tailor the navigation for logged in vs not @ericronne

**Comment by ericronne** [comment]
Documentation is available regardless of login status ... 🍐 on this issue?
Feels like a sticky wicket / IA can of worms

**Comment by line47** [comment]
Sure that sounds good, 👍

**Comment by el-mapache** [comment]
@wslack The breakpoint issue has been resolved! We might want to open another issue to put the menu somewhere else, having it at the bottom of the screen is sort of weird and doesn't lend itself to easy navigation.

**Comment by wslack** [comment]
👍 agreed with moving this to Done? and opening another issue.

This gets lost in the question of how/if to update the docs site and the interesting way it applies the USWDS right now....

**Comment by davidewarren** [comment]
I'm closing this, issue #1752 includes the other asks for the Federalist Docs site
