### ISSUE TITLE
Icon style is inconsistent, and some don't really represent what are meant to symbolize

### ISSUE THREAD

**Issue by ericronne** [18F/federalist#1540]
### Inconsistent line thickness:
![image](https://user-images.githubusercontent.com/9259185/35355002-908b1618-0111-11e8-9d10-3a30e5f87ae7.png)
![image](https://user-images.githubusercontent.com/9259185/35355015-9ba9a5f0-0111-11e8-8ff5-fedb61fb6ba2.png)

----

### Flat filled vs. outlined styles:
![image](https://user-images.githubusercontent.com/9259185/35355074-c51821d2-0111-11e8-8b48-5dd16ccae5b3.png)
![image](https://user-images.githubusercontent.com/9259185/35355079-cce1d3d6-0111-11e8-9a70-5aa48b5b8188.png)
![image](https://user-images.githubusercontent.com/9259185/35355227-46d316b4-0112-11e8-8074-b123bfb834d9.png)

----

### Could better represent the topic:
![image](https://user-images.githubusercontent.com/9259185/35355126-f543d2fc-0111-11e8-943b-cefa12ba5907.png)

---

## Definition of done

When we have a stylistically consistent new set for each of the 10 existing icons. Style should coordinate with the federalist bug:
![image](https://user-images.githubusercontent.com/9259185/35355369-b4842284-0112-11e8-8dba-b6ed26b9e1f7.png)

-------

### Level of effort

Upping to 1 – 2 days, since some customizing is in order.

**Comment by jseppi** [comment]
yaaaasssss

**Comment by jseppi** [comment]
The existing sprite sheet is also inconsistent in its offsets, which makes picking icons from it kinda yucky.

**Comment by ericronne** [comment]
Is it common (/recommended) to use a sprite sheet, as opposed to discrete svg files?

**Comment by jseppi** [comment]
Good question. I think it probably doesn't make much of a difference, especially given the number of sprites we have (not that many). I think individual svgs would be fine.

**Comment by wslack** [comment]
I would love to use individual SVGs if only to make it much easier for people to swap out files.

@ericronne can you do this work or would someone else (@leahbannon or others) need to take your work and generate a list of needed code changes?

**Comment by ericronne** [comment]
Another would doubtless be more fast and efficient than myself. 
If nobody is free, i'm game to give it a try 🤞

**Comment by jseppi** [comment]
awesome, @ericronne! those look great!

**Comment by ericronne** [comment]
Closed with #1549
