### ISSUE TITLE
Should we make a "templates" UA code that's separate from the other Federalist GA codes

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1541]
### Definition of done

We have a separate GA code for all of the templates and any sites built from them.

-------
_After evaluating, edit this part:_

**Comment by wslack** [comment]
cc @line47 for his expert opinion instead of trying to discuss in https://github.com/18F/federalist-modern-team-template/pull/33

**Comment by line47** [comment]
You could do something like this to track all sites built on Federalist. But you can't guarantee that the site will keep the template GA code. I'm not sure how we would ensure that the GA code stays with the template.

**Comment by wslack** [comment]
Oh I don't need to do that; the intent is for this to be a low-effort way to get data in case its useful in the future, but in a way that doesn't corrupt our other usage data.

**Comment by wslack** [comment]
It's ok if people switch their code because then they will have the data!

**Comment by wslack** [comment]
<img width="122" alt="screen shot 2018-03-08 at 12 20 35 pm" src="https://user-images.githubusercontent.com/10016577/37165634-1e8165c8-22cb-11e8-915e-b75ec69a4068.png">
I think we now have an alternate analytics code. All templates should have this code, I think?

**Comment by wslack** [comment]
Scott to confirm (not assigning to do the task, just to check my thinking)

**Comment by line47** [comment]
I'm not sure I follow what your are asking. 

Are you saying use the `config.yml` to set a GA code ?
like seen here? https://github.com/18F/federalist-uswds-template/blob/master/_config.yml#L13

**Comment by wslack** [comment]
Oh I'm saying that the UA code for all of our templates (that might follow forked repos) should be different than the UA code on the core federalist sites.

**Comment by line47** [comment]
Gotcha! Thanks for clarifying. We can certainly have a default UA code setup within the templates. 

If it is overridden that is OK yeah?

**Comment by wslack** [comment]
Absolutely, and it should be!

**Comment by line47** [comment]
Added GA code `UA-48605964-32` to all the config files for the template branches.
You can check them out there 
- https://github.com/18F/federalist-uswds-template/blob/master/_config.yml
- https://github.com/18F/federalist-uswds-template/blob/report-config/_config.yml
- https://github.com/18F/federalist-uswds-template/blob/modern-team-config/_config.yml
- https://github.com/18F/federalist-uswds-template/blob/landing-config/_config.yml

**Comment by wslack** [comment]
👍
