### ISSUE TITLE
Jekyll Environment - Production by default

### ISSUE THREAD

**Issue by s2t2** [18F/federalist#1545]
### Description of feature or bug

Jekyll sites [use](https://jekyllrb.com/docs/configuration/) a `JEKYLL_ENV` environment variable to allow developers to distinguish between environments. The default value is "development". 

~~I'm trying to use a gem (e.g. `activesupport`) to perform some functionality in the development environment only, but even when placed in the `:development` Gemfile group or a custom Gemfile group like `:my_group`, it breaks the Federalist build. For more information about Gemfile groups, see http://bundler.io/v1.12/groups.html.~~

Similar to platforms like Heroku, which use default production environment variables (e.g. `RAILS_ENV=production`), it would be nice if Federalist did the same.

Even if Federalist currently allows an admin to set environment variables, a default `JEKYLL_ENV=production` would lead to a better developer experience.

~~And if gem installation could exclude development environment gems, that would allow developers to use gems in development that wouldn't break the Federalist build.~~

### Definition of done

~~If the following Gemfile won't break the Federalist build:~~

~~source 'https://rubygems.org'~~

~~gem 'jekyll'~~
~~gem 'jekyll-sitemap'

~~group :development~~
  ~~gem 'activesupport'~~
~~end~~

EDIT: if the default `JEKYLL_ENV` is set to `"production"` without a site admin needing to do it manually.

### ~~Possible Fix~~

~~The following commands be a step in the right direction for producing a fix:~~

~~bundle install --without development test # I *think* this would work
JEKYLL_ENV=production bundle exec jekyll serve # runs server in production~~

-------
_After evaluating, edit this part:_

### Level of effort

low

### Implementation outline (if higher than a "low" effort):

add JEKYLL_ENV='production' to the environment used in the `build_jekyll` task

**Comment by wslack** [comment]
Can you clarify why this variable can't be set by the "custom code" options in the federalist config or by pulling the BRANCH NAME variable?

**Comment by jseppi** [comment]
What about for builds of branch previews? Would we still want `JEKYLL_ENV=production`, or should it just be limited to the primary "live" site build? Same question for the "demo" site build.

**Comment by wslack** [comment]
From what I'm seeing, this would only apply to the "live" site, but I am not sure.

**Comment by jseppi** [comment]
Also, @s2t2: could you clarify what breaks the build in Federalist? Is it something in that specific gem, or Gemfile groups in general?

**Comment by s2t2** [comment]
@jseppi the logs don't reveal what is breaking the build (see below). I'm performing some trial and error tests now in an attempt to find out.

```
Source: clone-repo
Timestamp: 2018-01-24T22:31:04.951Z
Output:
[COMMON] 2018-01-24 22:30:56 INFO: Cleaning /tmp/site_repo
[CLONE] 2018-01-24 22:30:56 INFO: Cloning s2t2/pif-website/mjr-counts to /tmp/site_repo
[COMMON] 2018-01-24 22:31:04 INFO: Cleaning /tmp/site_repo/_site


Source: run-federalist-script
Timestamp: 2018-01-24T22:31:06.619Z
Output:
[BUILD] 2018-01-24 22:31:05 INFO: Node version: v8.9.4

[BUILD] 2018-01-24 22:31:06 INFO: NPM version: 5.6.0
```

Also, FYI this issue isn't a blocker for what I'm trying to do anymore because I found a way to remove the `activesupport` dependency from my code.

**Comment by s2t2** [comment]
OK, so I'm having a lot of federalist issues right now that seem not to be related to any of this. Will report back when I know more.

**Comment by wslack** [comment]
Ok! If the app isn't working, we can help with those issues in the support channel.

**Comment by s2t2** [comment]
@wslack @jseppi So it seems the broken builds were due to that cloud.gov issue you helped resolve earlier today. Thanks again! 

Since then, I tested out a [new branch](https://github.com/presidential-innovation-fellows/pif-website/compare/master...s2t2:mjr-federalist-gem-test) to see if gem requirement could by itself break a build, and it does not ([works fine](https://federalist-proxy.app.cloud.gov/preview/s2t2/pif-website/mjr-federalist-gem-test/)). 🎉 

However, to address previous questions/comments, as a low priority enhancement, I would still advocate changing the default `JEKYLL_ENV` to `"production"` (on the live site as well as branch previews/demos, although if you wanted to use `"staging"` - or something other than `"development"` - for the previews/demos that would be reasonable as well). This change would improve the developer experience by conforming to industry best practices developers are used to when they use platforms like Heroku, and could also provide a practical example of how to set and configure environment variables.

**Comment by jseppi** [comment]
Great - thanks for the update, @s2t2!

I am on board with setting `JEKYLL_ENV` in our build container as you described.

We don't actually allow setting of environment variables themselves by customer sites -- rather, it would involve a (small) change to our builder code to set `JEKYLL_ENV`.

**Comment by wslack** [comment]
I'm not versed in this topic enough to know for sure, but it confuses me that the default value is the wrong one. I am not opposed to a consistent experience but I'm not sure why it matters if its set or not.

**Comment by jseppi** [comment]
That kind of default ('development' unless otherwise specified) is fairly common across other systems. For instance, `npm` always installs both production and development dependencies unless specifically instructed to run in production mode.

**Comment by jseppi** [comment]
As for why it matters: it will help those who care about/use it, including reducing their build times since development dependencies won't need be installed by the container.

Also, we _do_ run `npm` in production mode, so this will bring the `jekyll` build more in line with that practice as well.

**Comment by el-mapache** [comment]
One way it matters if you have one group of dependencies that you want running locally (maybe for logging or testing purposes) that you don't need running on the live site, either because it will slow down the app, or bloat it, or allow users to see diagnostic information about your app.

I've generally had to specify manually when I want an app to be run in production mode, but I think its probably safe to assume that any site deployed to Federalist is intended for production.

**Comment by wslack** [comment]
I'm sold. @el-mapache do you want to edit the issue to reflect how we'll do this?

**Comment by el-mapache** [comment]
I think @jseppi already noted this a few comments earlier, we just need to set `JEKYLL_ENV` to production before we run the build command here: https://github.com/18F/federalist-garden-build/blob/4fd4384d71dafef3cdb02801b6588660b091ff1f/tasks/build.py#L201

**Comment by wslack** [comment]
Sounds good; I'd say we're good to open the PR then.
