### ISSUE TITLE
Unauthorized banner has excess whitespace around it

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1546]
### Description of feature or bug

<img width="1229" alt="screen shot 2018-01-24 at 4 43 16 pm" src="https://user-images.githubusercontent.com/697848/35361120-c49d6168-0125-11e8-9ec2-ca8987a0a5f0.png">

Related to changes from #1496, currently only in `staging`.

### Definition of done

TODO

-------
_After evaluating, edit this part:_

### Level of effort

low

### Implementation outline (if higher than a "low" effort):

TODO

**Comment by line47** [comment]
Hey @jseppi I have a few questions maybe you can help answer how this error should look

- Would you expect the error to be the width of the site content or 100% width?
- Would you expect there to be no top or bottom space around the error?

CC @ericronne

**Comment by jseppi** [comment]
I'd mostly expect it have no whitespace around the top and bottom of the banner, but totally up for other opinions on that and the rest of the styling.

**Comment by line47** [comment]
What about something like this? 

![screen shot 2018-01-25 at 9 47 19 am](https://user-images.githubusercontent.com/1449852/35393894-4f14b4ca-01b4-11e8-90d8-e783a47421e9.png)

**Comment by jseppi** [comment]
Looks good to me

**Comment by ericronne** [comment]
Where would a user be taking an action that would bring them back to the home page?

**Comment by jseppi** [comment]
You'd see that, for instance, if you were currently logged out of Federalist but directly visited some internal page.

You can see on production by:
1. visiting https://federalist.18f.gov and clicking "Log out" if you are already logged in
1. visiting https://federalist.18f.gov/sites/3/builds. You should see the unauthorized error.

**Comment by jseppi** [comment]
There's a similar error message shown when you _are_ logged in, but attempt to view a site you don't have permissions for:

<img width="1077" alt="screen shot 2018-01-25 at 9 05 36 am" src="https://user-images.githubusercontent.com/697848/35395095-ff1798d4-01ae-11e8-90b8-6a26150508b0.png">

**Comment by ericronne** [comment]
Cool. Yeah content width seems good. Style-wise, the uswds version with the bar might be the way to go, unless we have reason to depart from that. Although i _prefer_ the version below …

![image](https://user-images.githubusercontent.com/9259185/35395301-9b7b68ae-01af-11e8-94d0-90be86b44612.png)
 
we should be consistent, so @line47's [layout](https://github.com/18F/federalist/issues/1546#issuecomment-360486697) feels more appropriate to me.

I would add a little vertical margin, align with the content, and if possible, offer a log in link …
![image](https://user-images.githubusercontent.com/9259185/35395709-c44e8bf2-01b0-11e8-9ae0-45c03f8504a0.png)
