### ISSUE TITLE
When creating a new site from a template, the template branch is used instead of master

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1547]
### Description of feature or bug

If a template is based off of a specific branch (like `redirect-config`), then when a new site is created from it via the Add Site from Template flow, the new site's primary branch is set to that specific branch, and a build is attempted for that branch. However, the build container always pushes a template-based new site to the destination repo's `master` branch.

Confirmation of bug (run locally off of PR #1544):
 
The newly created repository does in fact only have a `master` branch:

<img width="474" alt="screen shot 2018-01-25 at 9 24 20 am" src="https://user-images.githubusercontent.com/697848/35396115-b14e01a8-01b1-11e8-91df-388f0966c13c.png">

But the builds table in the web app and the site settings show the `redirect-config` branch:

<img width="572" alt="screen shot 2018-01-25 at 9 25 49 am" src="https://user-images.githubusercontent.com/697848/35396189-d451a6dc-01b1-11e8-9781-21d61df10c4d.png">

<img width="541" alt="screen shot 2018-01-25 at 9 26 43 am" src="https://user-images.githubusercontent.com/697848/35396213-e1d1b298-01b1-11e8-8265-f9cbb7e1754b.png">

### Definition of done

The first build and the site's primary branch are set to the `master` branch of the newly created repo.

-------
_After evaluating, edit this part:_

### Level of effort

TODO: e.g., low/medium/high

### Implementation outline (if higher than a "low" effort):

TODO

**Comment by el-mapache** [comment]
@jseppi Just so I understand this, we always want the base branch (in Federalist) of a site created from a template to be `master`, correct?

**Comment by jseppi** [comment]
Yup!
