### ISSUE TITLE
Replace sprite sheet and implement new icons

### ISSUE THREAD

**Issue by ericronne** [18F/federalist#1549]
### Description of feature or bug

Icons created or modified in #1540 need to be implemented as discrete svg files, replacing the [sprite sheet](https://github.com/18F/federalist/blob/staging/public/images/sprites.svg) currently in use.

-------
_After evaluating, edit this part:_

### Level of effort

TODO: e.g., low/medium/high

### Implementation outline (if higher than a "low" effort):

TODO

**Comment by ericronne** [comment]
Sound tempting, @line47 or @jseppi? ;)

**Comment by ericronne** [comment]
(duping this reference from #1540 …)
## Icon set …

![image](https://user-images.githubusercontent.com/9259185/35401869-5ee4c0dc-01c0-11e8-902a-60b690ec554a.png)


![image](https://user-images.githubusercontent.com/9259185/35401575-895c1244-01bf-11e8-86b1-8ae7118f5f68.png)

![image](https://user-images.githubusercontent.com/9259185/35401813-2b9d67a6-01c0-11e8-8b59-6b3f5c4c4b82.png)



_**Note: if we get a chance to address this logged-in UI, these may be impacted in one way or another**_

**Comment by ericronne** [comment]
Stubbed in the nav icons (#1548).

### Still to do:
- [ ] Add padding to push side nav text away from the icons
- [ ] Confirm sizing on all; adjust if necessary
- [ ] Drop in `icon-github` and `icon-link-external`
- [ ] Strip out old code related to the sprite sheet

**Comment by wslack** [comment]
YAY!

**Comment by ericronne** [comment]
this should unblock #1558
