### ISSUE TITLE
When a build container is restaged, it will re-run its last build based on the current environment variable values it has

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1551]
### Description of feature or bug

When a build container is restaged (for example, from scaling its memory or disk space), it will re-run its last build based on the environment variable values that were set at the time of the restage. This can cause, in some rare circumstances, problems with an existing site. For instance:

- a site had a "bad" build with an incorrect `BASEURL` value,
- which was subsequently fixed in a different build,
- and those builds happened on different build container instances, 
- and the bad-build build container gets restaged,

-> the "bad" build can get re-deployed over the good build. 

### Definition of done

TODO

-------
_After evaluating, edit this part:_

### Level of effort

TODO: e.g., low/medium/high

### Implementation outline (if higher than a "low" effort):

TODO

**Comment by jseppi** [comment]
This is a bit thorny because in many instances, we _do_ want the container to re-run its build. For example, if a container gets restaged in the middle of a build, we'd want the build to re-run automatically.

**Comment by wslack** [comment]
cc @greensteph for any input.

It seems like one fix would be to include the redone build in the logs if possible; that would help us understand what happened.

**Comment by wslack** [comment]
I'm ok with the problem happening as long as we can understand why.

**Comment by jseppi** [comment]
Agree; having the build logged would be great. It was unfortunately kind of happenstance that I even noticed what the root issue turned out to be, and that the old "bad" build environment hadn't been overwritten by another site's build.

**Comment by wslack** [comment]
right. Should we edit the issue to make it about better logging?

**Comment by wslack** [comment]
Resurrecting this discussion; @jseppi should we just add something to the logging noting there was a restart?

**Comment by jseppi** [comment]
The containers don’t have a way of knowing there was a restart.

**Comment by amirbey** [comment]
this issue is now n/a
