### ISSUE TITLE
Re-add icon descriptions for accessibility

### ISSUE THREAD

**Issue by ericronne** [18F/federalist#1558]
#### Description of feature or bug

New svg icons need descriptions added, for accessibility. Refer to previous (sprite-related) code.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] add alt text to images on the homepage 
- [ ] add alt text to featured site images on the example page

**Comment by line47** [comment]
Which icons are you referring to @ericronne ?

**Comment by ericronne** [comment]
All of the new ones. Previously they had meta info such as "Gear icon" in the code

**Comment by line47** [comment]
I think the images that are on the page and not pulled in via CSS need to have some `alt` text.
The background images can't have alt text and are also just decorative (in the left hand menu)

**Comment by ericronne** [comment]
Makes sense. Do we know if other 18F sites use alt text for icons? Seems like a nice-to-have, rather than a true accessibility issue.

**Comment by line47** [comment]
There are a few instances I've added to the issue TODO, should be easy to knock out

**Comment by jseppi** [comment]
The icons are now inlined-SVG. Do those still need an `alt` or `title` attribute?

Why is this labeled as "blocked?"

**Comment by wslack** [comment]
blocking is resolved.

**Comment by ericronne** [comment]
I started a [thread](https://gsa-tts.slack.com/archives/C02BT4H5Q/p1519141334000317) to discuss this in the slack accessibility channel, and folks recommend that we *not* add descriptions to these icons: "Those icons exist as visual shorthands, for which there are no necessary spoken equivalents—indeed, it would be better to suppress them."

That sounds wise to me. So i recommend closing. Thumb this up if you agree.

**Comment by jseppi** [comment]
thanks!

**Comment by ericronne** [comment]
_moved to "Done?" col on the board_
