### ISSUE TITLE
Implement new github svg in dashboard

### ISSUE THREAD

**Issue by ericronne** [18F/federalist#1559]
#### Description of feature or bug

Currently populates in a unique way, via `GitHubMark`. Implement new `icon-github.svg` file via css, for consistency with the rest of the dashboard. Visual reference:

![image](https://user-images.githubusercontent.com/9259185/35528742-73716cf8-04f4-11e8-8ae4-17a93bd721d8.png)

#### Definition of done

Icon implemented and size / positioning / color 👌 'd by @ericronne 

_After evaluating, edit this part:_

#### Level of effort
Low(?)

_Don't spend much time; will likely change when we have time to iterate the dashboard design_

**Comment by line47** [comment]
I think it would be nice to pull in the GitHub icon with CSS as a background image like we are doing for the other icons in the left nav and for external links. I think this would get into a bit of refactoring. I'm suer @jseppi or @el-mapache have thoughts here too.

**Comment by wslack** [comment]
What's the level of effort for the refactoring? I'm happy to tag this as `debt` but it doesn't seem urgent given the possible effort.

**Comment by jseppi** [comment]
Low effort, and I agree it isn’t particularly urgent.

**Comment by jseppi** [comment]
After seeing it in action on staging this sprint, I'm not fully onboard with using css `background` `url(...)` swapping for icons due to the flicker that happens. See #1592 for more discussion on this.

**Comment by line47** [comment]
I think we should go the CSS fill route for sure 👍

**Comment by jseppi** [comment]
As I kinda mentioned in #1592, we can still store the svg source file separately (in `icon-github.svg`), but use `import` in the React component to bring in the SVG content during the webpack build. That also means we'll get some slight bandwidth savings, and we can run easily all the SVGs through an optimizer during build.
