### ISSUE TITLE
Implement new "+" svg on "Add website" button, in dashboard

### ISSUE THREAD

**Issue by ericronne** [18F/federalist#1560]
#### Description of feature or bug

Replace thin plus symbol with `icon-plus.svg` and size / position like so:
![image](https://user-images.githubusercontent.com/9259185/35529469-c549224e-04f6-11e8-8cbf-b363821d013f.png)

#### Definition of done

👌 'd by @ericronne

#### Level of effort
Low(?)

_Don't spend much time; will likely change when we have time to iterate the dashboard design_

**Comment by wslack** [comment]
@ericronne moved to "Ready" - do you need someone else to do it or will you?

**Comment by ericronne** [comment]
Thanks. These are a little esoteric, so an official front-ender such as @line47 would be better equipped to tackle!
