### ISSUE TITLE
Test the public website with some users

### ISSUE THREAD

**Issue by ericronne** [18F/federalist#1561]
#### Description of feature or bug
To make any visual-redesign work more meaningful / impactful / smart, let's quickly test the current website with a small group of users.

#### Definition of done
This stuff:
- [x] identify a small test group for the public pages of the site
- [x] write a test plan
- [x] write a testing script
- [x] create email correspondence (recruiting note/thank you)
- [x] execute
- [x] draft results, to unblock completion of redesign for those pages

#### Level of effort
Medium-high

#### Implementation outline
_see above checklist_

cc @OpenGlobe @tram

**Comment by ericronne** [comment]
@vz3

**Comment by wslack** [comment]
cc @ShannonBad

**Comment by wslack** [comment]
I plan to source them from recs from current customers and from our sales leads that haven't bought.

Hoping for @ShannonBad to write the first draft of the recruiting note about what we're looking for

**Comment by ShannonBad** [comment]
Here is my proposed Federalist research plan. I am currently working on that recruiting note now.
[Federalist - UX research plan.pdf](https://github.com/18F/federalist/files/1743167/Federalist.-.UX.research.plan.pdf)
plan:

**Comment by ShannonBad** [comment]
Here is a proposed recruiting note (to be customized for each email).
[Federalist Recruitment Email.pdf](https://github.com/18F/federalist/files/1745129/Federalist.Recruitment.Email.pdf)

**Comment by ericronne** [comment]
[Invision prototype](https://gsa.invisionapp.com/share/FRG3K1CE5DV#/282149533_Landing-Desktop) of new design, for testing

**Comment by ericronne** [comment]
PDF of new landing-page design …
[federalist-landing-page.pdf](https://github.com/18F/federalist/files/1768709/federalist-landing-page.pdf)
