### ISSUE TITLE
Rewire the landing page

### ISSUE THREAD

**Issue by ericronne** [18F/federalist#1562]
#### Description of feature or bug
Tweak the structure of the landing page, based on the [content review](https://docs.google.com/document/d/10dl_3c6uTolRYtmMBhMJ7tnKVoXwvnAhTx93uLq2uSY/edit#heading=h.simzjkrcu7ui), [user journeys](https://app.mural.ly/t/gsa6/m/gsa6/1513697671001/a73fe75b9ab617eeb612dc585d47787e16e40cac), and test results (#1561).

#### Definition of done
New wires for the public [Landing page](https://federalist.fr.cloud.gov/)

#### Level of effort
Medium

cc @vz3

**Comment by jseppi** [comment]
Why is this labeled as "blocked?"

**Comment by vz3** [comment]
I'm guessing I'm tagged because I was working on a testing script during a couple cycles my team had free around the shutdown. I'll try to have something together for this for Monday.

**Comment by wslack** [comment]
@vz3 monday is a holiday but it would be good to get that script in the other issue #1561, or pass it back to us

**Comment by ericronne** [comment]
Plowed forward into the darkness (#1563)
