### ISSUE TITLE
Strengthen design of the marketing landing page (and overall site style)

### ISSUE THREAD

**Issue by ericronne** [18F/federalist#1563]
#### Description of feature or bug
Iterate toward making the public website be a great example of USWDS implementation, in order to inspire potential customers and strengthen the Federalist brand.

#### Definition of done
- [ ] ~A next-version wireframe is agreed upon (#1562)~
Proceeding with best-guess revisions for now.

- [x] A draft page is created and presented, including
   - new colors and adjusted typography and layout (begun with #1564) 
   - ~updated content (see #1493 and PR #1373)~
   - stubbed in section highlighting example sites (and more?)

- [x] The WIP redesign is tested (#1561)

- [ ] Changes suggested by ^ are discussed, noted, implemented

#### Level of effort
Medium / High

#### Implementation outline:
Work in Sketch

**Comment by ericronne** [comment]
### Some thoughts from the [visual-design review](https://docs.google.com/document/d/1nG_hF4hpZC7flBCBaSBu9PXa0VZe6M8tkp9OP1Gu6bU/edit#)

- Design could be more exciting. Make this a great example of USWDS implementation.
Banner background photo literally depicts one of the Federalist papers. Interesting, but suggests history and printing. Might reconsider in favor of something more modern. Possibly simple, abstract, colorful.
- Hero copy could be more inviting. See suggestions for this (and other content) in the [content review doc](https://docs.google.com/document/d/10dl_3c6uTolRYtmMBhMJ7tnKVoXwvnAhTx93uLq2uSY/edit#).
- See how users feel about the update counter in our tests (#1561). Dashboard-like info could serve to demonstrate how active the platform is. A redesign which includes more stats might make it more interesting. E.g. number of sites on Federalist, etc. Or not … up to the users!
- If [testing](https://github.com/18F/federalist/issues/1561) suggests it is needed, consider adding a section which links to the Example sites page. This could go near the bottom.

**Comment by ericronne** [comment]
And a few global notes to consider while designing this page:

- Breakpoint issues:
   - Header is responsive only in the Documentation section
   - Left nav in Documentation bumps down to an awkward footer-like layout when the window is still at about 1185 pixels wide. Still plenty of room for it. (Stopgap fix proposed in issue #1539)
- The form list is linked using three different calls to action: “Sign up for more information,” “Get started,” and “Learn more.”
- **A footer could serve as a nice signoff**, and — if we include an agency logo — a branding opportunity (see content review). (Documentation currently has a footer with the Federalist icon, but incorrect typography.)

**Comment by ericronne** [comment]
Here's a page for us to discuss!

![landing-desktop](https://user-images.githubusercontent.com/9259185/36040260-8e735a7c-0d8a-11e8-950b-78c3bce23284.png)

**Comment by ericronne** [comment]
cc @AvivaOskow @davidewarren @wslack @OpenGlobe

**Comment by jseppi** [comment]
😍

**Comment by wslack** [comment]
I think this is great, all around. I have some prose updates but those can be done in a PR.

**Comment by ericronne** [comment]
Here's Version 1 of a new style set. Refinements to come as more content is fleshed out (e.g. sub pp). Testing may also shed light on them, too.

![federalist typography](https://user-images.githubusercontent.com/9259185/36693730-d2bd186a-1b01-11e8-863f-a532d7f7dbe9.png)
![federalist colors](https://user-images.githubusercontent.com/9259185/36693735-d5be3e68-1b01-11e8-9e04-55d8810fab99.png)

**Comment by ericronne** [comment]
@wslack / @davidewarren / @ShannonBad 

I've updated three content sections ("Choose a template …," "Site code already …," and "Download these …") in order to make the page more realistic, for testing.

Please lmk if you have content changes, thx!

![landing-desktop-for-test](https://user-images.githubusercontent.com/9259185/36701312-81b73e20-1b18-11e8-9a76-54679759f2c6.png)

**Comment by wslack** [comment]
wonderful and thank you!

**Comment by ericronne** [comment]
@el-mapache here's an updated type spec sheet. As we discussed, i removed the `h1 hero` style in favor of the smaller `h1`. This will serve to reduce the height of the home-page hero, with an eye to encouraging the user to scroll.

Other changes include specs marked in ems.

![federalist typography](https://user-images.githubusercontent.com/9259185/37215004-648dd176-237c-11e8-91d9-d9d07fe2c9bf.png)

**Comment by ericronne** [comment]
Some stats specs...
![image](https://user-images.githubusercontent.com/9259185/37217015-ffb7305c-2381-11e8-8664-d799da9a028a.png)

**Comment by wslack** [comment]
❤️ 😍 😻

**Comment by wslack** [comment]
Should we put this live on staging before the content is final?

**Comment by wslack** [comment]
@mkhandekar dawwwww thanks!

**Comment by wslack** [comment]
https://drive.google.com/open?id=1t6DlmW6ZKtp-LC9Sz-xynKybwDeJ8w3T - sketch files live here if folks are looking in the future, will edit this above as well
