### ISSUE TITLE
Explore new options for color, typography, and style for the public site

### ISSUE THREAD

**Issue by ericronne** [18F/federalist#1564]
#### Description of feature or bug
Lay stylistic groundwork in order to jump head first into [redesign of the public pages](https://github.com/18F/federalist/issues/1563) once testing unblocks it.

#### Definition of done
Roughs in sketch based largely on the current content, along with general direction of typography set (based on USWDS)

#### Level of effort
Medium

**Comment by ericronne** [comment]
Here's an MVP-level collection of style samples and attributes. Will modify as page designs progress. Initial landing-page work, for starters (#1563)

![colors and type](https://user-images.githubusercontent.com/9259185/36002969-b6ee2a8e-0cf1-11e8-9511-944c17cf8794.png)
![icons and illustration](https://user-images.githubusercontent.com/9259185/36002970-b6fbf7a4-0cf1-11e8-8055-e443f8d30ce7.png)

**Comment by wslack** [comment]
@ericronne ooooooooohhhh
