### ISSUE TITLE
Redesign example sites page, now Case studies!

### ISSUE THREAD

**Issue by ericronne** [18F/federalist#1567]
#### Description of feature or bug
Based on (and thus blocked by) [revised wires](https://github.com/18F/federalist/issues/1566) (#1566) and the updated look and feel to be gelled on the [landing page](https://github.com/18F/federalist/issues/1563).

#### Definition of done
- [x] New wireframes are agreed upon (#1566)

- [x] Updated page design is presented

#### Level of effort
Medium

#### Implementation outline
Sketch layout

**Comment by ericronne** [comment]
### Some thoughts from the [visual-design review](https://docs.google.com/document/d/1nG_hF4hpZC7flBCBaSBu9PXa0VZe6M8tkp9OP1Gu6bU/edit#)

- The hero header design should be reserved for the home page. This page should get a less dramatic intro, and probably include “Example sites” (or “Example Federalist websites”) as a header.
- A content chunk about our templates might help visitors better understand what we offer (see what [testing says](https://github.com/18F/federalist/issues/1561)). (Currently users must be logged in to view them, or dig deeply into the documentation.) This might even merit its own page / top-nav link.
- Contextualize the examples so visitors don’t take them as design references, or divide the examples into custom and templated. If that makes sense, might that structure also help us better explain the range of what we offer?

**Comment by ericronne** [comment]
With site previews! 💃 

![case-studies-design-final](https://user-images.githubusercontent.com/9259185/37544099-d701432c-2931-11e8-9c5c-804dfb7faf32.png)

**Comment by wslack** [comment]
Awesome! Thank you @ericronne!

**Comment by wslack** [comment]
Leaving on Eric for retro presentation; this will then flow to Ready for @el-mapache to pick up when he has capacity.
