### ISSUE TITLE
Redesign compliance memo

### ISSUE THREAD

**Issue by ericronne** [18F/federalist#1568]
#### Description of feature or bug
Update the [compliance memo](https://federalist-docs.18f.gov/assets/documents/Federalist-Compliance-Memo.pdf) design once the overall visual direction is in a good place (reflected on the [landing page](https://github.com/18F/federalist/issues/1563)) 

#### Definition of done
Revised PDF published

#### Level of effort
Medium

#### Implementation outline (if higher than "low" effort):
Sketch or InDesign layout

**Comment by ericronne** [comment]
## [Draft layout](https://docs.google.com/document/d/1jWnMpUgXf_0kIOX9oW_ByX5bC5ToBXs0WXsQdxBbFS0/edit?usp=sharing)
based on the [Informational proposal](https://docs.google.com/document/d/1HeLanvq-0zoKyWBNwdXpB0NXT4GLnP6rON9ZzCnN0nk/edit#)

@thebestsophist @wslack @AvivaOskow

**Comment by wslack** [comment]
👍 next step is to convert the text!

**Comment by thebestsophist** [comment]
Updated footnotes that got messy in the copy/pasting.

**Comment by wslack** [comment]
👍 on me to put in the PR to upload it

**Comment by wslack** [comment]
not done yet, blocked by https://github.com/18F/federalist-docs/issues/222

**Comment by wslack** [comment]
Can move when https://github.com/18F/federalist-docs/pull/223 is merged.
