### ISSUE TITLE
Redesign marketing one-pager

### ISSUE THREAD

**Issue by ericronne** [18F/federalist#1569]
#### Description of feature or bug
Update the [marketing one-pager](https://federalist-docs.18f.gov/assets/documents/Federalist-One-Pager.pdf) design once the overall visual direction is in a good place (reflected on the [landing page](https://github.com/18F/federalist/issues/1563)), using https://docs.google.com/document/d/1HeLanvq-0zoKyWBNwdXpB0NXT4GLnP6rON9ZzCnN0nk/edit#.

#### Definition of done
- [ ] Revised PDF published on federalist-docs.18f.gov and if needed, on the main homepage

#### Level of effort
Medium

#### Implementation outline (if higher than "low" effort):
Sketch or InDesign layout

**Comment by annahsebok** [comment]
I've transitioned the old one-pager into the new design [here](https://docs.google.com/document/d/18omWPUMm9lVaqbBx5RUiQOmtySJLCVdUkW9UsW2ei_w/edit#). Refining the content a bit now, then this should be ready to publish.

**Comment by annahsebok** [comment]
I've made a few small content tweaks and flagged one question for @wslack.

Will, can you take a look and drop a 👍 here when you're finished?

Doc again for reference: https://docs.google.com/document/d/18omWPUMm9lVaqbBx5RUiQOmtySJLCVdUkW9UsW2ei_w/edit#
