### ISSUE TITLE
Create content for how to use templates

### ISSUE THREAD

**Issue by ericronne** [18F/federalist#1571]
#### Description of feature or bug
Our users need direction on how to make use of the Federalist templates. We need guides for them that include how to configure each of their templates and explain the possibilities of each template. 

#### Definition of done
- [ ] Content for template guides are created
- [ ] New issue created for Implementation of guides
- [ ] bulleted list of features or pros/cons so that customers knew when to chose one template over the other.

#### Level of effort - <low/medium/high>
Medium

#### Implementation outline (if higher than "low" effort):
Implementation Outline needed

**Comment by ericronne** [comment]
Related to #1311

**Comment by line47** [comment]
There is a fair amount of documentation that will apply to the updated templates here https://github.com/18F/uswds-jekyll/blob/master/README.md#jekyll--us-web-design-system

**Comment by ericronne** [comment]
Also: https://designsystem.digital.gov/page-templates/

**Comment by wslack** [comment]
I don't think that existing documentation is exactly what we're looking for. We need documentation to walk someone non-technical through adopting and editing a template leveraging the new templates.

**Comment by ericronne** [comment]
Sorry, i'm thinking of explicitly non-technical aspects here: content designed to introduce the templates to newbies, so they understand what we have to offer, and can better decide whether or not this is what they need. I probably should've used a word other than "documentation" in the title.

Marketing material.

**Comment by line47** [comment]
Unassigned myself as I'm working on #1645 which is different than the work described here

**Comment by wslack** [comment]
Thanks Eric. Agree with Scott; this is new content we'll need to create.

**Comment by wslack** [comment]
@davidewarren to see about consolidating this with #1678

**Comment by davidewarren** [comment]
I updated this issue to reflect the discussion ^

**Comment by adborden** [comment]
One thing that came up in the research was being able to see a bulleted list of features or pros/cons so that customers knew when to chose one template over the other.

**Comment by annahsebok** [comment]
Per our new [content approach](https://docs.google.com/document/d/1V1RPQ3fFdclCDE2ZCm6Htt25DLcPLJ5mbE01UqnnvnI/edit#), we're moving this work over to the federalist-docs work-stream. We have a hypothesis that "how to use templates" content belongs with our detailed guidance as opposed to with our sales information. We'll learn more about this in #1723.

**Comment by wslack** [comment]
Subject to more work after https://github.com/18F/federalist/issues/1775 is done - or if we prioritize it higher.
