### ISSUE TITLE
Finalize Federalist Content Review

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1576]
#### Description of feature or bug

@OpenGlobe did a great review that hasn't been finalized yet.

#### Definition of done

- [ ] The [content review](https://docs.google.com/document/d/10dl_3c6uTolRYtmMBhMJ7tnKVoXwvnAhTx93uLq2uSY/edit?ts=5a6bc249#) is completed and processed into issue.

_After evaluating, edit this part:_

**Comment by jseppi** [comment]
Is this different from #1493?

**Comment by wslack** [comment]
Duplicate!
