### ISSUE TITLE
Highlight current page in left nav

### ISSUE THREAD

**Issue by davidewarren** [18F/federalist#1577]
#### Description of feature or bug

For easier navigation on the main app pages - highlight the current/active page in the left navigation. 

#### Definition of done

- [ ] Left nav option is highlighted in sync with what page the user is on

**Comment by wslack** [comment]
Hi friends, should we do this? If so, seems like an easy change, but I'm not sure of the utility.

**Comment by el-mapache** [comment]
We have the site name featured pretty prominently on all `site` app screens so I'm not certain this is a 100% necessity. One thing I do think the side bar could benefit from is some kind of highlighting to let the user know what page they are on.

**Comment by line47** [comment]
I agree - Adding an active/current state to the side nav would be helpful

**Comment by davidewarren** [comment]
ok, it seems like there is agreement to 
1. not add the site name to the left nav bar
2. highlight the active page on the left nav bar 

@wslack - I'll update the content rules doc and edit this issue to just 2 ^ - sound good?

**Comment by wslack** [comment]
Endorsed, but I don't think it's that big impact - if the lift is more than 20 min of coding I would say we should just backlog.

**Comment by davidewarren** [comment]
Issue and Content Rules updated

**Comment by wslack** [comment]
Going to close this unless a customer asks or notes in user research.
