### ISSUE TITLE
Implement new "stacked" design on Add Site page

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1585]
#### Description of feature or bug

From @ericronne's [comment](https://github.com/18F/federalist/pull/1544#issuecomment-362610835):

![image](https://user-images.githubusercontent.com/697848/35739786-607ef708-07f8-11e8-9a8f-ce1162292c6a.png)

#### Definition of done

- [x] design is implemented and ok'd by @ericronne
- [ ] template descriptions are adjusted to fit new design

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by jseppi** [comment]
@ericronne: how should the "expanded" state of each template block look (ie, after the `Use this template` button is clicked)?

Currently it looks like this:

<img width="983" alt="screen shot 2018-02-02 at 9 10 08 am" src="https://user-images.githubusercontent.com/697848/35739956-efcb2a62-07f8-11e8-93c5-abef65e3d4d7.png">

**Comment by ericronne** [comment]
Like this!

![image](https://user-images.githubusercontent.com/9259185/35740745-6539a470-07fb-11e8-99a8-7839d229873c.png)

**Comment by wslack** [comment]
If we have time to do this by Tuesday, I am 👍 (@line47 do you have time?)

**Comment by line47** [comment]
I'd love to fit this in 🇺🇸

**Comment by line47** [comment]
Who is updating the template descriptions here?
@wslack see definition of done

**Comment by wslack** [comment]
@davidewarren should be

**Comment by line47** [comment]
Once I get the update template descriptions from @davidewarren - this issue should be good to go! 👍

**Comment by davidewarren** [comment]
@line47 - template description working doc - https://docs.google.com/document/d/1ZUX8JazAPM0M4rSNJNp_aTPmYi6XBITKlJAn1iORohw/edit#

New Descriptions: 

USWDS Template - The U.S. Web Design Standards landing page template. A multi page template designed to introduce an agency or program. 

Modern Team Template - A multi page template designed to introduce to an agency or program. This template offers an alternate look and feel to the USWDS template.

Basic Report Template - An easy to use template with a simple layout. This template is designed to host a multiple pages about a recent report or order. 

Landing Page Template - An engaging single page template. This template is designed to showcase specific work or a project. 

One Question @wslack 
USWDS Template - Is it ok to say that this **is** "The U.S. Web Design Standards landing page template"? - if yes, I think it's the best way to describe it

**Comment by davidewarren** [comment]
@line47 also, can we change the order of template options to match the order of the descriptions above?

**Comment by line47** [comment]
@davidewarren we can certainly change the order, can you also provide a description for the redirect template? We also moved away from the word "template" in the title to simplify a bit

**Current screenshot**
![screen shot 2018-02-05 at 11 56 18 am](https://user-images.githubusercontent.com/1449852/35817262-ebbb48fc-0a6a-11e8-8390-1b3543062d16.png)

**Comment by davidewarren** [comment]
@line47 thanks, I'll add the Redirect template description and give a little more information for each of the others. We have more room for a description than I realized at first.

**Comment by davidewarren** [comment]
@line47 Here are more detailed descriptions of each of the templates. 

U.S. web design system - The U.S. web design system landing page template. This flexible multi page setup is intended to introduce an agency or program. It offers an engaging Hero section for a current priority and a landing page layout designed to provide clarity and context for first time visitors. This template also offers navigation options for internal pages. 

Modern team - A multi page setup designed to introduce an agency or program that offers a different look and feel to the U.S. web design system. This setup includes a landing page with a Hero section and multiple sections on the landing page to showcase current work and projects. The navigation setup offers easy to customize internal pages meant to provide additional information. 

Basic Report - A simple, easy to use setup designed to host multiple pages about a recent report or order. This setup provides a clean space for complex details or instructions. Navigation can be customized to host many pages while maintaining a clear hierarchy. 

Landing Page - An exciting and engaging single page template designed to showcase specific work or a project. This setup offers a Hero section with a background image meant to provide a high-level summary and set the tone for site content. Navigation options in this setup are anchors to sections on the single main page.  

Redirect Page - A simple and professional redirect template that follows U.S. web design system principles. This redirect page fits well with a variety of different branding and styling.

**Comment by wslack** [comment]
@davidewarren if you want to edit those in yourself, you can do that here: https://github.com/18F/federalist/edit/sw-add-site-ui/config/templates.js?pr=/18F/federalist/pull/1586

**Comment by line47** [comment]
Thanks @davidewarren ok to remove that first sentence for the USWDS template "The U.S. web design system landing page template."

**Comment by davidewarren** [comment]
@line47 we could. My purpose with that sentence was to make it clear that the template was the exact template found here - https://designsystem.digital.gov/page-templates/#landing-page

But if that's clear enough from the title then it's not needed
