### ISSUE TITLE
Confirm error prop in AddSite component is needed

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1588]
#### Description of feature or bug

See https://github.com/18F/federalist/blob/staging/frontend/components/AddSite/index.js#L15

#### Definition of done

`TODO` comment is resolved

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by wslack** [comment]
worth immediate action or should this be backlogged?

**Comment by jseppi** [comment]
it can be backlogged IMO

**Comment by jseppi** [comment]
Should be quick, want to take @el-mapache?

**Comment by el-mapache** [comment]
Yeah I can grab it
