### ISSUE TITLE
Add CORS support for s.codepen.io

### ISSUE THREAD

**Issue by maya** [18F/federalist#1589]
#### Description of feature or bug

I have this CodePen: https://codepen.io/USWDS/pen/BYjrRK?editors=1100

and getting this error in the console in Chrome:
```
Access to Font at 'https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/add-utilities/dist/fonts/sourcesanspro-bold-webfont.woff2' from origin 'https://s.codepen.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://s.codepen.io' is therefore not allowed access.
```

From @jseppi:
>So, federalist would have to add some CORS headers. I think that can be done either at the S3 level or in our proxy. It’s not a technical big lift.

#### Definition of done

"pens" on `s.codepen.io` can AJAX-in assets from Federalist sites through `federalist-proxy.app.cloud.gov`

Testing pen: https://codepen.io/anon/pen/mXrXVR?editors=0011

_After evaluating, edit this part:_

#### Level of effort

~low~ medium (updated)

#### Implementation outline (if higher than "low" effort):

- [x] Delete existing CORS policy on the staging bucket so that it doesn't conflict with https://github.com/18F/federalist-proxy/pull/24. See details 
at https://cloud.gov/docs/services/s3/#allowing-client-side-web-access-from-external-applications and https://docs.aws.amazon.com/cli/latest/reference/s3api/delete-bucket-cors.html
- [x] Confirm staging works: https://codepen.io/anon/pen/mXrXVR?editors=0011
- [x] Merge changes to and deploy production `federalist-proxy`

**Comment by maya** [comment]
It would be great to have this by next week (2/12) when we plan to start using this in user testing.  cc @wslack @jseppi

**Comment by wslack** [comment]
this is pending compliance approval

**Comment by wslack** [comment]
@jseppi this has to be manually deployed, right?

**Comment by wslack** [comment]
should we test it with staging first?

**Comment by jseppi** [comment]
Yup. I've already deployed the change to `federalist-proxy-staging`.

**Comment by jseppi** [comment]
Unfortunately, this isn't working in staging :(

It seems there is some other level (S3 or maybe CloudFront) that is adding its own `Access-Control-Allow-Origin` header, which results in a duplicated header, and thus an error:

<img width="1140" alt="screen shot 2018-02-06 at 3 18 27 pm" src="https://user-images.githubusercontent.com/697848/35884723-2415cf24-0b51-11e8-9abc-90e49e98c924.png">

**Comment by wslack** [comment]
That's odd. If there was already a header with a wildcard this should have been working already.

Should we remove from staging and see what headers we can see without?

**Comment by jseppi** [comment]
huh, so the `staging` proxy appears to already have some CORS headers, while `production` does not.

<img width="633" alt="screen shot 2018-02-06 at 4 26 34 pm" src="https://user-images.githubusercontent.com/697848/35887636-8e8a8544-0b5a-11e8-8e92-aa877b8e2c9b.png">

**Comment by wslack** [comment]
That is real odd. And we know its not in the code...is the next step to ask cloud.gov?

**Comment by jseppi** [comment]
It's coming directly from the staging S3 bucket:

<img width="637" alt="screen shot 2018-02-06 at 8 02 22 pm" src="https://user-images.githubusercontent.com/697848/35894503-af771402-0b78-11e8-9049-91a99ec8d5d7.png">

**Comment by wslack** [comment]
Hmm k. I assume the only people who can see those settings are cloud.gov staff (why would they be different? so odd)

**Comment by jseppi** [comment]
Updated the implementation sketch with new details in light of finding out we can set CORS policy directly on the cloud.gov-brokered S3 buckets.

**Comment by jseppi** [comment]
Updated again :)

**Comment by wslack** [comment]
@jseppi I'm good doing a merge to `production` if we're sure that staging is working

**Comment by jseppi** [comment]
Alright, this should be all finished 🎉 

Want to confirm, @maya? I'm not seeing any more CORS errors on your pen at https://codepen.io/USWDS/pen/BYjrRK?editors=1101

**Comment by maya** [comment]
@jseppi LGTM 🎉 

yes, I checked some of my pens that had the errors before and they don't have it anymore!

**Comment by jseppi** [comment]
@maya: we changed how we're doing this in order to fix the `X-Frame-Options` problem. Everything looks like it works now to me, but can you confirm, please?

**Comment by maya** [comment]
Confirmed! Working for me 🎉
