### ISSUE TITLE
Remove icon from dashboard page titles

### ISSUE THREAD

**Issue by ericronne** [18F/federalist#1590]
#### Description of feature or bug

This doesn't add meaning to the page, and the style clashes with the rest of the iconography.
![image](https://user-images.githubusercontent.com/9259185/35814068-c16b05a2-0a5a-11e8-9004-d11e06256100.png)

💀  it.

#### Level of effort 
low

**Comment by wslack** [comment]
Moved to Ready. A relic of a bygone era.
