### ISSUE TITLE
Icons in SideNav "flicker" upon first hover-state triggering

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1592]
#### Description of feature or bug

Upon first mousing over the icons in the Side Nav, there is a quick flicker as the new background image SVG is swapped in for the first time. This happens independently for each icon.

#### Definition of done

Icons do not flicker on first hover.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

Use in-lined (or loaded via `import`) SVGs (in the React components) and styling rules (via CSS/SASS) to style hover states instead of swapping in individual SVG assets.  This will 1) prevent the initial flash of loading and 2) be more flexible should colors be changes. It'll also result in an extremely small reduction in bandwidth.

**Comment by jseppi** [comment]
_should_ is maybe too strong; _could_ is probably more appropriate.

We can only style with CSS/SASS if the SVGs are inlined into the markup instead of brought in via `url(...)` in CSS (as we currently have it).

**Comment by jseppi** [comment]
Another way, I think, to get rid of the flicker would be go back to a sprite sheet.

**Comment by jseppi** [comment]
cc @ericronne

**Comment by wslack** [comment]
Also applies to the site list but this feels like extremely low impact. Can it be done and tested in less than an hour?

**Comment by jseppi** [comment]
Maybe 2 to be safe. Might require a slight addition to our webpack loaders.

**Comment by wslack** [comment]
hrm. Relative to other things in Ready I am not sure, but I also know that this will bug people until we just fix it so maybe better to strike while iron is hot?

**Comment by jseppi** [comment]
@line47 and @ericronne cleaned this up in #1640 🎉
