### ISSUE TITLE
Validation error when only setting live domain and branch

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1599]
#### Description of feature or bug

This bug exists in both production and staging.

When setting live domain and branch without setting the demo domain and branch, a validation error is thrown that prevents the user from saving their setting.

Gif:

![bad-branch-validation](https://user-images.githubusercontent.com/697848/35929632-89562ad8-0bf5-11e8-9ec2-98823bee65bb.gif)

#### Definition of done

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by el-mapache** [comment]
Waiting to change this to `done?` until its been deployed and tested.

**Comment by jseppi** [comment]
The staging deployment just finished and I confirmed that the fix worked there.

**Comment by jseppi** [comment]
And confirmed it works on prod as well. 👏
