### ISSUE TITLE
Heuristic evaluation of Federalist / issue creation

### ISSUE THREAD

**Issue by ShannonBad** [18F/federalist#1600]
#### Description of feature or bug
Do a heuristic evaluation of the Federalist website in order to be more familiar with the website and the UX/design.
<TODO>

#### Definition of done
A document showing a heuristic evaluation, review the site architecture and a list of related questions.

<TODO>

#### Level of effort 
medium

#### Implementation outline:
Will be implemented as a visual aid of the web pages (with markup), created in Sketch with some writing with suggestions of things to consider. Also a list of questions created as a result, will be presented, some of which may have the option of future research.

This heuristic evaluation will address the Federalist main website pages; the home page, "example sites", "documentation", "get started". And this will cross-reference the principles of UI using Ben Shneiderman and Nielsen-Norman Group. 
<TODO>

**Comment by wslack** [comment]
@ShannonBad we talked about this vaguely but I feel like this is more than a "low" - how long do you think this will take?

**Comment by ShannonBad** [comment]
@wslack I suppose it depends on how large of a project you wish to make it and if there is to be any related research to support it? This project could also be larger if it also included future wireframe design or an iteration on the design (based on the heuristics/research)? But the first run at a heuristic evaluation can be done by next week, hopefully. Let me know if you want to discuss further or if I should widen the scope on here!

**Comment by wslack** [comment]
Cool. If it takes more than two hours I would say its not bad to sketch out your general plan for the work - and if you want to join our standups to give updates you have that option.

**Comment by wslack** [comment]
@ShannonBad looks good! I didn't realize you had edited.

**Comment by ShannonBad** [comment]
This is the PDF related to the heuristics plus a list of related questions and notes.
[Badiee_Heuristics for Federalist.pdf](https://github.com/18F/federalist/files/1721580/Badiee_Heuristics.for.Federalist.pdf)

**Comment by wslack** [comment]
This is good work and I will attempt to convert it into issues tomorrow!
