### ISSUE TITLE
Meet RE: template pages with WDS guidelines 

### ISSUE THREAD

**Issue by ShannonBad** [18F/federalist#1601]
#### Description
Meeting between Shannon Badiee and Scott Weber, to discuss the template pages with WDS guidelines.

<TODO>

#### Definition of done
Have meeting and Shannon has a better understanding of Scott's work.

<TODO>

#### Level of effort 
low

**Comment by wslack** [comment]
Great @ShannonBad please reach out to @line47 on Slack to schedule!

**Comment by wslack** [comment]
Scheduled for tomorrow
