### ISSUE TITLE
Expand landing-page stats

### ISSUE THREAD

**Issue by ericronne** [18F/federalist#1602]
### Potential customers might be reassured to see that the Federalist platform is very active. A live stats display could help do that.

---

#### Currently we show only the number of updates made in the past week 
![image](https://user-images.githubusercontent.com/9259185/35933262-bbeca044-0bff-11e8-85f5-1f2dec63b425.png)

#### The total website and user tally come to mind as potentially beneficial adds
![image](https://user-images.githubusercontent.com/9259185/35933435-44c7c592-0c00-11e8-8442-ef1f3fa6390c.png)

#### Level of effort - low

**Comment by wslack** [comment]
Federalist doesn't know how many sites it supports are actually "live" unfortunately, but that might be a neat stat if easily gathered. I would also not want to call people logging in "users" - we should say "collaborators" instead.

Other stats....we could do site updates over the past year, or new sites in the past week.....

**Comment by ericronne** [comment]
If they're built on federalist, could we reasonably include them in the count, regardless of whether they're currently live?

"XXX websites supported" could be another phrasing

**Comment by ericronne** [comment]
How about a total count of all site updates since the first site was launched?

**Comment by wslack** [comment]
@jmhooper we have ^^ right? I wouldn't want to run an expensive query all of the time to get that number though.

**Comment by jseppi** [comment]
Counting is very cheap in general for databases.

**Comment by ericronne** [comment]
Is there any way to quantify the efforts we've put into compliance in general?

**Comment by wslack** [comment]
not that I can think of. The "live site" count shows the results but part of the selling point is that we abstract it away.

**Comment by ericronne** [comment]
Something impressive about our code's history, boilt down to a single number? 

Git has lots to say about last month …

![image](https://user-images.githubusercontent.com/9259185/35937083-b7c400b0-0c0a-11e8-8321-d98f7cdb07da.png)

**Comment by ericronne** [comment]
"Collaborators" seems fuzzy to me. Something like "partner collaborators" more clear?

The word doesn't feel exactly right.

Also, how many agencies have we served?

**Comment by wslack** [comment]
9 agencies so far, I think.

partner collaborators is fine with me.

**Comment by ericronne** [comment]
Here's the kitchen-sink collection of the ideas we have so far.

Which ones feel most impactful to you?

It was my suggestion, but "Partner collaborators" feels a little funky to me.

![image](https://user-images.githubusercontent.com/9259185/35983742-53dfae74-0cb8-11e8-9f25-6e508fc520c8.png)

_NOTE: all of this assumes that enhanced stats on the home page would be a useful addition. Perhaps we add some and test._

**Comment by el-mapache** [comment]
The only issue I see here is getting the page views per day, since we don't have any analytics we'd have to parse Federalist log files and count IP addresses.

Is the page views metric supposed to be an aggregate of all daily page views for all the sites currently hosted with production Federalist?

**Comment by ericronne** [comment]
Re page views, whatever this is doing (on the example sites pg) ...

![image](https://user-images.githubusercontent.com/9259185/36046400-63fdb9fe-0d9e-11e8-9ee0-54ab97691434.png)

**Comment by wslack** [comment]
That number was me pulling an export with Jonathan and manually adding a number. We have no automatic way to pull it.

**Comment by wslack** [comment]
I think that more than 4 numbers ends up losing focus. An maybe we say "X site managers using Federalist" or something instead of collaborators.

**Comment by jmhooper** [comment]
> Federalist log files and count IP addresses.

Thanks to CloudFront caching, we actually can't do that since all we'd see is the requests from the CloudFront edge servers.

We got the data from earlier from sites that were on DAP's aggregate account.

**Comment by ericronne** [comment]
@wslack agreed! the long list was a kitchen-sink menu of notions from which to choose

how about this for MVP?
![image](https://user-images.githubusercontent.com/9259185/36047167-e8f1a48e-0da0-11e8-8e04-c7fcaa2ce55c.png)

**Comment by wslack** [comment]
what about *212* staff with *9* federal agency clients using Federalist?

**Comment by ericronne** [comment]
That feels a little ambiguous to me. _Thinking …_

**Comment by ericronne** [comment]
![image](https://user-images.githubusercontent.com/9259185/36047504-f0dad4d0-0da1-11e8-8f27-288b310ad787.png)

**Comment by wslack** [comment]
I do like that but it gets me back to wanting to be clear: our user is the public or whoever consumes the sites we support. We partner with other agencies, but as we make templates and such, the central customer is the eventual site consumer.

So I don't love narrowing down "user" to the people that manage sites with us, if that makes sense.

**Comment by wslack** [comment]
@ericronne what's the next step? Is this  good until other parts of page are good? Should we code this up now?

**Comment by ericronne** [comment]
Up-time % could also be an interesting stat

**Comment by jseppi** [comment]
`👷 5 days since our last safety incident`

**Comment by eddietejeda** [comment]
I updated the numbers. Added visitors using the calculations on 140,00 visitors number on case studies page. I then logged into DAP.. Login.gov provides a big chunk of traffic, so I updated the number.

<img width="311" alt="screen shot 2019-01-27 at 11 10 50 am" src="https://user-images.githubusercontent.com/669988/51803537-4b5c0680-2224-11e9-8e8e-9b4cffef8561.png">
