### ISSUE TITLE
Icon suggestions

### ISSUE THREAD

**Issue by maya** [18F/federalist#1605]
The new icons are looking great! A couple of suggestions...

"View repo" -- use the classic GitHub logo as it's more recognizable.

<img width="246" alt="screen shot 2018-02-08 at 11 22 09 am" src="https://user-images.githubusercontent.com/5249443/35993486-5a336086-0cc2-11e8-8ca4-7dfc5d5e404c.png">

The "View commit" icon -- it doesn't really need to be there since it repeats a bunch of time, but if you want an icon, consider something more subtle like the GitHub commit icon in a light gray.

**Example from CircleCI:**
<img width="90" alt="screen shot 2018-02-08 at 11 16 53 am" src="https://user-images.githubusercontent.com/5249443/35993387-09d52908-0cc2-11e8-869d-28611d05ba74.png">

**What it could look like:**
<img width="159" alt="screen shot 2018-02-08 at 11 26 47 am" src="https://user-images.githubusercontent.com/5249443/35993703-05686a6e-0cc3-11e8-89eb-041ccdf00da9.png">

Source: https://octicons.github.com/icon/git-commit/

**Comment by wslack** [comment]
I think we're trying to be clear when something is a link inside Federalist vs an external link - the icon helps with that. But @ericronne or @AvivaOskow may have a take.

I agree that the classic icon is more identifiable but it also clashes with the general icon set

**Comment by ericronne** [comment]
Thanks for the comments! Smart, per usual :)

Although the line-art github icon isn't as immediately identifiable as the stock one, my gut is that it's evocative enough for the supporting role these icons play. As part of the dashboard, those links will get a lot of usage. Should only take one click for anyone to learn. Will certainly take another look if they give users trouble.

I hope to have time to take a broader look at the dashboard design (as you suggested back in #1408, @maya, if slightly less ambitious!). The icons in this area may not be necessary at all, will see.

**Comment by maya** [comment]
Always good to test it with users ;) In general, I'm pretty open to custom iconography but when it comes to brands, I tend to use the recognizable logo as it's less of a cognitive load for users.

Since the icons in the build below are repeated around 50 times, you can give them even more of a supporting role by using a light gray (darken or change to blue on hover). And the commit icon I suggested above is a GitHub.com icon if you're worried about indicating that it's from GitHub.

These are just my 2 cents. I'm sure you'll learn more as folks use it, and perhaps learn the interface like you mention.

Looking forward to seeing what you do with the dashboard! Even simply changing the order of repos to the most recently added in Federalist would be a big improvement. All my stale repos are at the top now.

**Comment by jseppi** [comment]
I concur with @maya for what it's worth

**Comment by wslack** [comment]
After some reflection, I agree with Eric that users will learn and I think the is evocative enough. If I had to pick, though, I'd say the easiest logo makes sense if its not visually clashing. (and making it a bit lighter would be good as well)

The commit icon doesn't seem recognizable to me and I wouldn't want to change it without validating with users. Will be interested in @AvivaOskow's take as well at some point; I certainly don't feel stronger and am open to persuasion.

**Comment by wslack** [comment]
@ericronne to create screenshots of options

**Comment by wslack** [comment]
@adborden I don't think we ever decided which version of the icon was best. Want to make screenshots of options?

(options I can think of: current, using the "standard" black icon, using a grayed "standard" icon)

**Comment by adborden** [comment]
The options are endless! Notice the white GH icon in the footer on these

_Current Federalist icon_
![screencapture-localhost-1337-sites-1-builds-2018-04-19-16_50_37](https://user-images.githubusercontent.com/509703/39023846-d95c7e5e-43f1-11e8-8e98-eb08bc9c5e07.png)


_Blue GH icon (inherited from link color)_
![screencapture-localhost-1337-sites-1-builds-2018-04-19-16_31_20](https://user-images.githubusercontent.com/509703/39023800-ab3bd6e6-43f1-11e8-81f9-eafe026dd64f.png)


_Black GH icon_
![screencapture-localhost-1337-sites-1-builds-2018-04-19-16_32_19](https://user-images.githubusercontent.com/509703/39023789-9dd44e2a-43f1-11e8-82b5-2f3d6eb6c68b.png)


_Blue commit icon (inherited from link color)_
![screencapture-localhost-1337-sites-1-builds-2018-04-19-16_38_49](https://user-images.githubusercontent.com/509703/39023775-82565ba2-43f1-11e8-8ed5-a3ef3d111b82.png)


_Black commit icon_
![screencapture-localhost-1337-sites-1-builds-2018-04-19-16_39_41](https://user-images.githubusercontent.com/509703/39023744-60b0be98-43f1-11e8-97db-6eb4328f3ad5.png)


_Light grey commit icon_
![screencapture-localhost-1337-sites-1-builds-2018-04-19-16_45_40](https://user-images.githubusercontent.com/509703/39023728-4f52e054-43f1-11e8-9bb5-910be89886e8.png)

... And I just want to call out that GitHub icons might be hiding in a few other places, like on the new landing page:
![screenshot from 2018-04-19 16-21-28](https://user-images.githubusercontent.com/509703/39023997-e6c9ea12-43f2-11e8-83d8-aaff1f3c5251.png)

**Comment by adborden** [comment]
Implementation question for @el-mapache  or @amirbey:
GitHub offers the Octicons as an [npm module](https://github.com/primer/octicons) and they are accessed through JS. Do you have a preference to use the npm module, or should I just scrape the svg's into static asset files?

Given the close integration of Federalist/GitHub, it might make sense to just use the npm module so pulling in additional icons is easy. It also means we don't have to add any licensing caveats (the Octicons are licensed under MIT, which we would have to mark in our README).

**Comment by el-mapache** [comment]
Do we think we'll use more of these icons vs the custom ones we have now? If so it seems worth it to just import these as a module.

I guess the only other caveat/benefit is that we get updates for free, but obviously we don't control the way they make changes to the icons.

**Comment by wslack** [comment]
I think I prefer `Black GH icon`

**Comment by ericronne** [comment]
I haven't been following this thread closely, apologies, but i wouldn't run an official github logo alongside an unfilled, stroke-only icon like i see here. The visual inconsistency looks unprofessional …
![image](https://user-images.githubusercontent.com/9259185/39368280-c8ff8bec-49fe-11e8-9749-1dc30c53f15a.png)

If we're genuinely concerned about using a non-official github logo, we could consider getting rid of the github icon altogether, and swapping in the "opens in a new page" graphic for _all_ links that open in a new page/tab, including the github ones:
![image](https://user-images.githubusercontent.com/9259185/39368428-2729e276-49ff-11e8-88e9-af0ed431a38e.png)

"View repo" in the top-right utility area could be changed to "View GitHub repo," to add a little clarity:
![image](https://user-images.githubusercontent.com/9259185/39368818-43b25c56-4a00-11e8-940b-5ec14cf8d4e9.png)

If you wanted to try that idea, we would need to do the same on the "Your websites" page, too, for consistency.

My 2 cents! Your call, @wslack! :)
