### ISSUE TITLE
Fix cut-off SideNav icons

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1606]
#### Description of feature or bug

With the merge of #1598, two icons, `icon-cloud_upload` and `icon-branch`, in the SideNav component are very slightly cut off at their edges.

#### Definition of done

Icons are not cut-off.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

Work with @ericronne to make adjustments necessary. I'm not sure what is needed currently.

**Comment by jseppi** [comment]
Should be low effort, and since this is presentational it would be great to get it fixed up.

Will need to coordinate with @ericronne a little bit to see if we can get all the SVGs in the same viewbox, I think.

**Comment by ericronne** [comment]
This issue appears to be resolved. True? I don't see any cropping, but the spacing could be better.

Possible to center the icons in their "column," rather than left-aligning?

![image](https://user-images.githubusercontent.com/9259185/36434946-e4f20b70-1625-11e8-8cc0-224de0cc2cac.png)

**Comment by jseppi** [comment]
Here they are zoomed-in. Notice the flattened edges on the GitHub branches icon's circles and on the sides of the Uploaded files icon's cloud:

<img width="142" alt="screen shot 2018-02-20 at 10 09 07 am" src="https://user-images.githubusercontent.com/697848/36435056-303badfc-1626-11e8-9034-e2bbb94704f8.png">

**Comment by ericronne** [comment]
I'm not seeing that problem; browser-specific? Pair?

**Comment by ericronne** [comment]
Chrome Version 64.0.3282.167
![image](https://user-images.githubusercontent.com/9259185/36435856-615f2a7e-1628-11e8-80b7-1b1e80a0dd4f.png)

**Comment by jseppi** [comment]
Same Chrome for me.

This is not present on prod if that's where you're looking. Only currently in staging and in local dev.

**Comment by ericronne** [comment]
pairing req'd when you have time @jseppi thx!

**Comment by wslack** [comment]
do we think that something in staging is causing this?

**Comment by ericronne** [comment]
i think inline svgs are hard.
we're coming back to this when time permits.
