### ISSUE TITLE
Change organization authorization message to cover edge case

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#1610]
#### Description of feature or bug

Currently, the organization authorization error says the following:

```
Organization '${owner}' hasn't approved access for Federalist. Ask an owner to authorize it.
```

This fails to describe an edge case that occurs when a user is not a member of an organization, but does have access to a repository. We should change the message to say something like this:

```
Organization '${owner}' hasn't approved access for Federalist, or you aren't a member of the organization. Ask an owner to authorize the organization or make you a member.
```

#### Definition of done

The error message describes this edge case

#### Level of effort - low

**Comment by wslack** [comment]
Should be in "Done?"
