### ISSUE TITLE
update docs diagram

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1613]
#### Description of feature or bug

the diagram in https://github.com/18F/federalist/issues/903 isn't on the main docs site

#### Definition of done

the docs site is updated

_After evaluating, edit this part:_

**Comment by ericronne** [comment]
pdfs for both **[print](https://github.com/18F/federalist-docs/blob/master/assets/documents/how-federalist-works-diagram.pdf)** and for **[slide presentations](https://github.com/18F/federalist-docs/blob/master/assets/documents/how-federalist-works-for-presentation.pdf) have been uploaded to the docs site

sketch design files are in the **[google drive folder](https://drive.google.com/open?id=1JBr4etxJS9xdNUDK0JnyrVhqYVinOpEL)**
