### ISSUE TITLE
Create process to audit staging before pushing new code to Prod

### ISSUE THREAD

**Issue by davidewarren** [18F/federalist#1614]
#### Description of feature or bug

- Creating a mini-process to audit staging before pushing new code to production

#### Definition of done

- Process created, documented, and ready to be implemented 

#### Level of effort 

- Low

**Comment by wslack** [comment]
Ideas:

- Commit a change on an existing "live" branch, triggering a build, then restart the build
- Delete then add an existing repo to federalist
- Create a new branch from a build
- Restarted a build from a build I did not make
- Created a new site from a template with a capitalized org name
