### ISSUE TITLE
Published files aren't displayed on the UI

### ISSUE THREAD

**Issue by jeremiak** [18F/federalist#1615]
Seeing this message on `/sites/:id/published` for [the DOI site](https://github.com/18F/doi-extractives-data) which has a number of published branches and files:
![screen shot 2018-02-12 at 3 07 53 pm](https://user-images.githubusercontent.com/780941/36117282-fef47140-1006-11e8-8a77-67dd98c9eec7.png)

FWIW, if I do https://federalist.18f.gov/sites/5/published/<branch_name> then I am able to see the files

**Comment by el-mapache** [comment]
This is a simple fix, I accidentally removed the fetch action in `componentDidMount` in the relevant component.

**Comment by wslack** [comment]
We'll do a cherry pick merge to prod.
