### ISSUE TITLE
Error reading `id` on Uploaded files view - files not loaded

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1620]
#### Description of feature or bug

This is happening in production when I attempt to view branches for any site (ex: federalist-docs, https://federalist.18f.gov/sites/25/published).

<img width="1017" alt="screen shot 2018-02-14 at 1 00 34 pm" src="https://user-images.githubusercontent.com/697848/36222517-23f7077e-1187-11e8-9058-3cb899f610a5.png">

I thought this was resolved by #1616 and the hotfix deploy #1617, but it still seems to be happening.

cc @el-mapache 

#### Definition of done

- Uploaded files are displayed
- No error is shown
- Production is fixed

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by jseppi** [comment]
Oh, I might be confused. This is fixed in staging, but maybe just hasn't been deployed to prod yet?

**Comment by el-mapache** [comment]
Hmm I thought the fix around the published files bug was deployed, I wonder if it is a race condition? I can try on staging with my connection throttled to try and repo it.

**Comment by jseppi** [comment]
Yeah, was just about to post something to that extent. It looks like the store's `sites.currentSite` is not populated, so `mapStateToProps` gets a `null` `site` value.

**Comment by el-mapache** [comment]
The wording of the issue was slightly confusing, is it happening for every site or just one site?

**Comment by el-mapache** [comment]
In another component I had to also check for `currentSite` in `componentWillReceiveProps`, but I tested this out a few dozen times and it seemed to be ok, so I didnt add the check to this specific component.

**Comment by jseppi** [comment]
Amended, it's happening for all.
When I first started writing I thought it was just for one site.

**Comment by el-mapache** [comment]
I am a little confused that it is happening so consistently on production

**Comment by el-mapache** [comment]
Ah I think I know the issue. The `currentSite` property was added in the refactor PRs, but those didn't make it into prod as of the last deploy
