### ISSUE TITLE
Design Federalist informational proposal 

### ISSUE THREAD

**Issue by davidewarren** [18F/federalist#1622]
#### Description of feature or bug

Federalist needs a proposal handout that program folks at other agencies can circulate to explain the benefits of Federalist. 

Here is an example:
https://drive.google.com/file/d/1Ny2M4KA4mrzfkh3w3Hgk2bgYBtwO6aI5/view

#### Definition of done

Federalist proposal complete and ready to sent to clients. 

#### Level of effort - 

medium

**Comment by ericronne** [comment]
Blocked by #1630 (content)

**Comment by wslack** [comment]
Is https://docs.google.com/document/d/1s1RJsfXPQmGASFoPG_-ndBxPQsoY374vzGahPkPWmmA/edit far enough along that work can start?

**Comment by AvivaOskow** [comment]
Here is my working design doc. Still a draft, but people can start taking a look if they want! I still have to respond to some feedback from @ericronne about the header (more simple perhaps) and some of the elements are placeholder still (the pull quote, footer icons), but just getting some elements in place.

https://docs.google.com/document/d/19GoR7An1pdcEC6cj3G2ynzTl-Fr8svKsaYPAPtkfzuk/edit?usp=sharing

**Comment by ericronne** [comment]
A further draft …
https://docs.google.com/document/d/1m5G7s7B3AfFyDhEOyi2d_SqJ27u9YfkRrmirGK6oii4/edit?usp=sharing

**Comment by thebestsophist** [comment]
Tightened content up a bit, but didn’t outright cut anything. Back to you @ericronne, let me know if we to do a deeper restructuring or cut stuff to hit 2 pages.

**Comment by wslack** [comment]
I'm happy with this and moved to Done? but welcome other comments
