### ISSUE TITLE
create 'contact' page, kill the google form

### ISSUE THREAD

**Issue by leahbannon** [18F/federalist#1623]
#### Description of feature or bug

Create a new 'contact' page to replace the google form.

This (along with the content in the email template) fulfills the data gathering component of Trammell's UX research recommendation.

#### Definition of done

- [ ] needs contact designer review
- [ ] 'contact us' page is created
- [ ] all links to the google form are replaced with links to the contact us page

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by leahbannon** [comment]
content:

## Contact
Want to use Federalist?
If you’re interested in using Federalist, email (x). We’ll schedule a call to answer your questions and help you get started.

## Support for people who use cloud.gov
Email (x). We provide support during business hours for U.S. East and West Coasts. We don’t guarantee support outside those hours, though we’re always monitoring for issues that might affect customers.

You should not include any passwords or sensitive environment variables in your email (we don’t need them to help you, and you should keep them protected).

Federalist is hosted on cloud.gov. Cloud.gov is under constant monitoring and set up for low or zero-downtime deployments, and should be expected to be operating continuously. You can check Cloud.gov's current status and history of uptime at https://cloudgov.statuspage.io.

## Report a vulnerability
We welcome vulnerability reports [according to our vulnerability disclosure policy](https://18f.gsa.gov/vulnerability-disclosure-policy/), which includes how to best contact us for this kind of information.

**Comment by leahbannon** [comment]
email template for "Want to use Federalist?"

> What is your name and agency/office?
> 
> Tell us a little about your website -- is it new? Or are you interested in migrating an existing website? If so, can you share the link? How many users do you expect it will get? What features should it have?
> 
> Would you like to receive updates about Federalist?

**Comment by leahbannon** [comment]
email template for "support for people" email:

> What is your federalist website?
> 
> What were you trying to do?
>
> What actually happened? How can we improve it?

**Comment by jseppi** [comment]
Just so I'm clear: this will be a page with a couple of forms (one for potential customers, one for support), right?

What happens when the forms are submitted? Should the responses be emailed somewhere, be put in a database, be written to a google spreadsheet, or something else?

**Comment by jseppi** [comment]
From a logical/technical perspective, emailing the responses seems like the best option to me.

However, that will mean getting access to an email relay service, which has historically been quite a hassle for other projects in my experience. It will also need to be addressed in the ATO and system diagram.

**Comment by wslack** [comment]
we want to make a link like [this one](mailto:cloud-gov-inquiries@gsa.gov?body=What%27s%20your%20name%3F%0A%0AWhat%20agency%20or%20office%20do%20you%20work%20for%3F%0A%0AWhat%27s%20your%20job%20title%20or%20role%3F%0A%0ATell%20us%20a%20little%20about%20your%20project%20or%20your%20questions%20about%20cloud.gov:%0A%0AIf%20you%27d%20like%20us%20to%20call%20you%2C%20what%27s%20your%20phone%20number%20and%20when%20might%20be%20a%20good%20time%3F%0A)

**Comment by jseppi** [comment]
oooooh, ok

**Comment by wslack** [comment]
@ShannonBad did I assign this to you to create the link or to test it?

**Comment by ShannonBad** [comment]
@wslack I think you wanted to address this in the testing, so we know what we need for the redesign. But it looks like Leah did a lot of content work on this already. Which phase of design of this new contact page you wish to test?

**Comment by wslack** [comment]
What do you mean by "phase of design? I think we want to test a prototype so that we have direction for a final version.

**Comment by ShannonBad** [comment]
@wslack Is there already a prototype for the new contact page or do you need me to make a static mock for testing?

**Comment by wslack** [comment]
Will have to ask in standup; I don't recall.

**Comment by wslack** [comment]
Closing this as we've got other issues that cover this one's goals (#1795, #1761).
