### ISSUE TITLE
create page for updates

### ISSUE THREAD

**Issue by leahbannon** [18F/federalist#1624]
#### Description of feature or bug

As a potential customer, I might be more interested in Federalist if I can easily see it's frequently updated and addressing customer requests/concerns.
As a current customer, I might be interested in following updates to Federalist.

Create v. lightweight blog/feed for updates. Possibly include:
- high level summary of release updates
- new sites added 
- feature sites that have been around for awhile, for ex, if they do a redesign or are interested in writing a little a short feature about their site & experience with Federalist

Example: https://cloud.gov/updates/

#### Definition of done

- [ ] create updates page
- [ ] create several posts ahead of time so you know you'll keep it fresh, update at least once per week

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by wslack** [comment]
Closing - we ran an internal experiment and folks didn't seem to find them useful.
