### ISSUE TITLE
new feature: create test sites, similar to cloud.gov sandbox

### ISSUE THREAD

**Issue by leahbannon** [18F/federalist#1625]
#### Description of feature or bug

As a potential customer, I might be more interested in using Federalist if I can test it out and see how easy it is to use first.

This was a potential recommendation from Trammell's research, but it might require additional feedback from users first.

#### Definition of done

<TODO>

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by jseppi** [comment]
Seems like this can already be done by just launching a new site from a template. Is this more of a presentation/documentation thing during sales?

**Comment by wslack** [comment]
this is about people who haven't spoken to us being able to triy federalist. I think we can make a video maybe?

**Comment by jseppi** [comment]
Ohhhhh, got it. Reducing the friction of trying it out by removing the initial personal contact.

That would be neat, but it would be a large lift since we'd probably want a whole new environment (and stuff like: different bucket, slimmed-down features, automatic wiping, etc.).

**Comment by wslack** [comment]
Right, agreed.

**Comment by wslack** [comment]
@ericronne @thebestsophist can we convert this to developing a user experience for the "get started" screen? (Slide show, video, etc?)

**Comment by thebestsophist** [comment]
Yup! We were thinking along these lines, as well!

**Comment by wslack** [comment]
👍 let's edit it accordingly!

**Comment by wslack** [comment]
(LMK if you want me to do that)
