### ISSUE TITLE
create Footer

### ISSUE THREAD

**Issue by leahbannon** [18F/federalist#1626]
#### Description of feature or bug

We need a footer across the site.

#### Definition of done

Include in footer:
- [x] 18F and GSA logos
- [x] An official site of the U.S. Government
- [x] links to header menu items, including new "contact" page in replace for "get started"
- [ ] Federalist is a product of the General Services Administration. We developed Federalist to help deliver high-quality websites for departments and agencies across the US federal government. Want to learn more about what Federalist can do for your agency? (Contact us.)(link to new contact page)

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by wslack** [comment]
@jseppi WDYT about this as an MVP just so there's contact info on all pages for us?

**Comment by jseppi** [comment]
Seems good to me, and it would be lowish-effort.

**Comment by wslack** [comment]
@line47 I think we said this isn't super high priority but might be good to have on the "examples" page as well and set up as a real footer. Remind me?

**Comment by line47** [comment]
Yeah we talked about setting up a footer at one point in time. This would be relatively easy to knock out, might be good to get something in place before working on the larger redesign @ericronne is working on.

**Comment by ericronne** [comment]
did someone say 'footer'?

![image](https://user-images.githubusercontent.com/9259185/36488571-6490d8ca-16e9-11e8-863a-8cfecf98b825.png)

**Comment by ericronne** [comment]
That's from the upcoming full [landing-page redesign](https://github.com/18F/federalist/issues/1563), but perhaps we can adapt and use with current design. So it would need to be modified to work with the current design. I can do that. Once implemented, we'll have a small jump-start on the new design.

**Comment by ericronne** [comment]
Thoughts on these?

### Desktop
![footer-temp-desktop](https://user-images.githubusercontent.com/9259185/36498180-2b6d8678-1703-11e8-8cb6-75b642e7b8da.png)

### Mobile
![footer-temp-mobile](https://user-images.githubusercontent.com/9259185/36498186-2e7ff224-1703-11e8-9d35-53040e73ef68.png)

**Comment by wslack** [comment]
Those look great to me!

**Comment by wslack** [comment]
@line47 good enough to implement?

**Comment by line47** [comment]
certainly, queue it up!

**Comment by line47** [comment]
I'm having trouble finding a white Federalist logo. 
Is there an SVG hanging around somewhere?

**Comment by jseppi** [comment]
Maybe you could extract just the icon from this SVG: https://github.com/18F/federalist/blob/staging/public/images/logo.svg

**Comment by jseppi** [comment]
or re-color this PNG https://github.com/18F/federalist/blob/staging/public/images/federalist-logo.png

**Comment by line47** [comment]
Thanks @jseppi !

**Comment by wslack** [comment]
we could use a better set of logo files but we don't have anything except for the combined SVG

**Comment by line47** [comment]
Do we want the footer on the public site as well as the logged in version of Federalist?

**WIP footer screenshot**
![screen shot 2018-02-22 at 4 58 17 pm](https://user-images.githubusercontent.com/1449852/36566586-f603c1f6-17f1-11e8-8e51-fddeb2979b8c.png)

**Comment by line47** [comment]
☝️ @ericronne @AvivaOskow - I think we need a mail icon added to the icons folder for that link in the footer.

**Comment by wslack** [comment]
@line47 if not too much of a pain, yes - but we don't need the "example sites/documentation/get started" links - just the section below. If that's annoying, the footer as is is ok.

**Comment by line47** [comment]
@wslack OK, that's no problem and really easy to do 👍 

logged in footer would not have the navigation bar seen above.

![screen shot 2018-02-23 at 9 51 54 am](https://user-images.githubusercontent.com/1449852/36600082-4f0eac6a-187f-11e8-9601-419b80d74f3c.png)

**Comment by wslack** [comment]
👍 sgtm!

**Comment by ericronne** [comment]
Here's the envelope svg on [google drive](https://drive.google.com/file/d/1Fg4UQkAsx2sSe_UPtHezEAwKEAN9z1rp/view?usp=sharing)

I'm inclined to leave the nav on the footer for now, for consistency.

**Comment by line47** [comment]
I also agree with keeping the nav in the footer for consistency

**Comment by wslack** [comment]
I'm ok with that, but the nav changes in the live app. I wouldn't want the nav in the footer to mismatch the header. That's why I wanted to not have it in the MVP - to avoid the extra work of adding in different behavior. 

But if easy to set up, I'm fine with nav in both places.

**Comment by ericronne** [comment]
looks great!
