### ISSUE TITLE
create mailchimp list

### ISSUE THREAD

**Issue by leahbannon** [18F/federalist#1627]
#### Description of feature or bug

Start a mailchimp list. That's nbd now, right?

#### Definition of done

- [ ] Import contacts who have signed up to receive updates.
- [ ] Add link to sign up for updates about Federalist to the Contact page.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by wslack** [comment]
Correct.

**Comment by wslack** [comment]
We can't use mailchimp.
