### ISSUE TITLE
Use consistent placement of component propTypes and defaultProps

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1636]
#### Description of feature or bug

In our React components, we have not been consistent about where we define `Component.propTypes` and `Component.defaultProps`. We should be consistent.

Here are the two patterns we use:

```jsx
// pre-defined at the top of the file
const propTypes = { ... };
const defaultProps = { ... };

const MyComponent = () => ...;

MyComponent.propTypes = propTypes;
MyComponent.defaultProps = defaultProps;
```

```jsx
const MyComponent = () => ...;

// defined "in-line" after the component definition
MyComponent.propTypes = { ... };
MyComponent.defaultProps = { ... };
```

I have a _slight_ preference for the second option, but am definitely flexible.

#### Definition of done

- Style is chosen
- All React component files are consistent in their placement of `propTypes` and `defaultProps`

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by wslack** [comment]
Impact?

**Comment by jseppi** [comment]
Fairly low. This is just a minor maintainability/code quality thing.

**Comment by wslack** [comment]
backlogged

**Comment by ctrimm** [comment]
@wslack - I tackled this one since it was low-hanging fruit. Very straightforward - checkout the PR for more comments.

**Comment by wslack** [comment]
Thank you @ctrimm!

**Comment by wslack** [comment]
And now marked as Done for our sprint review later!
