### ISSUE TITLE
Finish up eslint issues

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1637]
#### Description of feature or bug

We've been steadily cleaning up linting errors in code files as they are touched. We're down to 365 from an initial ~7,000 when we started using the Airbnb eslint config.

We can probably just finish out the remaining issues in a single PR.

#### Definition of done

0 eslint issues reported when running `yarn lint`

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by wslack** [comment]
moving to ready for @jseppi to claim before he offboards! (or someone else)
