### ISSUE TITLE
Scroll to top of page on error

### ISSUE THREAD

**Issue by el-mapache** [18F/federalist#1638]
**Description of feature of bug**

Currently we don't scroll to the top of the page when the API returns errors. We  should look into adding this functionality, particularly on the `site settings` page, which is especially long.

**Definition of done**

`site settings` page scrolls to the top of the screen on error 

_After evaluating, edit this part:_

**Level of effort**

_low_

Implementation outline (if higher than "low" effort):

**Comment by wslack** [comment]
If this is easy, we should just do it and make it a normal behavior.
