### ISSUE TITLE
Look into setting up Federalist AWS console

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#1639]
#### Description of feature or bug

Currently, we are using a shared legacy 18F account for our AWS needs that can't be met by a cloud.gov service. This simplifies access control (because none of us can access it) but complicates management of our SQS queue (because none of us can access it).

#### Definition of done

One of the following is true:

- We have setup an AWS console, defined access controls, and migrated our SQS queue
- We determine that a Federalist AWS console should not be pursued

**Comment by wslack** [comment]
My initial feeling is that we should not pursue if something is offered by cloud.gov or the 18F Infrastructure team.

**Comment by wslack** [comment]
https://github.com/18F/federalist/issues/882 represents the overall need; this represents a particular path. Marking as "low" as well.
