### ISSUE TITLE
Find out if Eric had a style sheet artifact

### ISSUE THREAD

**Issue by ericronne** [18F/federalist#1643]
#### Description of feature or bug

We don't know how to record Eric's style guide output.

#### Definition of done

- [ ] We don't know what Eric meant by this issue and haven't lost any artifact he made into a GitHub thread.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by jseppi** [comment]
👍

**Comment by el-mapache** [comment]
hey @ericronne, can you chime in on this? Is there some artifact we should be archiving, in addition to the previous design files we got from you?

**Comment by ericronne** [comment]
Sorry, i have no recollection of this issue! 
Perhaps @jseppi hacked my account? 😂

**Comment by ericronne** [comment]
You already have all of my files 👍
