### ISSUE TITLE
Create MVP experience of new site creation

### ISSUE THREAD

**Issue by line47** [18F/federalist#1645]
#### Description of feature

When creating a new website - using the new site button help guide the user through the process. 

#### Definition of done

- [ ] When someone has an easy experience in creating their site on federalist from a particular template and using documentation/support to help them build their site.

#### To Do

- [x] Meet with @ShannonBad about new site creation process, take notes on how to improve 
- [x] Meet with @davidewarren about new site creation process, take notes on how to improve
- [x] Meet with @ericronne about new site creation process, take notes on how to improve
- [x] Meet with @AvivaOskow about new site creation process, take notes on how to improve
- [x] Meet with @thebestsophist about new site creation process, take notes on how to improve

**Comment by line47** [comment]
👆 @wslack feel free to add to/edit the main issue

**Comment by wslack** [comment]
made a few edits. We just want an MVP experience for a single template right now, I think.

**Comment by line47** [comment]
Here are the synthesized notes that came from the interviews.

## Before a user has any sites

- Show some explanatory info that prompts the user to create a new site and maybe explains the upcoming process a bit.
- This page could use some basic design the alignment of the text is ragged on the left
- Make it more clear what the next step is, move add site button or add site link down into page

## Add site page

### GitHub Repo section
- Put a link to some Github documentation explaining, what a repo is an any other high level Github info a user might need to know
- Explain what type of repo works/doesn’t  (static/Jekyll/Hugo)

### Templates section
- Increase size of thumbnail
- Make thumbnail clickable to view live demo
- Update the description to be a bulleted list of features or reasons to use a particular template. Most folks thought the sentence of text was too much to read. Get at why a user would want to pick one template over another
- Unclear if the live example is a demo site, example site or what, test different language here 

### Create site form

- Make it clear where the site goes and where is it hosted
- Possibly present the Github user account form element as a statement with opt in to edit rather than a textbox
- Show where the site will be created (like a path or URL)
- Name your site (Explain what this is and how it used?) Can I change it later? This is unclear that it will be the name of your github repo
- Allow user to close site creation form with a close/cancel button

### After creating site on the build history page

The build history is technical and hard to understand for non-technical users. 
Some explaining for first time folks would be beneficial and could go a long way to help orient them to Federalist. 
	
- Show welcome message that congratulated the user
- Show that the build is in progress
- Explain the contents of this page in an informational way for the first time user. Links to documentation on how to edit the site
- Explain what next steps could be
  - Go here to view your preview
  - Go here to start editing your site

[Full interview notes - Google Doc](https://docs.google.com/document/d/17ACpXnfl7FiLVhEodbJkd64yoFoNTX48tJZFkLhkFFc/edit#heading=h.qxiojxpn7dk9)

**Comment by line47** [comment]
@wslack should I create a new issue to track this work separately or just track within this issue?

**Comment by wslack** [comment]
@line47 methinks this issue is fine since I think you plan to ship this sprint.

**Comment by wslack** [comment]
Will to create GDoc for comments

**Comment by wslack** [comment]
Blocked pending Jury Duty.

**Comment by line47** [comment]
Moving to backlog

**Comment by wslack** [comment]
closing for right now - @amirbey you might want to check out the notes for the long term: https://docs.google.com/document/d/17ACpXnfl7FiLVhEodbJkd64yoFoNTX48tJZFkLhkFFc/edit#heading=h.qxiojxpn7dk9
