### ISSUE TITLE
Consolidate SQS instances

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1647]
#### Description of feature or bug

While working though some SQS permissions issues, @erik-burgess identified that there are three SQS instances apparently belonging to Federalist:

- `federalist-builds-cloudgov` in `us-west-2`, used in our `production` space
- `federalist-builds-staging` in `us-east-1`, used in our `staging` space
- `federalist-builds` in `us-east-1`, currently **unused**

It seems likely that `federalist-builds` was intended to be our production instance, but was forgotten in some move.

We can probably swap production over to using that one and have the current prod queue (`federalist-builds-cloudgov`) retired.

#### Definition of done

Depends on what we decide to do.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by erik-burgess** [comment]
For visibility, I've already added the ```sqs:GetQueueAttributes``` permission to the unused ```federalist-builds``` queue.

**Comment by wslack** [comment]
Is `us-west-2` in GovCloud? @erik-burgess do you have any preference where these are?

**Comment by wslack** [comment]
I do want them in the same spot, ideally located alongside other active services (vs being isolated)

**Comment by erik-burgess** [comment]
@wslack All of these are in a standard AWS account, meaning not GovCloud. I have no preference where they are located at this point in time as long as things are documented correctly in the SSP. With one of these being in a different region, it was easy to miss as it wasn't "default." If there's a business justification or technical reason behind that, it's no problem to keep them separated.

**Comment by wslack** [comment]
Ok. I endorse James' suggested change, though we should execute on it with a fallback plan in case something doesn't work as predicted.

**Comment by wslack** [comment]
👍 SGTM

**Comment by erik-burgess** [comment]
Happy to pair any time on this.

**Comment by wslack** [comment]
moved to ready

**Comment by jseppi** [comment]
@jmhooper: want to check my steps above? https://github.com/18F/federalist/issues/1647#issuecomment-367827518

**Comment by jmhooper** [comment]
lgtm :+1:

**Comment by jseppi** [comment]
Update list that I'm working through now:

- [ ] Change the `manifest.yml` for `federalist-builder` in `prod` to point to the new prod SQS url
    - PR: https://github.com/18F/federalist-builder/pull/68
- [ ] Change the `federalist-builder-env` service to contain credentials for the new prod SQS queue
- [ ] Change the related user-provided service variables for the `federalist` app to the new queue address and credentials
- [ ] Redeploy `federalist`
    - doing this first will make sure the new queue starts filling up and the old queue can drain before swapping over `federalist-builder`
- [ ] Redeploy `federalist-builder` after the old queue has drained (ie builds have been completed)
    - the changes won't take effect until it is redeployed, so there shouldn't even be any downtime.

**Comment by jseppi** [comment]
Ran into a snag -- the production deployer account credentials have expired, so I'm getting new ones and will update CircleCI with them.

**Comment by jseppi** [comment]
Also had to update the deployer account credentials in the CircleCI config for `federalist-builder`.

**Comment by jseppi** [comment]
All done! I ran a site build on `federalist.18f.gov` after all the switches and all looks nominal!

**Comment by jseppi** [comment]
After sprint review, we can ask Erik to retire the old production SQS queue.

**Comment by wslack** [comment]
👍

**Comment by wslack** [comment]
@jseppi did we make this ask yet?

**Comment by jseppi** [comment]
Nope, will do now.

**Comment by jseppi** [comment]
https://gsa-tts.slack.com/archives/C039MHHF8/p1521039132000801

**Comment by erik-burgess** [comment]
Unused queue (federalist-builds-cloudgov in us-west-2) has been decommissioned.
