### ISSUE TITLE
Add a redirect to federalist.18f.gov when user visits federalist.fr.cloud.gov

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1650]
#### Description of feature or bug

Something like:

```js
if (window.location.href.indexOf('federalist.fr.cloud.gov') !== -1) {
  window.location = 'https://federalist.18f.gov';
}
```

Would alleviate issues like #1641.

#### Definition of done

`.fr.cloud` hosts redirect to `.18f`.

#### Level of effort - <low/medium/high>

low

#### Implementation outline (if higher than "low" effort):

_N/A_

**Comment by jseppi** [comment]
cc @maya

**Comment by wslack** [comment]
should we ask people to reset their bookmarks?

**Comment by jseppi** [comment]
Just had another idea: We could have our server side app check the hostname and issue a 301 (permanent) redirect to the official url when a user visits the fr one.

**Comment by wslack** [comment]
Cool - as long as the code can be tested there I'm good.

-W
