### ISSUE TITLE
Certain extensions interact oddly with custom config textareas

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1651]
#### Description of feature or bug

<img width="580" alt="screen shot 2018-02-23 at 3 52 49 pm" src="https://user-images.githubusercontent.com/697848/36618679-abaec82e-18b1-11e8-8f8d-755630bbc3a9.png">

#### Definition of done

<TODO>

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by wslack** [comment]
@ShannonBad this was a user report. Do you want to try checking and confirming it as a side effort? (totally ok to pass on it)

**Comment by ShannonBad** [comment]
@wslack I am happy to look at it as long as it's not urgent, as I am trying to prioritizing the user research final document right now.

**Comment by wslack** [comment]
👍 not urgent at all.

**Comment by qmanderson1** [comment]
@wslack What page is this on? I just downloaded Firefox Quantum and would like to see if I can replicate the bug to determine whether or not the issue still exists.

**Comment by qmanderson1** [comment]
It looks like this bug has been fixed. @amirbey will review.

**Comment by amirbey** [comment]
i've been able to recreate this issue .. it req'd that I enable Grammarly extension in Chrome ... it occurs for a split second when initially clicking on the text area

**Comment by wslack** [comment]
Because this is caused by a specific extension, I'm going to deprioritize it until we hear more examples.

**Comment by wslack** [comment]
Done; moved to icebox.

**Comment by wslack** [comment]
Closing; hasn't reoccured.
