### ISSUE TITLE
Write tests for TemplateSite and TemplateSiteList components

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1657]
#### Description of feature or bug

There are none. There should be.

Ref: https://github.com/18F/federalist/pull/1656#issuecomment-368648604

#### Definition of done

Tests exist.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by wslack** [comment]
Will address in time as we look at this.
