### ISSUE TITLE
Create mechanism to send Federalist build results via Slack JSON webhook

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1659]
#### Description of feature or bug

As a Federalist user I would like to receive notifications in Slack when my branch (and other) previews have completed so that I can push an update to the repo, run to my next meeting, and be notified that the build succeeded (or, more importantly, failed) without necessarily being signed into Federalist in a browser. 

#### Definition of done

A webhook package is sent with each completed build with the GitHub username of the committer, the name of the branch, and if the build succeeded. A single webhook address can be set in the "advanced settings" for a site.

_After evaluating, edit this part:_

### Implementation Sketch

- Update Site model to include a webhook URL field
  - Include validation that it is a URL (and https?)
- Update API methods to allow to creating and updating webhook field
- Update build callback to POST data to webhook url if present
  - what exactly should be sent as the payload? Need to investigate
- Update front-end Advanced Settings Form include input for webhook URL and validation

**Comment by wslack** [comment]
Penny for @jmhooper and @jseppi's thoughts.

**Comment by jseppi** [comment]
Updated the LOE and implementation sketch.

I am assuming that for a first round MVP of this we won't have any logging of the webhook success/failure history. Correct, @wslack?

**Comment by wslack** [comment]
Correct.

**Comment by wslack** [comment]
Hmmm, medium effort.....hmmm.

**Comment by jmhooper** [comment]
I agree with medium. I'd expect figuring out how to test this to be the most challenging thing. May need to build a sandbox cloud.gov app or something similar to receive the webhooks.

**Comment by jseppi** [comment]
I think `nock` would work for intercepting the webhook requests during testing, right?

**Comment by wslack** [comment]
why would we need a separate app to test vs an integration in our own Slack for the docs site (or something like that?) Adding a new incoming webhook in Slack is easy.

**Comment by jseppi** [comment]
So this is specifically for Slack? Would be good to update the main issue with that. That should answer my question about what the payload contains.

I think that also means that we need to have an input(s) for the channel name and/or channel id? I haven't worked much with Slack webhooks so I don't know all the details.

ref: https://api.slack.com/incoming-webhooks

**Comment by wslack** [comment]
You set the Channel name in Slack and it gives you the endpoint.

I was hoping the JSON could be agnoistic though.

**Comment by jseppi** [comment]
Slack looks like it expects a specific JSON payload structure (`{ text: 'abc' }`), so we'd need to adhere to that. And if we want links included we have to use their specific markup (`<https://alert-system.com/alerts/1234|Click here>`).

**Comment by wslack** [comment]
ah kk

**Comment by wslack** [comment]
🤔 (not sure if worth prioritizing)

**Comment by jseppi** [comment]
In my opinion we already have pretty decent notifications via the GitHub PR status checks.

**Comment by wslack** [comment]
👂 yep, I've backlogged this until we hear it from other users.

**Comment by wslack** [comment]
Related to #1215

**Comment by wslack** [comment]
In another issue: 

These are the settings in CircleCI's Slack notifications:
>**Fixed/Failed Only:** Only send notifications for builds that fail or fix the tests and the first build on a new branch. Otherwise, send a notification for every build.

The "otherwise" is if this setting is not selected, some people may choose to have notifications for every build, but I wouldn't want this.
