### ISSUE TITLE
Figure out and document how to pull log of user permissions from cf cli

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1660]
#### User Story
As a Federalist developer, it's important for me to be able to pull out a log of user permission changes for compliance reasons.

#### Background

Ref: https://github.com/18F/cg-product/issues/727#issuecomment-287149627

#### Definition of done

- [x]  Simple copy-paste commands using `cf` and `jq` to pull user permission change logs are created and documented.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by wslack** [comment]
➕ that this is in Ready - maybe even the next top priority.

**Comment by jseppi** [comment]
@wslack This seems to work well:

1. In your terminal, make sure you are logged in to the federalist org:

```sh
 cf login --sso -a https://api.fr.cloud.gov -o gsa-18f-federalist
```

2. Run this command:

```sh
SPACE=production GUID=$(cf space --guid $SPACE) EVENTS_Q=type+IN+audit.user.space_d
eveloper_add,audit.user.space_developer_remove,audit.user.space_auditor_add,audit.
user.space_auditor_remove,audit.user.space_manager_add,audit.user.space_manager_re
move cf curl "/v2/spaces/$GUID/events?q=$EVENTS_Q" -X GET | jq -c -r '.resources[]
.entity | [ .timestamp, .actor_name, .type, .actee_name ] | @csv' | sed -e s/\"//g
```

3. At the beginning of that command, you can change where it has `production` to `staging` to get the staging env results if needed.

**Comment by jseppi** [comment]
@wslack: Please move to `Done?` if this works for you, or let me know what else you are looking for if this doesn't work for your needs.

**Comment by wslack** [comment]
didn't work for me

**Comment by wslack** [comment]
Corrected command:

`SPACE=production GUID=$(cf space --guid $SPACE) EVENTS_Q=type+IN+audit.user.space_developer_add,audit.user.space_developer_remove,audit.user.space_auditor_add,audit.user.space_auditor_remove,audit.user.space_manager_add,audit.user.space_manager_remove; cf curl "/v2/spaces/$GUID/events?q=$EVENTS_Q" -X GET | jq -c -r '.resources[].entity | [ .timestamp, .actor_name, .type, .actee_name ] | @csv' | sed -e s/\"//g`

I will run this around 4:45 each day to find out how far back it looks.

**Comment by wslack** [comment]
Got one results today.

**Comment by wslack** [comment]
https://cloud.gov/docs/apps/events/

 There is now more documentation about these events that we should look at to make sure that our commands are formed appropriately.

**Comment by amirbey** [comment]
As details here: https://cloud.gov/docs/compliance/auditing-activity/

1) Set organization GUID
export GUID=$(cf org YOUR-ORG --guid)

2a) For response in JSON:
cf curl "/v2/events?q=type+IN+audit.user.space_developer_add,audit.user.space_developer_remove,audit.user.space_auditor_add,audit.user.space_auditor_remove,audit.user.space_manager_add,audit.user.space_manager_remove&q=organization_guid:$GUID"

2a) For response in CSV:
cf curl "/v2/events?q=type+IN+audit.user.space_developer_add,audit.user.space_developer_remove,audit.user.space_auditor_add,audit.user.space_auditor_remove,audit.user.space_manager_add,audit.user.space_manager_remove&q=organization_guid:$GUID" | jq -c -r '.resources[].entity | [ .timestamp, .actor, .type, .metadata.request.name ] | @csv' | sed -e s/\"//g

**Comment by amirbey** [comment]
Attached txt of commands b/c copy and paste from the comment is not working. possible weird characters are being copied from web comment[https://app.zenhub.com/files/36463352/7373d450-41ee-418c-92bb-29712d3b9f29/download](https://app.zenhub.com/files/36463352/7373d450-41ee-418c-92bb-29712d3b9f29/download)

**Comment by wslack** [comment]
That link doesn't work for me?

-W

**Comment by wslack** [comment]
bingo, working now!
