### ISSUE TITLE
Iterate on the structure of the public website

### ISSUE THREAD

**Issue by ericronne** [18F/federalist#1661]
#### Description of feature or bug

Consider ways to organize various proposed content changes and additions

#### Definition of done

Will and the team agree on a rough sitemap, to serve as a guide for the next version of the public / marketing site.

**Comment by ericronne** [comment]
Check out the **[mural](https://app.mural.ly/t/gsa6/m/gsa6/1519835839589/1be43108db39f31a70854a9cb515091aed990312)**

**Comment by wslack** [comment]
moved to in progress since this is in progress. :)

**Comment by ericronne** [comment]
WIP structure (noted in #1668) …

- Landing page
  - Product
    - Overiew
    - How it works
    - Features
    - Templates
    - Fact sheets (downloads)
  - Case studies
  - Getting started / Walthrough / ???
  - User manual (links to documentation)
  - Contact us
  - Log in

**Comment by thebestsophist** [comment]
@wslack are these the right projects to highlight?
- [College Scorecard](https://collegescorecard.ed.gov/)—Education
- [vote.gov](https://vote.gov)
- [Privacy and Civil Liberties Oversight Board](https://www.pclob.gov/)
- [Extractive Industries revenue data](https://revenuedata.doi.gov/)
- [DHS Binding Operational Directives](https://cyber.dhs.gov/bod/)

I think 5 is a good number, but we discussed adding one or two more might be okay. Any others to add to the list? (Tempted to add 18f to say “yes, we eat our own food”.)

**Comment by thebestsophist** [comment]
Documenting a path not taken:

When thinking about what to rename “example sites”, thought about using “Success stories” instead of “case studies”. Decided that it the language sounded too much like a sales pitch. “Case studies” fit the tone better. I think this was the right decision given the comments we got in user research https://github.com/18f/federalist/issues/1667#issuecomment-371917703

**Comment by thebestsophist** [comment]
Let’s rename “Getting started / Walkthrough” to “Using Federalist”

This page/section will include:
- the demo for deploying your first site
- list of templates/themes
- migration guide
- future content that is created specifically for helping onboard folks into federalist, and demoing features.

**Comment by wslack** [comment]
@thebestsophist where are we going to document the "final draft" of a new IA? In a working Google Doc or here?

**Comment by thebestsophist** [comment]
Dropped a [copy the Mural](https://app.mural.ly/t/gsa6/m/gsa6/1522093516875/88001f9a465e1c1a57860657f3cbf6cb4708a7a4) that @ericronne and I worked on into Federalist’s mural space, and am updating the site structure with content notes for each section.

**Comment by annahsebok** [comment]
Per discussion re: our [content approach](https://docs.google.com/document/d/1V1RPQ3fFdclCDE2ZCm6Htt25DLcPLJ5mbE01UqnnvnI/edit#), the work here has informed the IA that we're now testing over in #1723. This issue can now be closed.
