### ISSUE TITLE
Evaluate how to make it easier to recover from a bad commit on a Federalist site

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1663]
#### Description of feature or bug

When a user commits private information onto GitHub/Federalist, the clean up process can be painful.

It would be neat if someone could push a button to roll a branch back to a past commit, delete the commits before that past commit on the branch, and wipe/rebuild that branch in S3.

#### Definition of done

We have a clear direction on how to implement an MVP of this.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by jseppi** [comment]
https://github.com/18F/federalist/issues/1629 (ability to delete a specific branch's files from S3) might help with this

**Comment by wslack** [comment]
agreed! I put this in icebox for now, though, given the likely lift to implement.

**Comment by el-mapache** [comment]
I'm not certain this is entirely possible in a 1-button approach, the process for pruning sensitive information involves a number of command line calls, one of which removes references to the sensitive files from the user's local copy of the repository.

Also, we wouldn't be able to account for branches that might have been based off commits with the sensitive info. If those branches are merged (as opposed to rebased), they could reintroduce the old commit history.

**Comment by wslack** [comment]
👍 icebox'd

**Comment by wslack** [comment]
Closing as all users that have committed bad content have had the ability to remove something from their Github history. https://github.com/18F/federalist/issues/1629 is what we'll do first, and that's a low as well.
