### ISSUE TITLE
Document and schedule deployer service account key rotation activities

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1666]
#### Description of feature or bug

cloud.gov service account credentials [expire every 90 days](https://cloud.gov/docs/services/cloud-gov-service-account/#handling-expired-passwords). We should have a documented process and some kind of reminder (a calendar event perhaps) for rotating our service account credentials within that window so we're not caught by surprise.

For both `production` and `staging`, we have two service account services:
- `federalist-[production|staging]-deployer-circle`
    - used for automated deploys from CircleCI
    - service credentials are saved in the CircleCI environment variables [settings page](https://circleci.com/gh/18F/federalist/edit#env-vars)
- `federalist-[production|staging]-deployer-build`
    - used by `federalist-builder` to launch `federalist-garden-build-containers`
    - service credentials are saved in the `federalist-deploy-user` user-provided service

#### Definition of done

- Documentation of process exists
- Recurring reminder exists

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by wslack** [comment]
@jseppi want to book a half hour for you to explain this to me or @davidewarren and then we write up a PR for the docs?

**Comment by jseppi** [comment]
sure, that works!

**Comment by amirbey** [comment]
this process is already documented here: https://federalist-docs.18f.gov/pages/for-federalist-developers/cloud-gov-setup/
