### ISSUE TITLE
Creation of a final user research document for testing the homepage

### ISSUE THREAD

**Issue by ShannonBad** [18F/federalist#1667]
#### Description of feature or bug
This document is the final user testing results research report, for testing the Federalist homepage. 
Related to user testing done on: #1561 

<TODO>

#### Definition of done

This stuff needs to get done:
- [x] organize the raw data
- [x] create takeaways from the raw data
- [x] create a glanceable overview from data
- [x] organize a document-style report

<TODO>

#### Level of effort

 Medium

#### Implementation outline (if higher than "low" effort):
see above checklist.

<TODO>

**Comment by wslack** [comment]
@ShannonBad moved to `ready` for you to put in `in progress` when you start!

**Comment by ShannonBad** [comment]
Link to the Mural.ly document to organize the raw data: https://app.mural.ly/t/federalistuserresearch0048/m/federalistuserresearch0048/1520551244743/820adf00a477778dfce8a4d8c8d4d31b34c3ccd7

**Comment by ShannonBad** [comment]
These are a few screenshots of the Mural.ly document with some key take aways
<img width="1075" alt="screen shot 2018-03-09 at 11 15 13 am" src="https://user-images.githubusercontent.com/35078464/37225339-30561148-238b-11e8-975c-f7bf3aaa1471.png">

<img width="1023" alt="screen shot 2018-03-09 at 11 15 55 am" src="https://user-images.githubusercontent.com/35078464/37225366-4704cca4-238b-11e8-83d2-2e1a42046ff4.png">

**Comment by wslack** [comment]
Thanks for posting the updates! I look forward to the progress!

**Comment by ShannonBad** [comment]
I am still working on finalizing/cleaning this research document, but here is the link. 

Federalist User Research Interview Results, in February – March 2018
https://docs.google.com/document/d/1kYePO7bb28s4YGZRJVb7J4OLYmBck-ERjTWo9bfKb_M/edit#heading=h.45uaz3fzd94t

In response to this document I will work on making a list (in a new document) regarding future research and design strategy, and an updated research plan with priorities, and considering the rough time frames/resources for each task.

**Comment by wslack** [comment]
@ShannonBad when is it ready for review? Now or should we wait? I can't tell from your comment.

**Comment by ShannonBad** [comment]
@wslack it is not ready for review, I am still working on it.

**Comment by wslack** [comment]
Cool - thank you for clarifying!

**Comment by wslack** [comment]
@ShannonBad status check - should we meet about this?

**Comment by ShannonBad** [comment]
@wslack I am wrapping this up and should be done this week.

**Comment by wslack** [comment]
Status check!

**Comment by ShannonBad** [comment]
@wslack I turned this into both Ben and Laura to get feedback/critique. Hoping to hear back from both of them in a few days.
