### ISSUE TITLE
Consolidate SQS queue env vars/credentials into single user-provided service (per app env)

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1669]
#### Description of feature or bug

In each app environment (`production` and `staging`), we currently have the SQS queue settings/credentials repeated in multiple places. For `production`, it looks like this (`staging` is the same with slightly different names):

- `federalist-ew-sqs-user` - contains AWS SQS keys and is used by `federalist-builder` app
- `federalist-env` - contains AWS SQS keys and queue URL, used by `federalist` app
- `manifest.yml` for `federalist-builder`, contains SQS queue URL, used by `federalist-builder` app

There's no reason to have this information spread out/repeated, so we should consolidate it all into a single user-provided service that is shared by `federalist` and `federalist-builder`.

#### Definition of done

- [x] a single user-provided service hosts SQS credentials, URL, and region environment variables
- [x] `federalist-builder` is modified to use the shared user-provided service
- [x] `federalist` app is modified to use the shared user-provided service
- [x] verify `federalist` and `federalist-builder` apps are using env variablized user-provided service names
- [x] verify APP_ENV env var is set for federalist-builder and federalist-builder-staging
- [x] update federalist-builder manifests to user sqs service
- [x] update federalists manifests to user sqs service
- [x] update federalist-builder to use sqs service for credentials
- [ ] deploy federalist-builder staging -> production
- [ ] old service (federalist-ew-sqs-user) are  unbound & removed in development
- [ ] old services (federalist-ew-sqs-user) are unbound & removed in production
- [ ] remove unused keys from federalst-*environment*-env service (keys: FEDERALIST_AWS_BUILD_KEY, FEDERALIST_AWS_BUILD_SECRET, FEDERALIST_BUILD_CALLBACK, FEDERALIST_BUILD_TOKEN, FEDERALIST_SQS_QUEUE)
- [x] docs are updated to reflect the new setup

_After evaluating, edit this part:_

#### Level of effort - <low/medium/high>

_medium_

#### Implementation outline (if higher than "low" effort):

Not complicated, but there are a number of things to check and check twice!

**Comment by wslack** [comment]
@jseppi we can split up permissions so that access to the production credentials is segmented with this approach, correct?

**Comment by wslack** [comment]
Assuming yes, I'm putting this in `ready`; I think its important to do to help out future staff who will be less familiar with the backend.

**Comment by jseppi** [comment]
Yup, it'll be segmented by cloud.gov space (`production` and `staging`).

**Comment by wslack** [comment]
Can we add documenting the setup to this issue (which I can help with) and prioritize it?

**Comment by jseppi** [comment]
Yup, definitely. We already have some docs on the current setup, so this change would simplify those as well.

**Comment by wslack** [comment]
Session tomorrow

**Comment by wslack** [comment]
We worked on this yesterday and deployed a new service successfully to staging!

**Comment by amirbey** [comment]
@el-mapache - shouldn't we variablize the service name (env)? https://github.com/18F/federalist-builder/pull/72/files

**Comment by el-mapache** [comment]
Sure, we can have a constant somewhere, not sure if there is a file to handle that already. That PR was pretty much just a test to make sure the new service was working, so I'd expect we'll make changes as we go!
