### ISSUE TITLE
Add some way to track/analyze if build containers are backed up

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1675]
#### Description of feature or bug

We have not identified a metric to know if our build containers or the build scheduler have builds backing up. We should identify and implement an appropriate metric and alerting for this.

#### Definition of done

- [x] When the queue gets above 10 messages, New Relic sends an alert.

_After evaluating, edit this part:_

**Comment by jseppi** [comment]
We might be able to heuristically determine a threshold for the `ApproximateNumberOfMessages` that gets reported by the federalist-builder `/healthcheck` endpoint to compare against for this (ie, alert if it's `> 5`), but I'm not totally sure.

**Comment by wslack** [comment]
Did we say earlier that this is tough because the various instances might report different numbers?

**Comment by jseppi** [comment]
Not our container instances, but just the way the SQS queue works. The queue doesn't have a method for reporting the exact number of messages in its instances.
