### ISSUE TITLE
Revise and reorganize federalist.18f.gov (sales content)

### ISSUE THREAD

**Issue by thebestsophist** [18F/federalist#1679]
Federalist.18f.gov serves as the primary sales and marketing for Federalist. We need to make content easier for less experienced technologists to understanding, reorganize the [content structure](https://app.mural.ly/t/gsa6/m/gsa6/1519835839589/1be43108db39f31a70854a9cb515091aed990312) for the site, refine navigation, and add some new content. All is outlined in subsequent issues.

**Comment by annahsebok** [comment]
Updated issue to reflect our new [content approach](https://docs.google.com/document/d/1V1RPQ3fFdclCDE2ZCm6Htt25DLcPLJ5mbE01UqnnvnI/edit#).

**Comment by wslack** [comment]
These issues have all been given labels, so I'm closing down this epic.
