### ISSUE TITLE
User's with mixed-case GitHub usernames can't add a repo they own

### ISSUE THREAD

**Issue by el-mapache** [18F/federalist#1680]
#### Description of feature or bug

If a user has a name with mixed casing, e.g. `TestUser`, and they attempt to add a repo to Federalist from their own GitHub account, Federalist will fail to find the user. This leads to Federalist thinking the user is an organization. When it fails to find that 'org' in its whitelist of valid orgs, an error is reported to the user.

#### Definition of done

- [x] A user with a mixed-case name should be able to add a site to Federalist
- [x] Ensure the fix doesn't break the site in other ways
 
#### Level of effort - <low/medium/high>
For some reason, we set the owner and repo name of a repository to lower case before querying GitHub or our database to check if the site or user exists. I think this is incorrect, since a user can sign up for our site with a mixed-case username, and users can create repos on GitHub with mixed-case too.

The fix is therefore to either remove the `toLowerCase` call from the owner string in the `SiteCreator` class OR force usernames to be stored all lowercase in our database.

#### Implementation outline (if higher than "low" effort):

lowish

**Comment by el-mapache** [comment]
@wslack I removed the offending code and all the tests pass, I suppose we just want to test this on staging for a bit and see what happens?

**Comment by el-mapache** [comment]
While storing future usernames in all lower case will prevent this from happening to _new_ users, it won't fix anything for users whose names are already stored mixed-case in the database.

Is there any harm in simply not enforcing case for usernames? We've always allowed for mixed-case in usernames, this just hasn't come up before.

**Comment by wslack** [comment]
I think we forced lowercase in order to keep github from sending failure responses when there was a case mismatch in URLs being added. @jmhooper do you remember more?

**Comment by el-mapache** [comment]
So we should definitely be down-casing all usernames when we add them to the DB, since obviously the case doesn't matter when visiting a URL.

Maybe it's worth it to go back and write a migration to force all usernames we currently have to lower case.

**Comment by el-mapache** [comment]
Conversely, if we expect people to be copy-pasting URLs of their repos directly from GitHub, the casing of a `username` will be properly preserved, e.g. uppercase characters will be present `https://github.com/ADBTest/TestRepo`. In that case having mixed-case user names isn't strictly an issue.

**Comment by el-mapache** [comment]
As per our discussion today, we'll address this by forcing all future `username` columns in the `User` model to be downcased, and by writing a migration script to convert all the existing mixed-case `username`s to be downcased.
