### ISSUE TITLE
Re-open Mark Trammell research

### ISSUE THREAD

**Issue by ShannonBad** [18F/federalist#1682]
#### Description of feature or bug
Re-open the Mark Trammell research with Will, Shannon & an 18F UX designer, to look at larger design issues. 

Prior to meeting, Shannon will review data to make sure this is still relevant and usable for future work. Also consider the possibility of creating an archive of research?

<TODO>

#### Definition of done
After meeting occurs and past research is organized in to a single location, then issue is done.
<TODO>

#### Level of effort
low

**Comment by wslack** [comment]
figuring out who will be the UXer now.

**Comment by wslack** [comment]
Will know tomorrow
