### ISSUE TITLE
Implement mobile view of landing page

### ISSUE THREAD

**Issue by ericronne** [18F/federalist#1684]
#### Description of feature or bug

Implement mobile view of [landing page](https://github.com/18F/federalist/issues/1563)

**Comment by ericronne** [comment]
![landing-mobile](https://user-images.githubusercontent.com/9259185/37297828-abfb0ca0-25ec-11e8-8770-9bb9b0d4d453.png)

**Comment by ericronne** [comment]
Menu, expanded …

![mobile-menu](https://user-images.githubusercontent.com/9259185/37297844-baf37260-25ec-11e8-868b-8927de2fd397.png)

**Comment by ericronne** [comment]
here!

![mobile-menu](https://user-images.githubusercontent.com/9259185/37298162-99cadb5e-25ed-11e8-9d04-c439f1f789f2.png)

**Comment by el-mapache** [comment]
PR here: https://github.com/18F/federalist/pull/1686
