### ISSUE TITLE
Iterate on content for landing-page

### ISSUE THREAD

**Issue by ericronne** [18F/federalist#1685]
#### Description of feature or bug

~Much of the content on the [revised landing page](https://github.com/18F/federalist/issues/1563) is placeholder. We've paid close attention to the design, but not as much to the words (and some supporting imagery) as of yet. Let's address in earnest!~ Content on the landing page has been refined and there's more work to be done!

(See image below)

#### Implementation outline (if higher than "low" effort):

- [x] Clarify primary audience
- [ ] Evaluate and remove/pivot/edit content so that it's geared towards primary audience, eliminating content that less technical users consider to be "hard"
- [x] Change `Documentation` navigation title
- [x] Change `Get started` navigation title
- [ ] Add useful links back into page copy, linking to docs site and other valuable artifacts/sites/documentation.

Other steps are TBD as outputs of #1723. We can open new issues for those as we learn more.

**Comment by ericronne** [comment]
![home-content-needs](https://user-images.githubusercontent.com/9259185/37306008-5ca1177c-2604-11e8-8c28-64e5b1c9da1c.png)

**Comment by ericronne** [comment]
cc @el-mapache

**Comment by ericronne** [comment]
cc @ShannonBad

**Comment by wslack** [comment]
I was hoping we could edit this in the PR of the actual site content...thoughts @thebestsophist?

**Comment by wslack** [comment]
@annahsebok to also review the PR from this AM where I flirted with some content changes. in #1743

**Comment by annahsebok** [comment]
👍 on that PR @wslack (with the exception of one small suggested change). Did you want me to take a look at this as a whole again once those changes are merged?

**Comment by annahsebok** [comment]
@wslack are these stats still right? 
![screen shot 2018-04-18 at 10 48 09 am](https://user-images.githubusercontent.com/6728448/38946209-01e89bca-42f6-11e8-99a6-0a80f7f44e40.png)
I know we're up to 121 live sites. Let me know if any of the other numbers need changing.

**Comment by annahsebok** [comment]
As I've been working on #1757, I've been thinking about whether or not it really makes sense to put a glossary on federalist.18f.gov. Given that it's more of a sales site, I'm thinking we should remove any of the "hard" terms from the homepage (via another PR) and make it even simpler, with the terms less experienced users struggle with being mentioned in a second or third layer of the site (and on the docs site). I'm going to gut check this approach with some other content folks today, and will follow up on any additional changes here after that convo.

**Comment by annahsebok** [comment]
Issue has been updated to reflect our new [content approach](https://docs.google.com/document/d/1V1RPQ3fFdclCDE2ZCm6Htt25DLcPLJ5mbE01UqnnvnI/edit#)

**Comment by annahsebok** [comment]
Per conversations with @wslack, our core audience for federalist.18f.gov is Chris the Communicator (persona link to come soon once I find it). This person is responsible for web content, but lacks knowledge and experience with compliance and technical details.

**Comment by ShannonBad** [comment]
@wslack @annahsebok why are we using the older personas?

**Comment by wslack** [comment]
@annahsebok to clean up

**Comment by wslack** [comment]
I moved todos per @annahsebok to #1794.
