### ISSUE TITLE
Add New Relic access to onboarding / offboarding of new devs

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#1687]
#### Description of feature or bug

New devs (especially leads) should have New Relic access to the Federalist account (https://rpm.newrelic.com/accounts/1078427):
- Either the project lead or the dev should request access to the account in `#admins-newrelic` (after they've created a NR login using their GSA email address).
- The new person should be added to email alerts in New Relic.

Devs who have been completely relieved of duties should have their access removed, and be removed from any email alerting policies within the New Relic account.

#### Definition of done

Onboarding/offboarding docs are updated

_After evaluating, edit this part:_

#### Level of effort - low

**Comment by wslack** [comment]
Updated https://docs.google.com/document/d/1FM1rwE17gpDnADRLwTapfKz4Z-IXfkjoAWu6A_Rp3-Q/edit, please review.

**Comment by jseppi** [comment]
👍 Looks good!
