### ISSUE TITLE
Figure out best content editor

### ISSUE THREAD

**Issue by dhcole** [18F/federalist#17]
Prose will let us get up and running quickly, but it's probably larger than we need for our purposes. That may be fine, or it may introduce complexity. As we have time, we should figure out what we need from an editor and figure out the best way forward.

Also to consider:
- via @cmc333333, https://github.com/madebymany/sir-trevor-js
- via @maya, https://github.com/chimecms/chime

**Comment by dhcole** [comment]
Also cc @leahbannon who has experience with Prose

**Comment by dhcole** [comment]
Here's an overview of Prose with a properly-configured metadata editor: https://github.com/18F/military-onesource-federalist/pull/1

**Comment by leahbannon** [comment]
I oppose use of Prose because of one significant bug that hasn't been addressed (otherwise I think it's great). If you are not authenticated in GitHub (like most prose users, probably), Prose lets you make edits to a document, click save and name the changes, and then hangs when you click submit. The changes are then effectively useless.

**Comment by dhcole** [comment]
Thanks @leahbannon. The good news is that we have contributor access to Prose :) I'll look into fixing this when we get there. Let me know if there are other issues that should be addressed.

Also in this use case, all users would have to authenticate before accessing Prose (since it would be embedded in Federal).

**Comment by bradnunnally** [comment]
The Sir Trevor content editor, on the surface, looks very simple and streamlined. Assuming that the sites that would be using the Federalist platform don't get too complex or deep, I could see that framework working really well.

It felt a lot like Tumblr when I was playing around with it, which is good for a variety of reasons. It would be interesting to run a prototype of this by some content editors/contributors that would be using Federalist in the future to see how it meets their needs.

**Comment by dhcole** [comment]
- https://github.com/jakiestfu/Medium.js

**Comment by dhcole** [comment]
Closing this research task as work is underway in #90
