### ISSUE TITLE
Error with ProseMirror

### ISSUE THREAD

**Issue by dhcole** [18F/federalist#170]
@jeremiak check out this page: https://federalist.18f.gov/#edit/us-federal-sbst/federalist-modern-team-template/master/pages/2015-annual-report.md

Wondering if it's because of unstandard markdown, such as `View 2015 Annual Report - PDF{: .usa-button }`?

What do you think? Should we make buttons includes or just normal html, which should be supported in a markdown document?

**Comment by jeremiak** [comment]
Huge bummer.

Apparently ProseMirror doesn't seem to like any HTML at all: https://federalist.18f.gov/#edit/jeremiak/federalist-modern-team-template/master/pages/2015-annual-report.md

I'll take a look at the ProseMirror docs and see if I just missed a config

**Comment by dhcole** [comment]
Yes HTML should be valid in a markdown document. Is there a sanitation
filter or something?

**Comment by jeremiak** [comment]
It looks like the markdown parser that ProseMirror uses is called [markdown-it](https://markdown-it.github.io/markdown-it/) and it has the `html` option set to `false` by default. The docs say this is to prevent XSS attacks.

I'm going to see if I can pass along the config options from ProseMirror

**Comment by jeremiak** [comment]
It looks like the offending block of code is the `<br>` at the [end of 2015-annual-report.md](https://github.com/us-federal-sbst/federalist-modern-team-template/blame/master/pages/2015-annual-report.md#L31). I have no idea why this tag is breaking ProseMirror, so I'll submit a bug on that repo.

In the meantime, we should probably just pull those `<br>`s out of the pages. Are they there for a reason?

**Comment by dhcole** [comment]
Just some extra spacing. Should be done with CSS anyway. We can remove them. 

Also, how about wrapping prosemirror in a try...catch and rendering codemirror on error? This would give us some level of functionality for any text file.

**Comment by dhcole** [comment]
error is here: https://github.com/ProseMirror/prosemirror/blob/master/src/convert/from_markdown.js#L8

possibly relevant (no <br>): https://github.com/markdown-it/markdown-it/blob/255d62d39122694872ddce840e2141379ac3deca/lib/common/html_blocks.js#L7

**Comment by dhcole** [comment]
Tried a few things... looks like any html will crash ProseMirror. Maybe we just need to have the expectation that md files contain only MD and liquid tags (so you can use html as includes).
