### ISSUE TITLE
Personas for user research

### ISSUE THREAD

**Issue by ShannonBad** [18F/federalist#1711]
#### Description of feature or bug
Create personas 3-4.
<TODO>

#### Definition of done
3-4 done personas include goals, users’ needs, experiences, and behaviors.
<TODO>

#### Level of effort - <low/medium/high>
medium

#### Implementation outline:
Depending on how much of the personas need to be created, defines the level of effort. Start with reviewing and possibly reuse some of the existing personas from earlier research (from persona versions in 2016 and 2017), sketch details for the current personas.
<TODO>

**Comment by wslack** [comment]
What's the benefit of additional personas beyond the two that we have? (realizing those two are probably incomplete)

**Comment by ShannonBad** [comment]
@wslack @bpdesigns personas help to focus decisions surrounding website design/components by adding a layer of real-world considerations to the discussion. We have the personas from 2016, we need to make sure this is all still usable information (since the product changed since then. It's possible the old personas may just need some refining). We use personas, so we can go forward in other aspects of the design process.

**Comment by wslack** [comment]
Ok cool! My hope is that the 2017 fall personas are enough but I look forward to finding out for sure!

**Comment by ShannonBad** [comment]
Four personas were updated and sent to Ben and Laura for feedback/critique.

**Comment by ShannonBad** [comment]
Link to four new personas: https://drive.google.com/open?id=1qyoqGu6wqXQWAyMRUmifb8BVswCyT3aU


![small personas](https://user-images.githubusercontent.com/35078464/38452377-3cb5303a-39f8-11e8-843d-8d20d75549f2.jpg)
