### ISSUE TITLE
Implement case studies page

### ISSUE THREAD

**Issue by el-mapache** [18F/federalist#1712]
#### Description of feature or bug

Using Sketch files as a reference, create mobile and desktop views for the new Case Studies page

#### Definition of done

- [x] New controller route to handle case studies URL, with accompanying test(s)
- [x] Mobile view matches designs as closely as possible
- [x] Desktop view matches designs as closely as possible
- [x] At least an MVP of all content and images necessary for page to be ready for user consumption

#### Level of effort - <low/medium/high>
_medium_

#### Implementation outline (if higher than "low" effort):

* Create new controller route
* Create new njk view
* Create new sass files as needed.
* Add additional CSS, changes should hopeful be additive

**Comment by wslack** [comment]
@el-mapache this is pending mobile designs correct?

**Comment by el-mapache** [comment]
Yep! I think we are still missing some of the content for it as well, although I'm not sure

**Comment by el-mapache** [comment]
@wslack where can I find the content for this page? Are we planning on using the existing sites on `examples sites` or do we have new ones?

**Comment by wslack** [comment]
@davidewarren add to https://github.com/18F/federalist/pull/1737/files#diff-94e400de2ee94bc6085747e511168c2bR36

**Comment by wslack** [comment]
Two initial sites: Performance.gov Cio.gov
