### ISSUE TITLE
Determine brand guidance for content and design

### ISSUE THREAD

**Issue by bpdesigns** [18F/federalist#1714]
#### Description of feature or bug

Identify need for design principles, brand and voice

#### Definition of done

- [ ] Find any work done so far on this 
- [ ] Find gaps
- [ ] Assign next steps 

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by wslack** [comment]
@kategarklavs can we merge this with the other issue?

**Comment by kategarklavs** [comment]
@wslack Hey! Just took a look at these two issues, and they can be merged. (Output of workshop will be content principles.) 

Also - I'm happy to work with visual designers on drafting vis design standards (or reviewing existing standards), but my focus for this week will be content principles.

**Comment by wslack** [comment]
Please close this when everything is migrated to #1727!

**Comment by kategarklavs** [comment]
Just made a few additional notes to #1727 — closing now 😎
