### ISSUE TITLE
Review collected research for relevance 

### ISSUE THREAD

**Issue by bpdesigns** [18F/federalist#1715]
#### Description of feature or bug

Determine what content is still relevant from collected UX research.
- what research was on previous versions Federalist that no longer applies?
- what was started that needs to be finished

#### Definition of done

Tag research and list action items for next steps to complete them

#### Implementation outline (if higher than "low" effort):

- [ ] Determine what needs to be completed

**Comment by bpdesigns** [comment]
@ShannonBad thoughts on this? am I missing anything? 

I know you are looking at previous personas in another issue.

**Comment by ShannonBad** [comment]
@bpdesigns yes, this is great. I was thinking to approaching this issue as a, "as-needed" review - by each research topic, since there is a lot of past research/strategy. But I welcome other suggestions too!

**Comment by bpdesigns** [comment]
@ShannonBad great point. I think in general we should come to these materials as needed
