### ISSUE TITLE
Landscape analysis

### ISSUE THREAD

**Issue by bpdesigns** [18F/federalist#1716]
#### Description of feature or bug

What can we learn from GSA products selling to other agencies?
What can we learn from commercial web publishing services?

#### Definition of done

- [ ] Make a list of examples that could be incorporated into ux and, or design strategy

_After evaluating, edit this part:_

**Comment by wslack** [comment]
Done in https://docs.google.com/spreadsheets/d/1TekHre9fs1BTG4FV0ix_qunll2R45-mjcFOAhR_Jhy4/edit#gid=1989085826
