### ISSUE TITLE
Ecosystem of people related to Federalist 

### ISSUE THREAD

**Issue by bpdesigns** [18F/federalist#1719]
#### Description of feature or bug

Identify all the people and roles connected to Federalist. 

This work will lead to clarity on who the most important personas are and support the development of journey maps and eventual service blueprint

#### Definition of done

A spreadsheet or diagram 

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by bpdesigns** [comment]
@ShannonBad for all these issue that I assign to you, please edit if needed and reach out for clarity or support.

**Comment by ShannonBad** [comment]
@bpdesigns ok, thank you!

**Comment by ShannonBad** [comment]
Holding off on the creation of this final document until the research related to Test Information Architecture (IA) #1723  is done, since they are related and it can inform the ecosystem document to be fully more developed.

**Comment by eddietejeda** [comment]
We can revisit this later. Will close for now.
