### ISSUE TITLE
Prep for Testing Information Architecture 

### ISSUE THREAD

**Issue by bpdesigns** [18F/federalist#1720]
#### Description of feature or bug

Determine if there is a better way to organize content on Federalist. 

#### Definition of done

Testing Script and artifacts to test 

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] Review past IA work on Federalist 
- [ ] Reviewing Feb/March Usability testing 
- [ ] Create 2-3 possible architecture concepts to test

**Comment by wslack** [comment]
@bpdesigns per the meeting yesterday, we may want to hold on this. I think we said @thebestsophist would be iterating on the IA in https://github.com/18F/federalist/issues/1661 - should we hold this issue until that iteration is set and then test based on it?

**Comment by bpdesigns** [comment]
@wslack agree! Lets hold for now.
