### ISSUE TITLE
Make a list of Features to be tested 

### ISSUE THREAD

**Issue by bpdesigns** [18F/federalist#1721]
#### Description of feature or bug

Make a list of Features to be tested. Federalist hasn't done user testing on many parts of the product. We should make a dent in that.

#### Definition of done

Spreadsheet with Feature descriptions, priority ranking and rational for rank

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] Collect features
- [ ] Decide how to rank them 
- [ ] Determine their rank

**Comment by wslack** [comment]
Moving to Ready, but @bpdesigns and @qmanderson1 - would be good to specify what the purpose of the issue is. Something like "Federalist hasn't done user testing on many parts of the product. We should make a dent in that."

**Comment by bpdesigns** [comment]
@wslack sounds good. Will address today

**Comment by bpdesigns** [comment]
@ShannonBad I'll send you the spreadsheet we're working on. Please add anything you've already uncovered.

**Comment by bpdesigns** [comment]
spreadsheet to collect information: https://docs.google.com/spreadsheets/d/1x91T57FNiBcbtWZQxjClRPV6L4fTdEgdSasFarm2KMI/edit#gid=0

**Comment by wslack** [comment]
Paused for now as is; spreadsheet represents progress to date.

**Comment by wslack** [comment]
Might be stuck until we have people to do this.

**Comment by wslack** [comment]
Closing: step 1 for UX folks will be watching a use and ID'ing problem spots, not making lists of features
