### ISSUE TITLE
Create a research pipeline 

### ISSUE THREAD

**Issue by bpdesigns** [18F/federalist#1722]
#### Description of feature or bug

Find users to test Federalist Features with

#### Definition of done

Spreadsheet with contact info and category of user types 

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] Define user categories for testing
- [ ] determine outreach methods
- [ ] reach out!

**Comment by wslack** [comment]
Moved to Ready! This one we can move on immediately.

**Comment by bpdesigns** [comment]
@ShannonBad will need your input here as it relates to #1711 and #1719

**Comment by bpdesigns** [comment]
spreadsheet to collect information: https://docs.google.com/spreadsheets/d/1cVk6RuFG6K8jWrYPYqE5s0gVlTEmVL-Cz0iIeNmk3hA/edit#gid=0
