### ISSUE TITLE
Record Federalist's Design Philosophy

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1727]
#### Description of feature or bug

Federalist has a lot of people rotating on and off the project right now.

While we have a [program README](https://docs.google.com/document/d/17vcjJ0PB4yxCUIDoKh8TP3mYK5ArhF90SymGrITxEx0/edit#), naming Federalist's priorities, we don't have design principles.

We do have:
 - [Content Rules](https://docs.google.com/document/d/1bqRoi97-G-ixoaJU2pB1K-tNJT57_h4L5twE3kkKer4/edit#)
 - Identified [content values from a content review](https://docs.google.com/document/d/10dl_3c6uTolRYtmMBhMJ7tnKVoXwvnAhTx93uLq2uSY/edit#bookmark=id.ri8yk7v8q1l5)
 - A lot of opinions from Will scattered across e-mails and Slack

#### Definition of done

 - [x] We have recorded Federalist's design principles 

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

 - [x] Formalize content voice principles (drawing on existing documentation) 
 - [x] We articulate the components of a design philosophy
 - [x] Workshop led by @kategarklavs 
 - [x] Synthesis of workshop
 - [x] Components (design principles) drafted
 - [x] Components (design principles) reviewed
 - [x] Principles shared with team/made accessible to future team contributors
 - [x] Next steps identified and assigned

**Comment by wslack** [comment]
@kategarklavs based on some other work with design folks, I'd like to ask for more clarity about the expected output.

The output here has been discussed as 

- design principles
- content principles
- Brand
- Voice
- Design Philosophy

Correct to say the aimed output here is "content principles" not "design principles" - or do they overlap?  

https://content-guide.18f.gov/content-principles/ doesn't seem to describe the work effort here; I guess I'm unclear about the kind of output you expect from this effort and if it will be useful for new UXers on Federalist.

**Comment by kategarklavs** [comment]
@wslack Hey! Apologies for any confusion — I was envisioning this work as creating a set of design principles and a set of content principles (which are pretty similar to design principles). As far as other branding work goes, I'd be happy to get started on this, though I'm not totally clear on what's meant by "brand."

In addition, as time allows, I could use existing documentation to start a project-specific content style guide (unless you all already have one — I didn't see one in Drive). Voice-related guidelines would be a part of this guide.

How does this sound?

**Comment by kategarklavs** [comment]
(Update - in looking at the Content review doc, it seems like you all are using the 18F Content Style Guide + the Content Rules doc as your style guide, so I could add voice guidance to the Content Rules doc)

**Comment by kategarklavs** [comment]
Update! Drawing on existing documentation, I created a Voice section in the Content Rules doc:

https://docs.google.com/document/d/1bqRoi97-G-ixoaJU2pB1K-tNJT57_h4L5twE3kkKer4/edit#

This includes a definition of Federalist's voice, an example of content (taken from the homepage) that exemplifies the brand voice, and tips for maintaining a consistent voice across the site.

Our affinity-mapping workshop (which will aid in the creation of design principles) is scheduled for Wednesday. Prior to that, I can get to work drafting content principles & populating the Mural with concepts I glean from existing documentation.

**Comment by kategarklavs** [comment]
Hey all! Here's a site that features examples of lots of different design principles (for reference): https://www.designprinciplesftw.com/

**Comment by kategarklavs** [comment]
Update for today! Shared (with @wslack) draft 1.5 of design principles. Will shared feedback, which I've incorporated. 

Also - just raised (via Slack) the prospect of the team adopting 18F's content principles. Federalist uses the 18F Content Guide as its content guide, and those principles are 1) part of the guide; 2) applicable to Federalist.

**Comment by kategarklavs** [comment]
Here's a link to the design principles doc: https://docs.google.com/document/d/1svZ9ksiMDG5uluIhLEncNr0C3mjuv9WwDbppgdvg3PI/edit?usp=sharing

**Comment by kategarklavs** [comment]
To wrap up with this issue, here are the next steps I've identified:

- [ ] Continue collecting feedback from the team on the design principles (it's a good idea to timebox this, at least for the first "official" draft of the principles).
- [ ] Implement any changes suggested by the team.
- [ ] Publish the principles. This can be as straightforward as adding them to existing design documentation, or it might involve publishing them on the Federalist site. There's no right way to publish/publicize the principles; the most important thing is that team members have access to them. 

If you all have any questions, please let me know! And feel free to re-open this issue, if necessary. It's been fun working with you all 😌

**Comment by wslack** [comment]
Reopening so we can close during retro (after opening the successor issue), but thank you @kategarklavs!
