### ISSUE TITLE
User Research for New Federalist Site

### ISSUE THREAD

**Issue by qmanderson1** [18F/federalist#1729]
#### Description of feature or bug

Test new site with research participants

#### Definition of done

Answer the following: 

Do people understand what federalist is while looking at this homepage? 
Can potential clients easily access information?
Which (if any) sections of the site do people find confusing?
Which (if any) features/information is missing from the site?
Are the calls to action clear?
Is there information that should be removed from the site?

_After evaluating, edit this part:_

#### Level of effort - <low/medium/high>

Medium

#### Implementation outline (if higher than "low" effort):

<[https://app.zenhub.com/files/36463352/08bbd10a-190c-43aa-8c7c-e6e42c04abd4/download](https://app.zenhub.com/files/36463352/08bbd10a-190c-43aa-8c7c-e6e42c04abd4/download)TODO>

**Comment by wslack** [comment]
@wslack to write up a close out.

**Comment by wslack** [comment]
We did a one day research effort!

**Comment by wslack** [comment]
Until I post the output

**Comment by wslack** [comment]
Notes from the research here: https://docs.google.com/spreadsheets/d/1PlpWgrODHPnM-NLa4BQ1l-NqjiozpRQjfAXzh573hAA/edit#gid=0

**Comment by wslack** [comment]
And posted in the summary. This is now Done!
