### ISSUE TITLE
Create mobile designs for case studies page

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1735]
#### Description of feature or bug

https://github.com/18F/federalist/issues/1567 did not include creation of mobile designs. We need those before implementation of the new case studies page.

#### Definition of done

- [ ] A front end developer has everything the need to implement the new case studies page

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by ericronne** [comment]
Here's a very rough stub-out of how the mobile layout might work. The [updated sketch file](https://drive.google.com/open?id=1yFiKCUoLYlbbgYj6b6lHe4n1ziyakavF) is on the drive.

![case-studies-mobile-wip](https://user-images.githubusercontent.com/9259185/37991396-a4066786-31ce-11e8-8827-1afca08940f8.png)

Please hit me up on slack with any questions, thx!

**Comment by wslack** [comment]
THANK YOU @ericronne!!!

**Comment by wslack** [comment]
we think this is enough to move on, for now.

**Comment by wslack** [comment]
@austinhernandez is checking this out for two hours at most

**Comment by austinhernandez** [comment]
Suggested mockup here:
![case-studies-mobile-ah](https://user-images.githubusercontent.com/23194720/38058662-a60feee2-32b1-11e8-8d69-97bc18c5bdc9.png)

Annotated:
![case-studies-mobile-ah-annotated](https://user-images.githubusercontent.com/23194720/38058831-38a3bd42-32b2-11e8-854d-da813744c1c8.png)


Confirmed with @ericronne that the button was removed from the new design in lieu of a contact us button at the bottom of a page. May need testing or data to back up if this form was ever used.
<img width="1033" alt="screen shot 2018-03-28 at 5 53 26 pm" src="https://user-images.githubusercontent.com/23194720/38058603-75b9b2fa-32b1-11e8-93c7-53313b430d77.png">

Also echoing comment that this mobile layout needs content and testing and to refer to the landing-page mobile layout for spacing and other style points.

Sketch file:
[federalist-sub-page--case-studies-v2.sketch.zip](https://github.com/18F/federalist/files/1857936/federalist-sub-page--case-studies-v2.sketch.zip)

**Comment by wslack** [comment]
TY TY TY

@el-mapache I think you're all set now?

**Comment by el-mapache** [comment]
@wslack Yep I can get started on this!
