### ISSUE TITLE
Record additional insights from design principles affinity-mapping session 

### ISSUE THREAD

**Issue by kategarklavs** [18F/federalist#1736]
#### Description of feature or bug

Our affinity-mapping session to generate design principles yielded many other valuable insights that didn't make it into the principles doc. I'd like to document these ideas in a separate document, which the Federalist team will be able to draw on as they create new marketing collateral (and, possibly, additional site copy). 

- [x] Additional insights are documented/made available to the Federalist team.

**Comment by kategarklavs** [comment]
OK! I've wrapped up this document, which contains additional insights from the affinity-mapping session: https://docs.google.com/document/d/1cfz89Ju9gSUnIsUTlbLfW8y3j4QHY2KbagMVfIn35ig/edit?usp=sharing

(Let me know if you have any trouble accessing it — it should be open (edit rights) to anyone within GSA, but I'm happy to share it w/individual people, if folks can't get into the doc).

@wslack - I'll leave this issue open so you can include it in the next retro, but feel free to close it whenever!

**Comment by wslack** [comment]
Done. Thank you @kategarklavs (you have been offboarded btw, so LMK if you keep getting invites to anything you shouldn't).

**Comment by kategarklavs** [comment]
@wslack Hey! I saw that I still had standup invites for next week (I deleted those manually). If you could check to make sure I've been removed from the standup invite, I'd be much obliged :)
