### ISSUE TITLE
Cordelia / Jamie Transition

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1738]
#### Description of feature or bug

@thebestsophist will hand off content work to @jamiealbrecht                        

#### Definition of done

- [x] There's a meeting 
- [x] There's a doc/record of the handoff materials

_After evaluating, edit this part:_

#### Level of effort - low

**Comment by thebestsophist** [comment]
[Handoff notes](https://docs.google.com/document/d/1nIDTDZ5TtPCLFkdBSpBuvYm4t-_WPiRLjy-p8zmZZv8/edit?ouid=101012440890849683885&usp=docs_home&ths=true) 🔒
