### ISSUE TITLE
Create Federalist talking points

### ISSUE THREAD

**Issue by annahsebok** [18F/federalist#1746]
#### Description of feature or bug

Create master list of talking points, prioritizing the most valuable one's for @wslack's FCW Event Solutions on Strategies for Managing the Cloud

#### Definition of done

Anna and Will are both  👍 on the talking points.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):
- [x] Review existing talking points
- [x] Pull in additional points
- [x] Organize by focus area
- [x] Prioritize points for cloud management strategies presentation
- [x] Share with @wslack 
- [x] Make them more plain language

**Comment by annahsebok** [comment]
Doc with talking points is [here](https://docs.google.com/document/d/1O_4zLgSlQDneaCu6qoh2lYdITa3wVSN3gWrbpn_QX20/edit).

**Comment by annahsebok** [comment]
@wslack I've flushed out a broader range of talking points in the doc linked in this issue and prioritized what I think could be most valuable on the first page for the even you're speaking at. Take a look and we can chat through in a bit!

**Comment by annahsebok** [comment]
@wslack Thanks for your time this morning! I'd consider this done. Please take a look and confirm when you can. 

The doc again, just in case: https://docs.google.com/document/d/1O_4zLgSlQDneaCu6qoh2lYdITa3wVSN3gWrbpn_QX20/edit#

**Comment by wslack** [comment]
Sent back to @annahsebok with edits and comments!

**Comment by annahsebok** [comment]
Thanks for your edits and comments @wslack! I've addressed the areas you explicitly flagged as need changes/more info and am looking for a little bit of clarity on your first comment (dropped my questions in the thread). Will circle back on this once you've had the chance to respond. Thanks!

**Comment by annahsebok** [comment]
Hey @wslack — these are as finished now as they can be within the google doc (with the exception of a few things we'll discuss in our talk/type session tomorrow). 

You mentioned on your last full pass something about making the language plainer — I made a number of changes and I think we're there. If there are specific words or phrases that stick out to you as challenging during your final review, please explicitly flag them and I can take another look. 

I want to add that because these talking points are currently for multiple audiences and different layers on the site, I think it's okay to leave some of the more technically nuanced information how it is. We'll dig into defining key terms in #1757. Also, given that we don't know exactly where this content is going to live on the site quite yet, I don't have the context I need to refine much further. Once we have a plan for implementing the new IA and corresponding content, we can refine this work based on who the primary audience is for each part of the site and where information is going in the site's structure.

**Comment by wslack** [comment]
Endorsed! I think this can be moved to "Done?"!

**Comment by annahsebok** [comment]
@wslack once I'm done editing the few things I added after our talk/type session this morning, I'll move it over!
