### ISSUE TITLE
Review Federalist backlog with fresh set of eyes

### ISSUE THREAD

**Issue by adborden** [18F/federalist#1748]
#### Description of feature or bug

Review the Federalist backlog with fresh eyes, considering Federalist's three main priorities of Availability, Sales and Growth, and Customer Service.

This is not an audit, and should be constrained to a few hours of effort.

#### Definition of done

- [ ] Suggest any issues that could be prioritized or de-prioritized.
- [ ] Flag any issues that are unclear or missing Definition of Done.

_After evaluating, edit this part:_

#### Level of effort - low

**Comment by wslack** [comment]
moved!

**Comment by adborden** [comment]
FYI, there are a lot of older issues without a Definition of Done. I would just make sure that when moving issues to Ready that the issues are groomed and have a valid Definition of Done.

**Comment by wslack** [comment]
Labels: Will to talk to @karareinsel about this.

**Comment by adborden** [comment]
Reviewed this with @wslack and @AlanAtlas
