### ISSUE TITLE
Document how Federalist would be deployed on AWS so BizDev can speak to it

### ISSUE THREAD

**Issue by adborden** [18F/federalist#1749]
#### Description of feature or bug

Occasionally BizDev gets questions about Federalist's previous life on AWS, before it was moved to cloud.gov. The documentation around this is missing, and would be helpful to have some of those details captured.

#### Definition of done

- [x] Document describing how Federalist was deployed on AWS before cloud.gov.
- [x] Include technical details as necessary, they don't have to be a set of instructions on how to set it up.

_After evaluating, edit this part:_

#### Level of effort - low

**Note**: This information is already documented, specific pages are noted in comments below.

**Comment by annahsebok** [comment]
@adborden let me know if/when you're ready for a plain language review or copyedit and I'm happy to take a look.

**Comment by wslack** [comment]
Used ECS instead of cloud.gov

**Comment by el-mapache** [comment]
I've looked into this and the good news is that Federalist operated pretty much the same way it does now! The biggest difference is that Federalist used to leverage Amazon ECS to spin up a container and build the sites, but we now use cloud.gov to host the `federalist-garden-build` docker container and scripts.

Info was sourced from commit `4f7d52d3592cd3d32940d978bc1af271c358445e` in `federalist-docs`. The relevant page is [here](https://github.com/18F/federalist-docs/blob/4f7d52d3592cd3d32940d978bc1af271c358445e/pages/how-federalist-works.md). You can also refer to the [the old system architecture diagram](https://github.com/18F/federalist-docs/blob/4f7d52d3592cd3d32940d978bc1af271c358445e/uploads/federalist-system-architecture.pdf)
