### ISSUE TITLE
Incorporate additional template information into docs site

### ISSUE THREAD

**Issue by annahsebok** [18F/federalist#1751]
#### Description of feature or bug

The [existing templates page of Federalist](https://federalist-docs.18f.gov/pages/using-federalist/templates/) is limited in the information it provides. Incorporating additional information about how template customization works would be helpful to include to offer additional context to users.

#### Definition of done

Details related to templates in the [federalist talking points](https://docs.google.com/document/d/1O_4zLgSlQDneaCu6qoh2lYdITa3wVSN3gWrbpn_QX20/edit#heading=h.sx367cr6bpux) have been incorporated into the Federalist docs page specific to templates.

_After evaluating, edit this part:_

#### Level of effort - low

**Comment by wslack** [comment]
moved up to "ready" - we should certainly have some info public about this, I think

**Comment by annahsebok** [comment]
Submitted https://github.com/18F/federalist-docs/pull/226, awaiting review/merge, then this will be done.

**Comment by annahsebok** [comment]
PR merged!
