### ISSUE TITLE
Create plan to clean up front end design of federalist-docs.18f.gov

### ISSUE THREAD

**Issue by davidewarren** [18F/federalist#1752]
#### Description of feature or bug

The Federalist documentation site - https://federalist-docs.18f.gov/ needs to be updated and has the follow issues: 

- site styling doesn't match the main Federalist
- The site could make better use of the USDWS template
- Navigation at bottom of the screen is awkward 
 
#### Definition of done

- [ ] Path forward for Federalist Docs site created 
- [ ] Issues created for implementing new plan

#### Level of effort - <low/medium/high>
Low

**Comment by adborden** [comment]
@el-mapache in your opinion, is federalist-docs and federalist UIs related enough that pulling out the federalist styles into an npm module would be helpful? Not sure where the sales site is hosted (part of federalist now?) but if we were creating a third microsite then this starts to look really attractive.

**Comment by adborden** [comment]
I'll have to take a look at how we override USWDS, but that's pretty common so I don't expect it to be an issue.

**Comment by eddietejeda** [comment]
We've redone the federalist-docs page.
