### ISSUE TITLE
User and marketing research: create plan to find out what people need to know to be convinced to learn more about federalist 

### ISSUE THREAD

**Issue by jamiealbrecht** [18F/federalist#1753]
#### Description of feature or bug

We have some questions about what people want and need to know about federalist to be convinced to learn more, become a partner, etc. Relevant to issues #1380 #1602 (incorporating ITIF report and landing stats).

#### Definition of done
Have a plan to conduct research

_After evaluating, edit this part:_

#### Level of effort - <low/medium/high>

medium

**Comment by eddietejeda** [comment]
This work has been replaced by this issue: https://github.com/18F/federalist-team/issues/24
