### ISSUE TITLE
pages-redirects: upgrade circleci from v1 to v2

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#1754]
translate the circleci.yaml to the v2 standard for circle
#### Description of feature or bug

<TODO>

#### Definition of done
working ./.circleci/config.yml file that runs pages-redirects test and builds and deploys successfullly

#### Level of effort - <low/medium/high>
Medium

**Comment by wslack** [comment]
Closed as duplicate of https://github.com/18F/pages-redirects/issues/98
