### ISSUE TITLE
vote.gov Case Study

### ISSUE THREAD

**Issue by annahsebok** [18F/federalist#1756]
#### Description of feature or bug

Write up case study of vote.gov.

#### Definition of done

Two page vote.gov case study is written and edited.

_After evaluating, edit this part:_

#### Level of effort - <low/medium/high>

medium

#### Implementation outline (if higher than "low" effort):

-check out EITI example
-talk to vote.gov team
-write draft
-ask for feedback

**Comment by annahsebok** [comment]
@jamiealbrecht FYI, I created this issue. Not sure if it should be assigned to you or me. :)

**Comment by annahsebok** [comment]
We got a recommendation to nix long-form case studies. @wslack is still thinking about whether or not we want to kill this, but it's deprioritized for now.

**Comment by annahsebok** [comment]
I recommend we close this issue in favor of https://github.com/18F/federalist/issues/1885, where all example sites implementation is now outlined and informed by our card sort study and [newest information architecture](https://app.mural.co/t/gsa6/m/gsa6/1522093516875/88001f9a465e1c1a57860657f3cbf6cb4708a7a4).

**Comment by wslack** [comment]
done!
