### ISSUE TITLE
Create glossary

### ISSUE THREAD

**Issue by annahsebok** [18F/federalist#1757]
#### Description of feature or bug

We learned [during research](https://docs.google.com/document/d/1kYePO7bb28s4YGZRJVb7J4OLYmBck-ERjTWo9bfKb_M/edit#) that some users are overwhelmed by the following terms due to their lack of knowledge or technical expertise:

- GitHub 
- advanced user
- Jekyll
- FedRAMP

I hypothesize that creating an easy-to-use glossary would make these terms (and others, like `static site`) less intimidating for users when they see them, making them less likely to run away and not pursue Federalist. fec.gov has a glossary that has been tested with users that we could fork in development of this feature. 

#### Definition of done

A user of federalist.18f.gov can navigate to a Federalist glossary from the home page.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [x] Create googledoc with glossary list @annahsebok 
- [x] Create JSON version of glossary
- [x] Add glossary HTML to Federalist — follow fec.gov implementation
- [x] Add glossary CSS to Federalist
- [x] Create a version of the glossary code that includes all dependencies for use in static stites
- [x] Add JS glossary config

**Comment by annahsebok** [comment]
If you're 👍 on prioritizing this @wslack, I can get to work on implementation step 1.

**Comment by annahsebok** [comment]
I've started dumping terms from our talking points doc into [this doc](https://docs.google.com/document/d/1bXFrUgA6m5p_uuBigM7Fu-csVdjlL5NjywoMapQgvUw/edit) (but haven't been defining them since this issue isn't prioritized yet).

**Comment by wslack** [comment]
I feel like we should verify that people we can get a glossary working on the homepage before doing too much work on content - to evaluate the effort to put that live.

**Comment by annahsebok** [comment]
Makes sense to me!

**Comment by annahsebok** [comment]
@el-mapache want to update the original issue with implementation steps (and effort if I'm off base with medium on your end of things).

**Comment by annahsebok** [comment]
@adborden I'd love your feedback on [the glossary definitions](https://docs.google.com/document/d/1bXFrUgA6m5p_uuBigM7Fu-csVdjlL5NjywoMapQgvUw/edit) if you've got some time today.

**Comment by annahsebok** [comment]
Thanks @wslack! Reviewed, accepted, and made some small modifications. We should be good to move on this once @commit-dkp has had the chance to review the item(s) you pinged him on.

**Comment by annahsebok** [comment]
Per [this comment](https://github.com/18F/federalist/issues/1685#issuecomment-382764521) on #1685, I'm thinking about simplifying the language on the federalist.18f.gov homepage so that we don't need a glossary — having a glossary on a sales-oriented site is feeling weird to me. We shouldn't have a language barrier on a site that's predominantly for sales.

That said, I think users could still benefit from a glossary on the docs site and am gut-checking that approach with some folks today. @el-mapache let's still pair on creating the JSON file today since you're rolling off soon, and then we can follow up later today or tomorrow about where the glossary code should live.

**Comment by adborden** [comment]
Looks great! I added a few comments.

**Comment by jmhooper** [comment]
@annahsebok: I just went through it. I only had a couple comments.

**Comment by annahsebok** [comment]
Thanks @jmhooper! Made some edits in response to your comments as well as @adborden's. Can y'all take another quick look?

**Comment by annahsebok** [comment]
We're moving the glossary files over to the docs site per our new [content approach](https://docs.google.com/document/d/1V1RPQ3fFdclCDE2ZCm6Htt25DLcPLJ5mbE01UqnnvnI/edit#), which means it's lower priority (in comparison to sales site issues). Will come back to this once we've cleared some of our sales site priorities! Moving this back into the backlog for now.

**Comment by annahsebok** [comment]
This is done for now. This MVP of the glossary was based on terms present on federalist.18f.gov, which are all also present on federalist-docs.18f.gov...but there are definitely others that haven't been grabbed just yet. Something for future iterations! Will create a new issue.
