### ISSUE TITLE
Create mechanism for onboarding Federalist team members to research outputs

### ISSUE THREAD

**Issue by annahsgraves** [18F/federalist#1758]
#### Description of feature or bug

There is currently no way for new or existing team members to review the current state of UX and research outputs for Federalist. 

#### Definition of done

We've created a mechanism for team members to review existing research findings and posture.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

To be added once the team has discussed an approach.

**Comment by wslack** [comment]
Task is to audit https://docs.google.com/document/d/17vcjJ0PB4yxCUIDoKh8TP3mYK5ArhF90SymGrITxEx0/edit# and add more links in that doc to the research.

**Comment by annahsebok** [comment]
In addition to the Spring 2018 findings that I've already linked there, I've suggested we also add the [fall 2018](https://docs.google.com/document/d/1BHJpid-5Q2X1o3hM-Y2qLF1AjxDmnvvoJ9i2Z8r9zgU/edit#heading=h.8y3d6ipwxte) and we should definitely add any of @ShannonBad's additional work once it's done.
