### ISSUE TITLE
Multiple Sites are actually the same site

### ISSUE THREAD

**Issue by gbinal** [18F/federalist#176]
I created a new site using the 'microsite template'.  I then created another two sites, again using the 'microsite template`.   

![screenshot 2015-09-17 at 12 43 32 pm](https://cloud.githubusercontent.com/assets/633088/9939780/1ae3d36e-5d3a-11e5-83e2-4e28a81700ad.png)

They all three actually appear to be the same site.  When I click 'View', I see the same URL.  When I edit a page in one, it's edited in all three.  

Sorry if I'm missing something, but it doesn't seem that I can create and manage 2 sites using that template.  This isn't surprising given #138, but it's problematic that it looks like it worked (see screenshot), when it doesn't.

**Comment by dhcole** [comment]
:+1: good call. The front-end needs to restrict adding a template that already exists until we figure out a way around #138
