### ISSUE TITLE
Research Google Forms API

### ISSUE THREAD

**Issue by el-mapache** [18F/federalist#1762]
#### Investigate Google Forms API + Federalist integration

To improve the customer on-boarding experience, look into using Google Forms API to submit customer inquiries, rather than redirecting user to google form. 

This may require work post-MVP phase in terms of designing UX for the new form.

#### Definition of done

- [x] Research Google Form API

#### Level of effort - <low/medium/high>

Low

**Comment by el-mapache** [comment]
Unfortunately, there is no REST API for interacting with Google Forms. There is an apps script API that I'm going to look into calling. I'm unsure at this point if this functionality only allows for decorating and existing form, not submitting one programatically.

**Comment by wslack** [comment]
> It would probably be quicker to either add a leads table to our existing database,

the hard part about this: we would be storing PII. I wonder if we should just drop the form and have an e-mail address only.

**Comment by wslack** [comment]
And thank you for the detailed investigation @el-mapache! I feel like your findings would be a great blog post or something for #mvb.

**Comment by wslack** [comment]
e-mails have names in them enough times that they count as well. If we have a system storing e-mail addresses, we are managing PII. :\

**Comment by el-mapache** [comment]
One alternative we might consider is just embedding the form in the federalist website, and showing/hiding it with the button. That could potentially alleviate the weirdness of redirecting to the  google docs URL.

**Comment by wslack** [comment]
Ohhhh - like in an iFrame?
