### ISSUE TITLE
Resolve FedRAMP Issue

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1766]
#### Description of feature or bug

https://github.com/GSA/fedramp-gov/issues/73#

#### Definition of done

https://github.com/GSA/fedramp-gov/issues/73 resolution

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by adborden** [comment]
I think we're all set. I submitted a PR https://github.com/GSA/fedramp-gov/pull/116 and am just waiting for them to review/merge.

**Comment by wslack** [comment]
👍 closed their issue.
