### ISSUE TITLE
Glossary implementation MVP on Federalist support site

### ISSUE THREAD

**Issue by el-mapache** [18F/federalist#1768]
#### Description of feature or bug

Glossary Implementation MVP

#### Definition of done

- [x] Add glossary HTML to Federalist — follow fec.gov implementation
- [x] Add glossary CSS to Federalist
- [x] Create a version of the glossary code that includes all dependencies for use in static stites
- [x] Add JS glossary config
- [x] Placement of glossary decided
- [ ] Using the list of words and locations of those generated as a part of https://github.com/18F/federalist/issues/1799, go through and wrap each of those words with the appropriate html.

For example:
```
<span data-term="ATO" class="term">ATO</span>
```

The values for  the`data-term` property can be found in `glossary.js`, in the `definitions` variable.

#### Implementation outline (if higher than "low" effort):

See Definition of Done section

**Comment by el-mapache** [comment]
It may be that this initial work is done, and we can remove the last bullet point in the `Definition of Done`section and resolve this part of the issue

**Comment by annahsebok** [comment]
With regards to placement, I suggest that it align with the page header so that it's immediately visible and easy to access (like on fec.gov). Looks like that's where you have it in #1767, so we should be good there I think. I'm finishing up #1757 today — will ping you when I'm ready to create the JSON version @el-mapache!

**Comment by annahsebok** [comment]
@el-mapache Alrighty — can you move this over to the docs site? We're not ready to launch it quite yet (and I'll be bugging you again when we are), but that's where it should live now.

**Comment by el-mapache** [comment]
@annahsebok Yes! I'll do that tomorrow am

**Comment by el-mapache** [comment]
PR and code moved to the docs site — WIP / evaluation PR [here](https://github.com/18F/federalist-docs/pull/236)!

**Comment by annahsebok** [comment]
Made a small edit — I suggest this work be on hold until https://github.com/18f/federalist-docs/issues/212 is completed (which will ultimately inform which additional words should be captured in the glossary).

**Comment by wslack** [comment]
Already ranked higher on backlog so this is fine!
