### ISSUE TITLE
Design Philosophy Successor Issue

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1769]
#### Definition of done

- [ ] Continue collecting feedback from the team on the [design principles](https://docs.google.com/document/d/1svZ9ksiMDG5uluIhLEncNr0C3mjuv9WwDbppgdvg3PI/edit?ts=5abd5836) (it's a good idea to timebox this, at least for the first "official" draft of the principles).

- [ ] Implement any changes suggested by the team.

- [ ] Publish the principles. This can be as straightforward as adding them to existing design documentation, or it might involve publishing them on the Federalist site. There's no right way to publish/publicize the principles; the most important thing is that team members have access to them.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by eddietejeda** [comment]
@amirahaziz check out the document linked.

**Comment by Bryanthales** [comment]
These are just a reference and read/review card.
