### ISSUE TITLE
Coordination for product development lifecycle

### ISSUE THREAD

**Issue by adborden** [18F/federalist#1770]
#### Description of feature or bug

From retro on 4/17/18, we discussed the following points of concern/caution. Creating this issue as a placeholder for followup.
- Not a lot of coordinated work, ideally design/development happens close together so you can work together to resolve issues instead of throw things over the wall.
- How do we ensure our customers see (know about) the benefits of our template improvements 
- Coordination seems limited. Would be really nice to have a product person to manage things

Can we get more support from the Product Chapter, even if it is to just give us a starting point?

#### Definition of done

<TODO>

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by adborden** [comment]
@wslack, hope I captured this right.

**Comment by wslack** [comment]
I think this addresses the points of concern. I think the definition of done is:

- [ ] We have an established process for building and releasing with different levels of UX support, but that does not wholly exempt user testing.

sound right?
