### ISSUE TITLE
Usability testing for new Basic Report uswds-jekyll based template

### ISSUE THREAD

**Issue by adborden** [18F/federalist#1774]
#### Description of feature or bug

We updated the Basic Report template to a new style of template https://github.com/18F/federalist/pull/1731. This uses the [uswds-jekyll](https://github.com/18F/uswds-jekyll) theme. We want to understand if this new template approach is meeting the needs of users, providing a simpler experience for low-tech users.

We think this boils down to a question of documentation. Once their new site is created, does the user understand what to do in order to:

- Customize the site with their agency/organization's name
- Add new content or pages.

#### Definition of done

- [x] Lightweight research plan is created.
- [x] Usability test is performed.
- [ ] Issues are created for follow up work.

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by adborden** [comment]
@vz3 and I walked through the experience and [recorded the observations and discussion](https://drive.google.com/open?id=1yad0tZGM-SJjEFRM2w4bq2-BNYdt9onr).

**Comment by wslack** [comment]
@annahsebok to watch as well!

**Comment by annahsebok** [comment]
assigning myself to this so I remember to watch it :)

**Comment by adborden** [comment]
@vz3 is working on these design recommendations which should be implemented before doing any usability testing. We really want to put forth our "best guest" for the users before testing it, otherwise we'll end up with a test that highlights what we already know. We might want to create a new issue to implement these rec's and move this issue to backlog.

https://docs.google.com/document/d/1mf2SJNU5GZqgA6v9w7cLRkvb1NtXQenvCOPIac_-JXU/edit#heading=h.6ez2j7n37g5n

**Comment by annahsebok** [comment]
@wslack @ShannonBad and I are transitioning this into issues in ~2 weeks. Moving this to `Blocked` until then.
