### ISSUE TITLE
Create a "quick start" guide for the Basic Report uswds-jekyll based template

### ISSUE THREAD

**Issue by adborden** [18F/federalist#1775]
#### Description of feature or bug

In order to understand if this new style of template is working for users we need focused documentation on how customers can get started with the new template. This also keeps the documentation that we need to test very focused, avoiding having to write and content edit all the uswds-jekyll documentation.

#### Definition of done

- [x] Guide covers how to add your agency/organization's contact info to the site.
- [x] Guide covers how to add or edit content.
- [x] Is reviewed by a content specialist.
- [x] Quick start guide is part of the template README.

**Comment by wslack** [comment]
@annahsebok what do you think about looking at this?

**Comment by annahsebok** [comment]
Happy to review when the quick start guide is ready! Please point me to it when it is.

**Comment by annahsebok** [comment]
Also @adborden if it will be helpful for you to talk at my while I type and then I refine structure and content from there, I'm happy to do that.

**Comment by adborden** [comment]
I wrote this somewhat generically and it outlines some of the advanced topics as placeholders for how the quickstart would link out to advanced customization.

https://docs.google.com/document/d/1CN-kbnS7oiK-m6RZS9h50bqPNXt-xb0zGin0knha-6o/edit#

I think for this issue, I would take the quickstart part and move it into the README.

**Comment by annahsebok** [comment]
Thanks @adborden! I'll take a look.

**Comment by annahsebok** [comment]
Apologies for the delay on this! I just finished my review. I've made a number of copy edits and flagged a few questions as well. Happy to chat if it's useful @adborden, or we can continue to work async.

**Comment by adborden** [comment]
Update: this is starting to look really good! It's feeling less like a README and more like a guide, so I moved it into the `federalist-docs` site to see how it would feel.

[Getting started](https://federalist-proxy.app.cloud.gov/preview/18f/federalist-docs/adb-quickstart/pages/using-federalist/getting-started/)

[Customizing your site](https://federalist-proxy.app.cloud.gov/preview/18f/federalist-docs/adb-quickstart/pages/using-federalist/customization/)

**Comment by wslack** [comment]
Oh neat! Should we wait for Anna to return to check this out or do you want feedback now so we can merge earlier?

**Comment by annahsebok** [comment]
@adborden Did you want me to take a look at this again?

**Comment by wslack** [comment]
@adborden why is this blocked? Shouldn't we move on it?

**Comment by wslack** [comment]
I wonder if the name of this issue should also be changed....

**Comment by adborden** [comment]
Yeah, I think this has changed a bit. It's really about a "getting started" guide for new Federalist users, and then a "Quick Start" in the README to remind you how to get started if you've already done it before. Here's an example [README](https://github.com/adborden/federalist-basic-report-template/blob/adb-quickstart/README.md) that would appear in the basic report template.

There's still some loose ends to wrap up, but it's been so long I have to read through all of this to remember what's left.

**Comment by wslack** [comment]
Merged the PR. Eddie should decide if we should reorganize the content so that the menu is less bloated, but this is good to move to "Done?" for now!
