### ISSUE TITLE
Create a new Jekyll gem-based theme and template for the Basic Report

### ISSUE THREAD

**Issue by adborden** [18F/federalist#1781]
#### User Story
As a new Federalist user, I want to be able to use the basic report template.

#### Background

Based on the [template recommendations](https://docs.google.com/document/d/1WSwpiw44DAfHOSh3uyQlY8VybaN4shUYYAW6NLpLnl4/edit#) we should create a gem-based theme and template for the Basic Report Federalist site.

#### Definition of done

- [x] Template contains a Quick Start guide in the README
- [x] Theme is published to rubygems.org
- [x] Documentation exists on how to develop and publish new versions of the theme
- [x] Goals of the theme are documented as per the recommendations
- [ ] Usability test is performed on the template experience
- [ ] Repos live under 18F github org

**Comment by wslack** [comment]
@adborden what do you think your timeline is on this?

**Comment by adborden** [comment]
I had started this work earlier, so a lot of it is there. Given that I'm working with reduced hours, its hard to predict the timeline. A few hours of extra work could mean an extra week before I get to it.

The next step is to integrate the quickstart guide from https://github.com/18F/federalist/issues/1775. Let's sync up later this week to see if it is up to snuff.

[Theme](https://github.com/adborden/federalist-basic-report-theme)
[Template](https://github.com/adborden/federalist-basic-report-template)

**Comment by adborden** [comment]
The repo currently lives under my github user. I think we should re-use the old https://github.com/18F/federalist-report-template , maybe rename it to federalist-basic-report-template and then remove the branch from federalist-uswds-template

**Comment by adborden** [comment]
@eddietejeda the repo used by Federalist currently is this (on the report-config branch) https://github.com/18f/federalist-uswds-template/tree/report-config

**Comment by eddietejeda** [comment]
@adborden lets deprecate `federalist-uswds-template` and `federalist-report-template`

In an earlier conversation, we talked about renaming:

- `federalist-uswds-template` to `federalist-starter-kit`
- `federalist-basic-report-theme` to `federalist-report-theme`

Does that still seem right to you?

**Comment by eddietejeda** [comment]
We will now only be focused on supporting standard USWDS theme. This will be the official theme: https://github.com/18F/federalist-uswds-jekyll
