### ISSUE TITLE
Delete old builder CDN service

### ISSUE THREAD

**Issue by el-mapache** [18F/federalist#1782]
#### Remove old federalist-builder CDN service

Currently https://federalist-builder.18f.gov points to a non-existent site. We currently use the `.fr` subdomain, so this one should be cleaned up

#### Definition of done

- [x] CDN route is removed

_After evaluating, edit this part:_

**Comment by amirbey** [comment]
TCOH2J-00AG3QK% cf service federalist-builder-ew-route
Showing info of service federalist-builder-ew-route in org gsa-18f-federalist / space production as amir.reavis-bey@gsa.gov...

name:            federalist-builder-ew-route
service:         cdn-route
tags:            
plan:            cdn-route
description:     Custom domains, CDN caching, and TLS certificates with automatic renewal
documentation:   
dashboard:       

There are no bound apps for this service.

Showing status of last operation from service federalist-builder-ew-route...

status:    create succeeded
message:   Service instance provisioned [federalist-builder.18f.gov => federalist-builder.apps.cloud.gov]
started:   2017-04-21T15:03:23Z
updated:   2017-04-21T15:32:55Z
TCOH2J-00AG3QK% cf delete-service federalist-builder-ew-route

Really delete the service federalist-builder-ew-route?> y
Deleting service federalist-builder-ew-route in org gsa-18f-federalist / space production as amir.reavis-bey@gsa.gov...
OK

Delete in progress. Use 'cf services' or 'cf service federalist-builder-ew-route' to check operation status.
TCOH2J-00AG3QK% cf service federalist-builder-ew-route       
Showing info of service federalist-builder-ew-route in org gsa-18f-federalist / space production as amir.reavis-bey@gsa.gov...

name:            federalist-builder-ew-route
service:         cdn-route
tags:            
plan:            cdn-route
description:     Custom domains, CDN caching, and TLS certificates with automatic renewal
documentation:   
dashboard:       

There are no bound apps for this service.

Showing status of last operation from service federalist-builder-ew-route...

status:    delete in progress
message:   Deprovisioning in progress [federalist-builder.18f.gov => federalist-builder.apps.cloud.gov]; CDN domain
           deej5fwwloisy.cloudfront.net
started:   2018-07-13T14:34:42Z
updated:   2018-07-13T14:34:47Z

**Comment by amirbey** [comment]
cf service federalist-builder-ew-route                         
Showing info of service federalist-builder-ew-route in org gsa-18f-federalist / space production as amir.reavis-bey@gsa.gov...

Service instance federalist-builder-ew-route not found
FAILED
