### ISSUE TITLE
Review Federalist homepage to identify opportunities for marketing improvements/optimizations

### ISSUE THREAD

**Issue by karareinsel** [18F/federalist#1788]
#### Description of feature or bug
Using the Federalist sales personas, review the Federalist homepage to identify if the current design supports the needs of the personas. Determine if existing marketing materials meet user needs, and if not, determine which marketing materials need to be created in order to better support users.
<TODO>

#### Definition of done

- [x] Review personas
- [x] Federalist homepage reviewed and existing marketing elements identified
- [x] Compare existing homepage marketing elements to the needs of the personas
- [x] Generate list of recommendations that could include new marketing materials (and who they support), modifying existing marketing materials (messaging, placement or design).

<TODO>

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by wslack** [comment]
Link to doc: https://docs.google.com/document/d/11meCVTB8PXEIX50ae8CNmk4uUalrTh-pMcjvXFOpYCg/edit?ts=5ae33381
