### ISSUE TITLE
Implement the Color Palettes

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1793]
#### Description of feature or bug

https://github.com/18F/uswds-jekyll/issues/122#issuecomment-377399786 was completed but not implemented

#### Definition of done

We have a set of plans/issues for somoene to pick up to implement the theming/color palette options.

_After evaluating, edit this part:_

#### Level of effort - low

cc @adborden so he knows this is filed - I'm not sure how much he saw the work on the palettes before

**Comment by adborden** [comment]
@wslack maybe this is worth a video chat. There are a number of ways to implement this from just documenting the cut/paste config options; to having separate repos for the user to clone; to having a UI in Federalist to choose the theme. The cut/paste config approach is the lowest lift, is that what you had in mind?

FWIW, I think ultimately, USWDS should own this kind of thing. @maya showed me an experimental code pen that did something similar.

**Comment by wslack** [comment]
Could meet need with examples and documentation. Need to be precise about how.
