### ISSUE TITLE
Create features page for federalist.18f.gov

### ISSUE THREAD

**Issue by annahsebok** [18F/federalist#1794]
#### User Story

As someone interested in Federalist, I'm curious what Federalist provides.

#### Background

We heard from users that they tend to assume Federalist is a CMS. They were also confused about the steps they must take in order to use Federalist. We believe that by creating a separate product page (linked to from the homepage navigation), we will be able to streamline the homepage, clarify what Federalist is and (from a high level) how to use it, and create a dedicated space to outline features and services without overwhelming the homepage.

This will involve moving some of the content on the homepage to this page.

#### Acceptance Criteria

- [x] We have created content for a product page that outlines what Federalist is, how to use it (at a high level), and what cool features it includes.
- [x] We have created a product page that is linked from both navigation bars on the homepage that reflects [Features - Desktop copy 2](https://gsa.invisionapp.com/share/YZKCIN2SKEP#/screens/302673508).

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [x] Clarify primary audience
- [x] Outline priorities for page
- [x] Develop content
- [x] Discuss potential visuals with viz designer
- [x] Build page
- [x] Publish content to page
- [x] Remove content from homepage that is duplicative of features page, eliminating content that less technical users consider to be "hard"
- [x] Change `Documentation` navigation title
- [x] Change `Get started` navigation title
- [x] Add useful links back into homepage page copy, linking to docs site and other valuable artifacts/sites/documentation. 
- [x] Corey or Will to review homepage changes
- [x] Will to ask Aaron about the bottom of the features page
- [x] Corey to do one more features page pass.
- [x] Will to ask Jen about bottom of page.
- [x] Will to make a fixing edit for bottom of page.

**Comment by annahsebok** [comment]
I'm _almost_ finished with the content here and will be wrapping this up tomorrow. Big thanks to @amirbey for trying to help me troubleshoot through getting federalist running locally. He's going to help me get a copy of the case studies page created so that I can then drop this new content in. Also planning on filing an issue with the design lab to help with the overall design of the page while I'm away. Another update coming tomorrow!

**Comment by annahsebok** [comment]
This is in a great place for a review from @wslack, and I've flagged a few specific sections where I'd like his input.

I've also filed [this design lab issue](https://github.com/18F/design-lab/issues/11) to jumpstart work on corresponding visuals for the content. Will followup on this when I'm back in the office.

**Comment by annahsebok** [comment]
@wslack Because I'm waiting on your input and am out of office, thereby unable to work on it.

**Comment by wslack** [comment]
Perfect - I knew you were OOO but didn't realize it was on me. Moving to "In Progress."

**Comment by annahsebok** [comment]
Just realized [the doc where this work is in progress](https://docs.google.com/document/d/1AAgJxrMD5wHYwOs4vAkp_9wNt71DucFD7bxU0dYQ3eE/edit) isn't linked in this issue anywhere. Womp womp.

@wslack are you finished with your review here?

**Comment by wslack** [comment]
@annahsebok finished with round one! https://docs.google.com/document/d/1AAgJxrMD5wHYwOs4vAkp_9wNt71DucFD7bxU0dYQ3eE/edit#

**Comment by annahsebok** [comment]
I'm meeting with the design lab tomorrow to move this forward!

**Comment by wslack** [comment]
Pulled in acceptance criteria from #1685.

**Comment by annahsebok** [comment]
@amirbey were you able to create the page like I mentioned in https://github.com/18F/federalist/issues/1794#issuecomment-388210178? I think I might've made this too complicated for myself before — if you're able to create the page and point me to where I can find it, I can easily add the content. 

We're scheduled to chat Monday and I'm happy to still do that, but if might be easier to tackle this how I've described above and nix our chat. Let me know what you think.

**Comment by annahsebok** [comment]
@wslack responded to some of your questions with a few questions. Can you pop in and take a look at them?

**Comment by annahsebok** [comment]
Tweaked @wslack's additions from https://github.com/18F/federalist/issues/1794#issuecomment-393253732.

**Comment by annahsebok** [comment]
@wslack This is ready for another review from you! After reading your comments and chatting more with @jenniferthibault, I've simplified and reorganized this quite a bit. [Take a look](https://docs.google.com/document/d/1AAgJxrMD5wHYwOs4vAkp_9wNt71DucFD7bxU0dYQ3eE/edit#). I'm looking forward to your comments!

**Comment by adborden** [comment]
There was some talk of me scrubbing in for @amirbey on this, but I'm not sure if I'm too late. Let me know what needs to be done!

**Comment by annahsebok** [comment]
Thanks @adborden! @jenniferthibault is working on the design for this page, and the content is nearly there. What we need is to have the page itself created within the structure of the site whenever the design is ready (with the addition of `Features` added to the top nav).

**Comment by annahsebok** [comment]
While I'm refining the content on the design we're going with, @wslack suggested that whoever is able to pick this issue up start creating the modules for `it's easy to get started`, `customize and publish`, `you don't need to start from scratch`, and the contact bar (along with updating the navigation bars). 

@wslack it's time for a staffing request to get some front end help for this (unless somebody on the team is available and can build this for us).

The modules are:

![screen shot 2018-06-13 at 8 57 51 am](https://user-images.githubusercontent.com/6728448/41359582-0d6b8142-6ee8-11e8-98cc-ec5756e021fb.png)

![screen shot 2018-06-13 at 8 57 57 am](https://user-images.githubusercontent.com/6728448/41359592-122a2f4e-6ee8-11e8-9bd6-cada86a7b509.png)

![screen shot 2018-06-13 at 8 58 03 am](https://user-images.githubusercontent.com/6728448/41359606-1a338ffa-6ee8-11e8-9ad2-24a6884deb76.png)

![screen shot 2018-06-13 at 8 58 10 am](https://user-images.githubusercontent.com/6728448/41359616-1d25e500-6ee8-11e8-850d-3b28447e76bc.png)

**Comment by wslack** [comment]
Noting here that @adborden will do the coding for this!

**Comment by jenniferthibault** [comment]
👋 @adborden there's also a mobile comp of these modules in [this InVision](https://gsa.invisionapp.com/d/main/#/console/14502959/303406212/preview).  

I used the standard USWDS grid system, and type styles that were already declared/set up in the design files from Eric Ronne's home page + Case Study page redesign. I was making an assumption that if those styles were set up in the design files, they'd likely be set up in the CSS, which may not be the case. Ping me if you hit anything unfamiliar.

Next up, I'll export the icons for you.

**Comment by jenniferthibault** [comment]
**Asset party!** 🎉 🖼 

📁 [Federalist-features-icons.zip](https://github.com/18F/federalist/files/2107191/Federalist-features-icons.zip)
- single color-icons exported at size used in the layout
- multi-color icons exported at size that matches how they're used on the home page. This way, they'll be scaled down uniformly for this page and will look matchy matchy. 

📁 [Features-gridlines.zip](https://github.com/18F/federalist/files/2107189/Features-gridlines.zip)

Includes:
-  grid layouts on desktop & mobile
- names of known type classes I used that set up in the design files

**Comment by annahsebok** [comment]
I just finished content edits for the top module (paired with the Sisyphus visuals) and shipped them over to @jenniferthibault who is working on the visuals this week. My remaining involvement on this issue includes making a few homepage updates (as outlined in the implementation steps) and opening two more issues — one to add pricing info to this page and a second to update the nav bars (which is also part of #1723).

**Comment by annahsebok** [comment]
I've checked off two more implementation steps (addressed via https://github.com/18F/federalist/pull/1870) and filed the issues I mentioned in my previous comment. As @adborden is creating the features page, content is with @jenniferthibault for the development of visuals, and I'm rolling off of Federalist on Wednesday, I think my work here is done (and I've removed myself from the issue). Add me back if I'm missing something @wslack! Also flagging this issue to @coreycaitlin should there be any remaining content needs I've missed.

**Comment by wslack** [comment]
SGTM!

**Comment by adborden** [comment]
I've started this work on this [branch](https://github.com/18F/federalist/tree/adb-features-page), based on @annahsebok 's home page. I figure those will be merged together.

There's a few spots where the visual design is different than the content, should I stick more to the content or the visual design? Or is it a middle of the road kind of thing?

**Comment by annahsebok** [comment]
@adborden I'm not entirely sure which spots you're talking about — I believe there are some content changes I shipped over to @jenniferthibault that she may not have gotten to making updates on yet. @jenniferthibault can you chime in here?

**Comment by jenniferthibault** [comment]
Correct, I haven't had a chance to update based on your changes yet @annahsebok, sorry for the delay here! 

I'll be able to come back into it late this afternoon and can try to clear things up @adborden

**Comment by wslack** [comment]
@adborden I can clarify during standup as well.

**Comment by jenniferthibault** [comment]
I couldn't run the site locally bc I didn't have the time to set it up, but based on design files + content , this is the only place I found that the design needed to be updated:

This is the most up-to-date both design and content:
![screen shot 2018-06-26 at 10 21 41 am](https://user-images.githubusercontent.com/11636908/41918671-ce5b2e60-792a-11e8-9b5a-9fd08a49708e.png)

If you're finding somewhere else @adborden, we might need some help translating :)

____

I also have a first draft of illustrations ready, and exported as pngs at 1x & 2x resolution.
📁 [Illustrations.zip](https://github.com/18F/federalist/files/2137524/Illustrations.zip)
Depending on your preference for approach to scaling images, @adborden , I'm glad to export any size/dimension you need.


For the image on the right, I used the concept from this [Noun Project icon](https://thenounproject.com/search/?q=sisyphus&i=1441102#), so we'll need to give the author attribution under their chosen [Creative Commons License](https://creativecommons.org/licenses/by/3.0/us/legalcode) in the codebase somewhere. I've typically done this in the License.md file


![screen shot 2018-06-26 at 10 25 45 am](https://user-images.githubusercontent.com/11636908/41918904-4c3744ae-792b-11e8-9798-42486e554bfe.png)


Definitely open to feedback to iterate the illustrations & styles, though my capacity is probably limited to an hour or two a week outside of regular projects.

**Comment by adborden** [comment]
@jenniferthibault I'll take a look at the images, they're probably fine as-is. I'll add a note in the license.

**Comment by adborden** [comment]
@jenniferthibault can you add me as a collaborator to the invision? somehow I lost access. I was working for me two weeks ago :man_shrugging:.

**Comment by jenniferthibault** [comment]
@adborden you're not showing up as a member to add on InVision, did your membership possibly change with 18F?

If that doesn't work, this link should let you view each page and left/right arrow through the two screens. Let me know! https://gsa.invisionapp.com/share/DBMMYPKASZF

Also feel free to reach out for any questions or pairing to build the page. I know I'm not on the project but glad to help as I can.

**Comment by adborden** [comment]
Thanks @jenniferthibault, unfortunately I'm getting an error with the link, that it's an old link and no longer valid? I'll ask around about getting re-activated in the GSA InVision org. Not a blocker, I'm still making progress. [Here's what it's looking like](https://adb-federalist-features.app.cloud.gov/features/) so far.

**Comment by coreycaitlin** [comment]
@wslack Does this copy tweak address the concern about setting expectations re "free"?
<img width="339" alt="screen shot 2018-07-23 at 5 00 50 pm" src="https://user-images.githubusercontent.com/1450354/43109177-5190acf4-8e9a-11e8-986c-03c31d745960.png">

**Comment by wslack** [comment]
@coreycaitlin if we add "temporarily" or something there I'm good with it (this is a policy change, but I think we should try this - there's no value delivered unless they go live).

**Comment by wslack** [comment]
We will aim to push this by Wednesday.

**Comment by coreycaitlin** [comment]
Edits — please change...

- `Self-controlled content and code` to `Easy to change content and code`
- `May require plug-ins to get features like simple editorial and development workflows or real-time publishing — and all plug-ins require their own security evaluation.` to `You may need plug-ins to get features like simple editorial and development workflows or real-time publishing — and each plug-ins will need its own security evaluation.`
- `Less collaboration and low reusability` to `Less collaboration and reuse`
- `Closed-source software may require costly training to learn.` to `Closed-source software may require expensive training to learn.`
- `If you have an in-house design team, they can use a static site generator like Jekyll, Hugo, or their own tools to deploy a custom site through Federalist.` to `Use a static site generator like Jekyll, Hugo, or other tools to deploy a custom site through Federalist.`
- `The code used for Federalist is open source and in the public domain for anyone to reuse. Share code with other agencies and vendors also using Federalist.` to `Federalist source code is open source and in the public domain. Share code with other agencies and vendors also using Federalist.`

In the footer, change the following content:

- `We offer basic training for both Federalist and GitHub.` to `We offer training on how to use both Federalist and GitHub.`
- `Join the Federalist community on Slack to learn more from other users.` extend to `Join our Slack community to connect and learn from other Federalist users across the federal government .`
- `The Federalist team is continuously learning from your experiences so that we can help you avoid recurring problems.` to `The Federalist team wants to learn from your experience so we can improve the product for all our users.`
