### ISSUE TITLE
Create contact content for federalist.18f.gov

### ISSUE THREAD

**Issue by annahsebok** [18F/federalist#1795]
#### User Story

As a Federalist partner or potential partner, I need an easy way to look up how to contact the Federalist team.

#### Background (Optional)

We heard from users that they are confused about when to contact Federalist and what method of contact is best (login, email, “get started”/contact form, or the contact us button/contact form). We believe that by creating a separate contact page (linked to from the homepage navigation) with the same design principles as the rest of the site, users will be more confident when contacting Federalist and we will see an increase in people reaching out to the Federalist team.

This is closely related to #1685, as it may involved moving some of the content on the homepage to this page.

#### Acceptance Criteria

- [x] To include: (when to contact, what method is best, and what to expect). 
- [x] Federalist Sales info is listed obviously
- [x] Reviewed by content designer

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [x] Outline priorities for page
- [x] Develop content
- [x] Ping in #1761 when content is ready

**Comment by annahsebok** [comment]
@wslack let me know what you think about this issue. We've also got #1761 and #1623, but this issue is related to the content development (whereas the other issues are not).

**Comment by wslack** [comment]
Pasting the Leah had possible content here: https://github.com/18F/federalist/issues/1623#issuecomment-365809963

**Comment by annahsebok** [comment]
Starting to outline this [here](https://docs.google.com/document/d/1PYVw2IgRCuatdtpn1_0nKBL8JBV4i5VbyARnFJuzk3o/edit).

**Comment by annahsebok** [comment]
This is done. Going to update front end issue now!
