### ISSUE TITLE
Support a build root path

### ISSUE THREAD

**Issue by dhcole** [18F/federalist#180]
In some cases, the static site or assets are part of a repo with other code. By enabling a root path for Federalist builds, we could support hosting the front end static assets / pages for these sites.

This applies to Federalist itself (`/assets/`) as well as Midas. Probably a lot of other sites too.

**Comment by wslack** [comment]
I think we do this now using custom url, but will check

**Comment by wslack** [comment]
Doesn't make sense for now; the use cases we know about are already possible.

**Comment by wslack** [comment]
@shawnbot mentioned this in a new issue; moving it here: 

> Currently, the build script explicitly [provides](https://github.com/18F/federalist-docker-build/blob/staging/build.sh#L45-L47) the `--source .` option to `jekyll build`, which overrides the corresponding option in `_config.yml`. This could be a problem for Jekyll sites—more specifically, repos that contain their site in a subdirectory, or those that build it via other tools, e.g. npm—but it would also be good to be able to tell Federalist the source directory for static sites and skip running Jekyll altogether.
> 
> The specific use case I have in mind is [Marigold](https://github.com/18F/marigold), which builds the entire static site with npm. In that case, Jekyll seems like overkill to just copy a bunch of files from `./build` to `./_site`. More generally, though, I think it would be good to nix the explicit `--source .` option, since that's the default, and sites may have a legitimate need to (either temporarily or permanently) build the site from a custom source directory.

**Comment by wslack** [comment]
Confirmed done!
