### ISSUE TITLE
Create and design a "How Federalist makes your life easier" 1-pager

### ISSUE THREAD

**Issue by karareinsel** [18F/federalist#1801]
#### Description of feature or bug
An easy to understand explanation of how Federalist’s baked in security and compliance makes customers lives easier and reduces costs by walking prospects through 3’ish scenarios that customers regularly encounter in their daily responsibilities. 
- Sample scenario 1 - TBD
- Sample scenario 2 - TBD
- Sample scenario 3 - TBD

<TODO>

#### Definition of done

<TODO>

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by annahsebok** [comment]
This seems like something we'd want to inform by user research. @ShannonBad based on your research, do you have any suggestions? We can probably also pulled from [the research done last fall](https://docs.google.com/document/d/1BHJpid-5Q2X1o3hM-Y2qLF1AjxDmnvvoJ9i2Z8r9zgU/edit).

**Comment by eddietejeda** [comment]
This work is being done here: https://github.com/18F/federalist-team/issues/24
