### ISSUE TITLE
Write a script for a one min snazzy Federalist video

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1805]
#### Description of feature or bug

Federalist needs a snazzy sales video! We should prepare a script for it.

#### Definition of done

- [ ] DigitalGov team has a workable script from us in a google doc

_After evaluating, edit this part:_

#### Implementation outline:

- [x] Outline
- [x] Outline is edited
- [x] Review from content
- [x] PM review

**Comment by wslack** [comment]
Will and @eddietejeda to talk!

**Comment by wslack** [comment]
Wrote a draft! https://docs.google.com/document/d/10Vsw_HtLXKXCB6mXRDyg-rjyp22SuzYHO-Pkw3m5kGM/edit

**Comment by wslack** [comment]
This is ready for @coreycaitlin to take a pass.

**Comment by coreycaitlin** [comment]
@wslack I think I only have edit access to the first draft, but I'm guessing I _should_ be responding to the "with edits" version?

**Comment by wslack** [comment]
@coreycaitlin to do a quick final look
