### ISSUE TITLE
Update hero image with screenshots of existing Federalist sites

### ISSUE THREAD

**Issue by karareinsel** [18F/federalist#1806]
#### Description of feature or bug
Replace the light grey background of the hero space with designed screenshots of the homepage of 2 or 3 of the best looking sites running on Federalist. Users can immediately see the product and it adds visual interest.
**The current grey background is problematic for users for two reasons.**
- The grey makes the space look inactive or that perhaps there’s something wrong with the design because it looks unfinished. 
- The fold line (at least on laptop) gives the appearance that the page ends immediately below the hero image. The site is responsive so this will vary depending on the device but wanted to flag.

<TODO>

#### Definition of done

<TODO>

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by eddietejeda** [comment]
Updated screenshots, highlighting prominent pages. Hero stayed the same.

<img width="772" alt="screen shot 2019-01-27 at 11 13 03 am" src="https://user-images.githubusercontent.com/669988/51803561-8d854800-2224-11e9-966c-2c1751916353.png">
