### ISSUE TITLE
Research replacing the Federalist stats box in the hero image with a call to action

### ISSUE THREAD

**Issue by karareinsel** [18F/federalist#1807]
#### User Story
As a first time visitor to the Federalist site, I want to understand if further investigation is worth my time. (need to build on from personas)

#### Background
the information that is displayed within this box do not line up with the needs of the personas. The stats information would be helpful to include on a page about Federalist’s clients.
Recommend replacing the messaging with a call to action (CTA) and link, such as linking to a 30 second or 60 second sizzle video that highlights the key features of Federalist.

#### Acceptance Criteria

- [ ] A set of options for how to use the space that serve various user needs

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by eddietejeda** [comment]
This issue has been replaced by this: https://github.com/18F/federalist/issues/2153
