### ISSUE TITLE
Light-background thumbnails should be slightly darkened

### ISSUE THREAD

**Issue by ericronne** [18F/federalist#1810]
#### One design subtlety not yet implemented is to slightly darken thumbnail images which have white or very-light backgrounds. Consequently these images tend to blend in with the background, e.g. on the home page …
![image](https://user-images.githubusercontent.com/9259185/39449461-bafa8588-4c8d-11e8-9341-986449051e76.png)

### How they should look:
![image](https://user-images.githubusercontent.com/9259185/39449594-1d2ee82a-4c8e-11e8-823e-c6167ee637e4.png)

### Technique:
![image](https://user-images.githubusercontent.com/9259185/39449624-2e7c3862-4c8e-11e8-9709-05a2faee9697.png)

<TODO>

#### Definition of done
Thumbs are darkened, either via code or simply in sketch

<TODO>

#### Level of effort
Probably low if sketch; medium if code-based

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by wslack** [comment]
Holding, pending @ericronne.

**Comment by wslack** [comment]
PR is in, moving to done!
