### ISSUE TITLE
Seeking automatic 404 config on Federalist

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1811]
#### Description of feature or bug

Using a single-page client-side web app is possible on Federalist out of the box as long as the hash is used in the routes. The hashes can be turned off so long as the index.html file is always delivered via 404 functionality. It's not possible to set a 404 page on the branch previews.

Looking for something similar to server-side applications using Apache's htacess file.

#### Definition of done

- [ ] A checkbox in Federalist's settings that just let someone always deliver the index.html file almost in spite of the route provided to the server

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by wslack** [comment]
This would be neat and has to be managed. No easy plan or path we know of. The manual path works _okay_.

**Comment by eddietejeda** [comment]
We are going to be taking this approach: https://github.com/18F/federalist/issues/2182
