### ISSUE TITLE
Menu button on mobile responsive is not working

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#1814]
#### Description of feature or bug
Clicking the menu button does nothing.  Throws the following error:

Failed to load resource: the server responded with a status of 404 ()
Refused to execute script from 'https://federalist.18f.gov/uswds/js/uswds.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

#### Definition of done
Load script properly.
Menu button presents options as expected and no errors.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by wslack** [comment]
Noting that addressing this bug is higher prioeority then other bugs.
