### ISSUE TITLE
Federalist Fact Sheet Suggestions

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1821]
#### User Story

As someone investigating Federalist, I need a one-page document I can glance over that piques my interest.

##### Move the assets down the page

Do we know from user research if users utilize the three existing documents (Federalist proposal, architecture diagram and compliance memo)? They are more appropriate for qualified prospects who are far down the sales funnel and therefore don’t need to be heavily promoted on the website. Recommend making them footer links.

##### Replacement Content

Recommend replacing the current assets with 2 or 3 documents specifically written to introduce prospects to Federalist. These are high-level, intro assets such as the comparison chart and how Federalist helps you 1-pager.

#### Definition of done

- [ ] Move the assets down the page

- [ ] Replacement Content

_After evaluating, edit this part:_

**Comment by wslack** [comment]
@annahsebok I'm fine with that.

**Comment by eddietejeda** [comment]
We now use this: https://federalist.18f.gov/assets/documents/Federalist-Proposal.pdf
