### ISSUE TITLE
Set up templates and DAP to work together

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1822]
#### Description of feature or bug

User stories related to this:

As a DAP admin in OPP (i.e. @tdlowden) I want the sites created and published using Federalist templates to report to DAP using my Google Analytics snippet so they appear in my rollups when I produce reports.

As a Federalist Product Owner, I want template sites to appear in either DAP or 18F's rollup so that I can analyze how customers are using template sites.

As a Federalist Customer, I want my template sites to be compliant with DAP by default so I don't have to worry about setting it up.

As a Federalist Customer, I want to be able to customize how my site interacts with DAP and Google Analytics in case my site or my agency has specific requirements.

#### Definition of done

<TODO>

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

<TODO>

**Comment by wslack** [comment]
@jmhooper to split into three

**Comment by amirbey** [comment]
the federalist templates both (Gatsby and Jekyll) have DAP configurations
