### ISSUE TITLE
Add SBST template to the template gallery

### ISSUE THREAD

**Issue by wslack** [18F/federalist#183]
I don't see the SBST site on the list of templates. Could the list have screenshots of "live" sites on those templates? I might also be misunderstanding.

**Comment by dhcole** [comment]
It's not added to Federalist yet — we have to do a bit cleanup of work to pull out SBST-specific content (just ran out of time after the launch). This is high on our list for when we pick up the next round of work. You can see it here though: https://github.com/us-federal-sbst/federalist-modern-team-template

**Comment by mogul** [comment]
Refer also to [this pull-request](https://github.com/18F/federalist-modern-team-template/pull/8)

**Comment by dhcole** [comment]
Closed by #197
