### ISSUE TITLE
Go through and create out labels for Federalist issues in :all-the: repos!

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1836]
#### User Story

As a Federalist team member, I want to be able to manage issue labels consistently regardless of which repo an issue is in.

#### Background (Optional)

Federalist has fourteen repos, and those repos don't have the same issues lists. A little bit of organizational work will help us categorize and manage the issues more consistently.

#### Acceptance Criteria

- [x] Team-endorsed labels are applied to the Backlog column with identical colors

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [x] Examine existing labels
- [x] Draft consistent [list](https://docs.google.com/spreadsheets/d/1LU8yGFV8JQ2bzxBU7ch8SwiPEmSa4FOzALwL1ys2lXs/edit#gid=0)
- [x] Team endorses list (Will signed off 7/17, Amir gave feedback)
- [x] Labels are applied to the issues in the Backlog column
- [x] Those labels are applied to additional repos where needed with matching colors
- [x] [stretch] We have asked the team to label their issues In Progress
- [ ] [stretch] We have stories written for the additional recommendations as outlined in the list linked above

**Comment by suprenant** [comment]
Picking this up.

**Comment by suprenant** [comment]
OK, my review is done. Take a look at the spreadsheet linked in this issue for my recommendations on the following:
 - Current labels
 - Labels we don't have but need
 - Pipelines (selected)
 - Next steps/additional recommendations

If I can get thumbs up soon on this plan (ideally this afternoon), I should be able to update all the labels and pipelines and get through labeling as many unlabelled issues as possible. 

The Next steps/additional recommendations section contains more work past this issue. As noted there, if we want to plan on doing that stuff, we can write issues for them.

**Comment by suprenant** [comment]
With feedback from Amir and Will, I'm starting to implement this labeling scheme...

**Comment by suprenant** [comment]
OK, I am considering this done / ready for review. Notes:
 - I added a 'devops' label and changed the older label to 'backend' and took a crack at applying these appropriately
 - Again, the team should add labels to everything in Progress (and having labels should probably be a criterion for having something groomed and in Ready)
 - If a team member tries to apply a label but finds it is not in the appropriate repo, they should add that label to that repo using the naming/color convention as outlined in the linked document

Screenshots are here for acceptance purposes. @wslack if you happen to have any more changes at this point, LMK, and I'll see what I can do.

![screen shot 2018-07-19 at 3 41 09 pm](https://user-images.githubusercontent.com/1452369/42968954-612b54e4-8b6a-11e8-9b94-f032e5116a9b.png)
![screen shot 2018-07-19 at 3 41 17 pm](https://user-images.githubusercontent.com/1452369/42968955-613cd700-8b6a-11e8-8d97-5969ed1b7847.png)
![screen shot 2018-07-19 at 3 41 21 pm](https://user-images.githubusercontent.com/1452369/42968956-61534b02-8b6a-11e8-9384-bbcf7566dc9d.png)
![screen shot 2018-07-19 at 3 41 25 pm](https://user-images.githubusercontent.com/1452369/42968957-61649736-8b6a-11e8-9e56-a0a2276191e6.png)
![screen shot 2018-07-19 at 3 41 29 pm](https://user-images.githubusercontent.com/1452369/42968958-6177d526-8b6a-11e8-8dc1-e139aa82ae58.png)
![screen shot 2018-07-19 at 3 41 32 pm](https://user-images.githubusercontent.com/1452369/42968959-618ce5a6-8b6a-11e8-9f2d-5c490d5c3b9d.png)
![screen shot 2018-07-19 at 3 41 35 pm](https://user-images.githubusercontent.com/1452369/42968960-61a5618a-8b6a-11e8-8673-0bad410b045a.png)
![screen shot 2018-07-19 at 3 41 39 pm](https://user-images.githubusercontent.com/1452369/42968963-6217f60a-8b6a-11e8-859d-b0c7c4e3b794.png)
![screen shot 2018-07-19 at 3 41 43 pm](https://user-images.githubusercontent.com/1452369/42968964-622ccc6a-8b6a-11e8-8da1-c1eab6b8e1e2.png)
