### ISSUE TITLE
Spike: determine if nginx buildpack is ready

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1837]
#### User Story

We need to know when we can use a dedicated buildpack for NGINX instead of the deprecated current buildpack.

#### Acceptance Criteria

- [x] We know when the nginx buildpack will be ready

**Comment by amirbey** [comment]
so nginx-buildpack is still in experimental phase and is not supported by cloud.gov so if we choose to use it we will be on our own and have to do our own patches and upgrades.  As per Josh Carp, Cloud.gov focuses on supporting buildpacks as designated by https://github.com/cloudfoundry/cf-deployment

**Comment by wslack** [comment]
@amirbey and @jmhooper to chat today about this.

**Comment by wslack** [comment]
@amirbey mind noting your findings here? I think this is "done?"
