### ISSUE TITLE
Update docs site with info on broken link checkers

### ISSUE THREAD

**Issue by maya** [18F/federalist#1839]
#### User Story

As a Federalist partner, I need information about how to use a broken link checker such as:

https://validator.w3.org/checklink
https://www.deadlinkchecker.com/

#### Background (Optional)

Our robots.txt is a hard stop on all automated scanning. Users need another path.

#### Acceptance Criteria

- [ ] Instructions are added to docs site on how to use card validators and link checkers on demo sites.
- [ ] Scan our website, especially with the new structuring of the content

_After evaluating, edit this part:_

**Comment by wslack** [comment]
I *think* our update will apply to all previews - I assume you are ok with that?

**Comment by wslack** [comment]
(will close after 7 days if no response)

**Comment by maya** [comment]
@wslack yes that is perfectly fine. I didn't respond bc I didn't find an issue with it.

**Comment by wslack** [comment]
ah sorry for being unclear. Will edit.

**Comment by maya** [comment]
I'd also like to be able to run the website these social media card validators:

https://cards-dev.twitter.com/validator
https://developers.facebook.com/tools/debug/

I don't mind if the URL is a demo site, a different URL, I just need to be able to run these things on it before launch.
