### ISSUE TITLE
Left-hand nav on developer hub template is unusable

### ISSUE THREAD

**Issue by mogul** [18F/federalist#185]
Reproduction steps in Gherkin-ish test code:

Scenario: The left-hand navigation should be usable without scrolling on a short page _(*but* it is covered up by the site footer on short pages)_
> When I look at the developer hub microsite example, 
> and I click on "API calls" in the left-hand navigation,
> then I should be able to see a link to the "Contribute" page in the left-hand navigation
> _but I cannot get to all pages listed in the left-hand navigation_

Scenario: The left-hand navigation should be usable after fully scrolling on a long page, _(*but* it is covered up by the site footer when you scroll all the way down)_
> When I look at the developer hub microsite example, 
> and I click on "Overview" in the left-hand navigation,
> and I scroll to the bottom of the page
> then I should be able to see a link to the "Contribute" page in the left-hand navigation
> _but I cannot get to all pages listed in the left-hand navigation_

**Comment by dhcole** [comment]
Thanks @mogul, I copied this to the upstream repo where the template is maintained: https://github.com/USG-Website-Templates/developer-hub/issues/11
