### ISSUE TITLE
Add uniqueness validation for sites model (owner,repo)

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#1852]
#### User Story

A user should only be able to have one site per repository in Federalist

#### Background (Optional)

A site existed in Federalist with two sites for the same owner/repo combination

#### Acceptance Criteria

- [ ] The site model does not allow adding a new site with the same repo/owner as an existing site

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] Add uniqueness constraint to site model
See http://docs.sequelizejs.com/manual/tutorial/models-definition.html

**Comment by amirbey** [comment]
This unique constraint cannot be added because the site models uses paranoia.  If this is an ongoing issue 'upsert' may be a resolution.

It appears previous version of SiteCreator allowed creating duplicate site:
https://github.com/18F/federalist/blob/c77a29e71aaedd3f20a2b533b033db91e3841a78/api/services/SiteCreator.js

The current version forces a check to see if site already exists using SiteCreator.checkSiteExists()

**Comment by wslack** [comment]
Declaring this a non-issue due to changes already made!
