### ISSUE TITLE
Support plugins with build containers

### ISSUE THREAD

**Issue by dhcole** [18F/federalist#186]

**Comment by dhcole** [comment]
Started a Docker image here: https://github.com/18F/federalist-docker-build

Next steps:

- [ ] new buildEngine that uses this image
- [ ] set up endpoint for receiving build status
- [ ] deploy the image as a Cloud Foundry service

**Comment by dhcole** [comment]
Probably worth setting up a new S3 account that only has access to the /build/ prefix to make sure builds never conflict with live sites.

**Comment by dhcole** [comment]
I've now got this working with AWS ECS so builds run as ECS tasks (docker containers) based on the [federalist-docker-build image](https://hub.docker.com/r/18fgsa/federalist-docker-build/).

Next step is to update that image to handle `git clone` too, so there is no need to shell out anything in the main application.

The following command (with the missing values filled in) will run the ECS task and wait for it to complete before exiting (requires the `aws` CLI and `jq`):

```sh
(output=$(aws ecs run-task --task-definition federalist-builder:2 --overrides '{"containerOverrides":[{"name":"builder","environment":[{"name":"AWS_ACCESS_KEY_ID","value":""},{"name":"AWS_SECRET_ACCESS_KEY","value":""},{"name":"S3_PATH","value":""},{"name":"FINISHED_URL","value":""}]}]}' | jq .tasks[0].taskArn | sed "s/\"//g") && aws ecs wait tasks-stopped --tasks $output)
```

**Comment by dhcole** [comment]
Updates to the docker container are ready for review here: https://github.com/18F/federalist-docker-build/pull/2

**Comment by dhcole** [comment]
Updated next steps to close this out:

+ [x] test local docker image
+ [x] push to github, federalist-docker-builder
+ [x] push to docker hub
- [ ] update ECS task definition
- [ ] test ECS task
- [ ] move ECS to its own cluster
- [ ] write builder app
  - [ ] listen on PORT, return 200 unless error
  - [ ] ECS receive_message, long poll
- [ ] have container remove messages from queue upon completion

**Comment by dhcole** [comment]
Builder app is here: https://github.com/18F/federalist-builder

Last step: 

- [ ] update API to post new builds to SQS

**Comment by jeremiak** [comment]
@dhcole this should be closed with your latest deploy, correct?

**Comment by dhcole** [comment]
Yes! Finally.
