### ISSUE TITLE
Federalist data strategy research effort

### ISSUE THREAD

**Issue by eddietejeda** [18F/federalist#1865]
#### User Story

As a user who needs more functionality from federalist, there are no examples that demonstrate more advanced functionality of what federalist is capable of. While we've done research to understand user needs, few have focused on understanding a long-term needs of users. 

To determine this, we will check with users to understand what work is currently not covered by existing features. Eddie will work with @wslack to identify users interested in sharing their perspective on new federalist functionality.

Working folder: https://drive.google.com/open?id=1EHG4e8qzeLcjt_ZrA0TzOLFlZvR7oUCn

#### Acceptance Criteria

- [x] Short summary of findings with a vision statement, citing user interview responses

Current working list: https://docs.google.com/spreadsheets/d/1E4N0VsR4T8-j_D40T9GHxl1P9DRzqCYjEt6MZJceubo/edit#gid=0

#### Implementation Plan

- [x] Talk to at least 5-10 current users, potential users and experts in government data systems

**Comment by wslack** [comment]
I am synthesizing the research.. into recommendations and data strategy. ideally, I will have draft by end of this week, complete by next week.

**Comment by wslack** [comment]
Eddie presented his findings today! https://docs.google.com/document/d/1WH25S-ZFY4SYpznOE-Hfyh97dLOLUM4-PW3hqltiz7M/edit#
