### ISSUE TITLE
Update terms in top and bottom navigational toolbars for federalist.18f.gov and federalist-docs

### ISSUE THREAD

**Issue by annahsebok** [18F/federalist#1869]
#### User Story

As a visitor to federalist.18f.gov, I want to be able to easily find features and pricing, example sites, contact information, and support documentation so that I can make decisions about whether or not to buy Federalist.

#### Background

During our IA work in #1723, we found that majority of users sorted Federalist content into one of four areas - `features & pricing`,`support`, and `contact` - along with something representing `example sites` (if we can think of something better). As a part of [our IA reorganization](https://app.mural.co/t/gsa6/m/gsa6/1522093516875/88001f9a465e1c1a57860657f3cbf6cb4708a7a4) based on a card sort with users, we should rename existing menu options on the top and bottom navigational toolbars to reflect the nomenclature above. 

_Note: We used to refer to the `case studies` page as `example sites`. The change to `case studies` was somewhat recent, but no users identified this content using the phrase `case studies`. `Example sites` was by far the most common title users used to identify the content to be included on this page._

#### Acceptance Criteria

- [ ] The top and bottom navigational toolbars have been updated.
- [ ] The top and bottom navigational toolbars match (excluding the log in button which should only be on the top bar) match with the federalist-docs toolbar.

_After evaluating, edit this part:_

**Comment by wslack** [comment]
This now includes the discussion in https://github.com/18F/federalist/issues/1668

**Comment by annahsebok** [comment]
To be clear, when I mentioned in standup that this needs to happen in tandem with homepage updates, I was referring to https://github.com/18F/federalist/pull/1870, not #1820.

**Comment by amirbey** [comment]
features and pricing - where is the pricing information?

Are we getting rid of Federalist Interest Signup form?

**Comment by wslack** [comment]
We haven't added pricing to the features page yet.

**Comment by wslack** [comment]
We haven't added the pricing issue yet.

The interest form should stay in the menu.

File an issue should disappear. It's never used and the source code is linked in the footer.
