### ISSUE TITLE
Improved file listing

### ISSUE THREAD

**Issue by dhcole** [18F/federalist#187]
As part of our effort to break away from git paradigms for content editors, we should lay out the file listing in a more usable way. Here's one approach: https://github.com/18F/federalist/wiki/Design-Documentation#site-file-listing

**Comment by jeremiak** [comment]
Our current thinking on this is that we should only show the users the "pages" that they might want to edit, and not the entire structure of their project. Here's a more recent design:
![](https://s3.amazonaws.com/f.cl.ly/items/2z1N0U2S0b3A0p0u2k2J/Screen%20Shot%202015-10-19%20at%204.50.56%20PM.png)

An idea that @dhcole had was to have the projects generate a `_navigation.json` file in the root of their project, that would describe all of the pages (and their child pages) that we want to present to the end user for editing. As long as the file adheres to the Pages schema we don't really care how it is generated. For many Jekyll projects, this file can be automatically generated on each build.

**Comment by dhcole** [comment]
@jeremiak Do you think we could keep this schema in memory as a model / collection / some other data structure, that way we can optimistically render the file listing after a new page is created, updated, or deleted?

I'm thinking of the case where a user saves a new page, then goes back to the file listing. It may take a minute for the file to render, so the user wouldn't see it in the listing and might try to re-create it.

If we maintain a file listing in memory and edit that, since going back to the file listing would just be a backbone route and not a full refresh, we could take into account any recent changes and show an updated file listing.
