### ISSUE TITLE
Get in touch with partners and ensure we have contact information for issues outside of business hours

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1872]
#### User Story

As a Federalist partner, if my site is down, and I can help fix it, I want to be made aware of that on a weekend or weeknight.

#### Background

We had an accidental downtime of two Federalist sites caused by a user [accidentally deleting](https://docs.google.com/document/u/1/d/1WvpTKSjZdlOBUTvcEJdSy_2AFZnZAAkLeJczwxvCoIU/edit?usp=drive_web&ouid=115402310886847049678) the sites from Federalist. As part of addressing that issue, we were able to reach the site owner because @wslack happened to have a separate phone number for that person.

That's not typical for most partners and we should give others the opportunity. E-mail only notification may not be acceptable to some partners.

#### Acceptance Criteria

- [ ] We have a [document with contact information for all partners (excepting TTS and OPM)](https://docs.google.com/spreadsheets/d/1Fnq93ABmfcd-t4KEDWXhr7muuIeJSatnVwRPNg5qs_k/edit#gid=2139836156) or a note they did not respond to our question.

_After evaluating, edit this part:_

#### Level of effort - medium

- [x] Cross-reference Processed Import tab to see if anything is missing from the External Customer Contacts tab in the [business dashboard](https://docs.google.com/spreadsheets/d/1Fnq93ABmfcd-t4KEDWXhr7muuIeJSatnVwRPNg5qs_k/edit#gid=2139836156)
- [x] Add fields and fill in as much as possible: IAA #, Contact date, Result of contact, Notes
- [x] Draft comms: [comms](https://docs.google.com/document/d/14TTjBhqHe7H9OKY-Tz-oGsKqTyVB9G5kME0tNDAASMc/edit)
- [x] @coreycaitlin or @wslack approves comms
- [x] Contact all partners via email, copying federalist-support@gsa.gov
- [ ] Track results

**Comment by suprenant** [comment]
From standup, Will left some notes, which I will review and ping him (vs. Corey, as she's got other stuff presently going on) for further review/approval so we can get this out.

(wrote this comment after standup, but it didn't go through, so here it is a bit later)

**Comment by suprenant** [comment]
Draft is revised and approved by @wslack. I'll start sending these out on Monday given we're past 5PM ET on a Friday.

**Comment by suprenant** [comment]
Starting to send these out, pinged Will in #federalist for a final check and also confirmation of approach if two contacts are listed: 

https://gsa-tts.slack.com/archives/C04823NMA/p1530543771000016

**Comment by suprenant** [comment]
Update: emails have all been sent to the partner contacts in the spreadsheet.

**Comment by suprenant** [comment]
This is more "Waiting" than "Blocked", but moved to Blocked. At this point, we have contacted everyone (my count is fourteen contacts for thirteen accounts) and received and filed contacts for eight accounts.

At this point, let's wait a bit for the other six to respond. If we don't hear back by early next week (after the holiday), we can determine next steps and move to close this issue.

**Comment by wslack** [comment]
As noted in standup, we don't need to re-ping people. I think we can just wait until next Friday and then close as done - we don't need to pressure anyone about putting in personal data.

**Comment by suprenant** [comment]
Update before the holiday – I haven't seen any more responses. Will check in again next week.

**Comment by wslack** [comment]
Declaring this done!
