### ISSUE TITLE
Audit site deletion and user removal workflows

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1873]
#### User Story

As a Federalist user, I want to clearly understand my options when deleting a site or deleting myself from a site.                       

#### Acceptance Criteria

- [x] @coreycaitlin does a audit of these workflows and writes up findings
- [x] @coreycaitlin opens any issues for follow-on work

_After evaluating, edit this part:_

**Comment by coreycaitlin** [comment]
I've walked through both of these flows, and here are my recommendations:

The "Delete site" flow is unclear. I recommend expanding this section of the advanced settings options as follows:

<img width="795" alt="screen shot 2018-06-20 at 5 03 23 pm" src="https://user-images.githubusercontent.com/1450354/41690815-321522a4-74ac-11e8-9cd7-b7e8c5573366.png">

This should make it much harder for users to do this without understanding what they're doing. I would also advocate for making people push at least two buttons to accomplish this, but that may already be true — I was afraid to try pressing the delete button for fear it wasn't. 😬

The collaborator flow is pretty simple, with the exception of the issue already spotted in #1884.

**Comment by coreycaitlin** [comment]
For non-image reference, here's the revised text for the **Delete site** section:

> Delete site
> Deleting a Federalist site removes the published site from our servers and disconnects the Federalist admin interface for all users. This will bring the entire site offline and make it inaccessible for users. Trying to remove a site from your list of Federalist sites? Remove yourself as a collaborator.
> 
> Danger zone
> Are you sure you want to delete this site from Federalist for all users, remove all published sites, and delete all previews?

This likely needs some edits — it's just a first draft.

**Comment by wslack** [comment]
@wslack to make a few edits

**Comment by wslack** [comment]
Moving to done since this review is done!
