### ISSUE TITLE
Add easy personal delete button to "my sites" list

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1877]
#### User Story

As a Federalist user, I want to easily clear sites off of my "my sites" list.

#### Acceptance Criteria

- [ ] Something like this is added to Federalist:
![2.jpg](https://images.zenhubusercontent.com/576b0940bf93871ccd9d0a0b/ab16b893-7d55-47bc-8600-eb687ddd9765)
- [ ] We've accounted for cases when people are the only users of their repo

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by wslack** [comment]
We think this is a rare use case, possibly applying only to folks at 18F, and are therefore putting in the icebox.

**Comment by eddietejeda** [comment]
@amirbey this is already done, right?

**Comment by amirbey** [comment]
hmm ... perhaps this icon is a good look?
but yes, #2097 is the same thing

**Comment by eddietejeda** [comment]
I think the X with tooltip is a better approach. Closing this issue. Lets continue the conversation in #2097
