### ISSUE TITLE
Support for uploading and managing assets

### ISSUE THREAD

**Issue by dhcole** [18F/federalist#188]
Things like images or other assets to be linked in content need an upload and management interface

**Comment by dhcole** [comment]
This requires extending prosemirror, for which better documentation is on the way. Moving this out of the milestone for now. Let's check back on it in a week.

**Comment by jeremiak** [comment]
Ran into a blocker with the prosemirror documentation, but have filed an issue [here](https://github.com/ProseMirror/website/issues/7)
