### ISSUE TITLE
Update user manual with information about how to conditionally set a robots.txt

### ISSUE THREAD

**Issue by maya** [18F/federalist#1888]
Most people will use the demo site as a staging environment, wouldn't it make sense to disallow search engines from indexing it like on other branch previews?

 #### User Story

As a Federalist site owner, I want search engines to index my real site and not point people to my staging site. Therefore, I want a way to set a robots.txt file that *only* is generated for my staging site without changing the build process of the main site.

#### Background (Optional)

Users can set conditional code in their sites to generate a robots.txt during the non-production builds only.

#### Acceptance Criteria

- [x] Create a demo site off of one of the templates
- [x] test suggested code on the template
- [ ] PR merged to docs site with example code and link to example implementation (showing that the robots.txt is present on a demo site but not the live site).

_After evaluating, edit this part:_

#### Level of effort -  low

**Comment by maya** [comment]
Another option, consider pointing to this code so developers can do it manually in their `<head>`:
```
{% unless site.env == "production" %}
  <meta name="robots" content="noindex, nofollow">
{% endunless %}
```

**Comment by wslack** [comment]
Will and @amirbey to talk more about this.

**Comment by wslack** [comment]
Prioritized!

**Comment by wslack** [comment]
@amirbey to try again!

**Comment by amirbey** [comment]
@wslack - what do you think about implementing this on federalist-docs and we can use that as an implementation example?

**Comment by amirbey** [comment]
@wslack - in addition to providing instructions to conditionally set robots,  is it necessary to show meta robots present on a demo vs. live site? If so, how do you suggest presenting this?

**Comment by wslack** [comment]
@amirbey good to go with federalist-docs

**Comment by wslack** [comment]
@wslack to write the basic code for this homepage and create a repo, trying to use the instructions. Amir to watch.

**Comment by wslack** [comment]
Couldn't create the repo, but we think we're going to fall back to using federalist-docs for this.

**Comment by wslack** [comment]
Huh, I don't see the file at https://federalist-proxy.app.cloud.gov/preview/18f/federalist-docs/wslack-patch-1/ - does it only work with a demo URL?
