### ISSUE TITLE
Define a content workflow

### ISSUE THREAD

**Issue by dhcole** [18F/federalist#189]
What should be the [GitHub Flow](https://guides.github.com/introduction/flow/) for writing content? Let's define this and implement in the Federalist interface.

My rough idea would be:

1. Before editing a site, create a draft
2. Multiple users can edit the same draft
3. Previews of the drafts can be shared behind a password
4. Once the draft is ready, submit it for review
5. A user accepts the draft and it is published

On the back end, this would be:

1. Create a new branch in the repo (you'd never be able to edit master directly)
2. [seeing branches is done]
3. [previewing branches is done]
4. Opens a pull request
5. Merges pull request and deletes branch

@melodykramer @gboone have any thoughts on this?

**Comment by gboone** [comment]
I like that flow. That's essentially the 18f.gsa.gov flow, though step 5is a separate manual step (or three).

**Comment by dhcole** [comment]
@gboone do you see a new to have a hard separation between users who write and users who publish, or can this be culture-enforced?

**Comment by gboone** [comment]
So far it's worked out well being culture-enforced. Technically anybody can merge their own pull requests but we've managed to avoid it in most cases.

**Comment by melodykramer** [comment]
I think we could write the directions so people wouldn't merge themselves, @dhcole

**Comment by gboone** [comment]
Yeah. +1. Great thing about culturally enforcing is giving content governance flexibility set these things on their own terms and be _really clear_ about why and how the publishing system works the way it does.

**Comment by dhcole** [comment]
@GailSwanson is taking the first pass at this. Gail, want to post here when your work is ready and then I'll pick it up for implementation?
