### ISSUE TITLE
Update federalist-docs toolbar look/feel

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1895]
#### User Story

When I visit the Federalist docs site from the Federalist site, I should feel like I'm still in "Federalist land" so that I feel safe.

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [ ] The Federalist-docs toolbar is updated to include a Federalist login button and the toolbar look/feel.

_After evaluating, edit this part:_

#### Level of effort - low

**Comment by eddietejeda** [comment]
Duplicate https://github.com/18F/federalist/issues/2029
