### ISSUE TITLE
Change name of federalist-docs site to "Federalist Support"

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1903]
#### User Story

As a Federalist user, I want to understand that I'm on the support site when I click into it, versus the main Federalist site.

#### Acceptance Criteria

- [ ] A new SVG is created that says "Federalist Support"
- [ ] It is uploaded onto the docs site.

_After evaluating, edit this part:_

**Comment by wslack** [comment]
Pending availability of a visual designer or front end developer.

**Comment by eddietejeda** [comment]
Duplicate https://github.com/18F/federalist/issues/2029
