### ISSUE TITLE
Build a library of includes

### ISSUE THREAD

**Issue by dhcole** [18F/federalist#191]
To make templates more modular, we can design a library of includes that can be dropped into any template. Could be something site-specific like a Digital Gov Search box, or something page-specific like a youtube embed that takes a youtube url and formats as a responsive embed using the no-cookie domain.

**Comment by el-mapache** [comment]
@wslack This is kind of similar to the template work scott is doing, correct? I think we can close this.

**Comment by wslack** [comment]
Similar yes, but don't know if we should close. Scott's work is for a config setting to create whole pages - vs HTML components that can dropped into templates.

**Comment by adborden** [comment]
IMHO, this is the kind of thing that having a community site would help with. Federalist users can post snippets of html/css/liquid that can be copy/pasted and reused. We could seed the site with some initial examples, but this would be maintained by the community.

The community site could also be implemented as a Federalist site (and ideally with Disqus, but I understand there's some hoops to jump through, first) :)
