### ISSUE TITLE
Enable Federalist users w/o repo write access to remove themselves as a Federalist collaborator

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#1913]
#### User Story

A user who who no longer has write access to a repo, I want to be able to remove myself as a collaborator from the site.

As a site owner, I only want to change the permissions in one place for  a collaborator to lose access to a Federalist site.

#### Background (Optional)

https://gsa-tts.slack.com/archives/C1NUUGTT5/p1531773679000203

#### Acceptance Criteria

- [x] A Federalist user removed from a GitHub repository (or dropped from write access) may remove themselves from the collaborators list.

_After evaluating, edit this part:_

#### Level of effort - low

**Comment by wslack** [comment]
This needs to be reviewed in sprint review
