### ISSUE TITLE
Make snazzy Federalist sales video

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1917]
#### User Story

As a evangelist for Federalist, I want to have something that I can easily share with others about Federalist.

As a possible Federalist user, I want to quickly learn Federalist's user story.

#### Background (Optional)

See #1805 and #1899

#### Acceptance Criteria

- [ ] DigitalGov has published a video on Federalist.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] Jeremy create initial deck
- [ ] Will and Jeremy create an initial set of images for the deck
- [ ] Will and Jeremy record [the script](https://docs.google.com/document/d/10Vsw_HtLXKXCB6mXRDyg-rjyp22SuzYHO-Pkw3m5kGM/edit) into audio
- [ ] Will records the audio, clicking through the deck

**Comment by eddietejeda** [comment]
I will close for now. We can reopen if we discuss this again.
