### ISSUE TITLE
Federalist build logs table redesign

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#1931]
#### User Story

As a Federalist user, when I check the build logs, I want to view the errors as one long scrolling page. In addition, I want jump-links to the sections of the logs.

When the logs are long, they are hard to view in their current, small little windows.

#### Background (Optional)

There was a request to see errors in a wider frame and also navigate between log sections using div and anchor tags.

#### Acceptance Criteria

- [ ] The build logs are in one text box

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by amirbey** [comment]
initial placeholder issue.  Requires A Further ?ness

**Comment by wslack** [comment]
IIRC this would mean not having three text boxes on the logs page.

**Comment by wslack** [comment]
Updated the user story; this is pending action form @jeremyzilar.

**Comment by jeremyzilar** [comment]
I updated the user story ☝️

**Comment by jeremyzilar** [comment]
I put together three rough ideas for how I feel like the logs page could function.
The side-nav would anchor-link you to the specific sections in the logs.

## v1
![federalist-logs-v1](https://user-images.githubusercontent.com/395641/44688806-64694d00-aa23-11e8-9fa8-86b857b8a8bc.png)

## v2
![federalist-logs-v2](https://user-images.githubusercontent.com/395641/44688848-7b0fa400-aa23-11e8-8414-1d9ba405db6e.png)


## v3
![federalist-logs-v3](https://user-images.githubusercontent.com/395641/44688854-7fd45800-aa23-11e8-9a88-5e8b8a51f79c.png)

## v4
![federalist-logs-v4](https://user-images.githubusercontent.com/395641/44688996-025d1780-aa24-11e8-963f-d18c0e3c0ad4.png)

**Comment by eddietejeda** [comment]
@amirbey what do you think of revisiting this?

**Comment by eddietejeda** [comment]
I like the first design the best, but I think it should include the colored circles of the last design to provide the status.

**Comment by eddietejeda** [comment]
Amir will need help with styling the menu.

**Comment by eddietejeda** [comment]
We can close this. We do not need the second level of navigation.

Thanks @jeremyzilar for the recommendation. Your changes are live!

**Comment by wslack** [comment]
🚀 ❤️
