### ISSUE TITLE
Federalist should be able to send notification when a build fails a la CircleCI

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1938]
#### User Story

<TODO>

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [ ] <TODO>

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by wslack** [comment]
Example: https://gsa-tts.slack.com/archives/C1NUUGTT5/p1533766687000126?thread_ts=1533763939.000371&cid=C1NUUGTT5

**Comment by maya** [comment]
These are the settings in CircleCI's Slack notifications:
>**Fixed/Failed Only:** Only send notifications for builds that fail or fix the tests and the first build on a new branch. Otherwise, send a notification for every build.

**Comment by wslack** [comment]
Feedback from team:
> High effort, medium impact, therefore low?
> Also low.

I am more interested in browser notifications that everyone can use than Slack integrations, given our overall customer base.

**Comment by wslack** [comment]
I'm going to close this as related to https://github.com/18F/federalist/issues/1659 but copy some info over there.

**Comment by wslack** [comment]
Closing otherwise as a dup or #1659 and https://github.com/18F/federalist/issues/1215
