### ISSUE TITLE
Users should see useful feedback when trying adding a repo that doesn't exist

### ISSUE THREAD

**Issue by dhcole** [18F/federalist#194]
@meiqimichelle ran into an issue while attempting to add a repository on the new site page that doesn't actually exist. There is no message displayed to the user. It appears as if the form never submits.

**Comment by dhcole** [comment]
Also the language around "owner" may be confusing. It follows GitHub's convention of a repository owner.

**Comment by meiqimichelle** [comment]
For context, I didn't know "owner" was a thing and so when I saw the end of the "owner" sentence on Federalist -- "GitHub username" I went with that. Now I know that "owner" is always part of the repo url and could have looked there to find the info. One solution could be text directing folks to that spot. Slightly different issue than the "adding repo that doesn't exist" feedback tho.
