### ISSUE TITLE
Include the preview link in the Build History view [pending spike]

### ISSUE THREAD

**Issue by jeremyzilar** [18F/federalist#1944]
As a user of Federalist, I often find myself having to browse over to the GitHub Branches tab in the Federalist Admin to find the preview link for my branch. 

Would it be possible to include the preview link in the "Build History" tab?

**Comment by wslack** [comment]
@jeremyzilar We haven't done this because of confusion for users that expect builds further down in the list to have available previews *from that specific commit* - when in fact previews are overwritten with each new build.

**Comment by wslack** [comment]
What do you think about that concern?

**Comment by wslack** [comment]
Notes: makes sense to JZ why we can't put it everywhere, maybe on the first line only?

**Comment by wslack** [comment]
@amirbey to check level of effort

**Comment by wslack** [comment]
Closing in favor of https://github.com/18F/federalist/issues/1974
