### ISSUE TITLE
Federalist homepage menus render incorrectly

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1949]
#### User Story

As a Federalist visitor or user, I can't easily use the bottom menu at certain screen widths because of strange behavior of the responsive design.

#### Background (Optional)

![Screen Shot 2018-08-21 at 2.13.41 PM.png](https://images.zenhubusercontent.com/576b0940bf93871ccd9d0a0b/c04d5ec0-c9a1-40dc-999f-3ce9c1516cec)

#### Acceptance Criteria

- [x] The menu renders cleanly at all widths
- [x] will go live in a prod deploy of Federalist app

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by wslack** [comment]
Will to talk to Aaron next time we see him.

**Comment by adborden** [comment]
I'll be at standup tomorrow, talk to you then!

On Tue, 2018-08-28 at 11:11 -0700, Will Slack <notifications@github.com> wrote:
> Will to talk to Aaron next time we see him.
> 
> -- 
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub:
> https://github.com/18F/federalist/issues/1949#issuecomment-416686764

--
Aaron D Borden
Human and Hacker
