### ISSUE TITLE
garden build deployed to registry via circle ci

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#1951]
#### User Story

As a Federalist developer, I want to be able to smoothly and safely deploy a new container image.

#### Background (Optional)

Right now, container image deployments take several steps, including using a local container to backdoor the image into a registry.

If we set this up, a federalist user can build a site using the garden build image on staging/prod as soon as it is merged into staging/master branch.

The trickiest part should be waiting for the registry to start.

#### Acceptance Criteria

- [x] Site containers can be deployed with one manual action: clicking "merge" on a PR.
- [x] This will be deployed by federalist-garden-build

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [x] Circle has the AWS access keys to store the images
- [x] Build a deploy script that recreates the manual workflow inside of CircleCI.

**Comment by wslack** [comment]
Chat with Jonathan when back!

**Comment by wslack** [comment]
Lower priority because of the effort/impact ratio.
