### ISSUE TITLE
Move 404 default page into a separate file, separate from publish script

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1952]
#### User Story

As a Federalist developer, manipulating the Federalist default 404 content is easier if its a separate file.

#### Background (Optional)

See https://github.com/18F/federalist-garden-build/pull/138#issuecomment-415145665

#### Acceptance Criteria

- [x] The file can be edited in clean HTML.
- [x] This change will be deployed by updating the build container image.

_After evaluating, edit this part:_

**Comment by eddietejeda** [comment]
This would be resolved when we moved each site to its own S3 bucket

**Comment by amirbey** [comment]
there will be additional effort required  ... b/c the 404.html must exist at the root of the bucket.

**Comment by amirbey** [comment]
the 404 page exists in its own separate repository and is editable via html and making changes do not require modifying build container ... thanks to @alexsoble

**Comment by wslack** [comment]
👏 👏 👏 (someday I'll stop getting notifications on these, but I still enjoy them 😄)
