### ISSUE TITLE
Error reported about RedCloth when creating a new site 

### ISSUE THREAD

**Issue by openbrian** [18F/federalist#196]
gh-pages (openbrian) 10/08/2015 2:33 PM
Command failed: Cloning into './.tmp/source/openbrian/developer-hub/gh-pages'... /usr/lib/ruby/vendor_ruby/bundler/spec_set.rb:92:in block in materialize': Could not find RedCloth-4.2.9 in any of the sources (Bundler::GemNotFound) from /usr/lib/ruby/vendor_ruby/bundler/spec_set.rb:85:in map!' from /usr/lib/ruby/vendor_ruby/bundler/spec_set.rb:85:in materialize' from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:140:in specs' from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:185:in specs_for' from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:174:in requested_specs' from /usr/lib/ruby/vendor_ruby/bundler/environment.rb:18:in requested_specs' from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:13:in setup' from /usr/lib/ruby/vendor_ruby/bundler.rb:127:in setup' from /usr/lib/ruby/vendor_ruby/bundler/setup.rb:18:in ' from /usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in require' from /usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in require'

**Comment by openbrian** [comment]
This error was given, when using debian sid, and running npm install.  Docker was not used.

**Comment by openbrian** [comment]
No error reported when using docker.

gh-pages (openbrian) 10/08/2015 4:01 PM
The build completed successfully.

**Comment by dhcole** [comment]
This should be avoided now by changes in the build process in #220. Please let us know if you're still seeing an issue.
