### ISSUE TITLE
Determine if Federalist should be technically aligned with CMS/CMS-like tools

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1960]
#### User Story

As a Federalist content creator, I want to be able to view my posts and meta information in a more structured way than Github allows.

#### Background (Optional)

Jeremy set up https://federalist-proxy.app.cloud.gov/site/gsa/digitalgov-workflow/, which allows a variety of workflows to manage the meta info of his site digital.gov. This site uses an JSON file generated during build inside Hugo.

#### Acceptance Criteria

- [ ] <TODO>

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by wslack** [comment]
cc @jeremyzilar

**Comment by wslack** [comment]
Will to set up a meeting with Corey, Eddie, Amir, and Jonathan.

**Comment by wslack** [comment]
Pending for @eddietejeda

**Comment by wslack** [comment]
This is neat, but a nightmare to maintain:

- Other open source tools exist
  - If we could do these locally would be best or via optional GitHbu plugins that customer can use or not use however they wish
- Relies on a specific data structure that could be brittle

**Comment by wslack** [comment]
Making a 3rd party tool at /admin work would require moving previews off of a common domain. Would have to add it to the templates.

**Comment by eddietejeda** [comment]
This issue is now being tracked here: https://github.com/18F/federalist/issues/2170
