### ISSUE TITLE
Update CORS settings for digital.gov

### ISSUE THREAD

**Issue by jeremyzilar** [18F/federalist#1961]
#### User Story

As a site owner, I would like to update the CORS whitelist for **digital.gov** team.

```
"AllowedOrigins": [
    "http://localhost",
    "https://federalist-proxy.app.cloud.gov/",
    "https://plainlanguage.gov",
    "https://workflow.digital.gov",
    "https://designsystem.digital.gov",
    "https://emerging.digital.gov"
],
```

Shouldn't  `http://localhost` and `https://federalist-proxy.app.cloud.gov/` be applied to every site out of the box?

#### Background (Optional)

When this is in place and working, you should see the full contents of a blog post on this page: https://federalist-proxy.app.cloud.gov/site/gsa/digitalgov-workflow/edit/?page=https://digital.gov%2F2018%2F07%2F17%2Fexperiments-in-tweaking-agile-for-ux%2F

#### Acceptance Criteria
- [x] This is set in the staging and prod.
- [x] Jeremy validates that the new CORS works.

#### Level of effort: low.

**Comment by wslack** [comment]
@amirbey what should the acceptance criteria be for this?

**Comment by amirbey** [comment]
@jeremyzilar - CORS updated in staging and prod  ... please validate things are working as you are expecting

**Comment by jeremyzilar** [comment]
It seems to be working here: https://federalist-proxy.app.cloud.gov/site/gsa/digitalgov-workflow/edit-taxonomy/?page=https://digital.gov%2F2018%2F07%2F17%2Fexperiments-in-tweaking-agile-for-ux%2F

However it is not working on `localhost`. 
Maybe we need to change it to `http://localhost:4000/`?

**Comment by wslack** [comment]
Amir to add for localhost:4000

**Comment by amirbey** [comment]
added 
"http://localhost:8000", // gatsby
"http://localhost:4000", // jekyll
"http://localhost:1313", // hugo
"http://localhost:80",
"http://localhost:8080",

**Comment by jeremyzilar** [comment]
Yes sir! That worked 🎉 Thank you @amirbey !
