### ISSUE TITLE
Spike: check level of effort for #1944

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1963]
https://github.com/18F/federalist/issues/1944

Less than 1 hour of work

- [x] Mark as done after new issue filed for change.

**Comment by amirbey** [comment]
Level of effort is Medium
Tasks Involved:
use map to track whether branch link has been displayed on prvious row
if not, Add BranchViewLink to buildLogs table
Update view site link

Super duper edge case:
Note: Builds are displayed by creation date which appears to be best.
If the a branch's most recently completed build is more than 100 site builds ago  and has a more recently created build (<= 100 builds ago) which is not the most recently completed build.
