### ISSUE TITLE
Allow Federalist user to specify hugo version

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#1976]
#### User Story

As a Federalist user or admin with a hugo site, I want to be able to specify my Hugo version in my repository.

#### Background (Optional)

This would achieve feature parity with other services like Ruby, NVM, RMC. We don't have a way to pass that information in right now.

#### Acceptance Criteria

- [x] Deploy change to build container for @DKP review.
- [x] Change made live via deploying build to federalist-registry
- [x] Add instructions for changing .hugo_version to federalist-docs

_After evaluating, edit this part:_

#### Level of effort - low, perhaps medium

**Comment by wslack** [comment]
Want to do this this sprint?

**Comment by wslack** [comment]
Oh nvm, zenhub broke. I see now.
