### ISSUE TITLE
Announce personnel change

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1980]
#### User Story

As the Federalist director, I need to tell people about upcoming changes to Federalist leadership.

#### Acceptance Criteria

- [x] e-mails sent

_After evaluating, edit this part:_

**Comment by eddietejeda** [comment]
have a draft to share yet?

**Comment by wslack** [comment]
https://docs.google.com/document/d/1Vtxd758f7slsfGUO4_kS0YAkYvNX2I6azNivh1IucHQ/edit#

**Comment by wslack** [comment]
@eddietejeda we only close completed work during retro (at least right now) :)
