### ISSUE TITLE
Uploaded files - appear to only show master branch files and not the selected branch

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#1986]
#### User Story

As a Federalist user, I want to see the files uploaded in a particular branch when troubleshooting.

#### Background (Optional)

This might have been broken for a long time. It shows that the page is mainly used to troubleshoot live sites.

#### Acceptance Criteria

- [x] preview links point to the /preview/ path.
- [x] Change made live via deployment of Federalist app.

_After evaluating, edit this part:_

**Comment by amirbey** [comment]
<img width="1269" alt="screen shot 2018-09-19 at 1 44 37 pm" src="https://user-images.githubusercontent.com/1261794/45770915-b57af400-bc11-11e8-882d-e03344b2d164.png">


notice the url at the bottom vs the branch listed at the top

**Comment by wslack** [comment]
@amirbey good catch....

It looks like it works for master and demo but not previews. I wonder when that broke?

I moved to "ready."
