### ISSUE TITLE
upgrade github-passport to v1 (oAuth2)

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#1991]
#### User Story

As a Federalist user, I want a defense in depth and to mitigate all security possible concerns, even those with no standalone risks.

#### Background (Optional)

oAuth2 has some security improvements. We currently use OAuth1.

#### Acceptance Criteria

- [x] Upgrade to oAuth2
- [x] upgrade passport-github gem to v1
- [x] Add the the state to the oAuth request
- [x] Verify state in the oAuth callback.
- [x] The [VDP issue](https://github.com/18F/vuln-reports-private/issues/29) is resolved
- [x] Change made live via deploy of Federalist to staging
- [x] Change made live via deploy of Federalist to production

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by wslack** [comment]
Stuck on:

- Getting the state to an access token request (either creating a fake state or something, then getting it accessible by the package)
