### ISSUE TITLE
Webhook error: {"message":"Validation error: Validation is failed","status":400}

### ISSUE THREAD

**Issue by wslack** [18F/federalist#1993]
Two failed hooks, no obvious causes. Resolved itself with a new commit about two fails.

https://github.com/uswds/uswds/settings/hooks

**Comment by wslack** [comment]
Means that the model validations failed because the build record is invalid. We aren't sure why and will monitor for reoccurrence for the moment.

**Comment by eddietejeda** [comment]
Not relevant anymore.
