### ISSUE TITLE
spike: passport/passport-github - is it being maintained???

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#1994]
#### User Story

As a Federalist user, I would like to authenticate using a secure and maintained login process.

#### Background (Optional)

We're concerned that passport/passport-github is no longer healthy and if we should continue to leverage it.

#### Acceptance Criteria

- [ ] Research possible passport replacements
- [ ] Federalist is using a authentication process that we have confidence in.
- [ ] Change made live via <TODO>.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by eddietejeda** [comment]
passport-github is a thin wrapper to passport, which is better maintained. We will keep an eye on this.

**Comment by eddietejeda** [comment]
The repo activity is light, but not pressing.
