### ISSUE TITLE
Trouble selecting bottom line of text in settings

### ISSUE THREAD

**Issue by awfrancisco** [18F/federalist#200]
I had difficulty selecting the bottom line of text (or a subsection of that line) in the input field of the settings tab. I could select any portion of text above it fine, but I was unable to on the bottom line. I created another line of text and the problem persisted to that new bottom line, though I could now easily select text in the second to last line. 

Happy to demonstrate this for you if my description isn't clear.

**Comment by dhcole** [comment]
@jeremiak sending your way in case it's related to #201
