### ISSUE TITLE
Web-based tool to allow WYSIWYG editing of Federalist sites

### ISSUE THREAD

**Issue by wslack** [18F/federalist#2003]
#### User Story

As a Federalist user, I want to be able to edit a page without having to know markdown or deal with markdown directly.

#### Background (Optional)

- API call to list files: curl -i https://api.github.com/repos/18f/18f.gsa.gov/contents/pages
- Here is how jekyll-admin writes files.... that could replaced with API call: https://github.com/jekyll/jekyll-admin/blob/master/lib/jekyll-admin/file_helper.rb#L17

#### Acceptance Criteria

- [ ] <TODO>
- [ ] Change made live via <TODO>.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by eddietejeda** [comment]
This issue is now being tracked here: https://github.com/18F/federalist/issues/2170
