### ISSUE TITLE
Discrepancies between WYISWYG and Markdown sent to GitHub

### ISSUE THREAD

**Issue by awfrancisco** [18F/federalist#201]
Context is [here](https://github.com/18F/18f.gsa.gov/pull/1241), but I was editing a blog post for 18F and when I saved it and went to GitHub to merge it, there were two parts of the markdown that were different from what was shown in the WYSIWYG. 

1) There was a trailing `\` on the first line of content, which was not visible in the Federalist editor. 
2) I selected a phrase and the leading space and italicized it. Federalist showed only the word be italicized, but when I moved the post to 18F's staging site, it italicized the phrase and everything after it until it ran into the next `*`.

**Comment by dhcole** [comment]
Thanks @awfrancisco this is really helpful. @jeremiak what do you think?

**Comment by jeremiak** [comment]
Interesting, thanks for the issue @awfrancisco. I'll take a look now.

**Comment by jeremiak** [comment]
Recreated Andre's content update here: https://github.com/jeremiak/federalist-modern-team-template/commit/f22a56f4853ba9c83a1a9af93273848a84bfd8c2

These are the changes that are made to his content without editing the document at all. In other words, all changes in that commit were made by prosemirror by virtue of loading it into the editor and requesting the markdown back out.

**Comment by dhcole** [comment]
@jeremiak any luck with this? Should we move it out of the milestone / work more on it / close it out?

**Comment by jeremiak** [comment]
@dhcole - I personally think we should either move it out of the milestone or even close it out. The editor will change content the first time its loaded because it will escape some characters and line breaks but won't do it on subsequent loads of the editor

**Comment by dhcole** [comment]
> 2) I selected a phrase and the leading space and italicized it. Federalist showed only the word be italicized, but when I moved the post to 18F's staging site, it italicized the phrase and everything after it until it ran into the next *.

@jeremiak anything we can do about that one, or is that just a quirk of the editor and whitespace?

**Comment by jeremiak** [comment]
@dhcole I think that's a quirk of the editor. I'm not sure that the maintainer(s) of the library would be interested in stripping white space from the selection before applying some of the formatting so I am going to close this issue for now.
