### ISSUE TITLE
Refresh content for developer experience

### ISSUE THREAD

**Issue by eddietejeda** [18F/federalist#2016]
#### User Story

As a developer of a new Federalist website, I want an easy way to get started. To do so, I need code templates that use best practices and are easy to customize.

#### Background (Optional)

This is related to work that Aaron is doing in the redesign of themes.

#### Acceptance Criteria

- [ ] <Check in Aaron to define criteria>

**Comment by wslack** [comment]
Here's the content I was referring to: https://federalist-proxy.app.cloud.gov/preview/18f/federalist-docs/adb-quickstart/pages/using-federalist/getting-started/

**Comment by eddietejeda** [comment]
We've reorganized the documentation page: https://federalist.18f.gov/documentation/
