### ISSUE TITLE
Update doc to explain how Federalist is free to testing, but require contract to move to production,

### ISSUE THREAD

**Issue by eddietejeda** [18F/federalist#2025]
#### User Story

As a potential Federalist user, I want to use Federalist to try out ideas, but need to understand when I need to convert to paying customer.

#### Acceptance Criteria

- [x] Update Federalist-docs to explain how protypes can be built for free but need to pay once it moves to production.

**Comment by eddietejeda** [comment]
@amirahaziz can you update the documentation page?

**Comment by amirahaziz** [comment]
I think we should add a new sub-tab to this page. It should be called "Getting started with Federalist sandboxes", and it should be located right under "customer responsibilities", and before "getting started with Jeklyll". Here's a draft of what that bullet should say: 
https://docs.google.com/document/d/1zOpKpgiolGg9h_eOOnTW7mnLnOIgY3Q_HOIkYzyC4Ic/edit

**Comment by amirbey** [comment]
@amirahaziz to raise PR
