### ISSUE TITLE
Buffer constructor deprecated in Node 10

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2034]
#### User Story

A Federalist user should securely use Federalist which is running current Buffer constructors.

#### Background (Optional)

(node:297) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/

#### Acceptance Criteria

- [x] Replace new Buffer() constructors
- [x] Update packages that use new Buffer() constructors
- [x] Change made live via deploy of Federalist.

_After evaluating, edit this part:_

#### Level of effort - Low

**Comment by eddietejeda** [comment]
This will require looking at all our deps and ensuring they are all current. We are going to do this piecemeal and check back in on January 7th.

**Comment by amirbey** [comment]
identified dependencies using new Buffer

dependencies
["aws-sdk", "body-parser", "db-migrate", "deep-extend", "express", "express-session", "newrelic", "pg", "rc", "sequelize", "socket.io", "urlsafe-base64", "winston"] 

devDependencies
["eslint-plugin-scanjs-rules", "json-schema-deref-sync", "mocha", "mock-fs", "nock", "node-sass", "nodemon", "nyc", "postcss-loader", "webpack"]

**Comment by eddietejeda** [comment]
Updates to 'sequelize' has caused problems and has requiring us to make changes to our application to support latest version of sequelize.
