### ISSUE TITLE
[WIP] Inject Google Analytics into all Federalist builds to track usage?

### ISSUE THREAD

**Issue by eddietejeda** [18F/federalist#2039]
#### User Story

As the manager of Federalist, I want to keep track of all Federalist sites with Google Analytics.

**Comment by davemcorwin** [comment]
This seems too invasive to me and ultimately it is the customer's responsibility to at least include DAP on the page. In addition, the nature of certain Federalist sites (SPAs) would require GA to be further integrated into the site than we could implement to provide accurate data.
