### ISSUE TITLE
Handle error messages consistently

### ISSUE THREAD

**Issue by dhcole** [18F/federalist#205]
We're handling error messages in a few different ways. Sometimes they're just strings; sometimes there's node Error objects.

On the client, sometimes we surface errors from the `error` query param, sometimes from the response of an error ajax response. Sometimes the server redirects (previews) and sometimes it doesn't (403 access error on any other page).

We should come up with and implement a consistent error reporting plan.

**Comment by dhcole** [comment]
Another example: user interface errors: https://github.com/18F/federalist/pull/240/files#diff-fea22b01f3d3a16912a825704e0da8e0R28

**Comment by wslack** [comment]
We want:

- [ ] A consistent way to communicate error messages
- [ ] A way to make sure that error messages for lacking admin permissions display correctly.

related to #648.
