### ISSUE TITLE
Ensure that themes support sitemaps by default to automatically work with Search.gov

### ISSUE THREAD

**Issue by eddietejeda** [18F/federalist#2051]
#### User Story

As a Federalist that would like to use Search.gov, I need to install `jekyll-sitemap` to keep my indexes up to date. Instead of requiring users to install this themselves, `jekyll-sitemap` could be provided as part of the standard package.

### Background

More information: https://help.github.com/articles/sitemaps-for-github-pages/ 
cc: @konklone @karentrebon

#### Acceptance Criteria

- [ ] Evaluate whether adding support for `jekyll-sitemap` by default is backward compatible.
- [ ] Add `jekyll-sitemap` to the default Jekyll themes
- [ ] Release a new version of default themes.

**Comment by afeijoo** [comment]
We're also running into this issue on several Federalist sites that use Search.gov. 

cc: @dawnpm & @wslack
