### ISSUE TITLE
Update CORS settings for workflow.digital.gov

### ISSUE THREAD

**Issue by jeremyzilar** [18F/federalist#2054]
#### User Story

As a site owner, I would like to update the CORS whitelist for **workflow.digital.gov**.

Can you make sure that the settings that are applied to **digital.gov**, are the same for **workflow.digital.gov**?

**See 👀**  https://github.com/18F/federalist/issues/1961

---

```
"AllowedOrigins": [
    "http://localhost",
    "https://federalist-proxy.app.cloud.gov/",
    "https://plainlanguage.gov",
    "https://workflow.digital.gov",
    "https://designsystem.digital.gov",
    "https://emerging.digital.gov"
    "http://localhost:8000", // gatsby
    "http://localhost:4000", // jekyll
    "http://localhost:1313", // hugo
    "http://localhost:80",
    "http://localhost:8080",
],
```

Shouldn't  `http://localhost` and `https://federalist-proxy.app.cloud.gov/` be applied to every site out of the box?

#### Background (Optional)

When this is in place and working, you should see no CORS error in the console on https://workflow.digital.gov/edit-topics/?page=https://demo.digital.gov/event/2018/11/07/dap-learning-series-basics-ab-testing-part-2/

#### Acceptance Criteria

- [ ] This is set in the staging and prod.
- [ ] Jeremy validates that the new CORS works.
- [ ] Jeremy has a text record of the `AllowedOrigins` for both digital.gov and workflow.digital.gov that we can use in our documentation/wiki.

#### Level of effort: low.

**Comment by eddietejeda** [comment]
Our team discussed this with @jeremyzilar and waiting on @amirbey to get back from PTO to make decision on how we can handle this in the future.

**Comment by eddietejeda** [comment]
Hi Jeremy. We are exploring supporting https://www.netlifycms.org for Federalist instead.
