### ISSUE TITLE
User Provided Environment Variables

### ISSUE THREAD

**Issue by eddietejeda** [18F/federalist#2056]
#### User Story

Site owners are unable to provide environment-specific configuration to their builds on Federalist.

In keeping with creating 12 Factor applications, users should be able to provide environment-specific configuration to their builds. This is especially important as builds can interact with 3rd party APIs that may require secrets for authentication, such as API keys. Currently, with one exception, users are unable to provide environment-specific information to their builds.

#### Acceptance Criteria

- [x] Site owners can create environment variables that are injected into the build environment
- [x] Site owners can remove environment variables
- [x] Site owners can view the last 4 characters of each environment variable
- [x] Site owners are presented with content informing them of Federalist's FISMA low status and the impact on environment variables
- [x] environment variables are encrypted and only decrypted in the garden build
- [x] documentation is updated to include how to use environment variables

#### Implementation outline (if higher than "low" effort):

- [x] See https://docs.google.com/document/d/1Rl-IjLJtOXb0RZZbsH428XqyuO2W9uyGYBZqFdLSx5w/edit#
- [x] Update documentation 
- [x] Explore if this behavior should be changed on the application

**Comment by davemcorwin** [comment]
Feature proposal to add User Provided Environment Variables: https://docs.google.com/document/d/1Rl-IjLJtOXb0RZZbsH428XqyuO2W9uyGYBZqFdLSx5w/edit#

cc @amirbey 
cc @pburkholder - curious to get your thoughts on this in general and how it might impact our SSP.

**Comment by jeremyzilar** [comment]
As a site owner, I would love to have greater control over the build scripts that run on preview branches and master.

At a minimum, there are three environments that we'd like to have more control over:
- master (_production_)
- demo (_staging_)
- preview (_dev_)

With **Hugo** there are a number of flags that we'd like to pass into the build scripts for each of these environments:
- [specify different config files](https://gohugo.io/getting-started/configuration/) based on the ENV
- minify the HTML (only on master)
- Run additional logging (on dev)

Having the ability to specify the config in the build script would give us the ability to exclude certain pages from our builds on DEV ad Staging branches. This would greatly reduce the time it takes to wait for a preview build to complete.

[More »](https://gsa-tts.slack.com/archives/C1NUUGTT5/p1587641430124800)
