### ISSUE TITLE
update search.gov handle from federalist-docs to federalist.18f.gov

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2064]
#### User Story

A federalist.18f.gov user should be able to search via the search bar on federalist.18f.gov

#### Background (Optional)

https://github.com/18F/federalist.18f.gov/blob/b102821c8fff66969d136b3ac797f1cfcfdc3bf5/_config.yml

#### Acceptance Criteria

- [x] update search.gov to federalist.18f.gov
- [x] [<update search.gov in federalist.18f.gov settings](https://github.com/18F/federalist.18f.gov/blob/e96b25ecb3c9845ba3bf0cd99845e05f1e5ac3e2/_config.yml#L16)
- [x] Change made live

**Comment by amirbey** [comment]
@eddietejeda - you've done this right? it can be closed?

**Comment by eddietejeda** [comment]
Yes
