### ISSUE TITLE
Use mobile friendly tables

### ISSUE THREAD

**Issue by davemcorwin** [18F/federalist#2106]
#### User Story

As a user I want mobile-friendly tables

![Screen Shot 2019-01-22 at 3.11.58 PM.png](https://images.zenhubusercontent.com/55539b1a4f7a08fbb7f2c453/591f6dba-39cd-46f3-82f7-f85a34e74f8d)

#### Acceptance Criteria

- [ ] Submit issue to design lab 
- [ ] Mobile friendly tables
- [ ] Change made live via Federalist.

#### Level of effort - <low/medium/high>
medium

**Comment by davemcorwin** [comment]
There is nothing straightforward I can do to just make the tables "work" on mobile. I think we should consider grabbing a designer to re-evaluate the table in a mobile-friendly way. I think something along the lines of "blades" instead of a table will probably work better. most of the content is understandable from the context and without table headers, so something adkin to https://circleci.com/dashboard could work, but I am wary of causing any accessibility issues.

**Comment by amirahaziz** [comment]
Submit a design issue to design lab: David will do this ^ (we have a few hours we can dedicate to this)

**Comment by davemcorwin** [comment]
Circle CI example:
![screen shot 2019-02-28 at 10 36 11 am](https://user-images.githubusercontent.com/6662371/53589673-d04c7f80-3b44-11e9-9056-f942f0a87e05.png)

**Comment by davemcorwin** [comment]
Design-lab issue submitted

**Comment by davemcorwin** [comment]
Waiting on https://github.com/18F/design-lab/issues/56

**Comment by davemcorwin** [comment]
https://github.com/18F/design-lab/issues/56 is complete, see for final images to implement.

**Comment by eddietejeda** [comment]
For those that don't have access to design-lab, here are the screenshots:

![federalist-tables--desktop](https://user-images.githubusercontent.com/2374206/55195366-bbcec780-5182-11e9-845f-ae189bed8e53.jpg)
![federalist-tables--mobile](https://user-images.githubusercontent.com/2374206/55195367-bbcec780-5182-11e9-9212-3045472e2a64.jpg)

**Comment by eddietejeda** [comment]
This is in production
