### ISSUE TITLE
Turn off Redux logging and React devtools in production environments

### ISSUE THREAD

**Issue by davemcorwin** [18F/federalist#2116]
#### User Story

As a user I should not see debugging information in the browser console or be able to inspect the application with React Devtools when using Federalist.

#### Acceptance Criteria

- [x] Redux logging messages should not appear in the console in staging and production environments.
- [x] React devtools should not be available in staging and production environments
- [x] Change made live via Federalist.

#### Level of effort - <low/medium/high>

low

**Comment by eddietejeda** [comment]
Duplicate #1481
