### ISSUE TITLE
Design a friendly and helpful 404 page for federalist client sites

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2129]
#### User Story

When a user encounters a 404 error wen visiting a site build with Federalist, they should see a well styled 404 page.

#### Background (Optional)

Turn this
![Screen Shot 2019-01-31 at 3.57.28 PM.png](https://images.zenhubusercontent.com/5a9d80ac4b5806bc2bc97452/505ce003-1fa8-4829-9929-0cfaa4c15f06)
into this:
![Screen Shot 2019-01-31 at 3.57.49 PM.png](https://images.zenhubusercontent.com/5a9d80ac4b5806bc2bc97452/02dac3df-4c75-4c3a-9f79-4be86d404e05)

#### Acceptance Criteria

- [x] upload to staging
- [x] create repo for tracking 404.html page 
- [x] Change made live via upload to production s3.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [x] Implement 404 design

**Comment by amirbey** [comment]
For reference: https://federalist-proxy.app.cloud.gov/404/index.html

**Comment by alexsoble** [comment]
Thanks @amirbey! 👍 🌈 ✨
