### ISSUE TITLE
Document mono-repo approach to hosting sites

### ISSUE THREAD

**Issue by eddietejeda** [18F/federalist#2137]
#### User Story

As the manager of multiple websites hosted on Federalist, I want to structure my sites in a mono-repo and host multiple sites within on repository. At the moment there is no clear documentation or example on how to support this functionality 

#### Background

- [x] Develop small script to show how you can structure multiple projects in one repository
- [x] Document how you can structure in /documentation page.

**Comment by davemcorwin** [comment]
Example mono-repo site: https://github.com/18F/federalist-monorepo-test

Do we want to keep this around as an example?

**Comment by eddietejeda** [comment]
Yeah, lets keep it around. We can make refinements to that example as our processes evolve.
