### ISSUE TITLE
When users are automatically removed, it noted it in the existing collaborators log

### ISSUE THREAD

**Issue by eddietejeda** [18F/federalist#2139]
#### User Story

When a user is automatically removed from Github access, track change in user-actions.

#### Background (Optional)

https://github.com/18F/federalist/issues/1914

#### Acceptance Criteria

- [x] when user is removed/added from SiteUser ... denote in the site-actions and collaborators list as appropriate
- [x] re-enable audit - undo #2140 
- [x] Change made live via push to Federalist

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by amirahaziz** [comment]
Will push to live 2/21
