### ISSUE TITLE
add jekyll and gatsby beta templates to federalis

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2145]
#### User Story

<TODO>

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [ ] <TODO>
- [ ] Change made live via <TODO>.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by eddietejeda** [comment]
Duplicate https://github.com/18F/federalist/issues/2115
