### ISSUE TITLE
rename federalist to federalistapp

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2148]
#### User Story

A federalist developer should view the fedearlist app as federalista pp in the cloud.gov dashboard.
A federalist user should be able to connect to federalist via websockets at federalistapp.fr.cloud.gov

#### Background (Optional)

Federalist.18f.gov application has been renamed Federalistapp.18f.gov 
and 
federalist-docs.18f.gov site has been renamed federalist.18f.gov

#### Acceptance Criteria

- [x] update manifests
- [ ] Change made live via push of Federalist
- [x] remove federalist-staging

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by amirahaziz** [comment]
After the release we can close, ETA release: 2/21
