### ISSUE TITLE
Set up a second space on Cloud Foundry

### ISSUE THREAD

**Issue by jeremiak** [18F/federalist#215]
There are some classes of bugs that are hard to reproduce locally so it would be helpful to have a second Cloud Foundry instance. This could be called `staging` or `secondary`, and wouldn't be part of the release process.

I'm imaging that it is just triggered by a branch name, so I can cut a `staging` branch from any commit, `git push --force` it to Github on that branch and it would deploy to Cloud Foundry so that I could test changes without having to release them to production.

**Comment by jeremiak** [comment]
I tried to deploy the app to the `dev` space within `federalist` org but I ran up against our memory limit:
> `Server error, status code: 400, error code: 100005, message: You have exceeded your organization's memory limit.`

Should I ask the devops team for a quota increase or is there another way around this error, @dhcole?

**Comment by dhcole** [comment]
I scaled down my testing application for containers to 1 instance instead of two. That should free up enough space to deploy another app. We could also ask for a memory increase if that doesn't work.

**Comment by dhcole** [comment]
Closing this as we're now using Docker for local testing.
