### ISSUE TITLE
Process for launching a new Federalist homepage

### ISSUE THREAD

**Issue by eddietejeda** [18F/federalist#2153]
#### User Story

As a potential user of Federalist, I need to have an overview of what a typical engagement looks like and what to expect.

#### Background

We can provide users with an overview of what our engagement looks like on the home page.

#### Acceptance Criteria

- [x] Document the major steps in launching a new site
- [x] Get confirmation from team that this is accurate (Amirah waiting for Eddie to review)
- [x] Amirah working with Jeff to review language 
- [x] Eddie: Make staffing request: Work with design chapter to implement a design [similar to this 18F document](https://user-images.githubusercontent.com/21244661/46877099-01cee380-ce0e-11e8-8f9d-6d19246a7cbc.png) - Amirah will reach out to Austin about this on 4/1

**Comment by amirahaziz** [comment]
Drafted process map & language: 

https://docs.google.com/document/d/1SXvmcoarJQ_PQwh5Qg9_2IdIFsJy27Q-Z2cNBpunJHE/edit

**Comment by eddietejeda** [comment]
I will need to request a designer for this.

**Comment by eddietejeda** [comment]
@amirahaziz can you get feedback from @abbeykos ?

**Comment by amirahaziz** [comment]
Amirah updated the landing page with new tagline & headings

**Comment by amirahaziz** [comment]
Jeff said he will take a look and review this document as well. Here are the proposed changes: https://docs.google.com/document/d/1-Dzw5uPHfu-aALvNDPst-15_8Nm3kgEtpzjhcjDc5fQ/edit

**Comment by amirahaziz** [comment]
Jeff and I went over the content changes, and that has been finished. Now need to begin work with designer to put this together
