### ISSUE TITLE
Update websites & docs with new value proposition language

### ISSUE THREAD

**Issue by eddietejeda** [18F/federalist#2158]
#### User Story

As a potential user of Federalist, I want to understand the value of Federalist quickly and expect all the documentation that I read to be consistent in reiterating the value.

#### Background

The current value proposition and tagline on website do not speak to the direct benefit of Federalist

#### Acceptance Criteria

- [x] Change tag lines in 
    - [x] 18F website
    - [x] Federalist proposal
    - [x] GSA website on cyber security (https://www.gsa.gov/technology/government-it-initiatives/cybersecurity/cybersecurity-programs-policy) 
    - [x] Federalist homepage
    - [x] Insite (https://insite.gsa.gov/cdnstatic/Federalist-Proposal.pdf)
    - [x] Insite (https://insite.gsa.gov/cdnstatic/how-federalist-works-diagram.pdf)
    - [x] Digital.gov
    - [ ] ~18F UI Style Guide (https://github.com/18F/18f.gsa.gov/blob/master/_styleguide/subpages/for-developers.md)~
    - [x] 18F Handbook (https://handbook.18f.gov/federalist/)

**Comment by eddietejeda** [comment]
Reach out to @18F (@dahianna) to make the changes on the 18F website:

https://18f.gsa.gov/what-we-deliver/federalist/

And GSA.

**Comment by eddietejeda** [comment]
Ask @dahianna to overwrite existing links:

https://insite.gsa.gov/cdnstatic/Federalist-Proposal.pdf

**Comment by eddietejeda** [comment]
https://docs.google.com/document/d/1juNSJnJoTLzMX32XnHB5r3u3V3duqBrB4YPpclPMEFA/edit

**Comment by Bryanthales** [comment]
background on why we created a new landing page and this influences the pricing document. Kenny uses some of our documentation that is out of date, so ideally we could update this stuff.
