### ISSUE TITLE
Enable users to specify bundler version

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2162]
#### User Story

A Fedearlist user should be able to use the bundler version of their choosing.

#### Background (Optional)

A client is hindered from upgrading gems using bundler 2 because Federalist only builds in bundler 1 and fails.

#### Acceptance Criteria

- [x] build container to check for .bundler-version file and build version specified ... or default to v1 bundler
- [x] Change made live via deploy of federalist-garden-build
- [x] Add instructions to federalist-docs

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by eddietejeda** [comment]
https://federalist.18f.gov/pages/how-federalist-works/bundler-on-federalist/
