### ISSUE TITLE
buggy notification settings

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2165]
#### User Story

When a federalist user updates their site's notification settings, it should save on the first try.

#### Background (Optional)

Frequently, it can take multiple save attempts for the save to occur in the interface after refreshing the page.

#### Acceptance Criteria

- [ ] Change made live via deploy to Federalist

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by davemcorwin** [comment]
Update - I have no idea whats going on here. The request is triggering an error in the browser, as if it were getting bounced for CORS or other security policy, however, other PUT requests that are almost identical are OK AND the request seems to actually make it through to the server, but the response is never received/ignored by the browser...

**Comment by davemcorwin** [comment]
The above was slightly incorrect. In development, despite the error, the request DOES make it to the server and updates the database. In staging/prod this does not happen.

**Comment by eddietejeda** [comment]
Hey @davemcorwin, so the fix was a preventDefault? That's it?

**Comment by davemcorwin** [comment]
@eddietejeda yes. When that is not called, the form submission triggers a page navigation which cancels any outstanding ajax requests. Depending on the timing, the request may or may not actually make it to the server, but regardless, the UI doesn't receive the response.
