### ISSUE TITLE
bug: adding unauthorized site is displaying inaccurate error message

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2166]
#### User Story

When a user attempts to add a new site to Federalist of which they are not an admin, they should receive an error message stating so.

#### Background (Optional)

https://gsa-tts.slack.com/archives/C1NUUGTT5/p1551380001000600

#### Acceptance Criteria

- [x] Ensure meaningful error messages that are not swallowed up by the auto-refresh error

**Comment by amirbey** [comment]
@davemcorwin - in pull https://github.com/18F/federalist/pull/2110/files ...
if the status === 'error' then the message is overridden with the hardcoded error message.  However, it is also preventing meaningful error message from being displayed. Is there another condition that is more specific to the refresh builds/logs failure that could be used to override the display the hardcoded error message specifically for the refresh failure?

**Comment by davemcorwin** [comment]
Appears to be working, received the below when attempting to add a repo to which I do not have admin access:

![Screen Shot 2019-03-27 at 1.59.01 PM.png](https://images.zenhubusercontent.com/55539b1a4f7a08fbb7f2c453/ec6ac175-d627-46bf-84cf-64b06aa6913e)

And received the expected error when builds refreshed while the application was stopped on Cloud.gov.

**Comment by eddietejeda** [comment]
This is now released.
