### ISSUE TITLE
Switch to GitHub Application owned by @18F

### ISSUE THREAD

**Issue by afeld** [18F/federalist#219]
@blacktm pointed out that Federalist is currently using an Application registered under @dhcole's account for OAuth...we should switch to using one under @18F. Just let me/#admins-github know what you want for each of these fields and we can set that up for you.

<img width="743" alt="screen shot 2015-10-27 at 4 55 19 pm" src="https://cloud.githubusercontent.com/assets/86842/10772297/ccb850e6-7ccb-11e5-9a3b-788259089c85.png">

Worth noting that all current users will need to reauthorize...don't think there's a way around that, unfortunately.

**Comment by dhcole** [comment]
Good catch — I never noticed. I just submitted a transfer to move the application to 18F. Can you accept it as an 18F admin? Shouldn't require changing any settings or keys.

**Comment by afeld** [comment]
Oh, sweet! Looks like it was accepted by someone, so all good.
