### ISSUE TITLE
Generate configuration when building the federalist proxy

### ISSUE THREAD

**Issue by apburnes** [18F/federalist#2192]
#### User Story

When a user creates a new site, the proxy server will have the site url added to its configuration

#### Background

To allow the `[federalist-proxy](https://github.com/18F/federalist-proxy)` to query all site bucket and region information and configure the proxy to all of the AWS endpoints

#### Implementation

- [ ] Add a `Procfile` with a `build` script
- [ ] Query the federalist database for all site's `awsBucketName`, `awsBucketRegion`, `owner`, `repository` that have **not** been `deletedAt`
- [ ] Generate route `configs` files to be included in the `ngnix` config

**Comment by eddietejeda** [comment]
This issue is no longer relevant. The approach of #2191 will supersede the issues outlined here.
