### ISSUE TITLE
Repository not found issue displayed for users who haven't logged in for a while

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2197]
#### User Story

A user who has not logged in for a while should not see a repo not found alert message until a repo verification has been completed since he/she has logged in.

#### Background (Optional)

reported by @philipashlock

#### Acceptance Criteria

- [ ] <TODO>
- [x] Change made live via <TODO>.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by eddietejeda** [comment]
See #2188
