### ISSUE TITLE
User navigation is not interactive in window is small/mobile

### ISSUE THREAD

**Issue by davemcorwin** [18F/federalist#2198]
@eddietejeda commented on [Fri Mar 29 2019](https://github.com/18F/federalist.18f.gov/issues/301)

@philipashlock reported that the MENU items on the right hand side of the site are not clickable when the screen is resized. I will reach out to Phil to provide screenshots.

---

@philipashlock commented on [Fri Mar 29 2019](https://github.com/18F/federalist.18f.gov/issues/301#issuecomment-478104085)

Tested with Firefox 65 on Mac OS. This only seems to be an issue when logged in. It doesn't seem to be a problem from the frontpage when not logged in. You can see that no hover state is triggered on the menu items and when clicking on one it just closes the menu but otherwise doesn't do anything. 

![federalist-menu](https://user-images.githubusercontent.com/183402/55254805-440aa680-522f-11e9-854b-cea890a57378.gif)

---

@eddietejeda commented on [Fri Mar 29 2019](https://github.com/18F/federalist.18f.gov/issues/301#issuecomment-478112367)

@davemcorwin can you take a look at this?

---

@davemcorwin commented on [Fri Mar 29 2019](https://github.com/18F/federalist.18f.gov/issues/301#issuecomment-478136572)

I observe the same behavior in Chrome.

---

@davemcorwin commented on [Fri Mar 29 2019](https://github.com/18F/federalist.18f.gov/issues/301#issuecomment-478148559)

This appears to be an issue with USWDS, I'm seeing if I can fix...

**Comment by eddietejeda** [comment]
@davemcorwin the "Sites" link points to: https://federalist-staging.18f.gov/
it should be: https://federalistapp-staging.18f.gov/sites

**Comment by davemcorwin** [comment]
@eddietejeda lets create a new issue for it, nothing here affected that.

**Comment by eddietejeda** [comment]
This is fixed now.
