### ISSUE TITLE
Rebuild button not rendering correctly

### ISSUE THREAD

**Issue by eddietejeda** [18F/federalist#2208]
The new button style is not rendering correctly in Branches section

<img width="820" alt="Screen Shot 2019-04-08 at 12 34 26 PM" src="https://user-images.githubusercontent.com/669988/55741266-db73b480-59fa-11e9-858d-93061dd5ae58.png">

**Comment by davemcorwin** [comment]
👍 @amirbey when developing locally, i don't see any branches on this screen, is this by design?

**Comment by amirbey** [comment]
i think it probably moreso the branches that exist for the repos you have on your local Federalist instance
