### ISSUE TITLE
Homepage process map: display key steps for getting started in a simple illustration 

### ISSUE THREAD

**Issue by eddietejeda** [18F/federalist#2215]
#### User Story

As a potential user of Federalist, I need the homepage to communicate what it does in a simple manner. Instead of showing users all functionality, focus on the key steps for getting started in a simple illustration.

#### Acceptance Criteria

- [x]  Complete content for Federalist landing page (including screenshots for process map)
- [x] find front-end volunteer for implementation @el-mapache 
- [x]  Work with frontend engineer to implement changes on the site 
- [x] add links for the process items once the contents is posted by @Bryanthales 
- [x] Release changes to live site

### Background
https://github.com/18F/federalist/issues/2153

#### Drafted Templates:

![image](https://user-images.githubusercontent.com/46540911/56765389-c8334980-675b-11e9-8415-333f1c9efef4.png)

![image](https://user-images.githubusercontent.com/46540911/56765430-da14ec80-675b-11e9-9386-f8b5e6e3ee57.png)

![image](https://user-images.githubusercontent.com/46540911/56765353-af2a9880-675b-11e9-8caf-0d39ad9faae4.png)

![image](https://user-images.githubusercontent.com/46540911/56765452-e8fb9f00-675b-11e9-8e79-e4b9cac009d8.png)

---

Amirah is working with @juliaklindpaintner on this issue.

**Comment by amirahaziz** [comment]
https://docs.google.com/presentation/d/1z4cZZ9xx57M-duJ3yrM7Fz6k7Tu-_9HBI4wAbiaelPU/edit?ts=5cb88deb#slide=id.p

**Comment by eddietejeda** [comment]
Julia is currently working on this. We will follow up this week.

**Comment by eddietejeda** [comment]
Can we have simplified/icon versions of the screenshots?

**Comment by juliaklindpaintner** [comment]
@eddietejeda Huh, that sounds interesting. You mean like illustrations? I'd love to collaborate to find out what the key things is you would want to show for each step.

**Comment by eddietejeda** [comment]
Yeah. Can you find time on my calendar?

**Comment by eddietejeda** [comment]
Woah, I just realized (forgot?) that Netlify uses a similar approach. 

https://www.netlify.com/

**Comment by juliaklindpaintner** [comment]
@eddietejeda @amirahaziz Sorry—I realized we didn't talk about a deadline for my next bit of work here after we spoke last week and then I was out on Friday. I think I remember the deadline generally being "as soon as possible," but just wanted to let you know that I'll definitely get to this this week. If you have any particular deadlines, let me know and I'll see if I can accommodate!

**Comment by amirbey** [comment]
should have drafts by EOD from design lab

**Comment by juliaklindpaintner** [comment]
@amirahaziz Wanted to share 2 potential design directions in advance of our check-in this afternoon.
![Screen Shot 2019-05-14 at 13 05 48](https://user-images.githubusercontent.com/42982184/57719197-38433a00-764d-11e9-8dce-c135ce4ce760.png)
![Screen Shot 2019-05-14 at 13 05 56](https://user-images.githubusercontent.com/42982184/57719198-38433a00-764d-11e9-9408-179391ca6d87.png)

**Comment by amirahaziz** [comment]
These are awesome! I really love both options, but I like the second options with the hands just because its a little more personal/engaging. @eddietejeda Any thoughts?

**Comment by davemcorwin** [comment]
these are great! i like the hands as well, but I do think they are a bit on the busy side.

Re: the text content for "Launch", I worry about "tech" since really thats up to the user. Perhaps we could add "deployment" instead so "You focus on the content, we'll worry about the security, compliance, deployment" ?

Re: the text content for "Manage", this is a little confusing to me. Is the CMS in reference to Netlify CMS? That would just control the content, but its the Federalist interface that "control[s] the process form start to finish". Maybe just "Use our intuitive interface to control the process from start to finish"?

**Comment by juliaklindpaintner** [comment]
@davemcorwin I really like both of those suggestions re: copy. I agree that the "Launch" image with the hand is too busy — I'll see what I can do to simplify it.

**Comment by eddietejeda** [comment]
I am on board with Corwin's suggestions.

**Comment by juliaklindpaintner** [comment]
Here's a draft in situ on the homepage!
[Federalist Homepage.pdf](https://github.com/18F/federalist/files/3193233/Federalist.Homepage.pdf)

**Comment by juliaklindpaintner** [comment]
New design proposal in situ on homepage. Feedback welcome
[Federalist Homepage.pdf](https://github.com/18F/federalist/files/3198209/Federalist.Homepage.pdf)

Here's the graphic only: 
![Screen Shot 2019-05-17 at 17 55 39](https://user-images.githubusercontent.com/42982184/58026775-37932380-7ae5-11e9-9fd3-d1c80f30e2d8.png)

**Comment by eddietejeda** [comment]
What's the status on this? Do we need a front-end engineer?

**Comment by juliaklindpaintner** [comment]
@eddietejeda Do you have any changes to the design? If not, I can go ahead and export the images and/or upload the sketch file here.

**Comment by eddietejeda** [comment]
Can you share exported images and sketch file to Slack?

**Comment by amirahaziz** [comment]
https://gsa-tts.slack.com/files/UCM110G4S/FJM4JQY90/federalist_homepage_redesign.sketch

Here is the Sketch file in Slack! I'll need to work with a front end engineer on our team to get this up on our sites. Thank you again! @juliaklindpaintner

**Comment by Bryanthales** [comment]
I think that this card is done now.
