### ISSUE TITLE
Gatsby Template build failing in staging

### ISSUE THREAD

**Issue by apburnes** [18F/federalist#2217]
#### User Story

When I tried to deploy the Gatsby template, the build was failing due to an error while loading a shared library.

### Error Message

```
> gatsby build "--prefix-paths"

success open and validate gatsby-configs — 0.012 s
success load plugins — 0.214 s
success onPreInit — 0.511 s
success delete html and css files from previous builds — 0.007 s
success initialize cache — 0.009 s
success copy gatsby files — 0.027 s
success onPreBootstrap — 0.004 s
success source and transform nodes — 0.377 s
success building schema — 0.323 s
success createPages — 0.000 s
success createPagesStatefully — 0.033 s
success onPreExtractQueries — 0.004 s
success update schema — 0.172 s
success extract queries from components — 0.115 s
success run graphql queries — 0.473 s — 3/3 6.38 queries/second
success write out page data — 0.014 s
success write out redirect data — 0.002 s


info bootstrap finished - 6.443 s

success onPostBootstrap — 0.001 s
success Building production JavaScript and CSS bundles — 15.115 s
success Building static HTML for pages — 1.170 s — 2/2 6.96 pages/second
info Done building in 22.734 sec

---------------------------
>> STDERR:
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.0/libvips-8.7.0-linux-x64.tar.gz
  ⚠ Command failed: /work/site_repo/node_modules/cwebp-bin/vendor/cwebp -version
/work/site_repo/node_modules/cwebp-bin/vendor/cwebp: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory


  ⚠ cwebp pre-build test failed
  ℹ compiling from source
  ✔ cwebp built successfully
  ✔ mozjpeg pre-build test passed successfully
  ✔ pngquant pre-build test passed successfully
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

#### Acceptance Criteria

- [ ] Staging builds the Gatsby template successfully

**Comment by davemcorwin** [comment]
Despite the error, it looks like the build and publish still succeeded?

**Comment by apburnes** [comment]
Ya I know... The Gatsby builds successfully but then throws the `sharp` dependency error so the site build log is registered as an error.

<img width="805" alt="Screen Shot 2019-04-17 at 1 09 08 PM" src="https://user-images.githubusercontent.com/693815/56317654-1ddf7480-6112-11e9-9aff-d63a5d613544.png">

**Comment by apburnes** [comment]
Also noticed the site's advanced settings had the site engine set to `Jekyll`.

**Comment by davemcorwin** [comment]
weird, I just ran it in federalist staging it "succeeded"...
<img width="790" alt="Screen Shot 2019-04-17 at 1 13 51 PM" src="https://user-images.githubusercontent.com/6662371/56317877-b249d700-6112-11e9-8733-043bc4896b1d.png">

FWIW - I do not see any errors when building locally.

Could this have something to do with changing the image we are using to build due to Cloud.gov deprecating the one we were using @amirbey ?

**Comment by apburnes** [comment]
Updated the site's advanced settings site engine from to `Jekyll` to `Node` and it worked!  Is there a way to update engine when using the templates?
