### ISSUE TITLE
Complete DOI success story

### ISSUE THREAD

**Issue by amirahaziz** [18F/federalist#2225]
#### User Story

Complete a DOI case study to add to growing bucket of Federalist success stories to be used in briefings and published to the Federalist website 

#### Acceptance Criteria

- [x] Eddie to send an email to DOI team introducing Amirah and purpose for case study
- [x] Amirah to interview DOI team (https://docs.google.com/document/d/1N9iUzoOFSn4vWF8yP7ZhWptAdBZZbbn99HmBOBbbsNM/edit)
- [x] Amirah to draft DOI case study based on interview notes (https://docs.google.com/document/d/1THOeo8EtbTEorgcAfES5y_hH_C5qycOhOUhwZFk-9ds/edit)
- [x] Amirah to share draft with DOI team for feedback
- [x] Amirah to build case study via new templates

**Comment by eddietejeda** [comment]
status: Interview is done, now working on the write up.

**Comment by amirbey** [comment]
@eddietejeda - pls review

**Comment by amirbey** [comment]
@eddietejeda - pls review

**Comment by amirbey** [comment]
@amirbey to review

**Comment by amirbey** [comment]
looks good!

**Comment by eddietejeda** [comment]
I left some notes. Let me know if you want to talk for more details.

**Comment by amirahaziz** [comment]
@amirbey Can you take a look at the final case study? Let me know if you think it needs to go through writing lab, or if we can build it right into the case study templates. Thanks! 

https://docs.google.com/document/d/1THOeo8EtbTEorgcAfES5y_hH_C5qycOhOUhwZFk-9ds/edit
