### ISSUE TITLE
Publish & publicize completed success stories 

### ISSUE THREAD

**Issue by amirahaziz** [18F/federalist#2226]
#### User Story

Our team has drafted, reviewed, edited and completed detailed success stories for AFWERX and CoE (with DOI in process). Once these stories are completed, its important to publish and publicize the stories to 18F and our customers. 

#### Acceptance Criteria

- [x] Build final success stories into new template designs 
- [x] publish stories onto Federalist 
- [x] link stories to Federalist home page 
- [ ] ~~Build success stories drafting deck (for future & current briefings)~~
- [x] Publicize stories throughout 18F (BD, strategy chapters, cloud.gov team, outreach)

**Comment by amirahaziz** [comment]
Draft: https://docs.google.com/presentation/d/1GEdNySEX4dPalDUjImwEadANPkQe8YLkPvRnvvb08rI/edit#slide=id.g5478bdf7d7_0_6

**Comment by amirbey** [comment]
@amirahaziz  - i have provided feedback as comments in the slide document

**Comment by amirahaziz** [comment]
@amirbey

I have written up a comms plan here:
https://docs.google.com/document/d/1Qn99YTqe6IB7S6I1aSWPXwyqWINezo3FhVZ0z2RpS7s/edit

**Comment by amirbey** [comment]
current success stories data is stored here: https://github.com/18F/federalist.18f.gov/blob/fb53677fd7289b2269cdf32a34b8b74b6dd147fb/_data/case_studies.yml

**Comment by amirbey** [comment]
@Bryanthales - i implemented the success stories into our new frontpage design .... you can preview it here https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/federalist.18f.gov/ab-homepage-redo-success/

**Comment by Bryanthales** [comment]
Heads up that I shared with Kenny that the new Federalist Success Stories were posted to the homepage of the site.
