### ISSUE TITLE
Process for migrating existing site from the shared to the private bucket

### ISSUE THREAD

**Issue by apburnes** [18F/federalist#2238]
#### User Story

As a user with an existing Federalist site, sites are hosted in a shared S3 bucket. This works well for them, but if they want to use the Netlify CMS interface, it will not be possible. Therefore, there should be a way for users to migrate their site to a private S3 bucket.

#### Acceptance Criteria

- [ ] Only if the site is in a shared bucket, the user will be presented with an option to "migrate" site
- [ ] Only an admin will see this option
- [ ] When the user clicks this option, they are presented with scary warnings to let them know the impact of this change. For example, they will need to change their registrar to the new S3 bucket location.
- [ ] When the build is complete in the new private s3 bucket and is successful, the cloudfront URL points to the new location.

**Comment by amirbey** [comment]
closed ... handled in #2297
