### ISSUE TITLE
Announce 1.0 

### ISSUE THREAD

**Issue by eddietejeda** [18F/federalist#2239]
Now that https://github.com/18F/federalist-uswds-jekyll/issues/14 is complete. We need to announce it to the world!

**Comment by eddietejeda** [comment]
@amirahaziz can you develop a first draft of a possible announcement? The goal is to publish it on the 18F website in May.

**Comment by eddietejeda** [comment]
some key points:
- the new web design system has been announced (say something about how great it is)
- federalist is the the easy way to get started with USWDS
- a bit of how federalist can help you build your sites
- we are excited to continue collaboration with USWDS
- TRY NOW!

**Comment by amirahaziz** [comment]
Drafted announcement here: https://docs.google.com/document/d/10L8KepksyFrOHgeHcfw097JKGOFcZy_bu1EdZ3GYhQs/edit

**Comment by eddietejeda** [comment]
I've looked it over and made some changes. Can you run this by the writing lab folks?

**Comment by amirbey** [comment]
@eddietejeda - has submitted this to writing to lab for review

**Comment by amirahaziz** [comment]
@eddietejeda Do you know if anyone in the writing lab picked this up?

**Comment by eddietejeda** [comment]
No one yet. Wanna check with individual people that you think can help? Cordelia? Jeff?
