### ISSUE TITLE
Improve new file addition

### ISSUE THREAD

**Issue by jeremiak** [18F/federalist#224]
This is a follow up to #174 because it is a bit of a weird experience for end users as it is currently implemented. Right now the experience is three steps:

1. Click "Add a new page" on the listing of pages in a site
![screen shot 2015-11-09 at 4 16 45 pm](https://cloud.githubusercontent.com/assets/780941/11046907/cca4b130-86fd-11e5-968d-2f18ae7b5011.png)

2. Enter the "path" of the new file. This is pretty confusing for anybody who uses Federalist because our pages/`_navigation.json` feature enables us to hide as much of the project structure as we want
![screen shot 2015-11-09 at 4 16 51 pm](https://cloud.githubusercontent.com/assets/780941/11046926/ecdfe71c-86fd-11e5-8781-8cf09370a461.png)

3. The editor loads with your new post. It looks for a file called `_defaults.yml` in the root of the project directory
![screen shot 2015-11-09 at 4 16 59 pm](https://cloud.githubusercontent.com/assets/780941/11046963/1c63693c-86fe-11e5-877b-38bfe20aef1f.png)

I'm sure this process can be easier to understand for end users. In particular, it should be easier for them to understand where the page will sit in relation to other pages in their site.

@GailSwanson and @dhcole, thoughts?

**Comment by jeremiak** [comment]
In addition, the defaults should be pulled from `_config.yml` and be the regular Jekyll post defaults. Right now they are expected to be in their own file `_defaults.yml`.

**Comment by dhcole** [comment]
@jeremiak all done, right?

**Comment by jeremiak** [comment]
:+1 all done
