### ISSUE TITLE
Netlify CMS: Restrict external authentication to repos that are deployed to isolated subdomains

### ISSUE THREAD

**Issue by davemcorwin** [18F/federalist#2242]
#### User Story

As a user, I do not want to be able to use Netlify CMS when my site is deployed to a shared domain since that jeopardizes the security of access to my Github repo.

#### Background (Optional)

While we roll out isolated S3 bucket/isolated subdomain deployments, there may be a period of time where Netlify CMS is available in production while some repos are still deployed to the shared domain. We do not want to give users a foot-gun that could leak access to their Github repo.

#### Acceptance Criteria

- [x] The "external" authentication process only succeeds for repos that are deployed to isolated subdomains
- [ ] Change made live via deploy of Federalist

#### Implementation outline (if higher than "low" effort):

- [x] Include the url/repo name as a query parameter when navigating to the external auth login page
- [x] verify the deployment configuration of the repo BEFORE redirecting to Github for authentication
OR include the repo name as a query parameter in the redirect url when authenticating with Github and verify the deployment configuration AFTER Github and user authentication succeeds
- [x] Authentication should fail if the repo is not configured for isolated subdomains.

@apburnes

**Comment by amirbey** [comment]
@davemcorwin and @amirbey  have discussed this and instead of implementing this ... users will be migrated to dedicated bucket #2274

**Comment by davemcorwin** [comment]
@amirbey Can we close this one?

**Comment by amirbey** [comment]
closed @davemcorwin
