### ISSUE TITLE
[RESEACH] Research migrating all users to private

### ISSUE THREAD

**Issue by eddietejeda** [18F/federalist#2243]
#### User Story

David raises the concern that having shared and private repos may be more complicated in long term. What's the strategy for moving all sites to private s3 buckets.

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [ ] <TODO>
- [ ] Change made live via <TODO>.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by amirbey** [comment]
this has been completed and migration is in progress cc @davemcorwin
