### ISSUE TITLE
[RESEARCH] improve security scans approval process

### ISSUE THREAD

**Issue by eddietejeda** [18F/federalist#2244]
#### User Story

A user can perform the site scan process of their site through the Federalist interface and automation.

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [x] @amirbey to brainstorm ideas on the process
- [x] @amirbey to schedule meeting with team on process ideas
- [x] engage security contact on their interaction on the process

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] N/A

- can we automate the security approval process

**Comment by amirbey** [comment]
@amirbey to schedule meeting
