### ISSUE TITLE
Delete Site appears to do nothing ... suddenly deletes

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2253]
#### User Story

A user deleting a site, should be notified that the site is in th emiddle of deletion.

#### Background (Optional)

When deleting a site in staging (w/ s3 private buckets) deleting a site takes a while and appears to do nothing for a several seconds before deleting.  A time bar or some icon should appear to let the user know that the deletion is in progress.

#### Acceptance Criteria

- [x] Add a waiting icon when deleting a site
- [x] Change made live via deploy of Federalist

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by apburnes** [comment]
Maybe we add an info toast when a site is being created or removed. Reuse what we've got when a site's settings are updated and saved.

![federalist-toast](https://user-images.githubusercontent.com/693815/57535341-de620d80-72f6-11e9-8a8f-9c0eb0401bd5.gif)

**Comment by amirbey** [comment]
While the delete is occurring there will be info toast?
Another option .. I was thinking of reusing this waiting icon.
<img width="1280" alt="Screen Shot 2019-05-10 at 10 48 01 AM" src="https://user-images.githubusercontent.com/1261794/57536074-6e14b580-7311-11e9-9852-b018ee9cd816.png">

**Comment by apburnes** [comment]
I came across the toast for the first time today and it pleasantly surprised me... and it made me think of this issue so I wanted to throw it out there.
