### ISSUE TITLE
develop plan to migrate to Concourse

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2270]
#### User Story

A user who has committed updates to their site, will have their site built in a build container that is pre-configured for their site engine.  Concourse will auto-scale and user will no loner have to wait for a build container to free-up if all are occupied.

#### Background (Optional)
Every time a user builds a site, the build container has to install the environment (ie: ruby, rvm, hugo, etc.) which is very time consuming.

#### Acceptance Criteria

- [ ] new issue exists containing implementation plan and issue # is commented in this issue

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] perform analysis of what is needed to migrate SQS/build containers to Concourse
- [ ] draft new issue containing implementations steps

**Comment by davemcorwin** [comment]
I think our current plan is to try to improve our efficiency while running on cloud.gov for now, as this is a large lift.
