### ISSUE TITLE
[spike] research: Display Federalist Preview URL in Github's Deployment UI box

### ISSUE THREAD

**Issue by afomi** [18F/federalist#2282]
<img width="882" alt="bbb" src="https://user-images.githubusercontent.com/67984/59049487-f026ca00-883c-11e9-8aaf-54e0da66e083.png">

 #### User Story

As a Developer,
I want to see the Federal Preview URL in Github,
So that I don't have to copy & paste the URL from Federalist onto all my PR's,
So that Preview URL's are more reliably available to PR Reviewers.

#### Background (Optional)

Github supports Deployments.
Federalist doesn't appear to currently support the Deployment functionality.
The goal is to leverage the Github deployment's UI box.

#### Acceptance Criteria

- [ ] 

#### Level of effort - <low/medium/high>

Medium

#### Implementation outline (if higher than "low" effort):

- [ ] research GitHub API to see how to alter/display the preview url link already being displayed
- [ ] create a new issue with details on implementation

**Comment by amirbey** [comment]
closing ... showed @afomi that preview link is available in PR
<img width="747" alt="Screen Shot 2019-07-23 at 3 36 26 PM" src="https://user-images.githubusercontent.com/1261794/61741860-ce879080-ad5f-11e9-86b7-9d28b431275e.png">
