### ISSUE TITLE
Research: Federalist LFS

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2291]
#### User Story

- [x] reserach solutions
- [x] scope out implementation plan

#### Background (Optional)
via GitHub interface users can upload files directly to S3
AWS pre-signed URLS
https://github.com/pqina/filepond
<TODO>

#### Acceptance Criteria

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by amirbey** [comment]
#2274

**Comment by eddietejeda** [comment]
should we close this?
