### ISSUE TITLE
document how a user can use Netlify CMS

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2296]
#### User Story

A user wanting to implement Netlify admin on their site, should have an information resource instructing them how to do so.

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [x] instructional documentation exists detailing how to add netlify admin configurations for jekyll
- [x] instructional documentation exists detailing how to add netlify admin configurations for gatsby
- [x] instructional documentation exists detailing how to add netlify admin configurations for Hugo
- [x] Change made live via federalist.18f.gov
- [x] Review content and edit as needed.
- [x] Merge with Master once Netlify CMS is launched.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

Documentation Draft Link: https://docs.google.com/document/d/1BNj4zJawMx_PL-Uy6G6RAQdQlMZDghLIHs2Hthqs_I4/edit

**Comment by Bryanthales** [comment]
Taking this over, will add draft docs. *Note: this will likely be a joint effort as I do the first pass and Amir refines with greater technical information.

**Comment by amirbey** [comment]
Paths to netllfy config.yml files:

https://www.netlifycms.org/docs/add-to-your-site/

Node or Hugo:
./static/admin/config.yml
 

Jekyll:
./admin/config.yml

**Comment by Bryanthales** [comment]
@amirbey Hey, I have done:
1. Updated Included With Federalist documentation page. Added Netlify CMS info to whats included. Removed no CMS to what is not included section at the bottom.
2. Added a Getting Started with Netlify CMS page to side navigation bar (_data/navigation.yml) and added content to page. ([draft content ](https://docs.google.com/document/d/1BNj4zJawMx_PL-Uy6G6RAQdQlMZDghLIHs2Hthqs_I4/edit))  

Build is [here](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/federalist.18f.gov/Bryant---CMS-Page/documentation/), but the page returns a 404 that I cant figure out how to fix. :(
