### ISSUE TITLE
draft messaging to users notifying unforseen on dedicated buckets migration

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2298]
#### User Story

A federalist user who is on a shared bucket and is being migrated to a dedicated bucket should be informed of unforseen potential impacts.

#### Background (Optional)

Migration to make way for Netlify CMS integration

#### Acceptance Criteria

- [x] @Bryanthales  to draft copy of messaging to all Federalist customers

- [x] @amirbey to review [Draft Notification](https://docs.google.com/document/d/1iQSkwqNJvXU_EJ3R_zBAAHMSDSax4F5t3o0mEtUbIkM/edit)

_After evaluating, edit this part:_

**Comment by Bryanthales** [comment]
Changes accepted yesterday.
