### ISSUE TITLE
uswds-jekyll build script for Windows

### ISSUE THREAD

**Issue by Bryanthales-zz** [18F/federalist#2303]
#### User Story

A windows user who is building a site  locally using the federalist uswds jekyll template, should be able to view all assets

#### Background (Optional)

Running a uswdws-jekyll site locally on a Windows machine doesn't work without tweaking. Since Bryant is a Windows user, we can solidify a build script for windows users.

#### Acceptance Criteria

- [ ] update build.bat with commands that replicate npm run build
- [ ] document the Readme to inform windows users
- [ ] Change made live via deploy to federalist uswds-jekyll template

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by Bryanthales** [comment]
I'm going to reengage on this one and work toward getting the software approved for use at GSA.

**Comment by Bryanthales** [comment]
https://gsa.my.salesforce.com/a1Zt0000000Axzt
Submitted Technology Request Form for RubyInstaller + DevKit (wasn't sure so went with DevKit version -- can update to remove DevKit it advised). 
Process typically takes 2-3 weeks from here.

**Comment by amirbey** [comment]
@eddietejeda - resolved using jekyll-plugin implemented by @davemcorwin
