### ISSUE TITLE
CDN in .gov TLD for USWDS static files

### ISSUE THREAD

**Issue by benwarfield-usds** [18F/federalist#2308]
#### User Story

U.S. Web Design System distribution files should be available at a known-safe location, controlled by the government, to lower barriers to entry and improve performance for sites that use the distributed files without customization.

#### Background 

For new users of USWDS (hi!) and users who do not have a need to customize the basic USWDS distribution, it would be helpful to have a known-good (and up-to-date) version of the distribution on the web, such that it could be hot-linked into a new site with minimal overhead (and, as an added bonus, if many such sites exist and are using the CDN, then users of multiple sites would benefit from cacheing the distribution files).

**History:**

* this has been previously discussed as a possible effort by the USWDS team (see uswds/uswds#1093), who decided not to pursue it.
* a non-government CDN took up the request and began mirroring the files (https://cdnjs.com/libraries/uswds), but this is not something we necessarily want to recommend other government users to employ (see uswds/uswds#1100, and in particular [Eric Mill's comment](https://github.com/uswds/uswds/pull/1100#issuecomment-220741247)).

To summarize very briefly, browser SRI support would allow pages to link to a specific version on an untrusted CDN and have confidence that it had not been altered, but in order for minor releases and bug fixes to make it into customer pages automatically, there needs to be an updatable "latest" version, which is incompatible with SRI. Also of note, the DAP team distributes their analytics javascript through a single central point, and probably has both experience and cautions to share about implementing this idea.

This issue is intended to revive the previous discussions in a different context, and see if the passage of time has made this seem like a good investment.

#### Acceptance Criteria

- [ ] <TODO>

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by amirbey** [comment]
@benwarfield-usds - i think this issue is better directed towards uswds and should be raised in https://github.com/uswds/uswds
