### ISSUE TITLE
allow users to set their own 404 routing rules

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2323]
#### User Story

A federalist user with a site on a dedicated bucket, can set their own 404 routing rules key/path.

#### Background (Optional)

Users with react-routing need to index.html routing

#### Acceptance Criteria

- [ ] user can set a 404 routing rule path/key
- [ ] Change made live via <TODO>.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] add custom 404 path field in site settings
- [ ] save custom 404 path field in database site table
- [ ] use aws api to set the 404 routing rule

**Comment by amirbey** [comment]
via AWS CLI API ?? https://docs.aws.amazon.com/cli/latest/reference/cloudfront/update-distribution.html

**Comment by davemcorwin** [comment]
Captured in the [Epic](https://github.com/18F/federalist-garden-build/issues/248).
