### ISSUE TITLE
Document sqs service whereabouts

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2337]
#### User Story

Tech Portfolio needs documentation on our use of AWS

#### Background (Optional)

Dependency: https://github.com/18F/tts-tech-portfolio/issues/276

#### Acceptance Criteria

- [x] document in "How our cloud.gov and Federalist AWS ..."

_After evaluating, edit this part:_

**Comment by davemcorwin** [comment]
https://docs.google.com/document/d/110o1L7EOby3hvE5d-cDhg2LBLHymbZLnMPe9kuk4qp8/edit#

**Comment by davemcorwin** [comment]
waiting on access to the doc
