### ISSUE TITLE
jekyll approval for windows users

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2339]
#### In order to better support our Windows based customers, we are seeking approval from GSA IT to install Jekyll on GSA Windows GFE.

<TODO>

#### Acceptance Criteria

- [x] Technology Request form submitted  
        - https://gsa.my.salesforce.com/a1Zt0000000Axzt
- [x] Security Review Completed
- [x] 508 Review Completed
- [x] TSC Review Completed

_After evaluating, edit this part:_

**Comment by eddietejeda** [comment]
Is this still happening?

**Comment by amirbey** [comment]
before  @Bryanthales-zz  left he got ruby approved so GSA users should be able to request Ruby from GSA IT
