### ISSUE TITLE
Provide Sub-resource Integrity

### ISSUE THREAD

**Issue by eddietejeda** [18F/federalist#2347]
#### User Story

#### Background (Optional)
Our security scans alert that assets are missing "Subresource Integrity" More info: https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

Can Federalist handle this for our users?

#### Acceptance Criteria

- [ ] investigate whether DAP supports this ... other scripts are supported in template
- [ ] add best practices info to the federalist documentation
- [ ] Change made live via deploy of templates

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by amirbey** [comment]
@eddietejeda  to discuss w/ team the vision on why this is necessary

@davemcorwin - while this is could be a best practice, requiring this could impact usability for our users

**Comment by davemcorwin** [comment]
@eddietejeda This is something that is specific to js resources loaded via script tags. The best we can do here is update any templates with script tags to include the `integrity` attribute. If so, we can create issues in the template repos to add them.
