### ISSUE TITLE
Monthly Scan report processing

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2364]
#### User Story

A Federalist user should be able to receive security scan report violations as GitHub issues.

#### Background (Optional)

IT scans all sites monthly and sends reports of sites containing violations.  It is time consuming of the Federalist team to individually contact each site owner.

#### Acceptance Criteria

- [ ] Change made live via deploy of Federalist

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] add a scan table (id, site, type, report(json), issueCreated, issueId, issueStatus?, user)
- [ ] create scan controller to GET,POST/PUT report 
- [ ] create scan model
  - [ ] method: createRepositoryIssue - link user to view report on Federalist
- [ ] add createIssue to GithHub service
- import scan report to Federalist app (db table, model, controller, route)
  - [ ] create scan route
  - [ ] create scan controller
  - [ ] create scan model
  - [ ] create scan table in database
- [ ] allow site user to submit scan request
- [ ] allow site user to view latest scan report
- [ ] dashboard to view sites w/ violations

**Comment by amirbey** [comment]
GSA IT has confirmed that NetPark is currently unable to deliver scans in bulk in json format but only per reqeuest.  The Netsparker team has  added bulk json reporting to their roadmap and have an ETA of 3-6 months

**Comment by davemcorwin** [comment]
The requirement for managing this process will be going away within the next 12 months and [other efforts](https://github.com/18F/federalist/issues/3680) are addressing certain parts of it. If this becomes an internal feature, we can revisit and will likely take a much different shape than envisioned here.
