### ISSUE TITLE
It should be easier for potential users to understand the value of Federalist

### ISSUE THREAD

**Issue by jeremiak** [18F/federalist#238]
@wslack gave us the feedback that sending folks to the current Federalist home page isn't really useful for non-technical users. He asked for a short [slides](https://github.com/18f/slides) presentation and suggested a few user stories to help us make the home page a bit more effective in explaining the value of the platform.

* As an executive director of a micro agency, I want to understand how federalist will allow me to create a website with the few components I need.
* As a person interested in a better looking website for my agency, I want to easily know what kind of looks federalist makes possible in terms of colors and templates. (There isn't currently a way to see current templates from homepage)
* As someone interested in buying federalist, I want to understand if you are open for business when the intake team refers me to the site as an option for my need.
* As a federal executive of a website built in Drupal, I want to understand what I gain and lose with federalist.
* As someone that would maintain a federalist site, I want to see what I would use to update the site - or the eventual vision for that toolset

**Comment by dhcole** [comment]
:+1: moved into our next milestone. @GailSwanson @jeremiak @goodnightjj, if you have ideas for content to address these points, please feel feel to draft them and post back here or start a Google doc.
