### ISSUE TITLE
redirect federalist-docs.18f.gov to federalist.18f.gov via pages-redirect

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2394]
#### User Story

For a better browsing experience, create a permanent redirect for federalist-docs.19f.gov

#### Acceptance Criteria

- [x] Users receive a 301 (permanent redirect) to federalist.18f.gov when attempting to access federalist-docs.18f.gov
- [x] Change made live via <TODO>.

#### Implementation outline (if higher than "low" effort):

- [x] Remove CDN service in `sites` space
- [x] Remove route service in `redirects` space
- [x] Create and share `federalist-docs.18f.gov` domain in `gsa-tts-fugacious`
- [x] Create CDN service in `redirects` space
- [x] Create and deploy an entry in `pages-redirects`
- [x] Update record in 18f DNS

**Comment by davemcorwin** [comment]
@amirbey Will attempt when the cdn service is up and running!
