### ISSUE TITLE
site configuration to display in more friendly yaml format

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2395]
#### User Story

<TODO>

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [ ] <TODO>
- [ ] Change made live via <TODO>.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by davemcorwin** [comment]
We'll be retiring the yaml site configuration.
