### ISSUE TITLE
site builds to have queued status

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2419]
#### User Story

A user should see an accurate build time in the site builds page that does not include the wait time for a build to be assigned to a build container.

#### Background (Optional)

The Site builds page starts the build time once the commit happens regardless of whether the build is queued or running.  The build time should only show the time spend building.

#### Acceptance Criteria

- [x] display of queued build when build containers are occupied
- [x] display more accurate build times
- [x] Change made live via <TODO>.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [x] create build with queued status
- [x] federalist-garden-build to sent status update to in progress

**Comment by jeremyzilar** [comment]
I would say that it is important to know how long it usually takes for our website to be updated, which I'd expect to be the number I see most of the time (like on the builds page)

But I would also like to see a breakdown of all the stages in Federalist, on the logs page.
For example, how long it took for the site to build, how long it too to upload the pages, etc...
