### ISSUE TITLE
Editor should warn you if you refresh without saving

### ISSUE THREAD

**Issue by jeremiak** [18F/federalist#243]
As a content editor, Federalist should warn me when I try to refresh a page without saving the latest changes.

It is great that you can refresh to start over if you haven't saved yet, but sometimes I hit the refresh button without meaning to and my changes are lost.

Additionally, if a user wants to discard current working changes, it isn't very clear to how do so.

**Comment by wslack** [comment]
Closing as the editor has been disabled.
