### ISSUE TITLE
Display error message when user attempts to access site they are not a user of

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2472]
#### User Story

When a user tries to access a repo to which they do not have access, they see a blank screen. Instead, return an error message

#### Acceptance Criteria

- [x] User sees an error message when attempting to access a repo to which they do not have access.
- [x] Change made live via deploy of Federalist

**Comment by davemcorwin** [comment]
@amirbey Food for thought, user receives same error when the site doesn't exist AND when it does exist but they can't access...
