### ISSUE TITLE
support for SameSite

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2477]
#### User Story

<TODO>

#### Background (Optional)

https://gsa-tts.slack.com/archives/C04823NMA/p1580830251010300

#### Acceptance Criteria

- [x] Change made live via deploy of Federalist

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by davemcorwin** [comment]
https://www.npmjs.com/package/express-session#cookiesamesite
https://www.troyhunt.com/promiscuous-cookies-and-their-impending-death-via-the-samesite-policy/

**Comment by davemcorwin** [comment]
@amirbey let's also review the implications for our use of socket.io
