### ISSUE TITLE
Some problems with code blocks in the WYSIWYG editor for 18f.gsa.gov

### ISSUE THREAD

**Issue by gboone** [18F/federalist#248]
We recently piloted writing a new blog post using (almost) only Federalist and a two unexpected things happened:
1. We wrote the post using the WYSIWYG editor and saw some problems with code blocks
2. When we clicked "save" the file created ended up here: [pages/1450132135106.md](https://github.com/18F/18f.gsa.gov/commit/997f76d4c61468e1e9313d6b3f057fdeff188c46) and not in the `_posts` directory where it was expected (EDIT on 6/30/16 by Will: https://github.com/18F/federalist/issues/270 covers this second issue, I have changed the title of the issue to focus on #1)

We created the new post by clicking the "New page" button here: https://federalist.18f.gov/#edit/18F/18f.gsa.gov/landingham/_posts

This post had a few code blocks and when we were editing we used the `<>` button and `code` formatting to try and get a code block:

```
code block
```

The markdown that generated for those code blocks ended up looking like this:

```
> `code block`
```

Which generated like this:

> `class CreateEmployees < ActiveRecord::Migration\ def change\ create_table :employees do |t|\ t.timestamps null: false\ t.string :slack_username, null: false\ t.date :started_on, null: false\ end\ end\ end`

When I went back in to the pages directory to edit this file this was all Federalist showed:
<img width="1066" alt="screen shot 2015-12-14 at 4 45 36 pm" src="https://cloud.githubusercontent.com/assets/312468/11796500/38ae4838-a282-11e5-8c5f-6e8e49cf5bad.png">

That was the biggest code block. It looked like each one got formatted slightly differently.

Also, as you can see in the full text the frontmatter was also malformed, with an extra `---` above the frontmatter block and above the post content. cc: @awfrancisco

**Comment by suprenant** [comment]
We'll look at this and write stories to address

Notes from meeting with Jeremia today on this one:
 - Location that new pages are saved at is configurable by user
 - Currently hardcoded
 - May have different site structure, would want to configure that
 - Could prevent us onboarding new clients
 - Should be okay for existing clients

**Comment by wslack** [comment]
@suprenant was this turned into stories?

**Comment by gboone** [comment]
Not to meddle but, to clarify:
> Location that new pages are saved at is configurable by user
User configurability would be good, but it'd be great if pages were created relative to the directory the user is browsing. In this case, for example, what we expected to happen was for the markdown file to be created in the same directory as the current view's context: `_posts`.

**Comment by wslack** [comment]
Ah, that makes sense.

**Comment by suprenant** [comment]
@wslack looks like this was resolved, but please let me know if there are any lingering questions

**Comment by wslack** [comment]
I don't think this was resolved;  it sounds like we should add it to the backlog to evaluate as a feature request since Federalist currently behaves unexpectedly.

**Comment by wslack** [comment]
@gboone is this covered by https://github.com/18F/federalist/issues/270 ?

**Comment by gboone** [comment]
Hey, sorry it took me a couple days to respond to this. This one has two parts: 1) the messy text when pasting raw markdown into the editor and 2) the post being saved to an unexpected location. The first part is not captured by #270 but the second is. Does that help? It's been a while since I filed this so it's possible the first part is different problem now than it was in December. I haven't tried using the editor ina few months. Let me know if it'd be helpful to give it another shot.

**Comment by wslack** [comment]
No worries! Is it ok if I rename this isuse to be specifically about code blocks @gboone?

**Comment by gboone** [comment]
Go for it! Whatever makes this more useful for the team is OK with me.

**Comment by jmhooper** [comment]
closing as the editor has been disabled
