### ISSUE TITLE
"View Site" link does not work

### ISSUE THREAD

**Issue by davemcorwin** [18F/federalist#2484]
#### User Story

When a user tries to use the following links, there are no `href` attribute for links so they do not work 
- "View Site" link in the upper righthand corner of repo specific pages (builds, logs, etc) does not work, 
  - ![Screen Shot 2020-02-06 at 4.00.56 PM.png](https://images.zenhubusercontent.com/55539b1a4f7a08fbb7f2c453/e9fe4e88-27d3-4b6a-8892-53a9f0fb2258)
- "View Site", "View Demo", and "Preview Site" links on the **Github branches** at `/site/:id/branches`
- "View Site", "View Demo", and "Preview Site" links on the **Uploaded Files** at `/site/:id/published`
- The "View" link to see a deployed site's published file at `/site/:id/published/:branch`

#### To Do
- [x] Update the `site` serializer to add `viewLink`, `viewDemoLink`, and `previewLink` to the support the frontend components to consume the expected attributes.

#### Acceptance Criteria

- [x] Clicking the link opens a new tab with the deployed site/demo/preview
- [x] Clicking the link to view a published file downloads the file
- [x] Change made live via deploy Federalist app

**Comment by davemcorwin** [comment]
@amirbey @apburnes So this is actually kind of interesting. The affordance here for "View Site" is associated with the Site, but we no longer have a url associated with a Site since they are Build (really branch) specific.

1. Should this link continue to always exist?
2. If so, should it point to the latest build of the "default" branch?
3. Or should it only exist if there is a custom domain and it points to the custom domain?

**Comment by apburnes** [comment]
I'll take a look into this and circle back.
