### ISSUE TITLE
Investigate implementing different permission levels in Federalist for site administration vs builds

### ISSUE THREAD

**Issue by davemcorwin** [18F/federalist#2486]
#### User Story

We have at least a couple options including differentiating between:
1. admin vs. write Github permissions (there other use cases for this)
2. separate Github teams

#### Background (Optional)

> Is it possible to let a GitHub user have write access on a repo as a collaborator, but not have access to Federalist settings? We would like some folks to be able to contribute to their own sections of a website but not have access to Federalist site settings. Or does Federalist only mirror GitHub permissions without any further granularity on the Federalist end?

>> Thanks for reaching out! Currently, we only piggyback off of Github permissions and do not maintain any separate roles in Federalist. We'd prefer to continue doing this, but that doesn't mean we can't evaluate adding a bit more granularity based on Github permissions. So we can fully understand your use case, would access to Federalist settings correspond to admin access for your repository? If not, would leveraging different teams in Github, where users still have only "write" access be a possibility?

>>> We have a number of content editors, and we'd like them to be able to easily update content in their respective pages and still be able to preview their changes. But we don't want them to have access to modify site-wide settings such as in Federalist. So either of the approaches you mentioned would work for our use case. In our case, only admins should have access to Federalist configuration, but we could also put the editors in a write group that does not have access to Federalist configuration.

#### Acceptance Criteria

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by amirbey** [comment]
i think this is a worthwhile request ... and side on repo admin vs write collaborator approach
