### ISSUE TITLE
Deprecate auto-generation of redirects to compensate for incorrect Jekyll paths

### ISSUE THREAD

**Issue by davemcorwin** [18F/federalist#2494]
#### User Story

<TODO>

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [ ] <TODO>
- [ ] Change made live via <TODO>.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by amirbey** [comment]
should have effective way to communicate with users to announce beforehand

**Comment by davemcorwin** [comment]
Duplicate of https://github.com/18F/federalist-garden-build/issues/229
