### ISSUE TITLE
Migrate from Jekyll => Federalist 

### ISSUE THREAD

**Issue by nmudd-cms** [18F/federalist#250]
Can we use:
```
hugo import jekyll 
```
to migrate our jekyll site to Federalist?

**Comment by dhcole** [comment]
Hey Nate, Federalist primarily runs Jekyll sites. We experimented with Hugo as an optional rendering engine, but we haven't kept up with it as much. We're focused primarily on Jekyll sites for now. So you should be able to just point Federalist at a repo with a Jekyll site to have Federalist build the site.

Also, feel free to drop in our #federalist-public room on Slack (access it via https://chat.18f.gov/) and we can talk more about you use case.
