### ISSUE TITLE
 Institutionalize CORS policy info

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2507]
#### User Story

A user should be able to request CORS policy and a Federalist admin can view/update the CORS policy in the admin interface

#### Background (Optional)

During migration the CORS policy for the shared bucket was not passed forward to future bucket sites.

#### Acceptance Criteria

- [ ] configuration is retrievable/updatable in database for site via admin
- [ ] Change made live via deploy of Federalist

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [x] add a json field to database to store additional site configurations

**Comment by davemcorwin** [comment]
Captured in [Epic](https://github.com/18F/federalist-garden-build/issues/248)
