### ISSUE TITLE
robots.txt is not being made for the new S3 buckets

### ISSUE THREAD

**Issue by wslack** [18F/federalist#2518]
#### User Story

Credit to @brittag for this bug being found.

As a person searching for 18F content on google, I get some confusing URLs like http://cg-f28e32aa-d42e-4906-a813-7d726f69183c.s3-website-us-gov-west-1.amazonaws.com/site/18f/18f.gsa.gov/tags/how-we-work/

<img width="762" alt="Screen Shot 2020-03-26 at 7 46 13 PM" src="https://user-images.githubusercontent.com/10016577/77707078-782bbb00-6f9a-11ea-9713-f9980be4b1ac.png">

I want to see the real URLs of these pages!

#### Background (Optional)

I think all of the separate S3 buckets were made without robots.txt files! We had to manually make them in the original S3.

#### Acceptance Criteria

- [x] Raw S3 bucket urls prevent indexing
- [x] Future changes made live via deploy of Federalist
- [x] Current changes made live via script

#### Implementation outline (if higher than "low" effort):

- [x] Add robots.txt in the federalist core after provisioning an s3 bucket

#### Notes

robots.txt content:
```
User-agent: *
Disallow: /
```

**Comment by amirbey** [comment]
#### Acceptance Criteria

- [ ] robots.txt is is reachable at each existing bucket
- [ ] robots.txt is is reachable at each newly created bucket
- [ ] Change made live via deploy of Federalist

_After evaluating, edit this part:_

#### Level of effort - Medium

#### Implementation outline (if higher than "low" effort):

- [ ] put https://federalist-proxy.app.cloud.gov/robots.txt at the root of each existing bucket
- [ ] as part of the bucket creation process, put https://federalist-proxy.app.cloud.gov/robots.txt at the root of the newly created bucket

**Comment by davemcorwin** [comment]
@amirbey 
What is process for differentiating between preview and custom domains? I think the end result should be that:

1. Preview domains should NEVER be indexed
2. Custom domains should be 100% up to the site owner (searchable by default)

My concerns with the above approach is that:

1. This ties us more to relying on the dedicated bucket approach
2. Requires manual intervention to REMOVE/EDIT the robots.txt file for custom domains.

**Comment by amirbey** [comment]
to be noted ... http://cg-f28e32aa-d42e-4906-a813-7d726f69183c.s3-website-us-gov-west-1.amazonaws.com/ is the shared bucket for staging

**Comment by amirbey** [comment]
buckets created before 2020-04-08 10:48:15 ET updated with robots.txt
