### ISSUE TITLE
Form fields for metadata

### ISSUE THREAD

**Issue by dhcole** [18F/federalist#254]
Per recent designs, common metadata (page settings) should be presented as metadata fields.

**Comment by jeremiak** [comment]
We want five metadata fields to be handled in a special way from any other fields. Those five fields are:

0. Title of the document (displayed as `[type=text]`)
0. Layout (displayed as a `<select>`)
0. Permalink of the document (displayed as `[type=text]`)
0. Author of the document (displayed as `[type=text]`)
0. Publish date of the document (displayed as `[type=date]`)

All other present metadata should be displayed as raw YAML text in a code mirror editor (just like we present all of the metadata now).

Saving the document should convert these fields into the proper YAML format and store them as the front matter of the document.
