### ISSUE TITLE
revert to publishing by diff

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2549]
#### User Story

<TODO>

#### Background (Optional)

The implementation of custom object caching has caused us to PUT to s3 every file from a build as opposed to formerly PUTing a diff of built files.

#### Acceptance Criteria

- [ ] only diffed files are pushed
- [ ] Change made live via <TODO>.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] possibly push per build caching rules onto s3 and use that when pushing up files to s3 to determine to replace a file

**Comment by eddietejeda** [comment]
This is an investigation, right? We're not sure if the current approach is what's causing the price difference yet.

**Comment by amirbey** [comment]
@eddietejeda 
is there a way to identify our usage/fees vs all of cloud.gov to assist in an investigation? 

for us we suspect that the volume of our PUT calls have gone up significantly since we made our recent publishing change.

we talked about it a bit and @davemcorwin first inclination (w/o my mention) was that this was likely a big impact in the recent co$t surge. making this change also has other side-benefits (ie: shorter build times due to faster publishing).

**Comment by eddietejeda** [comment]
Discussed with @amirbey and we will be implementing to change.

**Comment by amirbey** [comment]
use s3 sync ... will be more cost effective

**Comment by davemcorwin** [comment]
Captured in Epic: https://github.com/18F/federalist-garden-build/issues/248
