### ISSUE TITLE
Recent drafts has no buttons for edit or view

### ISSUE THREAD

**Issue by jeremiak** [18F/federalist#257]
The "edit" and "view" buttons are not showing up for some drafts (branches). In this screenshot, the site's "default branch" is set to "gh-pages", therefore master should be a draft.
![](http://f.cl.ly/items/3E043Y043U1d0n0h3b1p/Screen%20Shot%202015-12-16%20at%204.02.59%20PM.png)

**Comment by dhcole** [comment]
I wouldnt put much time into this now. I think the way drafts work will be completely redone with @GailSwanson's recent designs.

**Comment by jeremiak** [comment]
:+1: sounds good to me

**Comment by dhcole** [comment]
This should now be about removing this section / potentially adding a "view draft" and "rebuild" buttons next to the most recent instance of a build for each branch in the log. No need for this to be on the homepage anymore as part of the new designs and the new draft workflow.

**Comment by wslack** [comment]
this is outdated. Closing.
