### ISSUE TITLE
Add support for Gatsby incremental builds

### ISSUE THREAD

**Issue by rchillard-gov** [18F/federalist#2588]
#### User Story

As a content editor, I want my static site to only build the parts I changed, so that I can update sites with large amounts of content much faster.

#### Background (Optional)

Gatsby recently added support for [incremental builds](https://www.gatsbyjs.org/blog/2020-04-22-announcing-incremental-builds/), which is a really big deal in the static site generator world.  With incremental builds, Gatsby builds _only_ the pieces of content that were changed or dependent on the change, which makes individual content updates _very fast_ (~10 seconds).  For large sites, this really matters, because build times can be long and having to wait for an entire site to re-build after you change a single piece of content can sometimes get intolerable.

It's unclear if Federalist will have to become a 'Gatsby partner' in order to get access to this feature.

#### Acceptance Criteria

- Research done to determine if Gatsby will offer this outside of partner program
- Federalist supports increment builds for Gatsby

_After evaluating, edit this part:_

#### Level of effort 

Unknown

#### Implementation outline (if higher than "low" effort):

- Contact Gatsby
- ?

**Comment by amirbey** [comment]
Incremental builds are part of the SaaS solution and not the open source solution.  We will not be able to scope this at this time.

**Comment by davemcorwin** [comment]
Hi @rchillard-gov !

Thanks for raising this!

My understanding is that the "incremental build" is an offering by Gatsby Cloud, their paid SaaS product. The technology behind that is proprietary and unfortunately not part of the Gatsby open source library itself.

In addition, I believe the "partner program" is more of a marketing thing for dev shops to get their name on a list and some of their work showcased on the Gatsby site.

While I appreciate the benefits of faster builds, this is outside the scope of support that we can provide.
