### ISSUE TITLE
Search.gov results API key should be hidden from the page html

### ISSUE THREAD

**Issue by dawnpm** [18F/federalist#2599]
#### User Story

As Search.gov, I would like Federalist site customers who use our results API to have their API key stored in some sort of secrets file, rather than in the plain HTML, to reduce the potential for bad actors to send junk requests to the endpoint.

As a Federalist customer, I would like my search results API key obscured, to follow best practices.

#### Background (Optional)

The API key is visible in the page HTML, see line 36 of view-source:https://faq.coronavirus.gov/symptoms-and-testing/#what-are-the-symptoms-and-complications-that-covid-19-can-cause

Given that the key is listed in _config already, how could it be referenced by the search box form code from there, rather than inserted in the meta tags of the pages?

#### Acceptance Criteria

- [ ] `searchgov_access_key` meta tag is removed from the page templates
- [ ] update plan is communicated to current Federalist users who have this metatag in their production pages, whether that be that Federalist is making an update, or that the site managers need to make an update, or something else.
- [ ] Change made live via <TBD by Federalist team>.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by davemcorwin** [comment]
Hi Dawn,

1. Federalist sites are all statically generated which means there is no server component generating the responses at request time.
2. Every request made from a browser is totally visible to the user, so even if we obscured the value in some way (or even generated it at request time), it would still be visible in plain text in the request, e.g. in the "network" tab of Chrome devtools.
3. Any site making requests to Search.gov from the browser has these constraints, this is not restricted to Federalist.
4. The `_config` file you are referring to is a "build" time file, this does not exist as part of the actual site.

The Search.gov "access key" in this case should **not** be considered secret as any information sent to the browser is discoverable.

If the "access key" is meant to be secret, then Search.gov cannot be used in this way (requests straight from the browser).

As this is isn't an issue with Federalist or the templates per-se, I am going to close this issue. @amirbey or I are happy to chat with you more about this if you like.
