### ISSUE TITLE
"Select parent node" in menubar looks broken

### ISSUE THREAD

**Issue by jeremiak** [18F/federalist#261]
The "Select parent node" button in the editor menu bar looks broken because there is no icon displayed.

**Comment by jeremiak** [comment]
This looks like it might be an upstream issue since the ProseMirror demos also have this problem

**Comment by dhcole** [comment]
Maybe that's just the icon... like a dotted box selecting an element.

**Comment by dhcole** [comment]
Pretty sure this is just the way it is as part of the library an no action is needed.
