### ISSUE TITLE
create a sandbox team which is audited on an interval

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2690]
#### User Story

Federalist access for a sandbox user should be automatically removed after x days

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [ ] Sandbox user is removed after configurable x interval.
- [ ] Change made live via deployed to Federalist

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] create a team for sandbox users
- [ ] create a script to remove sandbox users created before x days
- [ ] configure the number of x days in env vars
- [ ] add scheduled to job to circleci to execute the script

**Comment by davemcorwin** [comment]
Handled in https://github.com/18F/federalist/issues/3029

**Comment by amirbey** [comment]
no longer applicable with pages Migration ... current gitHub auth will be phased out
