### ISSUE TITLE
Querying build logs is slow

### ISSUE THREAD

**Issue by davemcorwin** [18F/federalist#2692]
#### User Story

Querying build logs is extremely slow. Ex. on production https://federalistapp.18f.gov/sites/540/builds/130635/logs (federalist.18f.gov) takes 4-10 seconds.

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [ ] <TODO>
- [x] Change made live via <TODO>.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by amirbey** [comment]
fixed by adding indexes to tables
