### ISSUE TITLE
Do we need an "alpha", "beta" or other banner?

### ISSUE THREAD

**Issue by jeremiak** [18F/federalist#27]
I've seen lots of 18F sites that have banners to tell users of their status, the objective and to provide mechanism for gathering feedback. @dhcole, is this something we should include on a Great Pitch project?

**Comment by bradnunnally** [comment]
I think this would be a good idea. Just helps to set the tone for everything.

**Comment by dhcole** [comment]
We could add in something like what's on the 18F Dashboard page: https://18f.gsa.gov/dashboard/

> This site is in [alpha](https://18f.gsa.gov/dashboard/stages/). The content contained is not final.
