### ISSUE TITLE
The new page button always creates a file in the pages directory

### ISSUE THREAD

**Issue by gboone** [18F/federalist#270]
It seems like the "Add a new page" button always commits to a file with a numerical string in `/pages`. Subsequent edits save to the correct file in the expected directory.

Steps to reproduce:
1. Push an empty branch and navigate to the directory you want to create a new file in (example `_posts`)
2. Click the "Add a new page" button, write your content and save your changes
3. The page generated has a random numerical string for the filename in the pages folder
4. In the terminal `git mv <generated-filename> _posts/<new-filename>` then `git push` the branch back
5. Edit and save as normal

**Comment by wslack** [comment]
Needs to be updated with acceptance criteria

**Comment by wslack** [comment]
Closing as the editor has been disabled.
