### ISSUE TITLE
Pages without content don't show ProseMirror

### ISSUE THREAD

**Issue by dhcole** [18F/federalist#272]
The editor doesn't show ProseMirror when loading a page without content. I think the editor should still display so users can add in content. @jeremiak, @GailSwanson what do you think?

<img width="725" alt="screen shot 2015-12-30 at 11 27 49 am" src="https://cloud.githubusercontent.com/assets/170641/12053581/97983eea-aee8-11e5-9941-14dfb0545baa.png">

**Comment by GailSwanson** [comment]
I agree. There would be no way for users to add content otherwise.

**Comment by jeremiak** [comment]
Agreed. I'll pick this up now.

**Comment by jeremiak** [comment]
I believe this was closed by #275
