### ISSUE TITLE
update user  access

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2726]
#### User Story

Need to remove users associated with contracts that expired. See Slack for details.

#### Background (Optional)

https://gsa-tts.slack.com/archives/G0159N6KJJZ/p1593113456001700

#### Acceptance Criteria

- [x] remove access for user teams in federalist-users org

#### Level of effort - Low

**Comment by davemcorwin** [comment]
@amirbey should we delete these teams from Github?
