### ISSUE TITLE
if Federalist app is inoperable - update status page

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2747]
#### User Story

If the federalist web application or other services are down or degraded, the status page should be updated.

#### Acceptance Criteria

- [x] update for marketing site
- [x] update for web app
- ~[ ] update for builds~ This will have to be manual
- [x] Change made live via manual configuration in StatusPage, NewRelic and AWS

#### Level of effort - low

**Comment by davemcorwin** [comment]
Blocked by pending Terraform updates

**Comment by davemcorwin** [comment]
Not actually blocked.
