### ISSUE TITLE
proxy-edge: site.subdomain cannnot have periods

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2770]
#### User Story

A user should be able to securely visit a preview domain.

#### Background (Optional)

When a repository name has a "." it appears to create a new subdomain level and the cert is not valid.

#### Acceptance Criteria

- [ ] repository with "." in name appears secure in browser
- [ ] Change made live via deploy of Federalist

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] check to see multi level domain are available in AWS
- [ ] subdomain function replaces "." with another character (ie: "--")
- [ ] possible let people define their own subdomains?

**Comment by davemcorwin** [comment]
@amirbey is this done?

**Comment by amirbey** [comment]
implemented by david https://github.com/18F/federalist/pull/2877
