### ISSUE TITLE
Make README easier for all types of people to get started

### ISSUE THREAD

**Issue by jeremiak** [18F/federalist#28]
We'll open more issues like this in the future, but since we have @bradnunnally going through the process for the first time I'm going to use this issue to log all the bits that are currently confusing so we can check through them and improve!

**Comment by jeremiak** [comment]
[] Perhaps have a series of commands instead of telling people to "use `npm install`"

**Comment by jeremiak** [comment]
hey @bradnunnally feel free to leave comments here or make your own branch and issue a pull request

**Comment by bradnunnally** [comment]
Doh! @dhcole & @jeremiak I just saw this...and I made a google doc with a copy of the read me in it and added a bunch of comments. 

https://docs.google.com/a/gsa.gov/document/d/1ksO3DI391VW7V9KD36cYpFtQVLmhECauIu2fx7Qm2G8/edit?usp=sharing

I wasn't sure how to do something like this within Github.

**Comment by bradnunnally** [comment]
How crazy of a thought would it be to turn the whole install and local server set up into a script of some kind?

**Comment by jeremiak** [comment]
@bradnunnally Not that crazy. I think we should go further down this path since it makes setup much easier, hence #30.

Some of it will still need to be user entered, but I think we'll want to reduce that as much as possible to make it easier for people to come onto the project

**Comment by jeremiak** [comment]
I'm thinking that #30 should be resolved by this branch as well. Overall they're both improvements to make the onboarding process easier for future contributors
