### ISSUE TITLE
proxy@Edge should only allow request from cloudfront and custom urls not proxied requests

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#2809]
#### User Story

<TODO>

#### Background (Optional)

The Federalist proxy server should only accept requests from a custom url or *.sites-prod|staging.federalist.18f.gov.  
Namely, a domain should not be able to set the cname of their site to a preview url.

#### Acceptance Criteria

- [ ] ensure that CNAMEs for a domain cannot point to a preview url and block if so
- [ ] add logging to display the hostname, user-agent, IP etc.
- [ ] Change made live via <TODO>.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by davemcorwin** [comment]
Part of #3064

**Comment by amirbey** [comment]
proxy@Edge descoped
