### ISSUE TITLE
Document style guidelines

### ISSUE THREAD

**Issue by GailSwanson** [18F/federalist#281]
Create style guidelines for the styles established for use across the application. This will provide consistency across the application as it is extended over time. 
Things to include:
* text and background colors
* font styles, sizes, and usage
* element spacing and padding
* navigation element styles
* button styles, states, and usage
* transitions and animated behaviors

**Comment by GailSwanson** [comment]
ask each other questions

**Comment by goodnightjj** [comment]
moved to federalist-design
