### ISSUE TITLE
User provided env variable value hint show's last 4 digits no matter the size

### ISSUE THREAD

**Issue by apburnes** [18F/federalist#2862]
#### User Story

When a user views their site's user provided environment variables, the variable's value is displayed as a hint ie "xxxx4321".  The minimum number of characters for a env variable value is four.  When the user creates a four character value, the hint will show the value of the variable so a value set to "TRUE" will be seen in the hint as "xxxxTRUE".

#### Background (Optional)

- Possible solutions
  - Increase the minimum number of characters for an env variable value
  - Create logic for the hint to only show a portion of the value with the max number of characters shown to be four
  - Remove the hint

#### Acceptance Criteria

- [x] TDB based on solution

**Comment by amirbey** [comment]
Done ... implemented by @davemcorwin
