### ISSUE TITLE
Remove federalist-landing-template.18f.gov, federalist-report-template.18f.gov, federalist-uswds-template.18f.gov

### ISSUE THREAD

**Issue by davemcorwin** [18F/federalist#2880]
#### User Story

Outdated and replaced by newer templates.

#### Acceptance Criteria

- [x] remove entries from 18f/dns (https://github.com/18F/dns/pull/464)
- [x] delete cdn-services
  - deleted `federalist-landing-template.18f.gov-route`
- [x] delete from Federalist
  - deleted `federalist-modern-team-template`
  - deleted `federalist-landing-page-template `

#### Level of effort - low

**Comment by amirbey** [comment]
all domains removed by @davemcorwin
