### ISSUE TITLE
Allow users to remove a site from S3

### ISSUE THREAD

**Issue by GailSwanson** [18F/federalist#289]
# Feature Description

Users need the ability to unpublish a previously published page. This will allow users to sunset pages as needed. 
- Unpublish will be an additional state in the workflow. Any page may be draft, published, or unpublished.
- Unpublished pages will be clearly labeled as such.
- Unpublished pages shouldn't get in the way of viewing the rest of the site. 
## Questions
- Should a user be encouraged or discouraged from having a page in an unpublished state on a long term basis? 
- Will the interface become unusable due to a large volume of unpublished pages?

**Comment by wslack** [comment]
Right now, Federalist does not (as best I know) remove pages from S3 when they are removed from a build. We should ensure this happens.

**Comment by jmhooper** [comment]
We use the `aws s3 sync` command which AFAIK should remove pages when changes are made on the given branch. I can verify this in staging later.

What does not exist is a way to unpublish a preview branch or site. A corollary to that is that sites that are removed from Federalist are not removed from S3.

**Comment by jmhooper** [comment]
Here's the reference docs for [aws s3 sync](http://docs.aws.amazon.com/cli/latest/reference/s3/sync.html#options). See the `--delete` option which is used in our publish script.

**Comment by wslack** [comment]
updated title - I trust your knowledge of the command, which resolves the stronger concern. (Clarification: does a preview build stay up even when that branch is deleted?)

We should have a way to clean up an S3 bucket when a site is removed from Federalist, though.

**Comment by jmhooper** [comment]
Yes, the preview build stays up even when the branch is deleted.

**Comment by jmhooper** [comment]
We do get a webhook request when a branch is deleted though, and could use that to spin up a separate build container to delete all of the content at that preview branch's URL.

**Comment by wslack** [comment]
hmmmm 🤔 , worth discussing at standup for priority

**Comment by wslack** [comment]
@brandocalrissian: this is multiple issues, for different cases.

- Higher priority: delete sites when removed from Federalist
- Lower priority: delete branches when deleted from repo (should be moved to icebox)

**Comment by jmhooper** [comment]
Looking into this, and an after delete hook to clean up S3 is definitely doable.

Going down this path, I think there's some other benefits we can glean from tighter integration with S3, which I'll write up in another issue.

**Comment by wslack** [comment]
Also made https://github.com/18F/federalist/pull/810 to help clarify what #797 does for users.
