### ISSUE TITLE
File uploads

### ISSUE THREAD

**Issue by dhcole** [18F/federalist#297]
Users will want to upload files to link to from their sites, such as a PDF of a report. We can enable this in the same way image uploads work, where the regular `link` button has an option for a file upload dialog; the files go into `/assets/` and a link to the file is added to the content.

Uploads should be easy to link to from pages in Federalist
- [ ] Add instructions for users to know how to link to file uploads

**Comment by wslack** [comment]
I'm going to suggest closing this, as GitHub's file uploads are much more robust.
