### ISSUE TITLE
Should we pull in ngrok as an npm dependency

### ISSUE THREAD

**Issue by jeremiak** [18F/federalist#30]
Looks like there is an [npm module](https://www.npmjs.com/package/ngrok) wrapper around ngrok. It might be easier to just pull that in as a dependencies and then dynamically assign the webhook URL? That way it can all be run on `npm run dev` or something like that.

Not quite sure of this, but I'm thinking of ways to make it easier for new people to onboard onto the project.

Thoughts @dhcole?

**Comment by dhcole** [comment]
We can for now... only issue is that I believe the GSA network blocks `ngrok`... does it for for you in the NY building?

**Comment by jeremiak** [comment]
Oh wow, I didn't even notice. I run all my traffic through a personal VPN so I guess I hadn't even noticed.

Well, I mean anybody running the app is going to need to expose the app via ngrok-like things so we can just put a disclaimer in there that says get set up with a VPN or use a non-federal network?

**Comment by dhcole** [comment]
Mentioned in the readme. Seems good for now. We can expand the description there if we need more.
