### ISSUE TITLE
federalist sites can be added in the admin interface

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#3003]
#### User Story

A Federalist operator can add any site to Federalist via the admin interface.

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [ ] a site can be added to Federalist from the admin interface
- [ ] Change made live via Federalist.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] user can add repository, engine, default branch, ...?

**Comment by davemcorwin** [comment]
Thinking about this a bit, I don't think an admin should be able to create a site. Creating a site requires `repo admin` Github permissions, this should only be initiated by a user, unless we implement the "act as a user" behavior. Thoughts @amirbey @apburnes ?

**Comment by apburnes** [comment]
I'm not sure what __adding__ means in the issue context.  Is it adding a site to be viewable from the admin interface, Is it adding an existing site to a user's site list, is it creating a new site from an existing repository, is it creating a new site and a new repository for a user?

**Comment by davemcorwin** [comment]
I was taking it to mean adding a NEW site to Federalist, from an existing repo or not, but the possibility of creating a Github repo for someone makes me feel even more strongly that an admin should not be able to do this.

I'm not sure about about adding an existing site to a user's list of sites given that this also is based on the user's permissions.

I don't know why we would need to be able to do these things, we should have documentation OR it should just be clear enough to users how to do this that we should never have to.

**Comment by amirbey** [comment]
@davemcorwin - i have yet to come across a reason to need to create a new site on a client's behalf.  Looking at some of the existing data, it appears that past Federalist operators have created new sites on clients' behalves; however, I have not had the need to do so.  The only reason, I could see doing this is in a DR scenario, but perhaps we can implement other solutions.  However,  I would agree that since we haven't seen a need in the past 2+ years it could be forgone.

**Comment by davemcorwin** [comment]
The DR case is worth thinking about, didn't we just ran through an exercise of "moving" a site? I think we can make utilizing that plumbing easier for admins, but I don't think we need to touch the actual interactions with GH.

I am going to close this issue for now.
