### ISSUE TITLE
migrate to GH project board

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#3004]
#### User Story

Zenhub is disappearing and the interaction is somewhat awkward. Github Projects now supports multiple repositories, let's migrate over.

#### Acceptance Criteria

- [x] Federalist Project board exists and accessible
- [x] All Federalist repos are included
- [x] Project board configured appropriately
- [x] All issues have been migrated

#### Implementation outline:

- [x] Create project board
- [x] Configure project board
- [x] Migrate issues
- [x] Delete Zenhub workspace
- [x] Remove Zenhub webhooks/integration

**Comment by davemcorwin** [comment]
@amirbey ready for review
