### ISSUE TITLE
Institutionalize build log archiving to S3

### ISSUE THREAD

**Issue by davemcorwin** [18F/federalist#3018]
#### User Story

Build logs should be archived to S3 with an appropriate retention policy as not not blow up our database.

#### Background (Optional)

The build logs are filling up the database and need to be moved to more efficient storage.

#### Acceptance Criteria

- [x] build logs are automatically archived to S3
- [x] build log retention policy is instituted
- [x] internal and external facing documentation is updated
- [x] Change made live via deploy of Federalist application.

#### Implementation outline:

- [x] Add a nightly task to archive the current day's completed build logs
- [x] Update the build log bucket lifecycle policy to expire logs after 180 days
  - [x] staging
  - [x] production
- [x] Add customer documentation to communicate the retention period for build logs
- [x] Add internal documentation to communicate the configuration and process of archiving build logs
- [x] Migrate historical build logs
  - [x] staging
  - [x] production

**Comment by apburnes** [comment]
On the "Update the build log bucket lifecycle policy to expire logs after 180 days", should we also create a db trigger to update the build record to account for the log expiration?

**Comment by davemcorwin** [comment]
> On the "Update the build log bucket lifecycle policy to expire logs after 180 days", should we also create a db trigger to update the build record to account for the log expiration?

What about the build record would we update?

**Comment by apburnes** [comment]
Not sure. The goal would be able to reconcile the db record (Build and/or BuildLog) with the S3 log object expiration.

**Comment by davemcorwin** [comment]
When the build log is archived to S3 the following happens:
- the records in the `buildlog` table are deleted
- the `logsS3Key` column in the `build` table is populated with the S3 key

I'm not sure what else we would need to do once logs expire, there just won't be logs. We can put something helpful in the UI when viewing a build that is older than 180 days?

**Comment by apburnes** [comment]
Just putting the logic in the UI could be the best path. But maybe just updating the `logsS3Key` to some keyword like `expired` would be a way to track without having to do the date math... me just being explicit.

**Comment by davemcorwin** [comment]
We don't have permissions to update the lifecycle of the bucket, should we just do it on the objects?

**Comment by apburnes** [comment]
@davemcorwin cloud.gov can setup the lifecycle policy on request and has done it for other customers.

**Comment by davemcorwin** [comment]
I wish we had more control over these things, but it's the easiest path, thoughts @amirbey ?

**Comment by davemcorwin** [comment]
Another concern is that the expiration will happen relative to the create date of the object so historical logs will not expire until 180 days after migration. Not a huge concern, we'll just have extra hanging around for a while which is what we do now anyway.
