### ISSUE TITLE
send notification email to users before booting them from users GitHub org

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#3027]
#### User Story

<TODO>

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [ ] <TODO>
- [ ] Change made live via <TODO>.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by amirbey** [comment]
depends on https://github.com/18F/federalist-infra/issues/12

**Comment by amirbey** [comment]
this will change in uaa

**Comment by davemcorwin** [comment]
@amirbey This is going to be handled by IDPs, should we close this?
