### ISSUE TITLE
Discuss process for better managing sandbox accounts/sites

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#3029]
#### User Story

Determine better technical and logical process for managing sandbox accounts and sites.

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [ ] <TODO>
- [ ] Federalist access for a sandbox user should be automatically removed after x days?
- [ ] Change made live via <TODO>.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] Schedule discussion

**Comment by davemcorwin** [comment]
@18F/federalist-admins I feel like we have done this!
