### ISSUE TITLE
Pre-structured metadata

### ISSUE THREAD

**Issue by gboone** [18F/federalist#312]
Hey team,
The @18f/blog team were chatting about tagging on 18f.gsa.gov during this week's blog huddle. One of @melodykramer's findings was that there are many tags that are similar but the result of spelling errors or [lack of standardization in spelling](https://github.com/18F/micropurchase/issues/134) or people simply not knowing there's a better tag to use.

We're coming up with some solutions to help us in the mean time, but thought it'd be great if "tags" could be a field in the Federalist editor that included a way of suggesting or prioritizing existing tags rather than creating new ones. Similar to how WordPress or other CMS platforms have a typeahead function on the field populated by the existing tags. As I type it I realize it sounds like a lot of work but wanted to let you know it was something on our minds, happy to help flesh out the user story here.

**Comment by wslack** [comment]
This was also requested by another customer

**Comment by jmhooper** [comment]
closing as the editor has been disabled
