### ISSUE TITLE
Enable CORS platform-wide

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#3317]
#### User Story

Allow get requests for all to every site bucket.

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [ ] update all existing buckets cors
- [ ] set cors when creating new buckets
- [ ] Change made live via Federalist

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by amirbey** [comment]
worth checking out:
https://github.com/UpHabit/bull_exporter
https://newrelic.com/lp/grafana-monitoring
cloud.gov has Grafana as well

**Comment by davemcorwin** [comment]
Captured in this [Epic](https://github.com/18F/federalist-garden-build/issues/248).
