### ISSUE TITLE
Merging a branch doesn't always trigger a rebuild

### ISSUE THREAD

**Issue by gemfarmer** [18F/federalist#332]
With [this commit](https://github.com/18F/doi-extractives-data/commit/0a652524598bb80751948b272b55efa3517e4c94) EITI recently merged `dev -> staging`. Usually when a merge happens, a rebuild of the preview site is triggered on Federalist for the accepting branch, but this time no rebuild was triggered. This has happened before for us (rare, but has happened), and generally I have fixed the issue by making a small edit and pushed directly to the branch in question.

Here is the [Slack conversation](https://18f.slack.com/archives/federalist/p1458316890000003) @jeremiak: and I had.

> EITI recently merged dev -> staging and I noticed that the preview branch for staging didn’t update on federalist. This has happened before with merges, but with no (as far as I can tell) predictability. Is there a way that we can insure that merging a branch always triggers a rebuild of the preview site for the updated branch?

**Comment by gemfarmer** [comment]
I later triggered a build by merging `branch -> staging` with better results. 

https://github.com/18F/doi-extractives-data/pull/1329

**Comment by gemfarmer** [comment]
Another instance. 
![screen shot 2016-03-22 at 2 57 47 pm](https://cloud.githubusercontent.com/assets/4803473/13966040/ad8e353c-f03e-11e5-9701-0da852e81878.png)

**Comment by gemfarmer** [comment]
We have started to keep track of this in our `config.yml` file under the [`shuggie` key](https://github.com/18F/doi-extractives-data/blob/master/_config.yml#L48).

**Comment by wslack** [comment]
@gemfarmer @meiqimichelle has this happened since Nov 1? Please ask for help in #federalist-support when it recurs; my guess is that we fixed this bug in staging.

https://github.com/18F/federalist/pull/658 also allows you to restart a build with click in the new version of Federalist at https://federalist-staging.fr.cloud.gov/ if you want to try that out!

**Comment by wslack** [comment]
Closing this issue for now; will reopen when there's a recurrence. IIRC some of these were because of emoji in commit messages.
