### ISSUE TITLE
Landing page doesn't display errors

### ISSUE THREAD

**Issue by alexose** [18F/federalist#336]
Not a huge deal, but when I'm directed to `https://federalist.18f.gov/?error=Error.Passport.Unauthorized`, there's no indication that anything is wrong other than the URL.

**Comment by wslack** [comment]
@alexose thank you! how did you get sent to that URL? Was it an attempt to auth via GitHub that failed?

**Comment by alexose** [comment]
Yep, exactly!

**Comment by wslack** [comment]
Do you mind sharing a screenshot of what you see? Does it appear to be the homepage?

**Comment by wslack** [comment]
@alexose we should be all good now I think! want to verify and close?

**Comment by alexose** [comment]
Look good-- I went to the error URL directly and I'm seeing an informative message :)

Thanks!
