### ISSUE TITLE
do not display site.config textAreas if no value already exists

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#3407]
#### User Story

<TODO>

#### Background (Optional)

The site.config will be phased out.  Sites not already using the config feature should not see the field in their siettings.

#### Acceptance Criteria

- [ ] Sites not already using the config feature should not see the field in their siettings.
- [ ] Change made live via <TODO>.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] do not display config fields for a site if not already storing config values

**Comment by davemcorwin** [comment]
Already completed https://github.com/18F/federalist/issues/3414
