### ISSUE TITLE
admin: add config to sites

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#3412]
#### User Story

<TODO>

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [ ] <TODO>
- [ ] Change made live via <TODO>.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by davemcorwin** [comment]
Already completed: https://github.com/18F/federalist/issues/3409
