### ISSUE TITLE
Migrate push notification settings

### ISSUE THREAD

**Issue by davemcorwin** [18F/federalist#3426]
#### User Story

User-specific push notification settings should be preserved with the deprecation of the "Site-User" association. Move to the "Organization-Role" association or another suitable place, perhaps even just some user settings json.

#### Background (Optional)

Currently, this is implemented using the "Site-User" association which will be deprecated with the move to "Organizations".

#### Acceptance Criteria

- [ ] User-specific push notification settings are preserved
- [ ] Users are able to configure whether or not to receive push notifications per site
- [ ] Change made live via deploy of Federalist application.

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by davemcorwin** [comment]
With Organizations, there isn't a direct relationship between a user and a site, it is `User <-> Org <-> Site` instead of the current `User <-> Site` which means there is not an analogous place to hold the notification settings. We could keep the `User <-> Site` relationship around, but that may be confusing and it might be easier to have a clean break with Organizations. We have the choice of associating this data with the Site or with the User, and I think it makes more sense with the User, not only for the data model, but in the UI as well.

Right now, there is a "Notifications" page within the sub navigation for a site, which contrasts with the rest of pages in this sub navigation in that for the other pages, all users would see the same info, whereas the Site Notifications page is specific to the User. We also have somewhat of a need for a "User" page for other user/uaa/vcs provider info. 

Proposal:
- add a `settings` JSONB field to the `user`
- put `buildNotificationSettings` in `user.settings` by `site` id. ex `user.settings -> { buildNotificationSettings: { <site id>: 'site' } }`
- refactor logic around modifying the notification settings from the site/site user to user (urls, controllers, actions, reducers, etc)
- add a User Settings page with the build notification settings
- remove the Site Notifications page
- migrate data over
- not going to worry about the legacy column since the whole table will be dropped at some point

Thoughts @18F/federalist-admins ?

**Comment by amirbey** [comment]
I li

> With Organizations, there isn't a direct relationship between a user and a site, it is `User <-> Org <-> Site` instead of the current `User <-> Site` which means there is not an analogous place to hold the notification settings. We could keep the `User <-> Site` relationship around, but that may be confusing and it might be easier to have a clean break with Organizations. We have the choice of associating this data with the Site or with the User, and I think it makes more sense with the User, not only for the data model, but in the UI as well.
> 
> Right now, there is a "Notifications" page within the sub navigation for a site, which contrasts with the rest of pages in this sub navigation in that for the other pages, all users would see the same info, whereas the Site Notifications page is specific to the User. We also have somewhat of a need for a "User" page for other user/uaa/vcs provider info.
> 
> Proposal:
> 
> * add a `settings` JSONB field to the `user`
> * put `buildNotificationSettings` in `user.settings` by `site` id. ex `user.settings -> { buildNotificationSettings: { <site id>: 'site' } }`
> * refactor logic around modifying the notification settings from the site/site user to user (urls, controllers, actions, reducers, etc)
> * add a User Settings page with the build notification settings
> * remove the Site Notifications page
> * migrate data over
> * not going to worry about the legacy column since the whole table will be dropped at some point
> 
> Thoughts @18F/federalist-admins ?

I agree with your propossal. i think a jsonb uer.settings column is the way to go! 👍🏿
