### ISSUE TITLE
admin: verify dns settings for live/demo site domains

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#3439]
#### User Story

<TODO>

#### Background (Optional)

The admin dashboard should display the dns settings for the live site and demo site domains. This would be helpful for confirming a ready to launch as well troubleshooting cert renewals. Eventually, site owners could be notified via email/GH issue if DNS settings are incorrect.

#### Acceptance Criteria

- [x] display dns setting per site (live and demo) in the admin dashboard
- [x] Change made live via launch of Federalist app

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by davemcorwin** [comment]
Closed in favor of #2973

**Comment by amirbey** [comment]
pending https://github.com/18F/federalist/pull/3694
