### ISSUE TITLE
Sandbox Organizations

### ISSUE THREAD

**Issue by davemcorwin** [18F/federalist#3523]
#### User Story

As a user I want to be able to have a sandbox organization.

#### Background (Optional)

Organizations can be a sandbox.

Sandbox Organizations:
- Will not support custom domains
- Will have their contents and infra removed every 90 days
- Users will be notified 5 business days before infra is removed

Organizations should be named:
- `{agency}-{office/program/system}` OR
- `{username}`

depending on if they are for an agency/program or for an individual.

#### Acceptance Criteria

- [ ] Admins can create sandbox organizations
- [ ] Admins can upgrade a sandbox organization to a "production" one
- [ ] Change made live via deploy Pages

#### Implementation outline (if higher than "low" effort):

- [ ] add a boolean `isSandbox` column to `organization` with default value `false`
- [ ] add specifying `isSandbox` to everywhere organizations are created
- [ ] add affordance to "upgrade" sandbox org to admin
- [ ] display `isSandbox` everywhere organizations are displayed

**Comment by davemcorwin** [comment]
@amirbey @apburnes Look ok to y'all? using a boolean `isSandbox`? default `false`?

**Comment by apburnes** [comment]
The boolean and attribute name makes sense.

**Comment by apburnes** [comment]
Would it be too crazy to create a related table to hold an orgs sandbox status and other related agreement attributes? If we use the `isSandbox`, do we need to keep the `sandbox` prefix to allow them to update the agreement from sandbox to production... or do we just change the org name on sandbox status change?

**Comment by davemcorwin** [comment]
> Would it be too crazy to create a related table to hold an orgs sandbox status and other related agreement attributes?

Not all orgs will have agreements, ex. "individual" sandbox orgs for people won't have them so I think it might make sense to keep the `isSandbox` flag with the org, but then create a new table for agreement stuff when we are ready for it.


> do we need to keep the sandbox prefix to allow them to update the agreement from sandbox to production... or do we just change the org name on sandbox status change?

 I think the naming exists in CF because there's no concept of a "sandbox" in CF, but we control this in our system so we probably don't need to do it. I put it in for consistency, but I'd be happy NOT to use that naming convention.

In CF, sandbox orgs aren't upgraded, a new org is created, but again, we don't have to do this, there is no reason we can't just toggle the `isSandbox` flag for orgs to upgrade them, this will probably make things easier for customers. Do we need to explicitly differentiate between "individual" or "agency/office/program" org or will the naming convention/our brains be enough? I just think we wouldn't want to upgrade an "individual" sandbox org to a non-sandbox.

**Comment by davemcorwin** [comment]
wondering if we need some stuff in the client facing application to indicate when the org is a sandbox as well, perhaps in another issue...
