### ISSUE TITLE
regularly cleanup abandoned sites

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#3533]
#### User Story

A user should not have  abandoned sites occupying resources (ie: s3, routes, ...).

#### Background (Optional)

Deleted some, let's wait for after the assessment then reset the whole db.

#### Acceptance Criteria

- [ ] scheduled queued job to identifies and removes abandoned sites on regular interval
- [ ] Change made live via federalist

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] create scheduled queued job to identify and remove abandoned sites

**Comment by davemcorwin** [comment]
We need to determine exactly what we mean by "abandoned". I'm wondering if this will take care of itself once we move to Organizations. We probably won't want to remove sites for Organizations (or would at least want to notify), and those in sandboxes will be removed every 90 days.

**Comment by davemcorwin** [comment]
I believe this will be addresses automatically over time after the SCR.
