### ISSUE TITLE
Review Pages CRM (revisit 1/18)

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#3536]
#### Background (Optional)

Federalist must read and evaluate the full Pages CRM spreadsheet to identify any inaccuracies or clarifications.

https://gsa-tts.slack.com/archives/C022AMA3EJY/p1627332281000800?thread_ts=1627330502.000700&cid=C022AMA3EJY

Pending Peter/Lindsay work

#### Acceptance Criteria

- [] ~@amirbey has read the pages crm~
- [x] @davemcorwin has read the pages crm
- [x] @apburnes has read the pages crm

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by davemcorwin** [comment]
In progress doc
https://docs.google.com/document/d/1hBqsYT2fGjAkcV_UjyBoHBRQJyou15DFHm7KHquWwfs/edit#heading=h.gz33m2qfh6xb

**Comment by apburnes** [comment]
@davemcorwin where are we on review? Should it be good to go?

**Comment by davemcorwin** [comment]
we're still soliciting feedback on the draft memo
