### ISSUE TITLE
pages site - update logos on pages marketing site including pdfs and thumbnails

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#3563]
#### User Story

<TODO>

#### Background (Optional)

pages home - https://github.com/cloud-gov/cg-site/blob/pages/_pages/pages/index.md
1. website logo 
2. case-studies
3. pages facts sheets

#### Acceptance Criteria
the logos on the marketing site are update for:
- [x]  main logo
- [x] case studies (including thumbnails)
- [x] pages facts sheet thumbnails
- [x] Change made live via cloud-gov/cg-site

_After evaluating, edit this part:_

#### Level of effort - low

**Comment by amirbey** [comment]
@apburnes  to update the Federalist logo to Pages in https://github.com/cloud-gov/cg-site/tree/pages

**Comment by apburnes** [comment]
Closed with https://github.com/cloud-gov/cg-site/commit/fba11a36bd1df2d1510aac65c567a49e1c748c61
