### ISSUE TITLE
Improve Dev Onboarding

### ISSUE THREAD

**Issue by wslack** [18F/federalist#359]
cc @jeremiak and @el-mapache 

Capturing Questions
1. What environment variables do I need for Docker builder?
2. How does the staging environment?

Anything preceded by a -E flag is an environment variable. You will also need your Github OAuth token for access to the repo in question.
1.

**Comment by jmhooper** [comment]
Curious about what else we could add to this. Right now we have:

- [Running Federalist Locally](https://federalist-docs.18f.gov/pages/how-federalist-works/running-federalist-locally/)
- [Deploying Federalist](https://federalist-docs.18f.gov/pages/how-federalist-works/deploying-federalist/)
- [cloud.gov Setup](https://federalist-docs.18f.gov/pages/how-federalist-works/cloud-gov-setup/)

In addition, the [How Federalist Works](https://federalist-docs.18f.gov/pages/how-federalist-works/) doc has been significantly cleaned up. I've also made sure the README's for each of our repositories are up to date.

Anything else we want to add before closing this?

**Comment by jmhooper** [comment]
At the very least, I've gone through and added documentation to answer the questions that I had when starting on the project that haven't been resolved by cleaning up the codebase.

**Comment by wslack** [comment]
I'm happy to put it in Done? pending retro convo today.
