### ISSUE TITLE
Onboard Sven

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#3659]
#### User Story

Onboard Sven

#### Background (Optional)

https://docs.google.com/document/d/1tS-9hLb2yHtp500N3obmu0X70XpIMATuPlov2_vDVS0/edit

#### Acceptance Criteria
- [x] Share README
- [x] Grant appropriate access to Federalist backend in cloud.gov
- [x] Add to federalist-admins
- [x] Add to federalist-admins in federalist-users org.
- [x] Add to cloud-gov-team in cloud-gov org.
- [x] Add to pages-ops in cloud-gov org.
- [x] Make owner in the federalist-users org. 
- [x] Add to #federalist- channels in Slack as needed, and add to @federalist-team Slack user group
- [x] Add to daily standup, retro, and sprint planning
- [x] Ensure user has Federalist Github project and brief on its use
- [x] Add to New Relic
- [x] Add to federalist-support, federalist-alerts, and federalist-inquiries Google Groups as needed
- [x] Add them as an agent to https://federalist-support.zendesk.com/agent
- [x] add to Federalist search.gov account
- [x] Add new user as developer to the gsa-18f-federalist cloud.gov cloudfoundry organization
- [x] Add to statuspage.io account
- [x] Have a cloud.gov operator add to the “pages.admin” group in the cloud.gov UAA by using the make-pages-admin.sh script
- [x] Have a cloud.gov operator add to the “concourse.pages” team in the cloud.gov OpsUAA by using the make-pages-ops-admin.sh script so they can access Concourse CI
- [x] Add to Docker Hub
- [x] Add to AWS (Production GovCloud only)

**Comment by svenaas** [comment]
Thanks, @davemcorwin. @amirbey, a lot of the stuff in that onboarding checklist is done, but I can't assess all of it. For example number 2 "Grant appropriate access to Federalist backend in cloud.gov" is (deliberately) general and I don't know whether it's completely done.

**Comment by davemcorwin** [comment]
@LindsayYoung  I believe this is complete
