### ISSUE TITLE
Flesh out domain administration

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#3689]
#### User Story

An admin user can fully administer (CRUD) domains.

#### Background (Optional)
- deprovision domain from UI
- destroy domain from UI
- ~edit domain from UI~
- search domains by state in UI
- do not paginate sites in domain creation form site list

#### Acceptance Criteria

- [x] can deprovision domain from admin UI
- [x] can destroy domain from admin UI
- [x] ~edit domain from admin UI~
- [x] ~add domain to legacy site domain configuration after provisioning and rebuild~
- [x] add links to site page (in admin) from domain index/show pages
- [x] can search domains by state in UI
- [x] sites are not paginated in domain creation form site list

- [x] Change made live via Federalist

**Comment by svenaas** [comment]
Deprovisioning works as of PRs #3720, #3723, and #3726. Added a separate task, #3727, to improve the UX.

**Comment by svenaas** [comment]
PR #3731 took care of "can destroy domain from admin UI"
PR #3732 took care of "add links to site page (in admin) from domain index/show pages"
and "add domain to legacy site domain configuration after provisioning and rebuild" has been extracted into issue #3733. 

And with that everything here is done except "Change made live via Federalist" so I'm moving this to "Done?"
