### ISSUE TITLE
Setting Cache-Control headers

### ISSUE THREAD

**Issue by el-mapache** [18F/federalist#370]
Based on the output of https://compliance-viewer.18f.gov/results/federalist/current, it appears we should be setting the Cache-Control and Pragma no-cache headers on our requests.

I'm not 100% sure how that would be handled in a single page application. I think that we would probably want those headers on every page that is accessible only to an authenticated user?

I think a sails policy is the way to handle this. Open to all thoughts/suggestions!

**Comment by wslack** [comment]
Closing as redundant to https://github.com/18F/federalist/issues/428
