### ISSUE TITLE
Parameterize Federalist application name in Federalist Web

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#3709]
#### Background (Optional)

The web application hardcodes the title Federalist throughout the application.

#### Acceptance Criteria

- [x] no hardcoded use Federalist in the content
- [x] Change made live via deploy Federalist

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [x] replace hardcoding user of "Federalist" with a param/variable

**Comment by svenaas** [comment]
I believe these are out of scope: 
![image](https://user-images.githubusercontent.com/12150/149568175-54b57901-6da9-425d-b619-7c7d0bcff7ba.png)
![image](https://user-images.githubusercontent.com/12150/149568210-451357bf-807c-4230-9826-f65a60838c5a.png)
but please add your thoughts if you think they should be part of this work.

**Comment by apburnes** [comment]
See https://drive.google.com/drive/folders/1F_m3ZkBkMob6y60EsqTLI-jfsjWhvxRJ for Pages logo images

**Comment by svenaas** [comment]
Work in progress on [3709-parameterize-app-name-in-federalist-web](../tree/3709-parameterize-app-name-in-federalist-web)

**Comment by svenaas** [comment]
Merged into staging with https://github.com/18F/federalist/pull/3756
