### ISSUE TITLE
Offboard Amir

### ISSUE THREAD

**Issue by amirbey** [18F/federalist#3715]
#### User Story

Offboard Amir

#### Background (Optional)
https://docs.google.com/document/d/1tS-9hLb2yHtp500N3obmu0X70XpIMATuPlov2_vDVS0/edit

#### Acceptance Criteria
- [x] Remove access to `gsa-18f-federalist` cloud.gov org
- [x] Remove from federalist-admins and federalist-contributor in 18F GitHub org.
- [x] Remove from cloud-gov-team in cloud-gov org.
- [x] Remove from pages-ops in cloud-gov org.
- [x] Remove from federalist-users org.
- [x] Remove from @federalist-operators Slack user group
- [x] Remove from daily standup, retro, sprint planning
- [x] Remove user from Federalist Github project
- [x] Remove from any email alerting policies within the New Relic account.
- [x] Remove from New Relic
- [x] Remove from federalist-support, federalist-alerts, and federalist-inquiries Google Groups
- [x] Remove from https://federalist-support.zendesk.com/agent
- [x] Remove from Federalist search.gov account
- [x] Remove from statuspage.io
- [x] Have a cloud.gov operator remove the user from the “pages.admin” group in the cloud.gov UAA by using the make-pages-admin.sh script
- [X] Have a cloud.gov operator remove the user from “concourse.pages” team in the cloud.gov OpsUAA by using the make-pages-ops-admin.sh script so they cannot access Concourse CI
- [x] Remove from Docker Hub
- [x] Remove from AWS

**Comment by davemcorwin** [comment]
@LindsayYoung  I believe this is complete

**Comment by svenaas** [comment]
Ben just noted that he spotted Amir in Docker Hub and removed him. That's not on the list above, so I'm adding it.
