### ISSUE TITLE
Change org Delete button to Deactivate in admin client

### ISSUE THREAD

**Issue by svenaas** [18F/federalist#3728]
#### User Story

As an admin using the admin client I need to be able to deactivate organizations.

#### Background (Optional)

The Orgs index page currently presents a Delete button in the Actions column. This button currently does nothing. It should be changed to read "Deactivate" and trigger that functionality.

#### Acceptance Criteria

- [ ] The deactivate button is presented instead of the delete button
- [ ] Pressing the deactivate button results in the deactivation of an org.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] <TODO>

**Comment by svenaas** [comment]
Deactivation functionality is not yet implemented for organizations. I can implement this, but @davemcorwin, what business rules should determine whether an organization can or cannot be deactivated? Can organizations be deactivated if they have associated sites? If they have associated users? Does it depend on the status of those sites or users?

**Comment by svenaas** [comment]
Should we add the deactivation event to the audit log?

**Comment by svenaas** [comment]
Is org deactivation a serious enough action that we should require admin confirmation before carrying out the action, as we do for domain deprovisioning and deletion?

**Comment by davemcorwin** [comment]
> Deactivation functionality is not yet implemented for organizations. I can implement this, but @davemcorwin, what business rules should determine whether an organization can or cannot be deactivated? Can organizations be deactivated if they have associated sites? If they have associated users? Does it depend on the status of those sites or users?

The use case here is if an IAA expires, we want to essentially freeze the organization. I believe we already have this in place on a per site basis, so deactivating an organization should have the same effect for all of the sites within an organization as well as preventing access to that organization for its users.

> Should we add the deactivation event to the audit log?
Probably.

> Is org deactivation a serious enough action that we should require admin confirmation before carrying out the action, as we do for domain deprovisioning and deletion?
Probably.

**Comment by svenaas** [comment]
OK. Organization has an isActive property; at the moment my provisional deactivate implementation simply sets that to false. I haven't looked yet to see what, if anything, depends on isActive. It's possible that more things should than do, if we need this to have the effect of preventing users from accessing an org or its sites and that business logic hasn't already been implemented. 

I was imagining I'd have to add a `canDeactivate` method (which I have, though for the moment it just returns `true` since I wasn't sure of the rules). I was trying to figure out the best way to inject `canDeactivate` properties into each row in the results of the admin org controller's `list`, since the "Deactivate" button appears in a column of the admin org index page. But maybe there's no canDeactivate gatekeeping beyond making the admin confirm?

**Comment by davemcorwin** [comment]
I don't think there needs to be any additional gatekeeping. The only possible thing I can think of is if we didn't want to deactivate sandbox orgs, but that's pretty meh either way.

**Comment by svenaas** [comment]
(Implemented but not yet merged.)

**Comment by svenaas** [comment]
Merged, but I don't think staging is quite there yet to confirm it.

**Comment by svenaas** [comment]
I would like to confirm this on staging but there are currently no organizations on staging to deactivate, and I find I can't create one: #3779

**Comment by svenaas** [comment]
This is merged and deployed to production, but since it's a Pages thing I'd kind of like to confirm it in Pages staging before we move it done.

**Comment by davemcorwin** [comment]
@svenaas This should now be QA-able

**Comment by svenaas** [comment]
@davemcorwin I thought so too but apparently not. Slack'd.

**Comment by svenaas** [comment]
#3779 is still a big but it turns out not to be a blocker. This is good news, and it has enabled me to confirm that I can deactivate (and reactivate) orgs on Pages staging! 🎉
