### ISSUE TITLE
Integrate new domain management with legacy site settings

### ISSUE THREAD

**Issue by davemcorwin** [18F/federalist#3733]
#### User Story

User facing site settings should be in sync with new domain management

#### Acceptance Criteria

- [x] After a domain is provisioned and the corresponding live site/demo url DOES NOT exist, populate the corresponding live site/demo url in the site table with the first domain name from `domain.names` and rebuild
- [x] After a domain is provisioned and the corresponding live site/demo url DOES exist, do nothing 
- [x] When a domain is deprovisioned, depopulate the corresponding live site/demo url in the site table and rebuild ONLY if it corresponds to one of the names domain being deprovisioned
- [x] When a live/site demo URL is unset or when a domain exists for a live site/demo and one of its names matches the site url, disable the live site/demo url field in the UI and ignore it in backend parameters
- [x] Change made live via deploy Federalist application.

**Comment by svenaas** [comment]
Functionally complete and merged with #3739. Not yet inspected in staging (or deployed to production).
