### ISSUE TITLE
As a site maintainer, I would like to keep up with improvements to the USWDS

### ISSUE THREAD

**Issue by skonzem** [18F/federalist#377]
What's the best way to pull modern versions of the Draft U.S. Web Design Standards assets into the site templates? The Federalist Modern Team Template, for example, has a version from October, and the assets are checked directly into the repository. There have been many changes since then, including important improvements to Section 508 compatibility.

Federalist itself now pulls the assets from npm (#337). However, specific sites may not have been built against the same version of uswds as Federalist, depending on when the sites were cloned from their templates. If there are breaking changes between uswds versions, you wouldn't want to just pull in the most recent version.

A few ideas:
1. Continue to check the uswds assets into the site template repos. If a site maintainer wants to update their templates, they can merge in recent changes from the template using Git outside of Federalist.
2. Use a `package.json` in each template file to specify a uswds version from npm, and have Federalist process the dependencies during site deployment. The maintainer would still need to merge in template changes using Git outside of Federalist.
3. Manage the assets as in options 1 or 2, but create a button in Federalist to update the template for the site. Maybe the template would specify which directories contain the core of the template, and Federalist would do a Git merge looking only at those directories. Demo content would have to be ignored, because people are likely to have modified or deleted it, causing merge conflicts.

**Comment by wslack** [comment]
Thank you @skonzem! Will add this to our backlog to review.

**Comment by wslack** [comment]
I'll also check with the draft web design standards team.

**Comment by skonzem** [comment]
I submitted a PR along the lines of option 1 over in 18F/federalist-modern-team-template#15, but it would be easy to rework for option 2. Aside from minor class name and asset path changes, jQuery is now included within the USWDS package, and it jumps from v1.11.3 to v2.2.4. Commenting here since the FMTT repo appears inactive.

**Comment by wslack** [comment]
@skonzem thank you! I needed to watch that repo.

**Comment by skonzem** [comment]
Now that Jekyll 3.2 added [gem-based themes](https://jekyllrb.com/docs/themes/), would it make sense to refactor the site templates into themes? That would keep the site layout and USWDS assets out of the user's repos, which solves almost all of the change control problems.

Incidentally, over in 18F/web-design-standards#1379 they're considering creating templates to demonstrate the USWDS. That use case could be well addressed by the Federalist templates.

**Comment by wslack** [comment]
This is in progress; posted a message in the USWDS channel and will open a convo.

**Comment by jseppi** [comment]
I _think_ this use case has been handled in Federalist's uswds-based templates, which now use the uswds gem. Is that right, @line47?

Suggest closing if so.

**Comment by line47** [comment]
Yep that's exactly right, running a `bundle update` would get you the latest of the gem

**Comment by jseppi** [comment]
Great - closing as resolved!
