### ISSUE TITLE
Investigate capabilities for support person

### ISSUE THREAD

**Issue by apburnes** [18F/federalist#3826]
When we onboard the support personnel, we want a checklist of the permissions and task associated to the role.

## Acceptance Criteria
- [ ] List of possible tasks for a support person
- [x] Identify the permissions for a possible support person in the federalist-users Github
- [x] Identify the any additional roles needed to support the platform
- [x] Update the issue template or add a new page specific issue template [here](https://github.com/cloud-gov/product/blob/master/.github/ISSUE_TEMPLATE/support-member-onboarding.md)

**Comment by hursey013** [comment]
As of this moment, these have been identified tasks:
- Access requests/updates
- Reviewing CloudTrail logs
- Netsparker review/support
- Creating internal/external knowledge base
- Updating and maintaining documentation

Anything else you all would like to capture for posterity here @apburnes @davemcorwin?

**Comment by apburnes** [comment]
Checklist [doc](https://docs.google.com/document/d/183oBdLLxw6ySw6fDau4mFdNGWz0NnrUGUgXkkTN6990/edit?usp=sharing)

**Comment by hursey013** [comment]
Moving future iterations to shared doc ☝️
