### ISSUE TITLE
Remove "Static" from options when adding a site to Federalist

### ISSUE THREAD

**Issue by wslack** [18F/federalist#385]
Right now, when adding a new site, the "static" option appears to break Federalist.

**Comment by wslack** [comment]
Other places this code is referenced if we decide to remove the option entirely.

- https://github.com/18F/federalist/blob/master/test/browser/models/Github.test.js
- https://github.com/18F/federalist/blob/6bb931723fd7d12dae8a36515f0cab61a9478665/api/models/Site.js
- https://github.com/18F/federalist/blob/5e34487c769c067270f04cba15573489c69b1fdc/api/hooks/buildEngine/index.js

**Comment by jeremiak** [comment]
Should be closed as #433 was closed, 18f/federalist-docker-build#8 was fixed by 18f/federalist-docker-build#12
