### ISSUE TITLE
Support a "people page" like the 18F Team Page on a Federalist template

### ISSUE THREAD

**Issue by wslack** [18F/federalist#393]
A Federalist customer would like to have a "people page" that allows someone to view a set of people on a team.

The set of people should be drawn from a collection of markdown files or a similar data schema. The "team page" should enable someone to see the following:

- [x] Photo
- [x] Name
- [x] Sort by various tags

Drilling down should allow users to see
- [x] Bio
- [x] Contact info

An example of this feature is here: https://presidentialinnovationfellows.gov/fellows/
Data schema: https://github.com/presidential-innovation-fellows/pif-website/tree/master/_data/fellows

**Comment by wslack** [comment]
@jeremiak says this could be done or micropurchased.

**Comment by wslack** [comment]
Ideally, in March.

**Comment by wslack** [comment]
https://github.com/presidential-innovation-fellows/pif-website/tree/master/_data/fellows to make a page like this: https://presidentialinnovationfellows.gov/fellows/

**Comment by ericronne** [comment]
cc me! @ericronne

**Comment by mearley2013** [comment]
I believe tags for the main landing page will be Year, Domain, Agency Collaborators, Skills/Areas of Specialty. There may be others, but I will let you know asap!

It would be cool to also, on each individual person's drill down page, to link to the projects they worked on (from the projects page). Would this be possible as well?

**Comment by wslack** [comment]
@mearley2013 would you want to list a person's projects for each user, or to list the users for each project? (the data can only be in one place)

**Comment by mearley2013** [comment]
The first one, I think - I'm thinking of when you view a person's profile, the bottom could include 1-3 links to projects they worked on, but not vice versa (viewing a project drill-down page and then seeing who worked on it). If it's not possible, then not a problem!

**Comment by maya** [comment]
@mearley2013 will the people page have filters like the project page? If so, what would the filters be?

**Comment by wslack** [comment]
@maya should be by role on team, not sure what else

**Comment by mearley2013** [comment]
@maya Year, Domain, Agency Collaborators, Skills/Areas of Specialty are the tags for the team page

**Comment by maya** [comment]
@mearley2013 thanks! 

Here are the image dimensions for each image of team members: 700px x 700px

**Comment by wslack** [comment]
Team Preview: https://federalist.fr.cloud.gov/preview/gsa-oes/office-of-evaluation-sciences/update-uswds/team/

**Comment by wslack** [comment]
Sounds like "domain" isn't needed.

**Comment by wslack** [comment]
Example: https://federalist.fr.cloud.gov/preview/gsa-oes/office-of-evaluation-sciences/uswds-data-entry/team/kelly-bidwell/

**Comment by wslack** [comment]
Thank you @maya! closing this as part of Federalist retro.
