### ISSUE TITLE
ATO work for Storage

### ISSUE THREAD

**Issue by wslack** [18F/federalist#397]
- [x]  Work with Noah and Diego on evaluating what is needed to properly leverage cloud.gov
- [x] @el-mapache to list next tasks
- [x] Determine if you can set cloudfront information via an API (esp error pages)
- [x] Decide on if we can do S3 in E/W or GovCloud
- [x] Deploy in Staging
- [x] @el-mapache to add documentation information to federalist-docs
- [x] Deploy in Production

**Comment by jeremiak** [comment]
Question: do we lose access to the AWS web console UI if we use a cloud.gov brokered S3 service?

**Comment by wslack** [comment]
Flagged to discuss on Friday.

**Comment by NoahKunin** [comment]
@jeremiak Yep, but you're going to eventually lose the AWS web console UI for state changes regardless.

**Comment by jeremiak** [comment]
The S3 service broker will give us our credentials in the `VCAP_SERVICES` object:

```
 "s3": [
   {
    "credentials": {
     "access_key_id": "***",
     "bucket": "***",
     "secret_access_key": "***",
     "username": "***"
    },
    "label": "s3",
    "name": "federalist-staging-s3",
    "plan": "basic",
    "provider": null,
    "syslog_drain_url": null,
    "tags": [
     "s3",
     "object-storage"
    ],
    "volume_mounts": []
   }
  ]
```

From looking through the code, I _think_ we'd have to change the following places:
* [`config/build.js`](https://github.com/18F/federalist/blob/master/config/build.js#L13)
* [`api/services/SQS.js`](https://github.com/18F/federalist/blob/master/api/services/SQS.js#L39-L40)(Probably want to just rename all of the env variables since we'll have different AWS keys/secrets for the queue and S3)

**Comment by wslack** [comment]
@el-mapache to see what needs to be done for this

**Comment by wslack** [comment]
@el-mapache is waiting for some questions to be answered by @dlapiduz

**Comment by dlapiduz** [comment]
@wslack where are the questions?

**Comment by el-mapache** [comment]
@diego It's not a new question, but a follow-up to a chat from last week. You mentioned you were looking into how we could host federalist websites on cloud.gov's brokered S3 service. I think we were just looking for an update on that.

Thanks!

**Comment by dlapiduz** [comment]
I think the only issue is how to enable website hosting on the bucket. The worst case scenario is that we do it manually but I think once you get credentials to the bucket you should be able to use the api to enable it. Do you want to try it out in govcloud? Just create an S3 service instance, bind it to a random app and get the keys. Then try to enable website hosting there.

**Comment by el-mapache** [comment]
alright, I will test that out today!

**Comment by el-mapache** [comment]
@dlapiduz @wslack using the API I was able to upload files to the s3 bucket and set a bucket hosting policy. However, I am not able to set the ACL on the bucket. That operation returns a 403 Access Denied error. I think only accounts flagged as admins can adjust the policies at a bucket level.

**Comment by wslack** [comment]
@el-mapache to update todo list

**Comment by wslack** [comment]
Documentation is all in cloud.gov documentation besides the ACL part.

**Comment by wslack** [comment]
Confirmed; this is done permanently.
