### ISSUE TITLE
Add logging to API endpoints

### ISSUE THREAD

**Issue by wslack** [18F/federalist#407]
Most web apps provided at least a minimal log when a user hits endpoints on the server. Basic information is generally included, such as the originating machine's IP address, the requested route, POST parameters, etc. Logs can also include error messages. This generally make debugging easier when issues arise on the server.

It appears the Cloud Foundry does output some logs from federalist, though they all appear to be pings from socket.io. I'm unsure if other requests are recorded, although I don't see any GETs or POSTs for actions like loading a page or saving a draft.

This feature would probably involve adding some additional logs and finding a way to present these in a slightly more readable form, like cutting down on the number of long polling events that are reported.

**Comment by jmhooper** [comment]
Is this referring to the Federalist web application? If so, we added [winston](https://github.com/winstonjs/winston) in 9688ed891c9395f5c9421e30a94efce64190a87c which provides some pretty verbose request and SQL query logging.
