### ISSUE TITLE
Upload image immediately after user selects image from their computer

### ISSUE THREAD

**Issue by leahbannon** [18F/federalist#413]
From the UX study:

Participants clicked “add an image” with no problem, but then just had to wait for something to indicate that it had uploaded. Only a few participants clicked on “use image” immediately after uploading an image, which currently uploads the image to the Edit area. All other participants refreshed the page, or went back to the pages list and then back into the page where their image was, but their image still didn’t show up.

Recommendation: Currently, the “use image” button uploads the chosen image to the asset area. I’d recommend that the upload happens as soon as they choose an image from their computer. This would take the guesswork and waiting out from this particular interaction. “Use image” could then be used to insert the image into the Edit area.

**Comment by el-mapache** [comment]
This functionality has been added to the react branch. The user clicks the upload image button, selects one from their system file dialog, and it is automatically uploaded and added to the list of available images.
