### ISSUE TITLE
Show image thumbnail in asset area immediately after upload

### ISSUE THREAD

**Issue by leahbannon** [18F/federalist#415]
From UX study:

Participants clicked “add an image” with no problem, but then just had to wait for something to indicate that it had uploaded. Only a few participants clicked on “use image” immediately after uploading an image, which currently uploads the image to the Edit area. All other participants refreshed the page, or went back to the pages list and then back into the page where their image was, but their image still didn’t show up.

Recommendation: To prevent users from feeling like something didn’t work, show indication of progress, for example: [1] When user has clicked “Upload a new image” and has chosen an image to upload, show some kind of indication that the image is being uploaded in the asset area. [2] When it has successfully uploaded, show its thumbnail it in the asset area. [3] When the user clicks “Use image” to insert it with the edit text.

**Comment by wslack** [comment]
Related to https://github.com/18F/federalist/issues/389

**Comment by el-mapache** [comment]
Fixed in https://github.com/18F/federalist/pull/479
