### ISSUE TITLE
add form validation to YAML field in Federalist editor

### ISSUE THREAD

**Issue by leahbannon** [18F/federalist#418]
From UX study:
In Other Settings, the text is title:Contact Us, the page will not build successfully (in the pages list you will see a page called “182736892.md” instead, and when you click on it, there is no page content). There needs to be a space between title: and the page name, but there is nothing here that shows people the correct format.

Recommendations: Per JJ’s designs, make Title into separate input field.

<img width="662" alt="rtbijhe" src="https://cloud.githubusercontent.com/assets/4323988/16288298/2b7f9884-389f-11e6-93cc-cbe5fbbd1acb.png">
<img width="662" alt="gazfeav" src="https://cloud.githubusercontent.com/assets/4323988/16288299/2f50a6ec-389f-11e6-9225-a47555ded2e0.png">

**Comment by wslack** [comment]
@mkhandekar 

> Participants were instructed to add a title in the Other Settings input field. “This should be a different box! Nobody knows what YAML is.”

Should this be a separate issue?

**Comment by wslack** [comment]
Closing as the editor has been disabled.
