### ISSUE TITLE
Add visual cue so users know "Save & Publish" != Show in Menu

### ISSUE THREAD

**Issue by leahbannon** [18F/federalist#419]
From UX study:

The goal was to make sure that the new page is published on the live site. Most participants clicked Save and Publish, and expected the new page to on the live site. After asking participants to troubleshoot on the pages list, some were able to see and understand that “show in menu” was not checked in the new page’s Navigation Options.

Recommendation: Currently participants have to dig into each page’s Navigation Options to see if they are shown in the menu or footer. Consider incorporating a more visual cue to give people a faster understanding of the page’s status. For example (see toggle-able eye icon for show/hidden items):

<img width="118" alt="screen shot 2016-06-22 at 5 41 46 pm" src="https://cloud.githubusercontent.com/assets/4323988/16288439/af82f1f2-38a0-11e6-9f3d-b89536e654eb.png">

**Comment by wslack** [comment]
@jeremiak I feel like this is an outdated issue because of the new navigation config; correct?

**Comment by jmhooper** [comment]
closing as the editor has been disabled
