### ISSUE TITLE
Improve options for undoing styles in editor

### ISSUE THREAD

**Issue by leahbannon** [18F/federalist#422]
From UX study:

There is no way to undo styles. Participants were able to easily style their content, however ran into difficulties when trying to revert to normal text. For example: when participants selected text and clicked “blockquote” from the toolbar, the text became a quote as intended. When they clicked on the blockquote icon again, they expected the quote to revert back to normal text. Instead, they got a nested quote. And this happens with every type of style available in the toolbar. Also, the “undo/redo” buttons work on text that has been input, but not reliably on the styles that have been added to the text. 

Recommendation 1: Consider moving “undo/redo” buttons to the front of the toolbar. They currently shift their position in the toolbar depending on what is available in it. This made it difficult for participants to press undo/redo several times.

Recommendation 2: The ideal interaction is for the editor to recognize what state the text is in, and make the toolbar’s capabilities respond to the text styles.
For adding blockquotes: to quote: user highlights text, clicks on blockquote icon, text becomes a quote (and the blockquote icon is visibly on an “active” state). to revert to normal: User places their cursor anywhere in the quoted text, clicks on blockquote icon, text reverts to normal text (and the blockquote icon is visibly on “normal” state). Just like google docs. 
For adding URLS: to add: user highlights text, clicks link icon, inputs the target URL and presses enter. to remove link: user places cursor anywhere within the link, clicks link icon, and the target URL appears for me to edit.

Question: what does Title mean? It doesn’t seem to do anything in practice.

**Comment by wslack** [comment]
Closing as the editor has been disabled.
