### ISSUE TITLE
Drag and drop is too sensitive

### ISSUE THREAD

**Issue by leahbannon** [18F/federalist#425]
From UX study (high priority)

Participants tried to drag and drop items. But their cursor was often not near the text (page title) area where the active drag/drop area is, rather it was close by to the right of the text, or in the empty body area of each row, expecting the entire row to be draggable. It was challenging for most participants to successfully place pages as the task instructed, and one participant could not complete the task. 

“That was a lot of work. It would be cool if this used color to correspond to subpages. Maybe the black arrow would turn to another color based on if it’s a ROOT or a SUBPAGE. Some visual cues would be super helpful.”

Recommendation 1: Expand the active draggable area to include more of the empty body area in each row.

Recommendation 2: Once a user has “picked up” a row, consider adding more visual cues to when they move it to a location where they can “drop” it. For example, this could be a darker horizontal line between two items, or a small space could open up between two items. 

Recommendation 3: If a user wants to move an item to be a sub-page, consider adding some visual cues here too, for example, the background of the parent page might become active (change color slightly or have a border, etc) when their cursor is on top of the parent page.

**Comment by wslack** [comment]
this is out of date. Drag and drop is no longer used.
