### ISSUE TITLE
Make bulk actions grey/unclickable unless a page's check box is checked

### ISSUE THREAD

**Issue by leahbannon** [18F/federalist#426]
From UX study:

Bulk actions. Some participants realized that the links at the top (delete draft, delete page, publish) were bulk actions after they had checked a few pages. Other participants clicked on the top links without checking off any pages, and they got a popup that said “the pages you’ve selected will be deleted” educating them for next time.

Recommendation: Consider making these links inactive (gray?) and not clickable unless a page’s check box is checked. This would help users not feel distracted by them when they’re not needed. As soon as a box is checked, they would be active again, hinting to users that checking a box or multiple boxes opens up new options / actions to them.

**Comment by wslack** [comment]
I don't think this applies anymore
