### ISSUE TITLE
Add new relic to federalist-builder application

### ISSUE THREAD

**Issue by wslack** [18F/federalist#441]
- [x] Enable New Relic
- [x] Verify everyone who needs to get alerts is getting them

**Comment by jeremiak** [comment]
Currently blocked by figuring 18F/federalist-builder#1 out

**Comment by jeremiak** [comment]
No longer blocked, and deploys are happening. I see the `federalist-builder-prod` app in New Relic

**Comment by jeremiak** [comment]
Done
