### ISSUE TITLE
Refactor: Each site should have a simplified page listing view that utilizes a `_navigation.json` file

### ISSUE THREAD

**Issue by wslack** [18F/federalist#448]

**Comment by brandocalrissian** [comment]
How do we want to treat these nested views? How are they done in the non-react version?

![image](https://cloud.githubusercontent.com/assets/1403376/17486111/9abe25a2-5d5d-11e6-8ef9-5e61e6862262.png)

**Comment by brandocalrissian** [comment]
Work is happening over here: https://github.com/18F/federalist/tree/bk-448
