### ISSUE TITLE
Create a New User Checklist

### ISSUE THREAD

**Issue by bradnunnally** [18F/federalist#48]
Create a checklist of new users that may assist with getting Federalist up and running.

This list could things such as:

- Github Account
- Github Application
- Required Software
- Suggested Training/Tutorials
- etc.

**Comment by bradnunnally** [comment]
This issue is meant to provide content direction and strategy for the new user section of the landing page. This will be key for users that are using Federalist for the first time.

**Comment by dhcole** [comment]
@melodykramer in case you haven't seen this, I know you're working on similar content.

**Comment by dhcole** [comment]
Documented here: https://federalist-docs.18f.gov/
