### ISSUE TITLE
Evaluate cloud.gov tasks as a replacement for ECS

### ISSUE THREAD

**Issue by jeremiak** [18F/federalist#480]
With the new Cloud.gov runtime being deployed, we get some things that might help us with the ATO related move off of AWS ECS to run our [docker image](/18f/federalist-docker-build). I'm making this issue to track work and helpful documents.
- [Blog post about scheduling one off tasks](https://blog.pivotal.io/pivotal-cloud-foundry/products/using-diego-to-schedule-one-off-tasks-in-cloud-foundry)
- [Tasks API reference](https://github.com/cloudfoundry-attic/receptor/blob/master/doc/api_tasks.md)
- [What a Task request looks like](https://github.com/cloudfoundry-attic/receptor/blob/master/doc/tasks.md)
- [What an Action looks like (actions are part of a task)](https://github.com/cloudfoundry-attic/receptor/blob/master/doc/actions.md)

Refs #399

**Comment by wslack** [comment]
out of date
