### ISSUE TITLE
Logs formatted incorrectly

### ISSUE THREAD

**Issue by el-mapache** [18F/federalist#487]
Logs are currently formatted incorrectly in the React rewrite. The `duration` field is not being parsed properly, leading the `message` field being offset to the left by one table cell.

Handy photo reference: 
<img width="805" alt="screen shot 2016-08-25 at 9 24 05 am" src="https://cloud.githubusercontent.com/assets/1421848/17977247/c47a2e54-6aa5-11e6-99d2-4069b6c295ef.png">

**AC**

- [ ] Parse the log data correctly and ensure all fields are filled in

**Comment by wslack** [comment]
@el-mapache should we jump on this right now? Need to triage.

**Comment by el-mapache** [comment]
@wslack Is this something that needs to be addressed right away? Its just the duration field that is missing....the user will still know that the build was successful or why it failed.
