### ISSUE TITLE
Add a test for a react view

### ISSUE THREAD

**Issue by brandocalrissian** [18F/federalist#490]
Find the easiest react view to test and test it. Involves setting up the tooling for react testing. Had some luck making actual tests with https://github.com/airbnb/enzyme so going to use it.

**Comment by el-mapache** [comment]
I was looking at enzyme yesterday, it looks like an absolutely huge library. Does it seem like it will add anything significant over just using the React testUtils and shallowRender?

**Comment by brandocalrissian** [comment]
Good question!

Ideally, we can create concise tests that get at what we really want to assert and test in our React views. I don't want to build or maintain a bunch of boilerplate code to sit on top of the React testUtils.

A clearer test can make logical assertions about how a component is rendered but not necessarily couple our test with the expectation what we want to examine is nested within a div->ul->li->a tag hierarchy.

Anything that makes it easier for us to test the logic in our heavy React components with their "on component update, trigger a fetch unless our state says otherwise" react-lifecycle logic gives us some breathing room; I don't know how long these components will stay in the codebase and it'd be a shame to not test them.

If a test is easier to write and maintain, it's more likely to be written (we have lots of backfill to do) and to actually test what we think it tests.

Sure, Enzyme isn't a tiny library, but it seems to help us on all these counts. If we include it as a devDependency, it doesn't keep us from writing pure testUtils-based tests, but we're also freed from keeping up with testUtils changes when we do build on top of enzyme (assuming enzyme continues to be updated which seems reasonable right now).
