### ISSUE TITLE
Write tests for app/actions

### ISSUE THREAD

**Issue by brandocalrissian** [18F/federalist#497]
There's a fair bit of logic in there, particularly the siteActions set.

**Comment by brandocalrissian** [comment]
In progress on [bk-497 branch](https://github.com/18F/federalist/tree/bk-497).

**Comment by brandocalrissian** [comment]
Rebasing from staging as staging has changed while this long-lived branch has been in progress. Will push --force when done.

**Comment by wslack** [comment]
@el-mapache if you close it, it leaves the "done" column. Did you mean to close it?

**Comment by el-mapache** [comment]
Yep! The accompanying PR was closed last week during our sprint review.
