### ISSUE TITLE
Request for OCSP Stapling

### ISSUE THREAD

**Issue by wslack** [18F/federalist#499]
Per https://github.com/18F/18f.gsa.gov/issues/292

**Comment by jmhooper** [comment]
- [An announcement from Amazon on 08/2014 that seems to suggest OCSP stapling is on by default.](https://aws.amazon.com/about-aws/whats-new/2014/08/20/amazon-cloudfront-adds-support-for-advanced-ssl-features/) 
- [Here's Amazon's docs on OCSP stapling](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorS3Origin.html#request-s3-ocsp-stapling)

Despite the above, it looks like [SSL Labs is still saying we don't have OCSP stapling enabled?](https://www.ssllabs.com/ssltest/analyze.html?d=sbst.gov&latest)

I found an [AWS Developer Forum Thread](https://forums.aws.amazon.com/message.jspa?messageID=598537) where they point to the the docs on OCSP stapling posted above as an answer to why someone did not see OCSP stapling.

**Comment by jmhooper** [comment]
From Amazon's docs on OCSP stapling:

>  If your distribution doesn't get much traffic in a CloudFront edge location, new requests are more likely to be directed to a server that hasn't validated the certificate with the CA yet. In that case, the viewer separately performs the validation step and the CloudFront server serves the object. That CloudFront server also submits a validation request to the CA, so the next time it receives a request that includes the same domain name, it has a validation response from the CA.

So it looks like the servers in edge locations will only have OCSP stapling enabled when they receive multiple requests from a client over some period of time.

**Comment by wslack** [comment]
@konklone given the info ^^, should we leave this open? Seems like it should be closed unless we want off CloudFront

**Comment by konklone** [comment]
Let's close it and re-open if it emerges as a more significant issue later.

**Comment by konklone** [comment]
However, note that if Federalist ever needs to explicitly discuss the third parties that might receive data about visitors to Federalist sites, the certificate authority will need to be listed as a potential third party that will get pinged. One of the benefits of OCSP stapling is that it removes this data sharing.

**Comment by wslack** [comment]
kk, I'm going to move this to our icebox but leave it open

**Comment by wslack** [comment]
Closing; can reopen if ever asked.
