### ISSUE TITLE
Editor should support pasted Word content

### ISSUE THREAD

**Issue by dhcole** [18F/federalist#5]
Per @LindsayYoung, pasting from Word is a common workflow, but Word has messy HTML. Let's figure out how to sanitize it. 

Consider https://github.com/madebymany/sir-trevor-js/blob/master/src/to-markdown.js#L19-L25

**Comment by bradnunnally** [comment]
Something to think about/question is how much formatting do content writers do in Word and do they expect that formatting to still show up when they bring it into Federalist? 

Just making a note of this line of question so it doesn't get lost.

**Comment by dhcole** [comment]
Work's started on a new editor that supports this: #90

**Comment by LindsayYoung** [comment]
:+1:
