### ISSUE TITLE
Incorrect Markdown rendering with <h2> within <ul>

### ISSUE THREAD

**Issue by betson** [18F/federalist#515]
In a .md file I have the following Markdown:

```
- ![Alt text](... "Optional title")
## Header Title
lorem ipsum
- ![Alt text](... "Optional title")
## Header Title
lorem ipsum
```

Federalist renders this as:

```
<ul>
  <li><img src="..." alt="Alt text" title="Optional title" />
## Header Title
lorem ipsum</li>
  <li><img src="..." alt="Alt text" title="Optional title" />
## Product Title
lorem ipsum</li>
</ul>
```

On my local Jekyll and online editors that use Github-Flavored Markdown, this is rendered as:

```
<ul>
  <li><img src=... alt="Alt text" title="Optional title" />
    <h2>Header Title</h2>
    <p>lorem ipsum</p>
  </li>
  <li><img src="..." alt="Alt text" title="Optional title" />
    <h2>Header Title</h2>
    <p>lorem ipsum</p>
  </li>
</ul>
```

Specifically the `<h2>` and `<p>` aren't transformed in Federalist.

**Comment by jseppi** [comment]
This seems like a Jekyll issue, not a Federalist issue since Federalist itself doesn't do any markdown rendering.

`federalist-garden-build` either uses the version of `jekyll` in a site repository's `Gemfile`, or uses the latest version available from doing `bundle install jekyll` (ref https://github.com/18F/federalist-garden-build/blob/staging/build.sh#L67-L79).

**Comment by betson** [comment]
Looking in the `_config.yml` for the project, it looks like I had specified `markdown: kramdown`. I think my concern was that the Markdown was rendered correctly in `_site/` on my local Jekyll instance, but Federalist was rendering it differently. So I knew Jekyll *could* do it correctly, but I was unsure if Federalist was somehow transforming the Markdown in a way before rendering that was causing problems.

However, I no longer have some of the documentation used for this project. If the example Markdown I provided at the top of the Issue is rendering correctly for you, then you can close this bug.

**Comment by jseppi** [comment]
Thanks, @betson.

Federalist doesn't do any conversions of any source files -- everything is just passed to the selected static site engine.

Also I just did a [quick test](https://github.com/jseppi/test-federalist-site/pull/2) and it looks like with the example markdown you had initially provided, the correct output is generated:

```html
<ul>
  <li><img src="..." alt="Alt text" title="Optional title">
    <h2 id="header-title">Header Title</h2>
    <p>lorem ipsum</p>
  </li>
  <li><img src="..." alt="Alt text" title="Optional title">
    <h2 id="header-title-1">Header Title</h2>
    <p>lorem ipsum</p>
  </li>
</ul>
```

so whatever the root issue was, it appears fixed now 🎉
