### ISSUE TITLE
Incorrect nav menu items shown when logged in on staging

### ISSUE THREAD

**Issue by el-mapache** [18F/federalist#518]
Currently, the staging environment is displaying the wrong header navigation menu items. It should show (from left to right): The federalist logo, the logged in user's name (with a link back to their 'sites' list, and a 'log out' link.

**Comment by wslack** [comment]
I'm ok with it as is, though the "contact us" button should maybe be an e-mail address or the sign-up button?

**Comment by el-mapache** [comment]
Should we open a new issue for that behavior? I'm trying to get parity between the two environments

**Comment by wslack** [comment]
@el-mapache they have parity now?

**Comment by el-mapache** [comment]
No, but this gets us closer!
