### ISSUE TITLE
Enable Federalist users to update their homepage

### ISSUE THREAD

**Issue by wslack** [18F/federalist#526]
- [ ] Logo
- [ ] Make homepage editable from Federalist
- [ ] Basic content block support

**Comment by el-mapache** [comment]
Couple of comments for this issue 👇 

1). Basic content block support seems different to me from the rest of the tasks on this issue. Do we expect that content blocks would be a feature usable from any page? What interface allows the user to edit the content blocks? Is each one supposed to have it's own WYSIWG editor? It seems like that point should be its own issue.

2). On the basic federalist modern team template, the home page, or at least a file under the pages directory named `home.md` is editable by default. Is there a different page not represented in the `_navigation.json` file that points to the homepage? If not, there might be something wrong with the sbst-specific fork of the template.

thanks!

**Comment by wslack** [comment]
@el-mapache 

1. I don't know! I think full support is a ways off - the basic ask (I think) is the ability for someone to take our template homepage and remove sections at will. t doesn't need a WYSIWG editor as much as a way to edit the code with clear comments (at least as an MVP). Alternatively, Federalist could have instructions for editing on GitHub for certain scenarios.... 💭 

2. I think it is with their old fork (they also can't see the project pages). However, the editor on the current template only allows edits for some of the text. This might be a rabbit hole, though, just given how the page is coded to use front matter.

**Comment by jmhooper** [comment]
closing as the editor has been disabled
