### ISSUE TITLE
Set up an error message to flag when Federalist cannot parse information from GitHub

### ISSUE THREAD

**Issue by wslack** [18F/federalist#527]
- [ ] Have instructions for a user about how to reset a page or ask for help

**Comment by el-mapache** [comment]
This feels a little vague to me -- what does not being able to parse the content look like? Does this mean that nothing appears on the page? That an error has appeared but is non-sensical to a non-technical editor?

I think maybe some specific scenarios of what the problems are and what the user's see when they occur could be super helpful when we design a solution.

P.S. is there a way currently for a user to 'reset' a page via federalist? I guess this means checking out a clean version from the base repo? Or does it mean resetting to a previous state?

**Comment by wslack** [comment]
@el-mapache the current behavior is a blank page when trying to click into the editing page. We just need something better than that. To reproduce, add a hard return to the front matter, save the page, then try to reload it in the editor.

I don't think there's a reset mechanism right now either. The instructions might just be "e-mail federalist-support; this happens because of a typo introduced in past editing" or something like that.

**Comment by wslack** [comment]
Closing as the editor has been disabled.
