### ISSUE TITLE
Support a project page and drilldown project pages using a basic data schema on a Federalist template

### ISSUE THREAD

**Issue by wslack** [18F/federalist#529]
A Federalist customer would like to have a "projects page" that allows someone to view a team's projects.

The set of people should be drawn from a collection of markdown files or a similar data schema. The "project page" should enable someone to see the following:

- [x] Image
- [x] Name
- [x] Sort by various tags

Drilling down should allow users to see
- [x] A subpage with more Information and various data, including a description

**Comment by wslack** [comment]
model: https://18f.gsa.gov/what-we-deliver/

using data in this format: https://github.com/18F/18f.gsa.gov/tree/master/_projects

**Comment by wslack** [comment]
Step by step:
https://federalist.fr.cloud.gov/preview/gsa-oes/office-of-evaluation-sciences/will-slack-project/what-we-deliver/
https://federalist.fr.cloud.gov/preview/gsa-oes/office-of-evaluation-sciences/will-slack-project/what-we-deliver/agile-bpa

**Comment by mearley2013** [comment]
Clarifying on tags desired for each project (for sorting on the landing page, and to be shown in the sidebar of the drill-down, project specific page): Year, Domain, Agency Collaborator, Government Impact

Also, on the drill-down, project specific page, the sidebar content should include the tabs mentioned above, and a place for the link to the project abstract (very very similar to the 18f model linked to above)

For most projects, there will be an image or two that will need to be displayed within the following four text headers (reference the Reducing-Summer-Melt page on the will-slack-project branch within /_projects): What was the challenge?; What was the program change?; How did the evaluation work?; What was the impact?.

let me know what the specific needs are for the photos for each project, and I can get working on that as well!

Thanks!
Mo

**Comment by maya** [comment]
@mearley2013 I've added the new project variables (Year, Domain, Agency Collaborator, Government Impact) to the front matter on the `update-uswds` branch so they're ready to go: https://github.com/gsa-oes/office-of-evaluation-sciences/commit/c86d1592f2cf6bfb16088736fb1bbe76aec6e69c

**Comment by maya** [comment]
@mearley2013 Aside from the project cards, what content should be on the project page? Can we remove the first image so you can see the projects more easily? Do you want "Our approach" to be the intro text to that page?

**Comment by mearley2013** [comment]
@maya Can you send a link so I can preview? It will help me make a decision about your second question. thank you!

**Comment by maya** [comment]
@mearley2013 sure! Here's the prototype (still a work in progress): https://federalist.fr.cloud.gov/preview/gsa-oes/office-of-evaluation-sciences/update-uswds/projects/

I actually removed the image already, but you can see how the text and headings take up space before getting to the project cards. And we still need to build a filter which will take up space.

**Comment by maya** [comment]
@mearley2013 here are the dimensions I promised you for the project images: 
Width is: 1460px

It can be any height bc it will be set dynamically. No need to "size up" to the above if you don't have anything that big, just send us what you have. Thanks!

**Comment by wslack** [comment]
Project page: https://federalist.fr.cloud.gov/preview/gsa-oes/office-of-evaluation-sciences/update-uswds/projects/

**Comment by wslack** [comment]
Thank you @maya! closing this as part of Federalist retro.
