### ISSUE TITLE
Test for datetime.js relies on the current time of the environment

### ISSUE THREAD

**Issue by brandocalrissian** [18F/federalist#534]
the test: timefrom() -> shows a human readable elapsed time from start date

It fails now as we are no longer four months from the hardcoded time. Perhaps it'd be better to generate the startTime/endTimes in the test based on the current time?

**Comment by brandocalrissian** [comment]
<running tests>
1 failing

  1) datetime timeFrom() shows a human readable elapsed time from start date:

      AssertionError: expected '5 months ago' to equal '4 months ago'
      + expected - actual

      -5 months ago
      +4 months ago
      
      at Context.<anonymous> (test/client/app/util/datetime.test.js:30:36)

**Comment by el-mapache** [comment]
Fixed in https://github.com/18F/federalist/pull/525/commits/2891f577c14504075e8c0352cedde774a1c25ed3
