### ISSUE TITLE
Custom domain not working

### ISSUE THREAD

**Issue by jfredrickson5** [18F/federalist#540]
Either the custom domain setting is not working, or I am missing a step somewhere. I am seeing a 404 when hitting our custom domain: http://cto.gsa.gov/

```
404 Not Found
Code: NoSuchBucket
Message: The specified bucket does not exist
```

We have cto.gsa.gov configured as a custom domain in the Federalist dashboard, and an ALIAS record configured per the [custom domain section in the Federalist docs](https://federalist-docs.18f.gov/pages/using-federalist/).

```
;; ANSWER SECTION:
cto.gsa.gov.            96      IN      CNAME   federalist.18f.gov.s3-website-us-east-1.amazonaws.com.
federalist.18f.gov.s3-website-us-east-1.amazonaws.com. 59 IN CNAME s3-website-us-east-1.amazonaws.com.
s3-website-us-east-1.amazonaws.com. 4 IN A      54.231.120.113
```

We have not yet tried to set up HTTPS with a SSL certificate.

**Comment by wslack** [comment]
@jfredrickson5 we know the documentation on this isn't good. We have to do some work to explain what has to happen in Cloudfront custom domains work.

Question, though - did we execute an agreement to make y'all a live customer? I thought that was still in process.

**Comment by jfredrickson5** [comment]
Not sure on the status of the agreement, but we are not ready to go live. We just wanted to make sure the domain worked. The site should be rendering a placeholder page and not the actual site. If we shouldn't set up a custom domain until the live agreement, then no problem, we don't have to use the custom domain for now.

**Comment by wslack** [comment]
@jfredrickson5 we have a lot of custom domains working elsewhere on the platform so I'm not worried about this being too difficult when we're ready.

**Comment by jfredrickson5** [comment]
OK, we can table this for now. Do we need to do anything on our end for Cloudfront?

**Comment by wslack** [comment]
@jfredrickson5 nope!

**Comment by wslack** [comment]
@jfredrickson5 I ran this down; we'll be following the steps here: https://docs.cloud.gov/apps/custom-domains/#managed-service-method (with some additional arguments to make them work for you)

**Comment by wslack** [comment]
Here's the PR with how this will work in the future! https://github.com/18F/federalist-docs/issues/12

**Comment by wslack** [comment]
@jfredrickson5 any questions about the new documentation or can we close this issue?

**Comment by jfredrickson5** [comment]
All good for now, thanks!
