### ISSUE TITLE
Refactored federalist doesn't display nested files on page load

### ISSUE THREAD

**Issue by el-mapache** [18F/federalist#548]
Navigating to the pages directory doesn't show nested files.

<img width="871" alt="screen shot 2016-10-12 at 10 43 52 am" src="https://cloud.githubusercontent.com/assets/1421848/19314629/dc0894d2-9068-11e6-86bb-eac738590e97.png">

Once the `open` button is clicked, and the user manually navigates back to the previous page, the user is able to see the files nested in the parent directory.

<img width="858" alt="screen shot 2016-10-12 at 10 45 17 am" src="https://cloud.githubusercontent.com/assets/1421848/19314664/ff254b7c-9068-11e6-813c-2e9d0ad4d1ce.png">

This issue can be reproduced if you don't have a compiled navigation.json file. However, its unclear if that is a prerequisite to observing this behavior.

_AC_
On page load, users should be able to view nested files

**Comment by brandocalrissian** [comment]
* Does this work in the current master branch?
* Are the missing files contained within the "projects" directory (if that makes any sense)? I'm *guessing* the request to open the projects directory loads the next set of files and then these files are then added to the client-side state.

**Comment by el-mapache** [comment]
Yes, this currently works in the backbone branch on federalist.18f.gov.
The missing files are contained in the projects directory. I'm not sure why they aren't nesting, that is a separate issue, I suppose.

**Comment by brandocalrissian** [comment]
I keep looking at the backbone version of the app and don't see how it could have the behavior. After using it a bit, I wonder if the bug is actually displaying the nested files when the user hits the back button. That's the bit that's confusing to me as a user, especially when the bread-crumb navigation works.

**Comment by wslack** [comment]
@brandocalrissian this feature doesn't seem like a huge priority, so long as we can build out Federalist sites to make it really easy to edit one's pages

**Comment by wslack** [comment]
dropped priority

**Comment by jmhooper** [comment]
closing as the editor has been disabled
