### ISSUE TITLE
Document how to launch a static site on Federalist (was: launch epa-notice.usa.gov migration)

### ISSUE THREAD

**Issue by cmc333333** [18F/federalist#551]
We have a cloud.gov application running on epa-notice.usa.gov. We want to replace it with a Federalist-based static site (http://federalist.18f.gov.s3-website-us-east-1.amazonaws.com/site/18F/epa-notice-landing/)

From a discussion with @wslack and @jezhumble the path forward is the following (order may not be accurate)
- [x] Use the cloud.gov CloudFront broker to set up a distribution for epa-notice.usa.gov. See [docs](https://docs.cloud.gov/apps/custom-domains/#managed-service-method). Coordinate with @wslack about where to point it. Ask @jmcarp when help is needed.
- [x] We need to determine who controls the usa.gov domain to. @jezhumble to ask @jpyuda, @cmc333333 to ask @Journerdism 
- [x] When the above is figured out, we need to work with infrastructure to delegate the subdomain
- [ ] We want to document the above for Federalist as this will be a recurring task

**Comment by cmc333333** [comment]
Done and done. Here are the steps, using epa-notice.usa.gov as an example:

1. Publish your static site on federalist; find its url, e.g. http://federalist.18f.gov.s3-website-us-east-1.amazonaws.com/site/18F/epa-notice-landing/
2. Sign in to GovCloud Cloud.gov: `cf login -a api.fr.cloud.gov --sso
3. Select `gsa-18f-federalist` / `sites` for the organization/space
4. Create a CDN service:
```
cf create-service cdn-route cdn-route epa-notice.usa.gov-route -c '{"domain": "epa-notice.usa.gov", "origin": "federalist.18f.gov.s3-website-us-east-1.amazonaws.com", "path": "/site/18F/epa-notice-landing", "insecure_origin": true}'
``` 
(swapping out the domain, service name, and path for your values)
5. The above command will give you a cloud front distribution, such as `d2oezh1w8w4o1u.cloudfront.net`
6. Contact the owner of the root domain (in our case, GSA IT owns usa.gov) and ask them to add a CNAME to that distribution (e.g. epa-notice.usa.gov -> d2oezh1w8w4o1u.cloudfront.net)

**Comment by wslack** [comment]
Done here: https://federalist-docs.18f.gov/pages/how-federalist-works/custom-urls/
