### ISSUE TITLE
Setup continuous scanning with Clair

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#556]
We should setup [Clair](https://github.com/coreos/clair) so that it runs in cloud.gov and scans images in our private registry. We should scan under the following circumstances:
1. An image is pushed to the private registry
2. Vulnerability data changes upstream

**Comment by jseppi** [comment]
I wonder if there is anything from cloud.gov or GSA IT that we could leverage for this instead of setting up our own scanning mechanism. Needs investigation.

**Comment by wslack** [comment]
This is *super old* and @jmhooper can confirm, but I think we can just close this. It was based on an unfounded concern about Docker.

**Comment by wslack** [comment]
Closing per language on Feb 16. Amir to also learn about what Clare.
