### ISSUE TITLE
Fix or mitigate all clair vulnerabilities

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#557]
We used Clair to scan our [federalist-docker-build]() images and found some vulnerabilities. We need to address those for our ATO.

**Comment by wslack** [comment]
I think this can be moved to Done?

**Comment by wslack** [comment]
These are in the PO&AM and need to be worked through with the ATO team. Moving to blocked until then.

**Comment by wslack** [comment]
Pending direction from the ATO team.

**Comment by jseppi** [comment]
I think we can close this based on discussion in https://github.com/18F/federalist/issues/1035
