### ISSUE TITLE
Enable AWS_DEFAULT_REGION as an ENV variable

### ISSUE THREAD

**Issue by wslack** [18F/federalist#562]
This is necessary because we are migrating our sites from S3 in E/W to S3 in GovCloud.

To enable us to use one container image for multiple environments, we should set AWS_DEFAULT_REGION as a variable provided to the container environment by the main web app here: https://github.com/18F/federalist/blob/master/api/services/SQS.js#L38

**Comment by el-mapache** [comment]
Already added

**Comment by jmhooper** [comment]
Added in #563 here: https://github.com/18F/federalist/pull/563/files#diff-5ca03731f36ebee29a0218c7eb5ed4c1R38

We can close this once that is merged 👍

**Comment by wslack** [comment]
done!
