### ISSUE TITLE
Clean up and document branches in https://github.com/18F/federalist/branches

### ISSUE THREAD

**Issue by wslack** [18F/federalist#565]
We have a complicated branch structure during the migration, if I have this right:
- `master` doesn't do anything anymore
- `make_deploys_work_again` is the live code
- `staging` is the staging code (currently on E/W)
- `stagig-test-test` is the GovCloud Staging Code

We should prune old branches and change `master` to the new Production branch, I think?

**Comment by wslack** [comment]
Live site right now:
 - make_deploys_work_again on cloud.gov E/W

Legacy staging:
 -  staging > staging-legacy on cloud.gov GovCloud

Staging site right now:
 - stagig-test-test > staging on cloud.gov GovCloud

Production-in-waiting:
-  stagig-test-test (fork) on cloud.gov GovCloud, will become master

**Comment by wslack** [comment]
haven't messed with "master" yet. That will happen when staging is stable.

**Comment by wslack** [comment]
immediate steps:

clean up master
do a new test deploy
consider deplying shawn's code.

**Comment by jmhooper** [comment]
Master now reflects what's on federalist.18f.gov. Also, master _should_ be able to deploying from CI. We will not be able to confirm this until we get a new set of deployer creds from cloud.gov support.

**Comment by wslack** [comment]
@jmhooper here's to realizing these issues now and before we have a deploy issue!
