### ISSUE TITLE
Allow users to choose custom org for a repo being created

### ISSUE THREAD

**Issue by wslack** [18F/federalist#571]
See https://github.com/18F/federalist/pull/472

**Comment by jmhooper** [comment]
@wslack:

> how easy would it be to allow this? I worry about the number of edge cases where people try to create repos they aren't allowed to.

This would not be too complicated to setup. The authorization should fall to GitHub which should prevent users from creating sites they aren't allowed to.

The issues we'll see with this come from 2 things:

1. It isn't clear what part of the application is responsible for communicating with GitHub. At the moment that is handled both on the frontend and on the backend. We may want to consolidate that logic before we add more complexity
2. We don't have a very robust system for alerting users to errors that have occurred. This will be a problem if a user attempts to add a site and encounters an authorization problem. We'll want to communicate the problem which right now is something that app struggles to do.

**Comment by wslack** [comment]
related to https://github.com/18F/federalist-docs/issues/39

**Comment by jmhooper** [comment]
This was done in #762
