### ISSUE TITLE
Make new diagram for Federalist architecture

### ISSUE THREAD

**Issue by wslack** [18F/federalist#572]
- [x] Draft new diagram
- [x] Noah reviews
- [x] GSA IT reviews
- [x] Publish on federalist-docs.18f.gov

**Comment by wslack** [comment]
New version:
![screen shot 2016-10-27 at 8 19 50 pm](https://cloud.githubusercontent.com/assets/10016577/19790039/c8fbf9bc-9c82-11e6-959e-656316fd63ed.png)

**Comment by jmhooper** [comment]
I was working with this diagram today and realized that it does not have S3 anywhere.

**Comment by wslack** [comment]
@jmhooper bottom right

**Comment by jmhooper** [comment]
Ah, there it is. My bad. Carry on.

**Comment by jmhooper** [comment]
In the same vein, should we consider adding a component for a site visitor viewing the site on s3? Or maybe something about them talking to cloudfront and cloudfront talking to s3?

**Comment by jmhooper** [comment]
Also, the line drawing a connection between GitHub and federalist-builder should not be there. federalist-builder does not pull anything from GitHub. Only federalist and the build containers do that.

**Comment by jmhooper** [comment]
One more note: The build container communicates with federalist-builder. Whenever the build has finished, the container calls back to federalist-builder so federalist-builder knows the container has finished and it can stage a new build on it.

**Comment by wslack** [comment]
@jmhooper how does builder get the contents of the repo? The webhook call doesn't contain all of that information. Are you saying the build container should get the arrow instead of the builder?

**Comment by jmhooper** [comment]
The builder does not need to know what is on the site. It just needs to pass the information needed to pull that information down to the build container. The build container pulls the site itself here: https://github.com/18F/federalist-docker-build/blob/master/clone.sh#L9

So yes, the line that goes from GitHub to the builder should instead go from GitHub to the container.

**Comment by wslack** [comment]
Ok, so the changes we need:

- Add CloudFront -route service instances for custom domains
- change connection from GitHub to federalist-builder to be with the container
- Add box on left side for members of public viewing the sites (on either S3 or CloudFront)

**Comment by jmhooper** [comment]
We also need to add a path between the builder and the container. The builder starts the container and the container calls back to the builder to let it know it has finished building.

**Comment by wslack** [comment]
Does the container call back to the builder and to the main app or just one of them?

**Comment by jmhooper** [comment]
It calls back to both of them.

**Comment by wslack** [comment]
<img width="788" alt="screen shot 2016-11-23 at 12 46 12 pm" src="https://cloud.githubusercontent.com/assets/10016577/20572795/028fe9d8-b17b-11e6-97e8-14cb9e5a8125.png">

**Comment by wslack** [comment]
This is blocked pending @NoahKunin's review

**Comment by NoahKunin** [comment]
@wslack Reviewing now, but in the future, while I think I can often be a helpful pair of 👀s, I'm not a require reviewer. I'm not going to even enforce these to be reviewed by your Infra Lead, and let each BU figure out the process that works for them. I'm not even at the point where I will laying down an edict of how to draw these things (yet).

In unblocking myself I'll leave you with the following notes none of which are mandatory for the current ATO:

1. While I would know what the bi-directional orange arrow between GitHub and the vanilla `federalist` box means, I'm not sure someone else would absent other context. In keeping with a "less is more" perspective, the purpose of the bi-directional channel (edits in the Federalist GUI are written as commits to GitHub) is less important than in which directions are reads vs writes. I wouldn't bother changing this at the moment, but I usually think of each connection as a 2x2 matrix (client-bound reads/writes vs server-bound reads/writes) and draw it accordingly. 

Example:

<img src="https://cloud.githubusercontent.com/assets/565071/20642592/f6652fac-b3e0-11e6-84cf-8e1da0da980a.JPG" width="250">

I also usually color code `client-bound` vs `server-bound` flows differently to make it really easy to grok the system. 

2. When GitHub fires a web, is there any "response"? The above diagram says there is, but isn't it just a uni-directional `POST` at the moment?

3. Looks like the registry is now _in_ cloud.gov? That's great! Last I checked it was local to the client (laptop). Sweet!

**Comment by wslack** [comment]
I think we said that you were required because of the importance of the new Federalist ATO, but good to know that that will not be always the case. 

1. Good point.  You're correct that federalist is writing to GitHub, and not the other way around. 

2.  There is a response,  but it is only confirmation or an error message if something didn't work (like a mismatched sig). We can clarify.

3. Yes!

**Comment by wslack** [comment]
Version going onto federalist-docs:
![screen shot 2016-11-28 at 4 38 08 pm](https://cloud.githubusercontent.com/assets/10016577/20687079/15a1c638-b589-11e6-98c1-95f508d2d6f8.png)

**Comment by wslack** [comment]
https://github.com/18F/federalist-docs/pull/28 filed

**Comment by wslack** [comment]
Also, I dropped the .graffle file [here](https://drive.google.com/drive/u/0/folders/0Bw50xHl95jZwVXdNTTl3bXBXX0U) to avoid a risk of local disk failure.

**Comment by wslack** [comment]
<img width="397" alt="screen shot 2017-01-12 at 10 51 56 am" src="https://cloud.githubusercontent.com/assets/10016577/21896644/1fd70f24-d8b5-11e6-8be1-b051aea6a2cb.png">
@jmhooper does this show the S3 bucket for the registry well?

**Comment by jmhooper** [comment]
@wslack: Yes 👍

**Comment by wslack** [comment]
New image in SSP: ![screen shot 2017-01-12 at 11 16 58 am](https://cloud.githubusercontent.com/assets/10016577/21897829/b3742c5a-d8b8-11e6-800d-728800f11687.png)
