### ISSUE TITLE
Add request specs

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#576]
We need to add some request specs so we can modify the backend with confidence that we aren't introducing regressions to the API. The following API features need tests:
- ~~Auth~~
  - [ ] ~~Sign in~~
  - [ ] ~~Sign up~~
  - [ ] ~~Sign out~~
- Builds
  - [x] Find
  - [x] Find One
  - [x] Status
- Sites
  - [x] Find
  - [x] Find One
  - [x] Update
  - [x] Destroy
  - [ ] ~~Fork~~
  - [x] Clone
  - [ ] ~~Lock/unlock~~ 
- ~~Previews~~
  - [ ] ~~Proxy~~
- Users
  - [x] Find
  - [x] Find One
  - [ ] ~~Populate~~
  - [x] Username
  - [ ] ~~Add Site~~
- ~~Webhook~~
  - [ ] ~~Github callback~~

This will require work to setup a testing harness that will allow us to streamline things like creating test records, mock authentication, etc. This can be done as we write tests and see the need for such things.

**Comment by wslack** [comment]
This should take X hours for easiest pieces, and Y hours for everything.  @jmhooper to provide best estimates

**Comment by jmhooper** [comment]
Per #589:

> We are electing not to test the `fork` action since it does not seem to be implemented anywhere outside of the policies. We also aren't testing the `lock` and `unlock` actions since they are buggy and therefore not used for anything.

**Comment by jmhooper** [comment]
Also, regarding estimates:

- Auth: Very uncertain. May need to mock GitHub API calls which could take a while. 6-8 hours perhaps?
- Previews: 1-2 hours
- Users: 6 hours
- Webhook: 3 hours

**Comment by jmhooper** [comment]
Holding off on `user#populate` and `user#usernames` in light of #596 and #597

**Comment by jmhooper** [comment]
Auth moved to #598
GitHub webhook moved to #599
Previews moved to #600
