### ISSUE TITLE
Add build container logging

### ISSUE THREAD

**Issue by wslack** [18F/federalist#580]
- [x] Logging of activities within build container.
- [x] Count number of files produced (issue filed)
- [x] Log issues when setting up the build container (issue filed)
- [x] Consider having Federalist fail builds automatically if the containers don't launch (issue filed)

**Comment by wslack** [comment]
Filed https://github.com/18F/federalist-docker-build/issues/26 for the second item

**Comment by jmhooper** [comment]
Filed 18F/federalist-builder#15 for the third and fourth items
