### ISSUE TITLE
Drop circle-ci integration for now

### ISSUE THREAD

**Issue by brandocalrissian** [18F/federalist#583]
We're using travis and circle to fulfill the same purpose (automated building/test running). We should pick one.

Right now, the circle-ci builds are failing while travis builds are succeeding. It looks to be a caching issue on the circle-ci side.

Instead of fixing the circle-ci build right now and disabling travis, let's disable the circle-ci integration. We can always migrate to (the potentially more responsive) circle-ci later.

**Comment by brandocalrissian** [comment]
Disabled the webhook to disable circle-ci. I didn't remove the deploy key as we can use circle ci again later by adding the webhook back.

Verified it was a caching issue by clearing the cache on the circle ci side and re-running four failed builds. They all worked.

**Comment by brandocalrissian** [comment]
reopened to put it in the "Done?" bucket on the zenhub board. Seemed strange to close something on the board without discussing it with the team as per our normal process.

**Comment by wslack** [comment]
done!
