### ISSUE TITLE
Rename build container environment's PREFIX variable

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#584]
The `PREFIX` variable is sent in the build container environment to a build container which causes issues with NVM. Details about this problem are laid out in #570

Per my comments there, we should consider changing the name of the `PREFIX` container env variable to something like `SITE_PREFIX` in the web app and in the build container.

Here's where it is set in the web app: https://github.com/18F/federalist/blob/c0302467f5e63b4c5dd70f2c603bc4cb1d42da00/api/services/SQS.js#L49

**Comment by wslack** [comment]
this is holding for our retirement of E/W

**Comment by wslack** [comment]
Deployed in staging!
