### ISSUE TITLE
Define New Site User Workflow

### ISSUE THREAD

**Issue by bradnunnally** [18F/federalist#59]
This diagram is an initial draft of the potential workflow a user can go through to create a new site that is either custom (existing site or blank slate) or a template. 

I'm hoping to start the critical analysis of the various steps a user might have to go through when creating a new site and having to fill out certain pieces of information for Federalist to respond correctly. 

![federalist_new_ site_flow_v0](https://cloud.githubusercontent.com/assets/12515096/8169580/66c98d2a-1378-11e5-97de-764118516806.png)

**Comment by jeremiak** [comment]
I"m not sure what we want to ask users. It seems like we're not going to need to inject any sort of specific UA id (there is a gov-wide one we will use), so at this point I think we actually don't need to collect any information from the user beyond the type of template that they want.

**Comment by dhcole** [comment]
> I'm not sure what we want to ask users.

For users who want to "turn on" DAP analytics, we will need to collect a few things like agency, listed in #57

**Comment by jeremiak** [comment]
Essentially we would use that "agency" to populate the email that we sent off to the DAP team? It was my understanding that there is just one code snippet that works across all the sites and the filtering actually happens on the back end?

**Comment by dhcole** [comment]
We need to do two things with the `agency` and optionally `subagency`:

- add them as query string parameters to the url in the script tag for the DAP js file
- send them off to the DAP team view email

**Comment by jeremiak** [comment]
:+1: got it!

**Comment by dhcole** [comment]
Moved to the design wiki page: https://github.com/18F/federalist/wiki/Design-Documentation
