### ISSUE TITLE
Check if origin for config/cors.js can be set by environment.

### ISSUE THREAD

**Issue by wslack** [18F/federalist#590]
Per https://github.com/18F/federalist/pull/578#issuecomment-257919305

Can http://sailsjs.org/documentation/concepts/security/cors be set per environment?

**Comment by el-mapache** [comment]
It can certainly be set per environment. However, the PR I put in was basically a quick work around to a security vulnerability; I don't actually think this app needs CORS support at all.

**Comment by wslack** [comment]
I just opened this based on Brandon's comment, but happy leaving this in icebox (or just closing) if that makes sense.

**Comment by el-mapache** [comment]
Icebox seems fine!

**Comment by jseppi** [comment]
This seems like it can be closed. Not using sails any more :) And federalist the web app still does not need to support CORS.

**Comment by el-mapache** [comment]
@wslack We should close this out!
