### ISSUE TITLE
Consider removing `usernames` action from user API

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#596]
The user API expose a `usernames` action at `/v0/user/usernames` which can be used to access the usernames of all users on Federalist.

We should look to see if this is used anywhere, or if we have any intention of using it in the future, and if not we should remove it.

**Comment by jmhooper** [comment]
This may be necessary to implement the necessary controls for our System ATO. Specifically looking at [AC-2](https://web.nvd.nist.gov/view/800-53/Rev4/control?controlName=AC-2):

> Reviews accounts for compliance with account management requirements [Assignment: organization-defined frequency];

**Comment by wslack** [comment]
agreed. We need this.
