### ISSUE TITLE
Merge Passport and User model

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#625]
As it stands, a user only ever has one Passport record. In fact, there are several potential error states that arise if a user has more than one Passport. This makes the relationship an obvious candidate for a refactor.

We can simplify a lot of the logic in the backend by merging the Passport model into the User model. This would carryover into some less dramatic changes in the frontend that would mostly increase readability.

The attributes we'd need to merge over to the User model would be

- githubUserID <currently Passport.identifier>
- githubAccessToken <currently Passport.tokens.accessToken>

The rest of the attributes on the Passport model have values that are hardcoded into the application code where they're set and would not need to be migrated.

**Comment by wslack** [comment]
@jmhooper how much time do you think this will take?

**Comment by jmhooper** [comment]
Tough to call because it involves writing a migration which I've never done with Sails, but should be PR ready within 4 hours.
