### ISSUE TITLE
Create table of ports / protocols used in Federalist

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#635]
We need to create a table of the ports / protocols that Federalist uses for the ROE. This should include:

- What parts of the architecture are communicating
- What is being communicated
- What protocol is being used
- What port that protocol is using
- _tentative*_ How that communication is secured

**Comment by jmhooper** [comment]
| Components | Data | Protocol | Port |
|-|-|-|-|
| federalist / Site editor's browser | Requests involving site management | HTTPS | 443 |
| federalist / SQS | AWS API requests to add messages to the SQS queue | HTTPS | 443 |
| federalist / GitHub | Requests to load and edit content in a site's GitHub repository | HTTPS | 443 |
| federalist / GitHub | Webhook request in response to push event | HTTPS | 443 |
| federalist / build container | Request for federalist to update the status of a build running in the container | HTTPS | 443 |
| federalist / federalist-database | SQL queries to the postgres database | Postgres | 5432 |
| federalist / federalist-redis | Read / write requests to the redis instance to update session data | Redis | 6379 |
| federalist-builder / SQS | AWS API requests to read and delete messages from the SQS queue | HTTPS | 443 |
| federalist-builder / build container | cloud.gov API requests to update the build container's application environment and restage the application | HTTPS | 443 |
| build container / federalist-registry | Requests to pull an image to run in container | HTTPS | 443 |
| build container / GitHub | Requests to clone a site's repository via HTTPS | HTTPS | 443 |
| build container / federalist-s3-service | Requests to change site content in the S3 bucket | HTTPS | 443 |
| build container / federalist-builder | Requests to mark the container as available | HTTPS | 443 |
| federalist-s3-service / Site visitor's browser | Requests for site content | HTTPS | 443 |

**Comment by wslack** [comment]
Are these all TCP or UDP?

**Comment by jmhooper** [comment]
I am not 100% sure on redis, but the others are for sure. I'm like 90% sure redis uses TCP but I'd have to check.

**Comment by jmhooper** [comment]
> A client connects to a Redis server creating a TCP connection to the port 6379.

ref: http://redis.io/topics/protocol

**Comment by wslack** [comment]
Ok, for right now I think we should move this table's "source of truth" to the ROE document.

**Comment by wslack** [comment]
Need to add cloudFront

**Comment by wslack** [comment]
Closing since this issue is done
