### ISSUE TITLE
Determine what Clair vulnerabilities don't have an upstream fix in apt-get

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#636]
We need to determine which vulnerabilities found by Clair in federalist-docker-build don't have an upstream fix in Ubuntu 14.04's default or universe repositories.

**Comment by wslack** [comment]
@jmhooper status check on this  is this needed for ATO?

**Comment by jmhooper** [comment]
The vulnerabilities are in the POAM which I believe is good enough for the ATO.

We may need to make a pass through the POAM to see if there are any vulnerabilities that are supposed to be mitigated in the coming weeks (I remember some of them having January / February due dates).

**Comment by jmhooper** [comment]
Sorry, meant to comment the above on a different issue. This is not necessary for the ATO, but it will help us push back the dates on some of these.

**Comment by wslack** [comment]
Closing as we don't use Clare anymore cc @jmhooper
