### ISSUE TITLE
Add docs on how to deal with a failed deploy

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#661]
When a deploy fails, often time the venerable app that is created by autopilot does not get cleaned up. We should add documentation to the "Deploying Federalist" guide that explains how to deal with this situation.

Along with this work we could also add some documentation about how CI deploys are configured to work on Travis with autopilot since that documentation does not exist at this time.

**Comment by wslack** [comment]
Answered here: https://federalist-docs.18f.gov/pages/how-federalist-works/deploying-federalist/
