### ISSUE TITLE
Only way to know you aren't authorized because of orgs is the URL

### ISSUE THREAD

**Issue by jeremiak** [18F/federalist#67]
If you try and authenticate with a user that is not in one of the whitelisted organizations, you can't get in. This is awesome!

However, the only way the user would know this is if they looked at the resulting URL and saw `?error=Error.Passport.Unauthorized`. The frontend should handle this error and relay this message to the user so that they know how to get access and that the app is not just broken.

**Comment by dhcole** [comment]
Here's the list of possible error messages from the Sails authentication module with their recommended explanations. Usually, these would be added to the page as a flash message, but we're using without server-generated views, so I pass just the error key to the URL as an `error` parameter. Feel free to disregard or change the message strings. 

Also, I added `Error.Passport.Unauthorized` for users that are not part of an approved organization.

```json
{
  "Error.Passport.Password.Invalid": "The provided password is invalid!",
  "Error.Passport.Password.Wrong": "Whoa, that password wasn't quite right!",
  "Error.Passport.Password.NotSet": "Oh no, you haven't set a password yet!",
  "Error.Passport.Username.NotFound": "Uhm, what's your name again?",
  "Error.Passport.User.Exists": "This username is already taken.",
  "Error.Passport.Email.NotFound": "That email doesn't seem right",
  "Error.Passport.Email.Missing": "You need to supply an email-address for verification",
  "Error.Passport.Email.Exists": "This email already exists. So try logging in.",
  "Error.Passport.Username.Missing": "You need to supply a username",
  "Error.Passport.Password.Missing": "Oh no, you haven't set a password yet!",
  "Error.Passport.Generic": "Snap. Something went wrong with authorization.",
  "Error.Passport.Unauthorized": "You're account is not approved for access."
}
```
