### ISSUE TITLE
Site container redirects to site list when refreshed

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#671]
When the site container is refreshed, it redirects to the site list. This is because it is rendered before the `siteActions.fetchSites` action resolves triggering the `SITES_RECEIVED` action. Because of that it is rendered without site data and redirects to `/sites`.

We should build out the `SiteContainer` component so that it waits for site data before deciding whether it should render data or redirect.

**Comment by wslack** [comment]
@jmhooper I am having a hard time following the impact to the user - what is the negative outcome in the status quo?

**Comment by jmhooper** [comment]
If you got to a site and select any of the links in the sidebar then refresh, instead of refreshing the page it redirects you to the site list. So you refresh and then wind up on a totally different page.

This did not happen in the past because of a bug, the fix for which was recently merged.

**Comment by wslack** [comment]
@jmhooper gotta love bug fixes that unleash other issues. Thanks!
