### ISSUE TITLE
S3 settings to examine

### ISSUE THREAD

**Issue by wslack** [18F/federalist#672]
<img width="680" alt="screen shot 2016-12-07 at 6 20 23 pm" src="https://cloud.githubusercontent.com/assets/10016577/20990995/e45a0338-bca9-11e6-8fbb-edb6459e42b5.png">

**Comment by wslack** [comment]
index.html is already there, 404.html may also be wanted

**Comment by wslack** [comment]
Browsers will auto-seek a 404 page.

**Comment by jmhooper** [comment]
These settings can be configured use the [AWS CLI's `s3 website` command](http://docs.aws.amazon.com/cli/latest/reference/s3/website.html).

We mention using this command in [Federalist Docs](https://github.com/18F/federalist-docs/blob/5eb95c9908f6e0497438d7901e7478bfdc5778ca/pages/how-federalist-works.md#creating-new-buckets), but should update it to mention the 404 page.

**Comment by jmhooper** [comment]
18F/federalist-docs#41 is open to cover this. I also updated the bucket in staging to have a generic error document. You can check it out [here](http://cg-f28e32aa-d42e-4906-a813-7d726f69183c.s3-website-us-gov-west-1.amazonaws.com/this/is/not/a/real/website).

With both of those things out of the way, I'll move this to done.

**Comment by wslack** [comment]
Merged the PR.
