### ISSUE TITLE
Research work effort to disable editor interface

### ISSUE THREAD

**Issue by wslack** [18F/federalist#683]
- [x] Will to interview Austin
- [x] Will to interview Amira
- [x] Jonathan to look at code
 - [x] isolate the editor-related issues

**Comment by jmhooper** [comment]
Here's a preview of what the work would look like: https://github.com/18F/federalist/compare/staging...jmhooper-spike-remove-editor

So far, removing the editor has been pretty straightforward. Tracking down all of the code that supports it has not been so straightforward. Also, without the editor the frontend feels like it has some unnecessary complexity that was put in so it could support the editor.

**Comment by jmhooper** [comment]
### Without structural changes to the frontend:

- Optimistic: 6 hours
- Pessimistic: 12 hours

### With structural changes to the frontend:

- Optimistic: 12 hours
- Pessimistic: 21 hours

**Comment by wslack** [comment]
@jmhooper the structural changes would (in effect) lower the ability to reinstate the editor later, right?

**Comment by jmhooper** [comment]
In it's current form, yes

**Comment by wslack** [comment]
Feedback:
> based only on my individual experience I have found it more accessible to use github’s interface to make changes, github’s interface is especially useful to understand a top down view of the structure and content of the entire website and is more forgiving/easier to understand in terms of making changes to pages and layout. As such it may make sense to focus on tailoring existing templates for easy editing in github and creating new templates.

**Comment by wslack** [comment]
I am 90% sure about removing the editor, but want to check with Amira before confirming.

**Comment by wslack** [comment]
- Standardize naming conventions
- Better guides and resources for initial site build

**Comment by wslack** [comment]
We will be depreciating the editor
