### ISSUE TITLE
Evaluate and Document Migration Strategy for Webhooks

### ISSUE THREAD

**Issue by wslack** [18F/federalist#686]

**Comment by jmhooper** [comment]
May be worth considering finding a fix for #700 while putting together this strategy since a sticking point for that issue is deleting / creating webhooks which will need to be handled here.

**Comment by wslack** [comment]
1. Add webhook to federalist-gc
2. Site builds on federalist-gc
3. Direct CloudFront to federalist-gc
4. Give federalist-gc the DNS for federalist.18f.gov
5. Remove DNS for federalist-gc
6. Confirm all sites still build
7. Remove old webhooks

**Comment by wslack** [comment]
To be discussed with @brandocalrissian.

**Comment by wslack** [comment]
Documented here: https://docs.google.com/document/d/1HPEXy90_WRILo4RC13X27dzAyTPVEVmHC1v87fjKsxs/edit
