### ISSUE TITLE
Evaluate Migration Strategy for Site Data

### ISSUE THREAD

**Issue by wslack** [18F/federalist#687]
Document here when complete: https://docs.google.com/document/d/1HPEXy90_WRILo4RC13X27dzAyTPVEVmHC1v87fjKsxs/edit

**Comment by wslack** [comment]
Options here include:

1. Don't migrate past build data
2. Migrate if customers ask
3. Migrate all data

I don't think past build data is very helpful unless there are atypical circumstances, so I would suggest that we maintain old Federalist at a different URL if people need the data for a month or so, then retire it.

**Comment by jmhooper** [comment]
Worth noting that migrating data for only sites whose customers ask to keep their data may be more difficult then migrating it for all sites.

**Comment by wslack** [comment]
We expect not to migrate right now, but aren't 100% sure.

**Comment by wslack** [comment]
We aren't migrating build data.

**Comment by wslack** [comment]
closing as this was done
