### ISSUE TITLE
Quick Task: Open Issues as needed from the mid-project review

### ISSUE THREAD

**Issue by wslack** [18F/federalist#688]

**Comment by jmhooper** [comment]
Issues coming out of the mid-project review:

- Consider alternatives to Sails (https://github.com/18F/federalist/issues/690)
- Consolidate logic that communicates with GitHub (https://github.com/18F/federalist/issues/691)
- Audit and cleanup API routes (https://github.com/18F/federalist/issues/648)
- Research work to disable editor interface (https://github.com/18F/federalist/issues/683)
- Manage environment for build scripts (https://github.com/18F/federalist-docker-build/issues/22)
