### ISSUE TITLE
Consider alternatives to Sails

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#690]
We've had some problems with Sails and are considering migrating to another framework. This could potentially be a high effort issue depending on our decision. A few of the choices to be made:

1. Do we stay with node.js or move do a different platform (e.g. Rails)
1. If we stay on node, what web application framework do we use? Express or something based on it may make the most sense since Sails is built on top of Express
1. If we stay on node, what do we use to replace Waterline, Sails's ORM

A few suggestions for web application frameworks that were recommended when we asked around:

- [Express](http://expressjs.com/)
- [Kraken](http://krakenjs.com/)
- [Hapi](https://hapijs.com/)

A few suggestion for ORMs:

- [Bookshelf](http://bookshelfjs.org/)
- [Sequelize](http://docs.sequelizejs.com/en/v3/)

**Comment by wslack** [comment]
Blocked pending https://github.com/18F/federalist/issues/683

**Comment by wslack** [comment]
Work is now in #763 and this issue can be closed!
