### ISSUE TITLE
Consolidate logic that interacts w/ GitHub

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#691]
Currently, the code that handles interaction with GitHub is spread across both the frontend and the backend. In some places this makes sense, for example content management on the frontend. In other places it does not make sense, for example repo creation on the frontend when adding a site, then webhook creation on the backend.

We should examine the ways that our app communicates with GitHub and move communication involving site creation and administration into the backend and content management onto the frontend.

**Comment by wslack** [comment]
Closing as complete!
