### ISSUE TITLE
Determine reasonable amount of time to timeout builds

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#693]
Currently builds timeout in 5 minutes: https://github.com/18F/federalist-builder/blob/cbe1e574811dc9af7861a540ac25748044dcd9ee/src/cluster.js#L103

Some sites, such as 18f.gsa.gov, take longer to build, so we may want to consider moving to a 20 minute timeout to accommodate them.

**Comment by wslack** [comment]
@gboone or @elainekamlley, thoughts? Y'all have our largest site and it looks like your builds sometimes go past 20.

**Comment by wslack** [comment]
Done, with caveat issue filed!
