### ISSUE TITLE
Redirect to sites list after adding a site is broken

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#694]
After adding a site at `/site/new`, the frontend crashes. This means all links stop working and the redirect to `/sites` never happens.

This is tough to track down, but the root of the issue is that [the add-site action does not render the site with a build array](https://github.com/18F/federalist/blob/aad81328f4fafa3c842dd82b7666b07c1643af8e/api/controllers/UserController.js#L69) which the [site list item component expects it to do](https://github.com/18F/federalist/blob/aad81328f4fafa3c842dd82b7666b07c1643af8e/assets/app/components/siteList/siteListItem.js#L34).

Not that PR #667 refactors the site creation code to make the site response bodies have a consistent schema which fixes this issue.

**Comment by jmhooper** [comment]
This is blocked until #667 exits review

**Comment by brandocalrissian** [comment]
#667 has exited review, FWIW.

**Comment by jmhooper** [comment]
Sweet, thanks @brandocalrissian. I'll move this to done.
