### ISSUE TITLE
Use a unique webhook secret for each site

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#700]
Each website should have a unique webhook secret instead of a shared webhook secret.

This may be difficult to implement for the existing sites. A unique webhook secret will need to be assigned to each site. The existing webhook will then need to be deleted and replaced with a new webhook using the sites new webhook secret.

If this is done before the GovCloud migration, it can be integrated into the webhook migration strategy as part of #686.

**Comment by wslack** [comment]
@jmhooper what's the benefit of a unique secret? I get that its a point of risk, but as long as we don't disclose the secret and have admin access to partner repos, we can always make a change

**Comment by wslack** [comment]
1. Add webhook to federalist-gc
2. Site builds on federalist-gc
3. Direct CloudFront to federalist-gc
4. Give federalist-gc the DNS for federalist.18f.gov
5. Remove DNS for federalist-gc
6. Confirm all sites still build
7. Remove old webhooks

**Comment by wslack** [comment]
For right now, we won't have a unique secret.

**Comment by wslack** [comment]
@afeld right now, we're not going to pursue a unique secret, for a few reasons:

1. There are multiple versions of Federalist (staging, prod) but during the GovCloud migration one secret may point at two systems. Varying secrets will break this.
2. The worst thing someone can do with the secret is repeatedly kick off builds.
3. The secret is not exposed to anyone outside of the Federalist core team.
4. We're creating a script to delete/recreate the webhooks in the future automatically.

Happy to get pushback.

**Comment by wslack** [comment]
Closing - we didn't need this for ATO.
