### ISSUE TITLE
Replace Waterline with Sequelize

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#725]
As part of our move aways from Sails, we're going to need to replace Sails's baked in ORM, [Waterline](https://github.com/balderdashy/waterline), with something else.

After looking at a number of options, the one I like best is [Sequelize](http://docs.sequelizejs.com/en/v3/), because it offers the features we depend on from Waterline ([associations](http://docs.sequelizejs.com/en/v3/docs/associations/), [validations](http://docs.sequelizejs.com/en/v3/docs/models-definition/#validations), [hooks](http://docs.sequelizejs.com/en/v3/docs/hooks/)) and has some other ones that we could benefit from ([transactions](http://docs.sequelizejs.com/en/v3/api/transaction/), [scopes](http://docs.sequelizejs.com/en/v3/docs/scopes/)).

**Comment by wslack** [comment]
Done in https://github.com/18F/federalist/pull/732 and others (731, 729, 728).
