### ISSUE TITLE
Prose.io bugs that are potential landmines

### ISSUE THREAD

**Issue by jeremiak** [18F/federalist#73]
So far I've run into two bugs while testing out the prose.io/Federalist integration that definitely gave me pause and will likely be problematic for our users. Off the top of my head, here they are:

0. If you are unauthenticated with prose.io it doesn't give you much of an indication. However, if you go to make a commit prose will just bail on you.
0. If you are authenticated but put in a commit message when you try and save you will fail a reasonable percentage of the time (was 100% for me) and the app will fail mostly silently

**Comment by dhcole** [comment]
Referencing #17 for a discussion of bugs and alternatives

**Comment by jeremiak** [comment]
Closing this out, we decided to mostly go our own way on this project.
