### ISSUE TITLE
Node modules alert and updates for climate and OES

### ISSUE THREAD

**Issue by wslack** [18F/federalist#735]
- [x] Add to documentation
- [x] Add to migration

**Comment by wslack** [comment]
@jmhooper any idea why we added this during last retro?

**Comment by jmhooper** [comment]
Yes. Now that we run `npm install` during the build process, sites may generate a `node_modules` directory where they did not before. If they don't exclude the node modules during the site's build, the node modules will be built into the site and will then take a while to upload. This is a problem we saw with the landing page template: https://github.com/18F/federalist-landing-page-template/pull/2

**Comment by jmhooper** [comment]
Now that everyone is migrated, I'll sift through the bucket and looks for customers who have uploaded node modules along with their site. We can then tell them to adds those to their excluded files list in `_config.yml` and also add a not about that to the docs.

**Comment by jmhooper** [comment]
I've opened PRs or issue on every repo that has a Federalist site with published node modules

**Comment by wslack** [comment]
Both sites are merged now!

**Comment by wslack** [comment]
Last task: documentation.

**Comment by wslack** [comment]
Docs done in https://github.com/18F/federalist-docs/pull/114

**Comment by jmhooper** [comment]
Documentation added in https://github.com/18F/federalist-docs/pull/114

**Comment by wslack** [comment]
😆  I win!
