### ISSUE TITLE
GitHub admin error displays as "Internal Server Error"

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#743]
The error that is raised when a user does not have admin privileges is communicated to the frontend as a 500 with the message "Internal server error". That should be a 400 with a helpful error message.

It looks like this is happening because the error is being thrown in a Waterline lifecycle callback, which is wrapping the error in a Waterline error, preventing its status from being read in `res.error`.

In addition, the tests did not detect this bug and they should have, so that will need to be investigated.

**Comment by jmhooper** [comment]
This should be fixed in #733

**Comment by wslack** [comment]
This is done!
