### ISSUE TITLE
Add support for HSTS preloads for SLDs

### ISSUE THREAD

**Issue by wslack** [18F/federalist#748]
cc @konklone 

This requests a feature offered as a service for customers who host a parent domain (e.g. sbst.gov) with Federalist, that wish to preload or otherwise expand HSTS coverage to all subdomains.

To be clear, the default HSTS policy for Federalist is:

```
Strict-Transport-Security: max-age=31536000
```

And an example of a custom HSTS policy would be:

```
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
```

Only the parent domain root URL (e.g. `https://sbst.gov`) can effectively communicate this policy to browsers, so if someone hosts their parent domain with Federalist, they are fully dependent on Federalist for the ability to do this. This is why cloud.gov and sites.usa.gov both offer the ability to do this.

This is a feature request, not a security/compliance/ATO discussion, as Federalist's current HSTS posture is already meeting the security/compliance needs of Federalist's hosted services.

**Comment by wslack** [comment]
ref https://github.com/presidential-innovation-fellows/code-gov-web/issues/1

**Comment by wslack** [comment]
@konklone My concern is an unexpected impact on any sites whose subdomains don’t have https yet.

Quoting Jonathan:

If example.gov is on Federalist, and you have another site at app.example.gov. This change forces app.example.gov to have https, and I'm not sure that blocker will be obvious to whoever is running the app. Thoughts?

**Comment by konklone** [comment]
Yeah, you would need to make this opt-in per-customer, and customers should be (made) aware of what they're doing.

Sites.usa.gov took this approach -- they surveyed their users who hosted second-level domains (e.g. fedramp.gov) on the platform, and asked them if they would like to be opted-in to a preload policy. I worked with them to write the survey email and to answer questions. In the end, we got permission to preload all of the second-level domains except for digitalgov.gov (and now its replacement, digital.gov, will be preloaded).

**Comment by wslack** [comment]
@konklone my concern is mostly that this adds more complexity to the proxy in a way that feels like scope creep; I don't like adding specific headers per a whitelist that needs to be maintained. 

If we should move forward with this, it sounds like we should initiate first with GSA IT to ensure it's not a material change affecting the ATO.

**Comment by wslack** [comment]
I also don't like changing the support needs for certain types of URLs. Federalist's model is constructed so that the costs of a new site live are ~0; this white listing moves us to having a defined cost per site.

**Comment by konklone** [comment]
Yep, I completely agree with your assessment, and understand why it would be unappealing in terms of complexity or per-customer variation. However, it's what it would take in order to support this feature -- and for those with their second-level domains on Federalist, Federalist is the only entity capable of adding the header to cover their subdomains. So they'd be stuck without feature support, or would need to add their own proxy or something on their end.

**Comment by brownpl** [comment]
Do you all plan to add the "preload" parameter to the HSTS headers being sent by Federalist or is there a way we can add this for the College Scorecard?

**Comment by konklone** [comment]
@brownpl College Scorecard is at a subdomain, at https://collegescorecard.ed.gov. The `preload` directive won't do anything for you -- browsers generally won't preload subdomains, and they look for `preload` directives at the second-level (at e.g. `https://ed.gov`) covering all subdomains.
