### ISSUE TITLE
Draft comms to customer about using FedRAMP cloud.gov

### ISSUE THREAD

**Issue by wslack** [18F/federalist#760]
https://docs.google.com/document/d/10k6EjFCs48AyQUZ1acCFPoDqYB3uuyDAifxAOhDXPBM/edit

**Comment by wslack** [comment]
Still needs writing lab or other review

**Comment by wslack** [comment]
@fureigh is checking!

**Comment by fureigh** [comment]
Took a swing through it. Ready for another look (tomorrow), @wslack!
