### ISSUE TITLE
Remove Editor from documentation

### ISSUE THREAD

**Issue by wslack** [18F/federalist#770]

**Comment by saracope** [comment]
Did notice a mention of the editor on https://federalist-docs.18f.gov/

<img width="632" alt="screen shot 2017-03-08 at 7 59 23 am" src="https://cloud.githubusercontent.com/assets/2197515/23704979/6b4c9028-03d5-11e7-92de-9422559cf37c.png">

**Comment by wslack** [comment]
@saracope yep; I need to do a through search and refactor some of the docs. Been focused on migrations. Thank you for flagging!

**Comment by wslack** [comment]
This can be moved to "Done?"

**Comment by wslack** [comment]
Thanks @jmhooper!
