### ISSUE TITLE
Update build message to failing if publish doesn't complete

### ISSUE THREAD

**Issue by saracope** [18F/federalist#784]
I would like the build message to say failing or incomplete or whatnots if the build/publish doesn't complete. I had a build that was failing, but the build message still said completed successfully which didn't make sense to me.

Build errors:
<img width="1093" alt="screen shot 2017-03-02 at 1 33 16 pm" src="https://cloud.githubusercontent.com/assets/2197515/23521739/2f88bd5e-ff4e-11e6-8b3e-cb3637cc90f8.png">

Build message still said completed successfully:
<img width="860" alt="screen shot 2017-03-02 at 1 34 40 pm" src="https://cloud.githubusercontent.com/assets/2197515/23521720/1cccc08e-ff4e-11e6-895c-61b57840603c.png">

**Comment by wslack** [comment]
This should be fixed early next week.
