### ISSUE TITLE
Change branch views

### ISSUE THREAD

**Issue by saracope** [18F/federalist#785]
Would like to:

- View the branches from their own menu. Currently can only see these from the settings.
- Add a link to the builds page to view the branch from that listing.
- When viewing a branch, open it in a new window.

**Comment by wslack** [comment]
> View the branches from their own menu. Currently can only see these from the settings.

Would you care if they were only in their own pages (and not in settings?). 

> Add a link to the builds page to view the branch from that listing.

I worry a little about clutter with the "restart" and "logs" buttons already. Would you want the link after the name of the branch/build?

> When viewing a branch, open it in a new window.

I don't know the exact syntax, but would "automatically open this link in a few tab" be good?

**Comment by saracope** [comment]
I don't think I would miss them if they weren't in Settings.
What about hyperlinking the branch name instead of adding a new separate link?
Yes, opening in a new tab would be good.
Thx!

**Comment by wslack** [comment]
queued this up! Thank you.

**Comment by jmhooper** [comment]
This could likely be tied into #796

**Comment by wslack** [comment]
this is done, in a new "published" tab that will be going to prod early next week!
