### ISSUE TITLE
'npm install' seems to be run during builds for static sites

### ISSUE THREAD

**Issue by toolness** [18F/federalist#805]
Hi! I am not sure if this is actually a bug but I'm filing it here just in case.

Basically, I have a static site in a github repo at [18F/atul-docker-presentation](https://github.com/18F/atul-docker-presentation).

There happens to be a `package.json` in the root directory, but it's meant for local development only--it just sets up a local web server and some other stuff.

I told federalist that this is just a static site (i.e. not a jekyll site) but according to the logs, it seems to be trying to run `npm install` in the root directory, and eventually it seems to call `npm run federalist`, which isn't a script in the project.

It seems like the site is [publicly visible](http://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.s3-website-us-gov-west-1.amazonaws.com/site/18f/atul-docker-presentation/#/), so this isn't a critical bug or anything, but I figured I'd report it just in case.

<details>
  <summary>Full build log from <a href="https://federalist.fr.cloud.gov/sites/86/builds/1246/logs">sites/86/builds/1246/logs</a></summary>
<pre>
npm WARN package.json 18f-html-slides@0.0.1 No repository field.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm

> spawn-sync@1.0.15 postinstall /src/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

> node-sass@3.3.3 install /src/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /src/node_modules/node-sass/vendor/linux-x64-46/binding.node

> node-sass@3.13.1 install /src/node_modules/grunt-sass/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-46_binding.node
Download complete
Binary saved to /src/node_modules/grunt-sass/node_modules/node-sass/vendor/linux-x64-46/binding.node
Caching binary to /root/.npm/node-sass/3.13.1/linux-x64-46_binding.node

> node-sass@3.3.3 postinstall /src/node_modules/node-sass
> node scripts/build.js

` /src/node_modules/node-sass/vendor/linux-x64-46/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.

> node-sass@3.13.1 postinstall /src/node_modules/grunt-sass/node_modules/node-sass
> node scripts/build.js

Binary found at /src/node_modules/grunt-sass/node_modules/node-sass/vendor/linux-x64-46/binding.node
Testing binary
Binary is fine
grunt-contrib-watch@0.6.1 node_modules/grunt-contrib-watch
├── async@0.2.10
├── lodash@2.4.2
├── tiny-lr-fork@0.0.5 (debug@0.7.4, qs@0.5.6, faye-websocket@0.4.4, noptify@0.0.3)
└── gaze@0.5.2 (globule@0.1.0)

grunt-cli@0.1.13 node_modules/grunt-cli
├── nopt@1.0.10 (abbrev@1.1.0)
├── resolve@0.3.1
└── findup-sync@0.1.3 (lodash@2.4.2, glob@3.2.11)

grunt@0.4.5 node_modules/grunt
├── eventemitter2@0.4.14
├── dateformat@1.0.2-1.2.3
├── which@1.0.9
├── getobject@0.1.0
├── async@0.1.22
├── colors@0.6.2
├── lodash@0.9.2
├── rimraf@2.2.8
├── hooker@0.2.3
├── grunt-legacy-util@0.2.0
├── exit@0.1.2
├── nopt@1.0.10 (abbrev@1.1.0)
├── coffee-script@1.3.3
├── iconv-lite@0.2.11
├── underscore.string@2.2.1
├── minimatch@0.2.14 (sigmund@1.0.1, lru-cache@2.7.3)
├── glob@3.1.21 (inherits@1.0.2, graceful-fs@1.2.3)
├── grunt-legacy-log@0.1.3 (grunt-legacy-log-utils@0.1.1, lodash@2.4.2, underscore.string@2.3.3)
├── findup-sync@0.1.3 (lodash@2.4.2, glob@3.2.11)
└── js-yaml@2.0.5 (esprima@1.0.4, argparse@0.1.16)

grunt-contrib-connect@0.11.2 node_modules/grunt-contrib-connect
├── connect-livereload@0.5.4
├── opn@1.0.2
├── async@0.9.2
├── portscanner@1.2.0 (async@1.5.2)
├── morgan@1.8.1 (on-headers@1.0.1, basic-auth@1.1.0, depd@1.1.0, on-finished@2.3.0, debug@2.6.1)
├── connect@3.6.0 (utils-merge@1.0.0, parseurl@1.3.1, debug@2.6.1, finalhandler@1.0.0)
├── serve-static@1.12.1 (escape-html@1.0.3, encodeurl@1.0.1, parseurl@1.3.1, send@0.15.1)
└── serve-index@1.8.0 (escape-html@1.0.3, parseurl@1.3.1, batch@0.5.3, http-errors@1.5.1, mime-types@2.1.14, accepts@1.3.3, debug@2.2.0)

grunt-contrib-cssmin@0.14.0 node_modules/grunt-contrib-cssmin
├── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.1)
├── clean-css@3.4.25 (commander@2.8.1, source-map@0.4.4)
└── maxmin@1.1.0 (figures@1.7.0, gzip-size@1.0.0, pretty-bytes@1.0.4)

grunt-autoprefixer@3.0.4 node_modules/grunt-autoprefixer
├── diff@1.3.2
├── chalk@1.0.0 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── postcss@4.1.16 (js-base64@2.1.9, es6-promise@2.3.0, source-map@0.4.4)
└── autoprefixer-core@5.2.1 (num2fraction@1.2.2, browserslist@0.4.0, caniuse-db@1.0.30000632)

node-sass@3.3.3 node_modules/node-sass
├── get-stdin@4.0.1
├── async-foreach@0.1.3
├── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2.0.0, strip-ansi@3.0.1, has-ansi@2.0.0)
├── nan@2.5.1
├── mkdirp@0.5.1 (minimist@0.0.8)
├── glob@5.0.15 (inherits@2.0.3, path-is-absolute@1.0.1, once@1.4.0, inflight@1.0.6, minimatch@3.0.3)
├── npmconf@2.1.2 (inherits@2.0.3, ini@1.3.4, uid-number@0.0.5, once@1.3.3, semver@4.3.6, nopt@3.0.6, osenv@0.1.4, config-chain@1.1.11)
├── gaze@0.5.2 (globule@0.1.0)
├── meow@3.7.0 (trim-newlines@1.0.0, decamelize@1.2.0, map-obj@1.0.1, object-assign@4.1.1, camelcase-keys@2.1.0, minimist@1.2.0, loud-rejection@1.6.0, redent@1.0.0, normalize-package-data@2.3.6, read-pkg-up@1.0.1)
├── cross-spawn@2.2.3 (cross-spawn-async@2.2.5, spawn-sync@1.0.15)
├── node-gyp@3.5.0 (graceful-fs@4.1.11, semver@5.3.0, rimraf@2.6.1, osenv@0.1.4, nopt@3.0.6, which@1.2.12, glob@7.1.1, minimatch@3.0.3, fstream@1.0.11, tar@2.2.1, npmlog@4.0.2)
├── request@2.80.0 (tunnel-agent@0.4.3, aws-sign2@0.6.0, oauth-sign@0.8.2, forever-agent@0.6.1, is-typedarray@1.0.0, caseless@0.12.0, stringstream@0.0.5, aws4@1.6.0, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, performance-now@0.2.0, uuid@3.0.1, qs@6.3.2, mime-types@2.1.14, combined-stream@1.0.5, tough-cookie@2.3.2, form-data@2.1.2, hawk@3.1.3, http-signature@1.1.1, har-validator@4.2.1)
└── sass-graph@2.1.2 (glob@7.1.1, yargs@4.8.1, lodash@4.17.4)

grunt-sass@1.1.0 node_modules/grunt-sass
├── object-assign@4.1.1
├── each-async@1.1.1 (set-immediate-shim@1.0.1, onetime@1.1.0)
└── node-sass@3.13.1 (get-stdin@4.0.1, lodash.assign@4.2.0, lodash.clonedeep@4.5.0, async-foreach@0.1.3, in-publish@2.0.0, chalk@1.1.3, nan@2.5.1, mkdirp@0.5.1, cross-spawn@3.0.1, glob@7.1.1, npmlog@4.0.2, meow@3.7.0, node-gyp@3.5.0, request@2.80.0, sass-graph@2.1.2, gaze@1.1.2)
npm ERR! Linux 4.4.0-64-generic
npm ERR! argv "/usr/local/nvm/versions/node/v4.6.1/bin/node" "/usr/local/nvm/versions/node/v4.6.1/bin/npm" "run" "federalist"
npm ERR! node v4.6.1
npm ERR! npm v2.15.9

npm ERR! missing script: federalist
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR! <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR! /src/npm-debug.log
</pre>
</details>

**Comment by jmhooper** [comment]
That's coming from this line in the build container: https://github.com/18F/federalist-docker-build/blob/f0235b9f6dfee82f68dbc2e56684753e4bdd65d7/build.sh#L33

That allows sites to add an npm script to run before their site is built. We need to get around to modifying it so that it does not run that if the script does not exist.

**Comment by toolness** [comment]
Ooo that's good to know that I can put a `federalist` script in my `package.json` to do any custom static asset generation though!!!  Is this documented anywhere?  Or is it a feature that might go away anytime soon?

**Comment by jmhooper** [comment]
It is documented here: https://federalist-docs.18f.gov/pages/how-federalist-works/node-on-federalist/

**Comment by wslack** [comment]
@toolness is this resolved?

**Comment by toolness** [comment]
Hmm, I think this is the bug, ultimately, mentioned in [jonathan's comment above](https://github.com/18F/federalist/issues/805#issuecomment-285125751):

> We need to get around to modifying [`build.sh`] so that it does not run that if the [`npm run federalist` script] does not exist.

So unless that issue is recorded somewhere already, I think this issue should probably remain open. (It's not really anything particularly urgent, though, since it just logs a somewhat confusing error but still deploys the site.)

**Comment by jmhooper** [comment]
The issue to track that is right here: https://github.com/18F/federalist-docker-build/issues/33

**Comment by wslack** [comment]
https://github.com/18F/federalist-docker-build/issues/33 was fixed so this issue is fixed
