### ISSUE TITLE
Stop using gov-templates

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#819]
The microsite template produces the following error at build time in the Federalist container:

```
[31m Liquid Exception: Failed to get header. in /src/_posts/2013-11-20-welcome-to-jekyll.markdown[0m
```

We should investigate whether this problem occurs with the developer template. From their we should determine how difficult it would be to fix and whether or not we should fix or remove those broken templates.

**Comment by wslack** [comment]
Changing issue

**Comment by wslack** [comment]
cc @shawnbot that we'll be getting rid of these thanks to the USWDS template!
