### ISSUE TITLE
" in a commit message breaks builds in Federalist

### ISSUE THREAD

**Issue by wslack** [18F/federalist#823]
I was doing a Federalist demo and had a message "in quotes" and my build didn't work (not because the hashes didn't match). We should mitigate this issue.

**Comment by jmhooper** [comment]
Looks like S/O is saying there's [not an easy way to do this](http://stackoverflow.com/questions/9301673/can-i-escape-chars-in-git-log-output). I'm wondering if we have any sites that depend on the git log info being in the config? If not, any chance we could fix this by removing it?

**Comment by wslack** [comment]
I don't follow the remedy - would this be fixed by getting rid of something in config for each site?

**Comment by jmhooper** [comment]
What the code that is breaking is doing is adding the commit shah, author, date, and message to the config. This is an issue when the message doesn't parse into valid yaml:

```yaml
message: This is a message "with quotes"
```

I don't think anyone is using this info in their sites. Fixing it would be pretty involved, so I'm wondering if removing it is an option.

**Comment by wslack** [comment]
oh yeah, no one is using that. We con't incorporate the message in builds; this can be removed.
