### ISSUE TITLE
View links provided for sites by the API are relative to S3 URL instead of federalist.fr.cloud.gov

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#825]
The view links use the S3 root as the host for site view links instead of the Federalist host name. This works for the default branch, but preview URLs should be proxied through Federalist.

The fix for this likely involves adding the desired hostname to the config and making preview URLs relative to that.

**Comment by wslack** [comment]
would that hostname be config'd per site or for each Federalist instance?

**Comment by jmhooper** [comment]
Staging would be `federalist-staging.fr.cloud.gov`. Production would be `federalist.fr.cloud.gov` until E/W is retired at which point we can change to `federalist.18f.gov`.

**Comment by wslack** [comment]
and this would be config'd as environment variables? (is URL not currently an env variable?)

**Comment by jmhooper** [comment]
We have options for that. It can be an env variable, or it can be hardcoded into the config for the given environment.

**Comment by jmhooper** [comment]
Also, to answer the second question, the URL is available in the cloud foundry environment, but it is available as an array of URLs (since apps can have multiple).

An option if we didn't want it in the env would be to pull it from the request object. That just means handing the request object or the hostname off to the model when generating the preview URL.

**Comment by wslack** [comment]
This is done! (for staging only)
