### ISSUE TITLE
Allow users to remove sites from their personal Federalist site list

### ISSUE THREAD

**Issue by wslack** [18F/federalist#829]
We should add a button to remove a site from someone's personal Federalist view without removing the site from Federalist for everyone. This will allow people to keep their Federalist site list clean

**Comment by jmhooper** [comment]
I'm thinking through what this would look like. Right now my thinking is that it would be nice to have a list of users who have added the site and have the "Leave Site" button near that. Also important, if we do that, it is a long ways from the "Permanently Delete This Site" button.

**Comment by wslack** [comment]
Oh I like that. I would do the "leave site" button, show the list of other users, then have "permanently delete for all users" at the bottom of that long list.

**Comment by wslack** [comment]
This is a small lift.

**Comment by wslack** [comment]
This is done via the self-removal PR merged a few sprints ago.
