### ISSUE TITLE
Single page editor based on Sir Trevor

### ISSUE THREAD

**Issue by jeremiak** [18F/federalist#83]
For this next milestone we'll want a single page editor that we can start to use in place of Prose. This ticket is completed when:

* We have a single page editor that is passed a Github URL to pull the original content from
* Use Sir Trevor to enable authors to edit the page content
* Spit out the new markdown to somewhere (could be a console log or w/e for now) so that we can verify the new markdown respects front matter and content updates.

**Comment by dhcole** [comment]
Done in #90
