### ISSUE TITLE
Add loading states

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#832]
Currently our app has no loading states. When you go to a page, you'll often see a message saying something like "No Sites added", which will then disappear and be replaced with a list of sites. We should add a message that says something like "Loading sites" that is then replaced with a "No Sited added" or a list of sites depending on whether the user has added any sites.

**Comment by jmhooper** [comment]
The following parts of the UI should display a loading state while we wait for data:

- [x] Home page while we determine if the user is logged in
- [ ] Site list while site data is loading
- [ ] GH branch list while GH branch data is loading
- [ ] Build tables while build data is loading
- [ ] Published branch table while published branches are loading
- [ ] Published branch files table while files are loading

**Comment by wslack** [comment]
So many changes made, yay!
