### ISSUE TITLE
Reorganize Federalist Menus with card sort results

### ISSUE THREAD

**Issue by wslack** [18F/federalist#834]

**Comment by wslack** [comment]
@wslack to record outcomes from Murally.

**Comment by wslack** [comment]
![screen shot 2017-07-31 at 12 16 16 pm](https://user-images.githubusercontent.com/10016577/28787409-1540f390-75ea-11e7-979c-86df2e5e7738.png)

**Comment by wslack** [comment]
Order:

Build History
GitHub Branches
Data on S3
Users
Settings

**Comment by jseppi** [comment]
Done as part of #1216
