### ISSUE TITLE
Update federalist-builder, federalist.fr.cloud.gov, and federalist builder to all run on multiple instances

### ISSUE THREAD

**Issue by wslack** [18F/federalist#882]

**Comment by jmhooper** [comment]
All of them do now, except the builder.

Since the builder instances would need a shared queue, we'll need a new FIFO SQS queue with a visibility timeout to make sure 2 instances aren't working on the same build.

**Comment by jseppi** [comment]
Having multiple federalist-builder instances will also prevent downtime caused by cloud.gov rolling upgrades, app instance restarts, etc. Multiple app instances are a critical part of being production-ready: https://cloud.gov/docs/apps/production-ready/#more-than-one-instance
