### ISSUE TITLE
Investigate switching to SQS queue in GovCloud

### ISSUE THREAD

**Issue by wslack** [18F/federalist#885]
After this is resolved, we can look at https://github.com/18F/federalist/issues/882

- [ ] File e-mail to cloud-gov-support
- [ ] List steps and functionality loss

**Comment by wslack** [comment]
we want a FIFO queue with a visibility timeout so we can provision multiple instances of the builder

**Comment by jmhooper** [comment]
I emailed cloud.gov support on May 9th. I sent a follow up today. Moving this to block until we hear back.

**Comment by jmhooper** [comment]
I heard back from cloud.gov. Their advice was to create and manage our own AWS account in the GovCloud region, which complicates things with the ATO. We'd have to use the AWS CX matrix for the queue instead of the cloud.gov CX matrix.

**Comment by wslack** [comment]
I'm checking in with cloud.gov about this.

**Comment by wslack** [comment]
For right now, let's hold put on the status quo.

**Comment by wslack** [comment]
What about using this https://redis.io/topics/pubsub ? It's already broker'd by cloud.gov.

**Comment by jmhooper** [comment]
RE: Redis PubSub

There's a few disadvantages over SQS:

SQS persists messages until they are received and deleted. This means that if the builder is offline, the message wait in the queue until it is back up to receive them. Redis PubSub does not do that. If the builder is offline, messages sent to it are lost.

Also, SQS holds on to messages until we delete them. We take advantage of this by leaving messages on the queue until we've started a build. This means that if there are no containers available, we can leave a message on the queue until there is a container available. With Redis PubSub, we'd need to build out a persistence solution to save builds until there is a container on which to start them.

**Comment by mogul** [comment]
Another potential option that keeps you in cloud.gov's FedRAMP boundary and is already brokered in cloud.gov: https://blog.andyet.com/2015/04/06/postgres-pubsub-with-json/

**Comment by mogul** [comment]
(Note in particular the bit about persistence near the end.)

**Comment by wslack** [comment]
Hmmm so we can achieve some feature parity with custom config, but its not clean.

**Comment by mogul** [comment]
Well, @jmhooper said:

> Also, SQS holds on to messages until we delete them. We take advantage of this by leaving messages on the queue until we've started a build. This means that if there are no containers available, we can leave a message on the queue until there is a container available. With Redis PubSub, we'd need to build out a persistence solution to save builds until there is a container on which to start them.

I think that blog post is basically showing a really straightforward way to build out that persistence solution and only rely on Postgresql for delivering messages. cloud.gov brokers Postgres via AWS RDS, so this path would likely be pretty damned solid by comparison with our Redis, and definitely fully within our FedRAMP boundary.

**Comment by wslack** [comment]
We met with GSA IT and they are fine with a separate SQS queue that we manage. Do you know how we could "get" that - would Holly or Erik be the folks to ask? cc @jseppi

**Comment by wslack** [comment]
Can either use our own AWS account or use something else for queue.

This is blocked until we get separate AWS console access.

**Comment by wslack** [comment]
Moving to Icebox; current set up is approved for ATO.

**Comment by wslack** [comment]
i'm fine with the current set up.
