### ISSUE TITLE
Update docs site with Rubygem version discussion

### ISSUE THREAD

**Issue by wslack** [18F/federalist#889]
Per https://github.com/18F/climate-labs/pull/52#discussion_r114223093, we should discuss if Federalist sites should have pinned version of Rubygems. 

Reasons not to set:

- Sites don't go down because of failed builds, so it's ok to have a broken build.

Reasons to set:
- Sites will not break unexpectedly

**Comment by jmhooper** [comment]
I worry less about builds that outright break than I do about builds that break quietly. It is conceivable that a misconfigured ruby version could cause Jekyll or a plugin to misbehave in a way that produces a site that is built, but malformed.

With the addition of rvm to the build container, it is possible for sites to specify their own ruby version. If they do so, the ruby version will not shift underneath them, and their sites will not break if they specify a ruby version in their Gemfile and we change the platform ruby.

**Comment by wslack** [comment]
Should we ad guideance to set a version in the Gemfile for all former Pages sites? (or do they not use Ruby like this?)

I think I'm confusing this issue with the best practice for search, which may be about the background guides_style.

**Comment by wslack** [comment]
@jmhooper to record detailed options

**Comment by wslack** [comment]
@el-mapache one possible thing to take

**Comment by el-mapache** [comment]
@wslack I believe this is already possible. Looking in federalist-garden-build I see [this code ](https://github.com/18F/federalist-garden-build/blob/91c0591bd00d85297b7a4461caba862a4fea804e/tasks/build.py#L141) which seems to indicate that if a project specifies a version inside a file called `.ruby-version`, that is the version that will be used to install gems and build the site.

Based on the conversation, I'm not sure what the ask is for this issue. Are we just looking to document the fact that users can specify a ruby version in their jekyll sites?

**Comment by wslack** [comment]
I think we're trying to figure out if the templates should set a specific version - like, what is the best practice that we suggest for the partner sites.

**Comment by wslack** [comment]
ah kk. Does this need to be a PR to federalist-docs or a change to https://github.com/18F/federalist-uswds-template/ ?

**Comment by el-mapache** [comment]
I think we just need a PR into the docs, any jekyll site can use this functionality. I don't think it needs to be in the templates themselves since those should work fine with the version of Ruby the build container uses.

**Comment by wslack** [comment]
Updated title; didn't move to "Ready" for now.
