### ISSUE TITLE
Federalist should be aware of repositories that have been deleted from GitHub

### ISSUE THREAD

**Issue by jeremiak** [18F/federalist#89]
When a user deletes a repository from Github the app should change in some way. I can imagine two different actions being taken after we get a webhook POST from Github:
1. Federalist could delete the site from the database
2. We flag the site as missing a repository and ask the user to either supply a new repo URL or remove the site

We could also simply trigger these actions when the user tries to take an action on a repository that Github says no longer exists.

**Comment by wslack** [comment]
Hasn't turned into a noted issue. Closing.
