### ISSUE TITLE
Custom URL for a preview branch

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#894]
Customers have requested the ability to view one of their preview branches at a custom url. For example, the owner of `example.gov` may want to have `preview.example.gov` to view changes before moving them to the default branch.

Changes this will require

- Add ability to configure which branch will be used and what the url will be in the site settings
- Change the config sent to the build to use the right base url for the preview
- Change the proxy to proxy this branch
- Update the docs to describe the feature and how to setup the custom url

Also, the temptation is to call this a "preview url", but since we already have a concept of "preview urls", we'll need to come up with a different name.

**Comment by wslack** [comment]
Other ideas:

- "beta URL"
- "staging URL"
- "secondary live URL"

also cc @zachmargolis that we're planning on adding this as a core feature given the multiple requests.

**Comment by wslack** [comment]
@jeremyzilar we've completed this!

**Comment by jeremyzilar** [comment]
Thank you ! 🎉
