### ISSUE TITLE
Builds in the build logs are sorted in the wrong order

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#898]
The build logs are sorting builds in order from oldest to newest. It should show the newest builds first.

**Comment by wslack** [comment]
Is this in staging? I'm not observing in production.

**Comment by jmhooper** [comment]
Yeah, looks like it is only in staging.

**Comment by jmhooper** [comment]
This looks like the change that triggered it: https://github.com/18F/federalist/commit/a7043231df57080ea8cf00e7af3238758983548c#diff-3f1456d53bd84ee767ee73d4891ccb0bR29

**Comment by wslack** [comment]
Fixed this!
