### ISSUE TITLE
Add a mechanism for Federalist to be able to easily load and display an error or maintenance message

### ISSUE THREAD

**Issue by wslack** [18F/federalist#900]
Would display before the menu bar

**Comment by jmhooper** [comment]
Discussed using a user provided service for this one. That may not work though because we'd want the value present at asset compilation which happens in CI.

**Comment by jseppi** [comment]
Good point, @jmhooper. That might be more reason to implement https://github.com/18F/federalist/issues/958, which would allow us to set server-side context variables and have them displayed in the rendered site template.

**Comment by jmhooper** [comment]
For the time being, I was planning on using EJS to render it above the content based on a UUPS

**Comment by jseppi** [comment]
That sounds like it'll work out -- it'll just give us less control over the placement, but I think the very top of the page probably is where we'd want it anyway.

**Comment by jmhooper** [comment]
Yeah, I'm thinking it should not incur too much debt since it will fit in well with the plan outlined in #958
