### ISSUE TITLE
Evaluate setting caching headers with a max-age on the proxy

### ISSUE THREAD

**Issue by wslack** [18F/federalist#901]
This will limit the issues from typos in the path of a new CDN route

**Comment by jmhooper** [comment]
This could conflict with a number of possible implementations of #179

**Comment by wslack** [comment]
Prevents bad caching, some value.

**Comment by jseppi** [comment]
My understanding of the implementation is just to modify the nginx.conf of https://github.com/18F/federalist-proxy to add `Cache-Control: max-age=0` to all proxied requests that do not already contain the `Cache-Control` header.

**Comment by amirbey** [comment]
this was completed by @davemcorwin  in #2407

**Comment by wslack** [comment]
Woooooooo go @davemcorwin!
