### ISSUE TITLE
Change name of federalist-docker-build

### ISSUE THREAD

**Issue by wslack** [18F/federalist#902]
to `federalist-garden-build`

**Comment by wslack** [comment]
Or maybe https://github.com/18F/federalist-docker-build

**Comment by jseppi** [comment]
What was the name you suggested, @wslack? Something like `federalist-garden-builder`?

**Comment by wslack** [comment]
federalist-garden-build`

**Comment by jseppi** [comment]
- [ ] Rename the `federalist-docker-build` repository to `federalist-garden-build`
- [ ] Re-tag current container image with the new name and push it to the staging registry
- [ ] Merge https://github.com/18F/federalist-builder/pull/29 and wait for it to successfully deploy to staging
- [ ] Initiate a build on federalist-staging and make sure it uses the new image name
- [ ] Repeat steps 2-4 for production instances
- [ ] Merge https://github.com/18F/federalist-docs/pull/96
