### ISSUE TITLE
Make new system diagrams for Federalist

### ISSUE THREAD

**Issue by wslack** [18F/federalist#903]

**Comment by wslack** [comment]
![screen shot 2017-05-09 at 5 36 05 pm](https://cloud.githubusercontent.com/assets/10016577/25873848/0120e020-34de-11e7-8c92-eb5881a447d0.png)

**Comment by jseppi** [comment]
Is there a source file for this? We'll need the updated version for the RoE doc (#1086)

**Comment by wslack** [comment]
Last time around I just put the image in the doc. Need the file still?

**Comment by jseppi** [comment]
Oh is the image here the updated one? I haven't reviewed it thoroughly yet.

**Comment by wslack** [comment]
yep!

**Comment by jseppi** [comment]
Excellent! So we can close this issue as well?

**Comment by wslack** [comment]
[Federalist Diagram - July 27 2017.pdf](https://github.com/18F/federalist/files/1181159/Federalist.Diagram.-.July.27.2017.pdf)

Here's the same thing in PDF format. This is the most current diagram.

**Comment by wslack** [comment]
I leave the image open so that if/when changes are required, we can just make them. I would close when the SSP is accepted.

**Comment by jseppi** [comment]
Update the `federalist` block to `federalist-core`.

This slight name change will allow us to more easily differential the entire "Federalist" system from the node.js web app that we also have been calling "Federalist".

**Comment by wslack** [comment]
Opened https://github.com/18F/federalist/pull/1091 to reflect the change

**Comment by wslack** [comment]
![screen shot 2017-07-31 at 5 38 20 pm](https://user-images.githubusercontent.com/10016577/28799555-144cd8dc-7617-11e7-9f3e-7eeb4dee2798.png)

How is this @jseppi?

**Comment by jseppi** [comment]
Looks good, thanks!

**Comment by wslack** [comment]
Blocked awaiting future updates before next ATO effort.

**Comment by jseppi** [comment]
Per SSP feedback from @afeld:

- Add Protocol and Port to arrows
- Names in diagram components should match the names in the Software Components Table
- Add external systems like New Relic and Digital Analytics Program

**Comment by afeld** [comment]
...and make sure to follow [the instructions in Before You Ship](https://before-you-ship.18f.gov/ato/ssp/#systemnetwork-diagrams) closely.

**Comment by wslack** [comment]
![screen shot 2018-01-11 at 4 32 43 pm](https://user-images.githubusercontent.com/10016577/34848519-12e7a4ac-f6ed-11e7-90ef-5e04970379f0.png)

**Comment by wslack** [comment]
![screen shot 2018-01-11 at 4 33 04 pm](https://user-images.githubusercontent.com/10016577/34848538-219d1234-f6ed-11e7-9b2a-b757b1e5a9e1.png)

**Comment by wslack** [comment]
![screen shot 2018-01-11 at 5 53 36 pm](https://user-images.githubusercontent.com/10016577/34851533-6a8145aa-f6f8-11e7-8f30-ef25911e51c5.png)
