### ISSUE TITLE
Consider adding a limit to the number of builds in the build log

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#905]
We should consider adding a limit to the number of builds displayed in the build log. Currently, it displays all of a site's builds, which can be quite a lengthy list after time. We may want to limit that to something like the most recent 100 builds.

**Comment by wslack** [comment]
Concur.

**Comment by wslack** [comment]
asking users for feedback in slack

**Comment by wslack** [comment]
See https://gsa-tts.slack.com/archives/C0801BNJE/p1494529110052320
