### ISSUE TITLE
Clarify text and links to view previews

### ISSUE THREAD

**Issue by wslack** [18F/federalist#912]
Needs some UX time to make sure we are showing people the right links in the right places.

**Comment by jseppi** [comment]
Can you expound on what this means? I'm not sure which text and links are referenced.

**Comment by wslack** [comment]
Right now, the only links to previews are in the "settings" subpage. I'm wondering if its be better to have that table on a separate page since its not a "setting" really.

**Comment by wslack** [comment]
Redundant with card sort.
