### ISSUE TITLE
Add robots.txt to Federalist Proxy

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#913]
We don't want sites on Federalist Proxy indexed by search engines. As a result, we'll likely want to add a robots.txt to the S3 bucket (or otherwise serve it at `/robots.txt`) saying that content should not be crawled.

**Comment by wslack** [comment]
💯

**Comment by wslack** [comment]
Can we do that this sprint?

**Comment by jmhooper** [comment]
Yeah, the easiest way to do this is to upload a `robots.txt` file to the root of the S3 bucket. I think we'd want to add a note about that to our "Cloud.gov Setup" doc as well.

**Comment by wslack** [comment]
not to the federalist-proxy repo?

**Comment by jmhooper** [comment]
That is another option. It means reconfiguring the proxy to also serve its own static files in addition to proxying content.

**Comment by wslack** [comment]
🤔  I like the idea of no human logging into the bucket, but I also like a simple proxy. How hard would it be to add to the proxy?

**Comment by jmhooper** [comment]
I investigated and it turns out it's actually not as difficult as I thought. Done here: https://github.com/18F/federalist-proxy/pull/7
