### ISSUE TITLE
Transfer team and project pages into a Federalist template

### ISSUE THREAD

**Issue by wslack** [18F/federalist#915]
Following on https://github.com/18F/federalist/issues/529, we should migrate this functionality into a Federalist site along with some sample data in each collection.

**Comment by wslack** [comment]
Current functionality viewable here: https://federalist.fr.cloud.gov/preview/gsa-oes/office-of-evaluation-sciences/update-uswds/

**Comment by hbillings** [comment]
For reference:
https://federalist.fr.cloud.gov/preview/gsa-oes/office-of-evaluation-sciences/update-uswds/team/
https://federalist.fr.cloud.gov/preview/gsa-oes/office-of-evaluation-sciences/update-uswds/work/

Should be able to display structured data like this with a collection.
