### ISSUE TITLE
Evaluate and refactor (if needed) within Federalist GUI

### ISSUE THREAD

**Issue by wslack** [18F/federalist#916]
The Federalist frontend has a lot more tools and features that have been added piecemeal. We should consider if they can be better organized.

**Comment by wslack** [comment]
@hbillings where is the list of stuff we generated for this issue? I can't find it.

**Comment by hbillings** [comment]
@wslack apologies, just seeing this! If you haven't found it yet, I think this is what you're looking for: https://github.com/18F/federalist/issues/940

**Comment by wslack** [comment]
TY! Closing this one.
