### ISSUE TITLE
Switch from Travis to CircleCI - due 9/1

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#922]
Infrastructure has suggested moving off of Travis to CircleCI since Circle is moving through the approval process. Apps we have on Travis:

- [x] Federalist
- [x] Federalist Builder - PR: https://github.com/18F/federalist-builder/pull/46
- [x] Federalist Proxy - PR: https://github.com/18F/federalist-proxy/pull/15
- [x] mark off completed migrations in https://trello.com/c/ip9ya65W/223-assist-in-move-off-of-travis-ci

**Due date is 9/12**

**Comment by jseppi** [comment]
Do we need to do this before ATO stuff, @afeld?

**Comment by afeld** [comment]
Ummm, I'd prioritize the other ATO work, but can't say for sure. I would hope you're held to the same deadline as everyone else.
