### ISSUE TITLE
Remove compiled styles.css from repository

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#931]
`styles.css` is built from from SASS sources and should not be checked into the repo.

To Do:
- [x] ensure that `styles.css` is built (probably during CI) and included in the deployment package

ref https://github.com/18F/federalist/pull/930#issuecomment-303528979

**Comment by jmhooper** [comment]
It is created as part of the `build` npm script which is invoked [here](https://github.com/18F/federalist/blob/staging/.travis.yml#L34) in CI
