### ISSUE TITLE
Remove SASS source files from public directory

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#932]
Currently the SASS source files located in `/public/styles/sass` are served from the production site. There is no need for this, so they should be moved to a different directory.

Ref: https://github.com/18F/federalist/pull/930#issuecomment-303528979

**Comment by jseppi** [comment]
Ah, whoops, I'm used to using GitHub's auto-issue-linking stuff. I'll train myself to use ZenHub's stuff instead for this project!

**Comment by wslack** [comment]
@jseppi the main thing is that we want to close issues during sprint review only

**Comment by jseppi** [comment]
Makes sense!
