### ISSUE TITLE
Create process to keep USWDS up to date for federalist main app

### ISSUE THREAD

**Issue by wslack** [18F/federalist#934]
re https://github.com/18F/federalist/pull/930#issuecomment-303546095

(it might not be a big lift)

**Comment by jseppi** [comment]
This is kind of gnarly, unfortunately. I still think it is worthwhile, but perhaps it would make more sense to do it if/when we have a designer, especially if we are going to implement some of the information architecture ideas that came out of #834.

**Comment by jseppi** [comment]
Suggest we de-prioritize this one given my feedback above.

**Comment by wslack** [comment]
done

**Comment by el-mapache** [comment]
@wslack This was done by @line47 a while back. I think this issue ca be closed, although it might be worth building some kind of regular updates of the web design system into our process; it's gone up ~15 minor versions since we last updated it.

**Comment by wslack** [comment]
Maybe convert this into a "regularly update the USWDS" issue?
