### ISSUE TITLE
Federalist app: Design update suggestions

### ISSUE THREAD

**Issue by hbillings** [18F/federalist#940]
(Update: only three of these left! https://github.com/18F/federalist/issues/940#issuecomment-339487582)

@wslack and I trolled through the federalist app and came up with the following list of small design tweaks. Should probably be broken out into other issues. 

Navbar:
- change username to "x's sites" or other language
- capitalize "log out"

New site page:
- all template boxes should be same height

Site settings screen:
- Make a "live site settings" box like "demo site settings" box with default branch and "custom domain"
- Github branches: Should be called "preview sites" or something similar
-- why is there a GH branch list in settings as well as in published? Consider condensing these.
- Make github branches collapsible
- Padding between delete button and label

Published page:
- Links should say "view site" and "view files"
- Make the default branch visually distinct from previews in the list
- Add a little collapsible help text box at the top

**Comment by wslack** [comment]
Things I can do:

Navbar:
- capitalize "log out"

New site page:
- all template boxes should be same height

Site settings screen:
- Make a "live site settings" box like "demo site settings" box with default branch and "custom domain"

Published page:
- Links should say "view site" and "view files"

@hbillings ok if I move those to a different issue?

**Comment by wslack** [comment]
- [ ] change username to "x's sites" or other language

- [ ] all template boxes should be same height

- [ ] Add a little collapsible help text box at the top

**Comment by jseppi** [comment]
Want to just make separate issues for those three items so they're easier to track and kanban?

**Comment by wslack** [comment]
if they are hard enough that they take more than 5 min apiece, sure

**Comment by line47** [comment]
I think these should be broken out into discrete items and I'm happy to do that @jseppi @wslack - just let me know

**Comment by wslack** [comment]
@line47 there are only two left but 👍  with making separate issues of them and moving this to "Done?"

**Comment by line47** [comment]
Created 2 new issues for track and closing this issue 🎉

**Comment by wslack** [comment]
Thank you! Just noting: we don't close issues until sprint review. Instead, we move them to the "Done?" category once we are finished working on them.
