### ISSUE TITLE
google-fonts.css is missing

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#947]
The `google-fonts.css` stylesheet, referenced in `index.html`, is missing both in dev and on the current production site.

I'm not sure what it was/is or if it should be there. If it is no longer needed we should just remove the  `<link>` to it in `index.html`

<img width="484" alt="screen shot 2017-05-30 at 9 07 52 am" src="https://cloud.githubusercontent.com/assets/697848/26587281/7b976164-4517-11e7-9baf-6a652df2ea4c.png">

**Comment by jmhooper** [comment]
I also have no idea what it was there for either so, 👍 to removing it

**Comment by jseppi** [comment]
My guess is that it was an old uswds thing.

**Comment by wslack** [comment]
SGTM
