### ISSUE TITLE
Fix React deprecation notices

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#948]
React has deprecated a couple things we are using. Fixes should be fairly easy. The deprecation warnings are showing up both in local dev and on prod.

- PropTypes
- React.createClass

<img width="482" alt="screen shot 2017-05-30 at 9 09 57 am" src="https://cloud.githubusercontent.com/assets/697848/26587447/1055ec26-4518-11e7-8bf1-5623492fcc35.png">

**Comment by jmhooper** [comment]
This is fixed in our code, but we still need to upgrade some deps to get them off deprecated React functionality.

**Comment by jseppi** [comment]
Oh, sorry, it's not actually fixed in our code. I had created a branch with a fix to our code, but because that touched tons of files, which then required lots of linting fixes, I punted on it.

I think the approach should be to fix it in files as they are touched, but maybe not whole-hog.

**Comment by jseppi** [comment]
Or, as discussed, go ahead and make the fix, but ignore the linting errors as long as tests pass.

**Comment by wslack** [comment]
This was addressed by James!
