### ISSUE TITLE
Consider using jest in place of chai/mocha

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#951]

**Comment by wslack** [comment]
At this point, more effort than benefit.

**Comment by wslack** [comment]
We don't know how much benefit this might provide, but think it would require re-writing many Federalist front end tests. Can reopen if @adborden or @toolness say we should keep!

**Comment by toolness** [comment]
I agree, I don't see a big benefit in using Jest over chai/mocha here (though it is fortunate that their APIs are very similar).
