### ISSUE TITLE
Cannot log out of Federalist if logged out of GitHub first

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#953]
1. Log in to GitHub
1. Log in to Federalist
1. Log out of GitHub
1. Try to log out of Federalist -- you will not be able to

Similar and probably related to #952

**Comment by wslack** [comment]
@jseppi have you tested these yourself? I am not sure that all actually apply.

**Comment by jseppi** [comment]
Haven't verified yet -- wanted to log it before I forgot though.

**Comment by jseppi** [comment]
Confirmed. After logging out of GitHub, then clicking the log out link in the header of Federalist, the page essentially just refreshed, and I was still logged-in.

**Comment by wslack** [comment]
seems like something worth an immediate look then?

**Comment by jseppi** [comment]
potentially upstream? https://github.com/jaredhanson/passport/issues/246

I'm still investigating...

**Comment by jseppi** [comment]
Huh, actually this bug is **not** happening for me any more.

@wslack or @brandocalrissian - could you verify?

**Comment by wslack** [comment]
Yeah, I can't reproduce. I can continue to click around in Federalist if I don't press "log out."

**Comment by jseppi** [comment]
Ok, closing!
