### ISSUE TITLE
Sails/socket.io requests occurring on production

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#954]
I noticed a bunch of `404`'d `GET` requests to `/socket.io/` with some sails params while streaming logs (`cf logs federalist`) in `production` space. They all looked something like this

```
GET /socket.io/?__sails_io_sdk_version=0.11.0&__sails_io_sdk_platform=browser&__sails_io_sdk_language=javascript&EIO=3&transport=polling&t=1496242182206-570584 HTTP/1.1" 404
```

I don't know what these are, but I don't think they should be happening. @jmhooper: know anything about them?

**Comment by jmhooper** [comment]
Only that they shouldn't be happening. Maybe it's stale JS left over from the old app at federalist.18f.gov?

**Comment by jseppi** [comment]
Yeah, maybe it was just bad timing before #942 was deployed and client caches cleared. I just checked recent logs for production and didn't see anything that looks like the request in the description here.

**Comment by jseppi** [comment]
Closing this since it is no longer reproducible.
