### ISSUE TITLE
Sites page - Add margin to left of Delete button

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#955]
The button and the text run into each other:

<img width="365" alt="screen shot 2017-05-31 at 8 18 36 am" src="https://cloud.githubusercontent.com/assets/697848/26640441/5769d26e-45ed-11e7-9cf4-a4f244d10ef1.png">

**Comment by jseppi** [comment]
On prod currently  this actually looks even worse:

<img width="531" alt="screen shot 2017-06-02 at 3 09 23 pm" src="https://cloud.githubusercontent.com/assets/697848/26742963/8aeec428-47a5-11e7-86c6-762f575ae4fd.png">

The icon is visible because the icon path for the alert class used for that div was corrected in https://github.com/18F/federalist/pull/924

**Comment by wslack** [comment]
Let's fix it all!
