### ISSUE TITLE
Federalist prod PR status are not reporting, but staging is

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#956]
We saw this on https://github.com/18F/18f.gsa.gov/pull/2442. The **production** federalist [build succeeded](https://federalist.18f.gov/sites/3/builds/6531/logs), but its PR status was not reported. The federalist **staging** build failed, due to a [build timeout](https://federalist-staging.fr.cloud.gov/sites/32/builds/1826/logs) of currently unknown cause, and its PR status did report (as failed).

cc @wslack 

To Do:
- [x] Confirm that a site with builds happening both in federalist prod and federalist staging shows two independent GitHub statuses with the correct names ("federalist/build" and "federalist-staging/build")

**Comment by wslack** [comment]
Expected behavior: the build status reports in the PR, or both build statuses report.

**Comment by jmhooper** [comment]
Ref #906

**Comment by jseppi** [comment]
Confirmed that both status reporters are reporting!

<img width="791" alt="screen shot 2017-06-07 at 3 18 14 pm" src="https://user-images.githubusercontent.com/697848/26899408-a2e2a246-4b94-11e7-9b8d-747e4dfc553b.png">

(from one of my test repos: https://github.com/jseppi/test-federalist-site/pull/1)

**Comment by wslack** [comment]
Woo hoo cc @gboone
