### ISSUE TITLE
Single user has issue cloning new repos

### ISSUE THREAD

**Issue by wslack** [18F/federalist#957]
A specific user has been unable to add a new template on federalist.18f.gov. I have confirmed that myself and other users (inside and outside GSA) can use the templates just fine.

This user gets this error in Chrome: `{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}` and this in Firefox: `You are not authorized to perform that action`
<img width="764" alt="screen shot 2017-05-31 at 6 33 39 pm" src="https://cloud.githubusercontent.com/assets/10016577/26657030/b3e700b0-462f-11e7-8871-9a0a948b5a96.png">

At some point in the past, the user was able to add a site, but the error logs show this:
```[clone.sh] Cloning site
Cloning into '.'...
fatal: Remote branch master not found in upstream origin
Unexpected end of command stream
```

What we've tried:

- Different computers at the user's home (not on a VPN)
- Different GitHub accounts
- Different browsers
- Incognito browser windows
- Hard refreshes
- Different names of repos
- Looking at console logs in the user's browser and on the Federalist site (which all show a 404 error)

We have not tried:

- Connecting from a different location
- Testing with the staging environment
- Trying to add a forked template repo manually

**Comment by wslack** [comment]
Sent to user:

Two things to try:
1. Please try the workflow at our staging site (where we test new code): federalist-staging.fr.cloud.gov

2. If you don't mind, could you try manually forking one of the template repos (top right button on this page, https://github.com/18F/federalist-modern-team-template) and then trying to add it to Federalist manually? That will help us understand more about the issue.

**Comment by afeld** [comment]
That sounds like they are trying to use the wrong URL or something.

**Comment by wslack** [comment]
@afeld they are clicking this button in Federalist; just as others do for whom the button works:
<img width="337" alt="screen shot 2017-05-31 at 6 47 16 pm" src="https://cloud.githubusercontent.com/assets/10016577/26657401/9d183f3c-4631-11e7-9de3-51a963e59c16.png">

**Comment by toolness** [comment]
Hmm, I had a sort of similar problem when trying to access my super simple project gallery page from pycon.  It just uses the github API to get a list of all the repos I've made, but it was returning a similar `You are not authorized to perform that action` response.

I had thought that perhaps it was due someone at pycon somehow abusing github, and maybe github had temporarily banned our IP or IP range from making API requests, but I'm not sure.

Can you put up a very simple example webpage up on e.g. jsbin.com that uses the github API in a trivial way, and see if that works for them?  If it doesn't, then you might be able to show your code to GitHub support as a test case, and they might be able to help figure out what's going on...

**Comment by wslack** [comment]
I'm going to see if he can get anything from https://api.github.com/emojis

**Comment by jmhooper** [comment]
It looks like the issue is coming from the code that creates the repo when creating a site from a template. I would like to check with the user to see if I can send requests to GitHub with their access token to create a repo and see if I can recreate the issue.

_Aside: I quietly suspect that the problem stems from the fact that the user's username has capital letters in it_

**Comment by wslack** [comment]
Nice suspecting!
