### ISSUE TITLE
Extract common site elements into template

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#958]
Implementation sketch:

1. extract common site components (header, footer, etc) into a template
1. refactor the home page to use the template, and stop loading its content with React
1. refactor the single-page app to use the template
1. create a custom 401 page that uses the template and return that after an unauthorized user authenticates with GitHub

This has a few benefits that I can think of off the top of my head:
1. Easier to add additional static content or error pages (like a custom 401 page, ref #924)
1. Smaller main JavaScript bundle since it will no longer in-line the `home.html` content
1. Simplified code, which will be easier to maintain/modify, especially for the header (which right now is all done in React).
1. Improved routing. Right now I sometimes notice a slight flash of the original Home page content when signed in, before the Sites page content is loaded by the React router.

**Comment by wslack** [comment]
Let's discuss in standup tomorrow!
