### ISSUE TITLE
Draft comms for out-of-beta for customers and list

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#959]

**Comment by wslack** [comment]
- [ ] List
- [ ] Listserv

**Comment by wslack** [comment]
https://docs.google.com/document/d/1-Zm1stRMmZ0AWkI56BmIJqnG4XzBz9620ZCAPOQwhtM/edit

and 

https://docs.google.com/document/d/1ZDkLxQ1UMgs_cInELW6B3mZApGlmUAVTGliwviNDZ8Q/edit
