### ISSUE TITLE
Lock node dependencies

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#967]
This can be done using either `yarn` (via its `yarn.lock`) _or_ now via `npm v5`'s new `package-lock.json`. If we want to use `yarn`, we'll want to update README instructions, etc. If we want to use `npm`, we'll have to make sure to specify that v5 is used. Either way, the lockfile will need to be committed to the repo.

More information on why pinning dependencies is a good practice is described in the 18F Before You Ship guide: https://before-you-ship.18f.gov/infrastructure/pinning-dependencies/

**Comment by wslack** [comment]
Prefer yarn.lock
