### ISSUE TITLE
federalist.18f.gov is using the development build of React.

### ISSUE THREAD

**Issue by romellogood** [18F/federalist#968]
According to [react dev tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en) this site is using the development build of React instead of production.

The reason this is bad can be found [here](https://facebook.github.io/react/docs/optimizing-performance.html#use-the-production-build).

**Comment by wslack** [comment]
@romellogood will check this out now; thank you!

**Comment by jseppi** [comment]
Thanks for reporting this, @romellogood! It will be fixed as part of our move to using webpack (PR #949), which is run in production build before deploying (https://github.com/18F/federalist/pull/949/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R45).

**Comment by romellogood** [comment]
Great 👍

**Comment by jseppi** [comment]
Update: this appears not done on staging.

<img width="1189" alt="screen shot 2017-06-09 at 2 48 39 pm" src="https://user-images.githubusercontent.com/697848/26992192-1ab5c214-4d23-11e7-8ad7-07700add4ce2.png">

**Comment by jseppi** [comment]
Just kidding - that development version was just temporarily deployed to staging during review.
