### ISSUE TITLE
Evaluate effort to add Hugo support

### ISSUE THREAD

**Issue by wslack** [18F/federalist#969]
Per https://github.com/18F/federalist/issues/756#issuecomment-305671183

> As we move DigitalGov over to Federalist, we would like to formally request that the Federalist Team consider supporting HUGO as a build option.

> We currently have around 1550 blog posts, 120 pages, 300 event pages, and a few hundred additional collection pages.

> This week, our team met with one of the members of the HUGO team here in New York. His name is Bud Parr. It became increasingly clear that in order to move DigitalGov to Federalist, we are going to need the key component Hugo offers — speed.

> The tradeoffs between Jekyll and Hugo are slim, and the community around HUGO appears to be growing. It is also nice to be able to reach out to people on the core team with questions, should we get stuck.

To Do for a minimal implementation of this feature:

- [x] Finish up and merge https://github.com/18F/federalist-docker-build/pull/51 to staging 
- [x] Modify web UI to add `hugo` to build engine dropdown(s): See PR #1010.
- ~Add database migration to include `hugo`~ Not needed: `hugo` is already an enumerated value in the [site model](https://github.com/18F/federalist/blob/staging/api/models/site.js#L97)

**Comment by wslack** [comment]
@jseppi to investigate level of effort

**Comment by jseppi** [comment]
Self note: will need to be added in https://github.com/18F/federalist-docker-build/blob/staging/build.sh

**Comment by jseppi** [comment]
Which version of hugo? Latest is currently `0.21`. Is there some way to specify a hugo version (like how a Gemfile can be used to specify a jekyll version?)? cc @jeremyzilar

**Comment by jseppi** [comment]
Started a PR over in https://github.com/18F/federalist-docker-build/pull/51

**Comment by jseppi** [comment]
Will also need to make some (I think small) modifications to the federalist app to allow selection of Hugo as the site engine.

**Comment by jseppi** [comment]
A somewhat large concern I have is that `hugo` releases seem to be often (it does not yet have a stable 1.0 release), and can break on sites that were working on previous versions. This could be a big maintenance problem for Federalist. 

Would it be up to Federalist to keep up with the most current version, or should we have some way to let customers specify the version used? If we use the most current version and a site build breaks, then we'll have to effectively communicate that problem to our end users.

**Comment by jeremyzilar** [comment]
Yeah, that is what they do for Nelify CMS — https://hugodocs.info/hosting-and-deployment/hosting-on-netlify/#building-with-a-specific-hugo-version

I would have the ability to put in a version num, and if that is not set, take the most recent version of HUGO
+ @thisisdano

**Comment by jeremyzilar** [comment]
Here is a working `branch` of our HUGO build https://github.com/GSA/digital.gov/tree/replatform-hugo

**Comment by wslack** [comment]
@jseppi says this should be pretty easy to get something up.

Will not worry about version number, and will need to do a database migration so the hugo version is added to site model.
