### ISSUE TITLE
Builds are not reporting their progress

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#970]
Numerous users have reported issues with builds ~either actually stalling or~ being reported as running for extremely long amounts of time.

- https://gsa-tts.slack.com/files/scottweber/F5NN855C7/screen_shot_2017-06-02_at_11.54.01_am.png
- https://gsa-tts.slack.com/archives/C1NUUGTT5/p1496434590545718
- https://gsa-tts.slack.com/files/kynetiv/F5MH4VC2K/screen_shot_2017-05-31_at_3.57.48_pm.png

Potentially a caching problem, as users have reported that after hard-refreshes of the sites list page, the correct build information is reported.

**Comment by wslack** [comment]
The last link doesn't show a problem?

**Comment by wslack** [comment]
I checked one of these sites. The builds all appear just fine for me for identity-site.

**Comment by wslack** [comment]
A hard refresh worked for another user one of these cases.

**Comment by wslack** [comment]
The final user reported that there's a caching issue as well.

**Comment by wslack** [comment]
I feel like we should edit this to make clear that builds are not stalling, but instead browsers aren't displaying completed builds because of caching issues.

**Comment by jseppi** [comment]
Whoops, edited to the correct link.

**Comment by jmhooper** [comment]
This look like it was caused by #978 where CloudFront was caching the response from `/v0/site/:id/build`. #976 should have a fix.
