### ISSUE TITLE
When GitHub is having an API outage, logging out of Federalist does not seem to work

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#972]
While GitHub is having an API outage, try to logout of Federalist. You will be redirected back to Federalist's site page and still be logged in.

Possibilities:
 - does not seem to happen on staging, so possibly Cloud Front error swallowing?
 - The logout handler is fairly simple, but perhaps passport is interacting again with the GitHub api under the hood and encountering an API error that prevents the logout

**Comment by jmhooper** [comment]
This may be caused by #978 and CloudFront caching the response from `/v0/me`. #976 should have a fix.
