### ISSUE TITLE
Add a CloudFront custom domain to staging to better reflect production environment

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#977]
This will hopefully help us see and debug any CloudFront-related (generally caching) issues before they are seen in production.

To Do:
- [x] create cdn-service
- [x] update dns
- [x] update environment variables and user-provided service variables with new domain 
- [x] update github auth callback to use new domain
- ~`cf map-route` with the new domain (?)~

**Comment by jseppi** [comment]
Ref #978

**Comment by wslack** [comment]
we can just go back to federalist-staging.18f.gov I think

**Comment by jseppi** [comment]
Created cdn-service named `federalist-staging-route` in `staging` space.

Opened https://github.com/18F/dns/pull/118 for DNS record for `federalist-staging.18f.gov`

**Comment by jseppi** [comment]
I just checked this morning, and I think the DNS change went through, as https://federalist-staging.18f.gov/ resolves, but it returns the generic cloud.gov `404` message. 

I think we also need to do `cf map-route federalist-staging 18f.gov --hostname federalist-staging`, but I don't see mention of that in https://cloud.gov/docs/services/cdn-route/.

**Comment by jseppi** [comment]
It doesn't appear that the production app has had a route bound to it for its URL, so I'm not sure why the cdn-service domain is not hitting the staging app. @wslack: any ideas?

**Comment by jseppi** [comment]
Ah, I wonder that since staging is at `.fr.cloud.gov` (and not `.app.cloud.gov`) if it is not considered an "internal" app (see [options](https://cloud.gov/docs/services/cdn-route/#options)) and needs to have the `origin` parameter set in the `cdn-route` service.

**Comment by wslack** [comment]
@jseppi I don't know how the route for federalist.18f.gov is configured; would suggest asking Jonathan about that (though its likely documented in the URL change plan as well)

**Comment by jmhooper** [comment]
Yeah, when we created the one for `federalist.18f.gov` we had to specify `federalist.fr.cloud.gov` as the origin instead of letting it be inferred. As such there was no need to work with routes in cloud.gov; we only had to update the DNS repo.

**Comment by jseppi** [comment]
ok, updating the service to add `"origin": "federalist-staging.fr.cloud.gov"`

**Comment by jseppi** [comment]
🎉  yay, that worked!
