### ISSUE TITLE
Cloudfront's caching causes weird issues in production

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#978]
Currently, the production app is fronted with a Cloudfront distribution. That has resulted in some strange behaviors.

Currently, the code base on master does not set a `Cache-Control` header. This causes CloudFront to cache API responses. This causes it to serve out of date responses leading to weird bugs where updates to sites don't appear, even though they are written to the database, and the build table does not display the most recent builds. It appears that we can resolve this issue by adding the following header to API responses:

```
Cache-Control: max-age=0
```

Additionally, it looks like errors responses are cached as well. This is a problem for us, because we determine if users are authenticated by sending a response to `/v0/me` and checking for a 403 or 200. The caching leads to a problem where `/v0/me` will report a cached 403 response leading us to believe erroneously that the user is not logged in.

[Here](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/HTTPStatusCodes.html) are the docs on how CloudFront caches errors. It looks like `4xx` and `5xx` responses ignore the `Cache-Control` header and are cached for a TTL that is set by the distro which we do not have access to since it is provided by a cloud.gov brokered service.

**Comment by wslack** [comment]
@jmhooper did you e-mail cloud-gov-support? (maybe cc federalist-support if you haven't yet?)

**Comment by jmhooper** [comment]
@wslack: I sent an email to cloud.gov support and did CC Federalist support.

**Comment by wslack** [comment]
I am bad at e-mail. Carry on!

**Comment by jmhooper** [comment]
I put in the request to change the Minimum TTL for errors, but it is unclear if they have made the change. As of right now, it looks like the CDN is still caching errors.

**Comment by jmhooper** [comment]
cloud.gov support changed the settings for our CDN distributions and it looks like this is working in both prod and staging.

Thanks to @fureigh and @jcscottiii!!!

**Comment by jseppi** [comment]
Should the required settings and how to get them set (ie by contacting an operator) be in the deployment docs?

**Comment by jmhooper** [comment]
@jseppi: Yeah, good thought 💡

**Comment by wslack** [comment]
Issue made!

**Comment by wslack** [comment]
Staging and production are set! Closing!
