### ISSUE TITLE
Azure support proposal

### ISSUE THREAD

**Issue by anweiss** [18F/federalist#98]
Proposing support for Azure. Immediate roadmap indicates AWS S3 for static content hosting but there could be an opportunity to get Azure included pending the current state of the roadmap. Some thoughts:

- Develop an `Azure` service with stubs similar to those of the `S3` service for static content hosting
  - Provisions Azure Web App
  - Pushes content to Azure Web App with Git
- Include Azure configuration options in `sails.config.build.azure`
- UI support for establishing connectivity to AWS, Azure or both
- Include one-click provisioning support to Azure for hosting the Federalist platform itself for development and production purposes

**Comment by anweiss** [comment]
Tracking in [pull/azure](https://github.com/Microsoft/federalist/tree/pull/azure) branch. Will re-work pending the creation of a new buildEngine installable hook per #104

**Comment by dhcole** [comment]
Closing in favor of #121
