### ISSUE TITLE
Remove FEDERALIST_BUILD_CALLBACK from README

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#985]
It's not used any more. Also probably simiarly named STATUS and LOG vars.

**Comment by jmhooper** [comment]
The variable was replaced by `APP_HOSTNAME`. We'll want to confirm that is in the docs.

**Comment by jseppi** [comment]
Also `APP_COMAIN` [sic] probably needs to be removed from README too

**Comment by wslack** [comment]
This was cleaned up and we didn't close this.
