### ISSUE TITLE
Add app_env to page title to make tabs easier to distinguish

### ISSUE THREAD

**Issue by jseppi** [18F/federalist#988]
This is mostly a developer affordance, but I think we should use the new `config.app.app_env` in the site's `<title>` so that browser tabs are easier to distinguish.

**Comment by wslack** [comment]
Seems like a very easy PR that will help people; correct?

**Comment by jseppi** [comment]
Yeah, it's easy. It's mostly to help devs, but could also be nice for any users testing stuff on staging.

**Comment by wslack** [comment]
put in ready on that basis. I'm all for high impact small changes.
