### ISSUE TITLE
Internal server error when deleting a site

### ISSUE THREAD

**Issue by jmhooper** [18F/federalist#990]
It looks like the server will sometimes respond with a 500 error for a request to delete a site. The log output is as follows:

```
error: Sending 500:  MalformedXML: The XML you provided was not well-formed or did not validate against our published schema
```

The stack trace reaches into the AWS SDK node modules, suggesting there is a syntax error in the request we are sending to S3 to either list or delete the contents of the S3 bucket.

**Comment by jseppi** [comment]
Could it be a bug in a dependency? Versions could be misaligned from production to staging since we don't have a dependency lock file.

**Comment by jmhooper** [comment]
Potentially. I think it may also be related to the contents of the S3 bucket. I'm seeing it for one of my sites and not the other.
