### ISSUE TITLE
Automatically expire invalid sessions in shorter time period

### ISSUE THREAD

**Issue by wslack** [18F/federalist#996]
- Would be opaque to users with unrevoked access.
- This would surprise-destroy sessions.

created from #952

**Comment by jseppi** [comment]
Here's a reference implementation for adding a refresh token middleware (though in Django): https://github.com/18F/cg-django-uaa/blob/52b18a0e475c9587939900dd55c6a535e82a1126/uaa_client/middleware.py#L18

**Comment by wslack** [comment]
Closing as not recently raised and addressed by past security updates.
